### ISSUE TITLE
发现一个新的疑似吸血bt客户端： cacao

### ISSUE THREAD

**Issue by Vigi0303** [c0re100/qBittorrent-Enhanced-Edition#100]
发现一个新的疑似吸血bt客户端
已上传200+MB的情况下（资源总大小8GB），进度为0.0%
客户端tag： cacao_torrent/0.16.9.0

Operating System: win10

问题如下图：
![无标题](https://user-images.githubusercontent.com/9861673/76291380-f1af8200-62e7-11ea-95e7-0ec4ca805050.png)

**Comment by c0re100** [comment]
會在下個版本(4.2.2)加入黑名單
