### ISSUE TITLE
现可使用 Chocolatey 安装 qBittorrent-Enhanced-Edition

### ISSUE THREAD

**Issue by iYato** [c0re100/qBittorrent-Enhanced-Edition#101]
### qBittorrent version and Operating System
Windows

### What is the problem
现可使用 Chocolatey 安装 qBittorrent-Enhanced-Edition，现由我维护。package 详情页：https://chocolatey.org/packages/qbittorrent-enhanced

```powershell
choco install qbittorrent-enhanced
```

**Comment by c0re100** [comment]
謝謝~
已更新README
