### ISSUE TITLE
Client Blacklist

### ISSUE THREAD

**Issue by Mike-Reddick** [c0re100/qBittorrent-Enhanced-Edition#103]
@c0re100 can you please share with us the Client Names and Peer Ids of the known bad clients, like Xunlei and the others? Because now Tixati also have a feature to blacklist clients, so if you share, Tixati users can use it also. And if you keep a Client Blacklist on this repository? Thanks!

**Comment by c0re100** [comment]
Source:
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_2_x/src/base/bittorrent/session.cpp#L2148

**Comment by Mike-Reddick** [comment]
Thanks so much
