### ISSUE TITLE
上游已更新到4.2.2

### ISSUE THREAD

**Issue by abcfy2** [c0re100/qBittorrent-Enhanced-Edition#104]
今天看到上游突然将4.2.2的里程碑的issue全关了，昨天看还有十几个issue挂着呢。

可以考虑同步上游更新了，好久都没有新版本了

**Comment by 123336-mike** [comment]
可以更新吗

**Comment by abcfy2** [comment]
> 可以更新吗

qbittorrent上游已经关闭了4.2.2所有的issue，并且已经打了4.2.2的tag，已经算是正式发布了

**Comment by 123336-mike** [comment]
> > 可以更新吗
> 
> qbittorrent上游已经关闭了4.2.2所有的问题，并且已经打了4.2.2的标签，已经算是正式发布了

知道啊，我也在等待开发者的更新

**Comment by c0re100** [comment]
Cause I switch from Intel to AMD recently. 
So I need rebuild qbittorrent development environment first. 
I hope I can release new version tonight :joy:

**Comment by 123336-mike** [comment]
> 原因我最近从Intel切换到AMD。
> 因此，我需要首先重建qbittorrent开发环境。
> 希望今晚可以发布新版本😂

Thank you for your hard work

**Comment by 123336-mike** [comment]
> Cause I switch from Intel to AMD recently.
> So I need rebuild qbittorrent development environment first.
> I hope I can release new version tonight 😂

Can you increase the speed of viewing connected peers? If it's too much trouble, forget it

**Comment by kkwong7878** [comment]
靜待更新😎

**Comment by c0re100** [comment]
I will release v4.2.2 in the next few hours.
