### ISSUE TITLE
局域网IP出现的原因是什么？

### ISSUE THREAD

**Issue by ausers** [c0re100/qBittorrent-Enhanced-Edition#105]
![QQ截图20200325152151](https://user-images.githubusercontent.com/54773815/77512357-db8bef00-6ead-11ea-987d-e5680d2b55dc.png)
如图，偶然发现用户IP与本机局域网网关IP相同，感觉不是正常显示（甚至曾有瞬间出现127.0.0.1的，没来及截图）

**Comment by c0re100** [comment]
> ![QQ截图20200325152151](https://user-images.githubusercontent.com/54773815/77512357-db8bef00-6ead-11ea-987d-e5680d2b55dc.png)
> 如图，偶然发现用户IP与本机局域网网关IP相同，感觉不是正常显示（甚至曾有瞬间出现127.0.0.1的，没来及截图）

在開啟了LSD情況下，本地會主動連接同一區域的Peer 
Local Peer Discovery
https://en.wikipedia.org/wiki/Local_Peer_Discovery
我不清楚大陸的網絡情況，但可以猜測到你應該是NAT網絡的一> ![QQ截图20200325152151](https://user-images.githubusercontent.com/54773815/77512357-db8bef00-6ead-11ea-987d-e5680d2b55dc.png)
> 如图，偶然发现用户IP与本机局域网网关IP相同，感觉不是正常显示（甚至曾有瞬间出现127.0.0.1的，没来及截图）

在開啟了LSD情況下，本地會主動連接同一區域的Peer
127.0.0.1是正常情況
Local Peer Discovery
https://en.wikipedia.org/wiki/Local_Peer_Discovery

我不清楚大陸的網絡情況，不過你應該是[Carrier-grade NAT](https://zh.wikipedia.org/wiki/%E7%94%B5%E4%BF%A1%E7%BA%A7NAT)的一份子。

**Comment by abcfy2** [comment]
开启Upnp之后就是这样，会将本地端口映射到路由器上，所以你会看到那个

**Comment by ausers** [comment]
> > ![QQ截图20200325152151](https://user-images.githubusercontent.com/54773815/77512357-db8bef00-6ead-11ea-987d-e5680d2b55dc.png)
> > 如图，偶然发现用户IP与本机局域网网关IP相同，感觉不是正常显示（甚至曾有瞬间出现127.0.0.1的，没来及截图）
> 
> 在開啟了LSD情況下，本地會主動連接同一區域的Peer
> Local Peer Discovery
> https://en.wikipedia.org/wiki/Local_Peer_Discovery
> 我不清楚大陸的網絡情況，但可以猜測到你應該是NAT網絡的一> ![QQ截图20200325152151](https://user-images.githubusercontent.com/54773815/77512357-db8bef00-6ead-11ea-987d-e5680d2b55dc.png)
> 
> > 如图，偶然发现用户IP与本机局域网网关IP相同，感觉不是正常显示（甚至曾有瞬间出现127.0.0.1的，没来及截图）
> 
> 在開啟了LSD情況下，本地會主動連接同一區域的Peer
> 127.0.0.1是正常情況
> Local Peer Discovery
> https://en.wikipedia.org/wiki/Local_Peer_Discovery
> 
> 我不清楚大陸的網絡情況，不過你應該是[Carrier-grade NAT](https://zh.wikipedia.org/wiki/%E7%94%B5%E4%BF%A1%E7%BA%A7NAT)的一份子。

根据光猫IP与IPIP查询结果一致均为180.*.*.54来看，应该不是电信级NAT，且该现象出现时网络中仅有电脑手机两部设备，截至此IP消失，这个与网关IP一致的IP给我贡献了总文件近一半的下载量

**Comment by c0re100** [comment]
> > > ![QQ截图20200325152151](https://user-images.githubusercontent.com/54773815/77512357-db8bef00-6ead-11ea-987d-e5680d2b55dc.png)
> > > 如图，偶然发现用户IP与本机局域网网关IP相同，感觉不是正常显示（甚至曾有瞬间出现127.0.0.1的，没来及截图）
> > 
> > 
> > 在開啟了LSD情況下，本地會主動連接同一區域的Peer
> > Local Peer Discovery
> > https://en.wikipedia.org/wiki/Local_Peer_Discovery
> > 我不清楚大陸的網絡情況，但可以猜測到你應該是NAT網絡的一> ![QQ截图20200325152151](https://user-images.githubusercontent.com/54773815/77512357-db8bef00-6ead-11ea-987d-e5680d2b55dc.png)
> > > 如图，偶然发现用户IP与本机局域网网关IP相同，感觉不是正常显示（甚至曾有瞬间出现127.0.0.1的，没来及截图）
> > 
> > 
> > 在開啟了LSD情況下，本地會主動連接同一區域的Peer
> > 127.0.0.1是正常情況
> > Local Peer Discovery
> > https://en.wikipedia.org/wiki/Local_Peer_Discovery
> > 我不清楚大陸的網絡情況，不過你應該是[Carrier-grade NAT](https://zh.wikipedia.org/wiki/%E7%94%B5%E4%BF%A1%E7%BA%A7NAT)的一份子。
> 
> 根据光猫IP与IPIP查询结果一致均为`180.*.*.54`来看，应该不是电信级NAT，且该现象出现时网络中仅有电脑手机两部设备，截至此IP消失，这个与网关IP一致的IP给我贡献了总文件近一半的下载量

我在想......會不會DNS解析問題?
你有開到這個qB選項嗎?

**Comment by ausers** [comment]
> > > > ![QQ截图20200325152151](https://user-images.githubusercontent.com/54773815/77512357-db8bef00-6ead-11ea-987d-e5680d2b55dc.png)
> > > > 如图，偶然发现用户IP与本机局域网网关IP相同，感觉不是正常显示（甚至曾有瞬间出现127.0.0.1的，没来及截图）
> > > 
> > > 
> > > 在開啟了LSD情況下，本地會主動連接同一區域的Peer
> > > Local Peer Discovery
> > > https://en.wikipedia.org/wiki/Local_Peer_Discovery
> > > 我不清楚大陸的網絡情況，但可以猜測到你應該是NAT網絡的一> ![QQ截图20200325152151](https://user-images.githubusercontent.com/54773815/77512357-db8bef00-6ead-11ea-987d-e5680d2b55dc.png)
> > > > 如图，偶然发现用户IP与本机局域网网关IP相同，感觉不是正常显示（甚至曾有瞬间出现127.0.0.1的，没来及截图）
> > > 
> > > 
> > > 在開啟了LSD情況下，本地會主動連接同一區域的Peer
> > > 127.0.0.1是正常情況
> > > Local Peer Discovery
> > > https://en.wikipedia.org/wiki/Local_Peer_Discovery
> > > 我不清楚大陸的網絡情況，不過你應該是[Carrier-grade NAT](https://zh.wikipedia.org/wiki/%E7%94%B5%E4%BF%A1%E7%BA%A7NAT)的一份子。
> > 
> > 
> > 根据光猫IP与IPIP查询结果一致均为`180.*.*.54`来看，应该不是电信级NAT，且该现象出现时网络中仅有电脑手机两部设备，截至此IP消失，这个与网关IP一致的IP给我贡献了总文件近一半的下载量
> 
> 我在想......會不會DNS解析問題?
> 你有開到這個qB選項嗎?

我没找到dns相关选项，并且除已经观察到的长期存在的`192.168.2.1`和偶然出现的`127.0.0.1`外，还观察到某瞬间出现了我的公网IP`180.*.*.54`
PS，注意到了`192.168.2.1`的端口是有可能变化的

**Comment by ausers** [comment]
> > > > ![QQ截图20200325152151](https://user-images.githubusercontent.com/54773815/77512357-db8bef00-6ead-11ea-987d-e5680d2b55dc.png)
> > > > 如图，偶然发现用户IP与本机局域网网关IP相同，感觉不是正常显示（甚至曾有瞬间出现127.0.0.1的，没来及截图）
> > > 
> > > 
> > > 在開啟了LSD情況下，本地會主動連接同一區域的Peer
> > > Local Peer Discovery
> > > https://en.wikipedia.org/wiki/Local_Peer_Discovery
> > > 我不清楚大陸的網絡情況，但可以猜測到你應該是NAT網絡的一> ![QQ截图20200325152151](https://user-images.githubusercontent.com/54773815/77512357-db8bef00-6ead-11ea-987d-e5680d2b55dc.png)
> > > > 如图，偶然发现用户IP与本机局域网网关IP相同，感觉不是正常显示（甚至曾有瞬间出现127.0.0.1的，没来及截图）
> > > 
> > > 
> > > 在開啟了LSD情況下，本地會主動連接同一區域的Peer
> > > 127.0.0.1是正常情況
> > > Local Peer Discovery
> > > https://en.wikipedia.org/wiki/Local_Peer_Discovery
> > > 我不清楚大陸的網絡情況，不過你應該是[Carrier-grade NAT](https://zh.wikipedia.org/wiki/%E7%94%B5%E4%BF%A1%E7%BA%A7NAT)的一份子。
> > 
> > 
> > 根据光猫IP与IPIP查询结果一致均为`180.*.*.54`来看，应该不是电信级NAT，且该现象出现时网络中仅有电脑手机两部设备，截至此IP消失，这个与网关IP一致的IP给我贡献了总文件近一半的下载量
> 
> 我在想......會不會DNS解析問題?
> 你有開到這個qB選項嗎?

![QQ截图20200327141323](https://user-images.githubusercontent.com/54773815/77727419-3d2a9580-7035-11ea-9050-8f2fce0ac080.png)
还能出现上传的，，，实在没搞懂这个显示问题来自哪里，我是不是应该去官方版本提问？

**Comment by leomsn** [comment]
我也是持续发现网关ip在贡献上传和下载

**Comment by leomsn** [comment]
另外，跟UPnP是否打开应该无关，因为我是关闭upnp的

**Comment by leomsn** [comment]
所以从2020年到2024年，这个显示都在，估计也就是显示问题，无伤大雅，也没人关注并修复，哈哈哈
