### ISSUE TITLE
The speed of connected peers

### ISSUE THREAD

**Issue by 123336-mike** [c0re100/qBittorrent-Enhanced-Edition#106]
*Can developers add the ability to view the speed of connected peers? If it's too much trouble, forget it

**Comment by 1970633640** [comment]
支持 使用别的客户端可以看到qBittorrent用户的下载速度，说明qBittorrent应该是支持这个功能的 这个功能很有意思，有娱乐性。

agreed. Other clients can view the download speed of qBittorrent users, so I guess qBittorrent support this feature. This feature is useful and entertaining.

**Comment by c0re100** [comment]
Sorry.
libtorrent removed `remote_dl_rate` feature since libtorrent 1.2, I can't implement this feature.
`Other clients can view the download speed of qBittorrent users`: the estimate speed may inaccurate.
