### ISSUE TITLE
Windows 版本安装包不再打包 PDB 文件

### ISSUE THREAD

**Issue by Crystal-RainSlide** [c0re100/qBittorrent-Enhanced-Edition#108]
### qBittorrent version and Operating System
无关

### What is the problem

建议考虑作为 releases 项目，放在压缩包内单独发布。

或者，有否选项或方法能够压缩或精简 PDB 文件体积？目前已经达到 100MB，而大多数人是没有调试这个程序的必要的。

### What is the expected behavior
无关

### Steps to reproduce
打开安装目录，查看 qbittorrent.pdb 体积

### Extra info(if any)
无

**Comment by c0re100** [comment]
PDB是用來定位qBt出錯時的位置
刪除後就無法正確顯示哪一段源碼有問題

沒有PDB情況下
```
#  0 ???                  0x00000000001c96b2 0x001c96b2()
#  1 ???                  0x00000000001cbcb2 0x001cbcb2()
#  2 ???                  0x00000000009271ea 0x009271ea()
#  3 ???                  0x000000000092ded2 0x0092ded2()
#  4 ???                  0x000000000092276f 0x0092276f()
#  5 ???                  0x0000000000922d8c 0x00922d8c()
#  6 ???                  0x00000000009260a5 0x009260a5()
#  7 ???                  0x0000000076f96ab9 0x76f96ab9()
............
```

有PDB情況下
```
#  0 qbittorrent.exe      0x000000013f3396d1 straceWin::getBacktrace()[ app\stacktrace_win.h : 213 ]
#  1 qbittorrent.exe      0x000000013f33d687 sigAbnormalHandler(signum)[ app\main.cpp : 400 ]
#  2 qbittorrent.exe      0x000000013fdc6581 _seh_filter_exe(xcptnum, pxcptinfoptrs)[ d:\th\minkernel\crts\ucrt\src\appcrt\misc\exception_filter.cpp : 215 ]
#  3 qbittorrent.exe      0x000000013fe8c7dd `thread_start'::`1'::filt$0()[ d:\th\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp : 117 ]
#  4 qbittorrent.exe      0x000000013fdab374 __C_specific_handler(ExceptionRecord, EstablisherFrame, ContextRecord, DispatcherContext)
.............
```

我查了一下後，Visual Studio是有提供PDBCompress這個選項
https://devblogs.microsoft.com/cppblog/shrink-my-program-database-pdb-file/
但內文說`This switch won’t have any impact if the operating system’s file system does not support compression`
所以大概無解...

**Comment by Crystal-RainSlide** [comment]
他也有给出两个编译选项的链接，不知道是否有用：
https://docs.microsoft.com/en-us/cpp/build/reference/gy-enable-function-level-linking
https://docs.microsoft.com/en-us/cpp/build/reference/opt-optimizations

既然 `/PDBCOMPRESS` 是 NTFS 压缩，可能在安装中添加 CMD `COMPACT /C` 命令，在支持压缩的 NTFS 卷上进行事后压缩吗？

**Comment by c0re100** [comment]
> 他也有给出两个编译选项的链接，不知道是否有用：
> https://docs.microsoft.com/en-us/cpp/build/reference/gy-enable-function-level-linking
> https://docs.microsoft.com/en-us/cpp/build/reference/opt-optimizations
> 
> 既然 `/PDBCOMPRESS` 是 NTFS 压缩，可能在安装中添加 CMD `COMPACT /C` 命令，在支持压缩的 NTFS 卷上进行事后压缩吗？

Gy和OPT都有用了
COMPACT這個方案可以在下一個版本(4.2.3)試試~~

**Comment by Crystal-RainSlide** [comment]
那么，命令大致就是这样：
``` CMD
COMPACT /C "{app}qbittorrent.pdb"
```
模板语法适用于 Inno Setup 而不是 NSIS，修改过去就可以了~
