### ISSUE TITLE
Wrong scaling and bad font rendering in HiDPI 

### ISSUE THREAD

**Issue by bv5757** [c0re100/qBittorrent-Enhanced-Edition#109]
**Please provide the following information**

### qBittorrent version and Operating System
4.2.2.10, Windows 10 2004

### If on linux, libtorrent-rasterbar and Qt version
(type here)

### What is the problem
It is scale to 200% when set on 150% scaling and font rendering goes badly that without Anti-Aliasing

### What is the expected behavior
UI becomes so large that could only see a few of information in screen and some buttons goes out of screen caused some operation could not be operated
Font are lose their own smoothing that be harder to see
![image](https://user-images.githubusercontent.com/37390710/77819575-be0d8e00-7116-11ea-8e8b-c36995ad3401.png)

### Steps to reproduce
turn the scale to 150% on system settings

### Extra info(if any)
(type here)

**Comment by c0re100** [comment]
> **Please provide the following information**
> 
> ### qBittorrent version and Operating System
> 4.2.2.10, Windows 10 2004
> 
> ### If on linux, libtorrent-rasterbar and Qt version
> (type here)
> 
> ### What is the problem
> It is scale to 200% when set on 150% scaling and font rendering goes badly that without Anti-Aliasing
> 
> ### What is the expected behavior
> UI becomes so large that could only see a few of information in screen and some buttons goes out of screen caused some operation could not be operated
> Font are lose their own smoothing that be harder to see
> ![image](https://user-images.githubusercontent.com/37390710/77819575-be0d8e00-7116-11ea-8e8b-c36995ad3401.png)
> 
> ### Steps to reproduce
> turn the scale to 150% on system settings
> 
> ### Extra info(if any)
> (type here)

UI issue fixed in upstream, I will release new version when they released.

**Comment by c0re100** [comment]
v4.2.3.10 released~
