### ISSUE TITLE
是否可以考虑增加屏蔽 FDM 客户端呢？

### ISSUE THREAD

**Issue by IceCodeNew** [c0re100/qBittorrent-Enhanced-Edition#11]
### qBittorrent version and Operating System
qBittorrent v4.1.1.3(Enhanced Edition)
Windows 10

### Extra info(if any)
如题，我在每次有大流量上传时都能看到 FDM 的身影。
一方面我过去也使用过这个客户端，二来我也有实际对每次看到的 FDM 客户端做观察。一段时间过后，我认定这个客户端也属于只下载不上传的那类客户端，所以申请开发者添加 FDM 到屏蔽客户端之列。
如果我的这个认识是错误的，欢迎各位网友们指正。
最后感谢开发者花时间对 qBittorrent 客户端做修改，您的成果对我帮助很大！

**Comment by zanewayne78** [comment]
主要是用FDM的用户一般都是下载http，ftp类型的，没有补种的习惯，下完就退出。
FDM本身没有吸血的行为。

**Comment by IceCodeNew** [comment]
主要我过去用 FDM 下载的时候确实从来都没有看到过上传速度这个东西。所以究竟这个软件现在有没有默认开启给种子做种的功能我也不是很清楚。
另外一方面当然就是用户的问题了，我说一句用 FDM 的人会比用 μtorrent 或者 qBittorrent 的人更少有人有做种的意识不过分吧。
所以在我看起来，用 FDM 和用迅雷用 QQ 旋风没有多大的区别。本身 FDM 也不是一款规规矩矩的 torrent 下载软件，所以我不愿意给他们上传。

**Comment by c0re100** [comment]
剛剛做了測試
我這一邊的FDM是有上傳的, 而且它預設為做種模式, 亦可以設定上下傳速度
就像 @zanewayne78 所說, 大概是用戶問題多吧...
