### ISSUE TITLE
v4.2.2.10版本，下载完成的任务不按时间排序

### ISSUE THREAD

**Issue by HuGnnn** [c0re100/qBittorrent-Enhanced-Edition#110]
麻烦可以回调到之前的排序方式吗？也就是下载中任务按进度排序，完成的任务按完成时间排序

或者说在设置里面能够调整（我没找到）

**Comment by c0re100** [comment]
> 麻烦可以回调到之前的排序方式吗？也就是下载中任务按进度排序，完成的任务按完成时间排序
> 
> 或者说在设置里面能够调整（我没找到）

Bug，要等upstream修復
