### ISSUE TITLE
任务处于下载上传中时，无法解析域名 ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by BedivereZero** [c0re100/qBittorrent-Enhanced-Edition#111]
**Please provide the following information**

### qBittorrent version and Operating System
v4.2.1.10(64-bit) (Enhanced Edition)
Windows 10 专业版 1903

### What is the problem
在 qb 的任务处于上传、下载时，浏览器无法打开网页（baidu.com），报错 ERR_NAME_NOT_RESOLVED
停止 qb 的任务，等待几分钟后，浏览器可以打开网页

在 qb 的任务处于上传、下载时，在 powershell 中 执行 nslookup 也无法解析域名

```powershell
nslookup baidu.com
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  210.22.70.3

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** 请求 UnKnown 超时
```

### What is the expected behavior
这个问题是否与 qb 的资源占用有关
如果有关，能否通过限制 qb 的资源占用避免
我做了一些限制，但问题依然存在：

```
Global maximum number of connections: 100
Maximum number of connections per torrent: 10
Global maximum number off upload slots: 8
Maximum number of upload slots per torrent: 4

Alternative Rate Limits Upload & Download: 64 KiB/s

Apply rate limit to μTP protocol
Apply rate limit to transport overhead
```

**Comment by c0re100** [comment]
網絡卡/路由器問題
無法負荷太多連接

**Comment by Crystal-RainSlide** [comment]
是否有其他程序占用大量连接？

然后，无法解析也可能是 DNS 服务器的问题，有没有尝试过检查 DNS 服务器的可用性以及更换 DNS 服务器？

我回复现时测试，（虽然无法 ping 通）可以通过 `210.22.70.3` 完成查询。可以再看看问题是否存在。

**Comment by BedivereZero** [comment]
十分感谢
我进一步调低了限制 Global maximum number of connections: 64
问题出现的频率大大降低，过去一周仅出现两次
很可能是我路由器的问题 🙇‍
