### ISSUE TITLE
可以对特定 IP，单独限速吗

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [c0re100/qBittorrent-Enhanced-Edition#113]
**Please provide the following information**

### qBittorrent version and Operating System
(type here)
v4.2.1.10(32-bit)(Enhanced Edition)
windows 10

### If on linux, libtorrent-rasterbar and Qt version
(type here)

### What is the problem
(type here)
某些用户下载几百 KB，但是上传限制到只有几 KB
现在只能完全拉黑他们，或者全局限制上传

### What is the expected behavior
(type here)

希望可以单独对他们进行上传限制，只分给他们 5KB 速度

### Steps to reproduce
(type here)

### Extra info(if any)
(type here)

**Comment by c0re100** [comment]
不能，libtorrent已經移除了相關功能~

**Comment by LakeishaKowalczyk** [comment]
@c0re100 
谢谢，为什么要这样设计
