### ISSUE TITLE
DHT在代理启用时无法工作

### ISSUE THREAD

**Issue by eebssk1** [c0re100/qBittorrent-Enhanced-Edition#114]
**Please provide the following information**

### qBittorrent version and Operating System
(type here)
v4.2.3.10 
win10 1909
### If on linux, libtorrent-rasterbar and Qt version
(type here)

### What is the problem
代理启用时DHT不工作。
看起来如果使用了代理，qB会强行在代理上进行发现，不管用户是否设置使用代理进行用户连接。
(type here)
### What is the expected behavior
(type here)
除非设置了使用代理连接，qB应保持在本地进行发现。
### Steps to reproduce
(type here)
启用代理
### Extra info(if any)
(type here)
http直接0节点，因为http代理不支持其他花里胡哨的协议。
至于socks，只有少部分代理提供商能正常进行发现。

**Comment by c0re100** [comment]
libtorrent bug
https://github.com/qbittorrent/qBittorrent/issues/11735

**Comment by c0re100** [comment]
Upstream fixed.
