### ISSUE TITLE
為什麼無法兼容PT？

### ISSUE THREAD

**Issue by CoderCore** [c0re100/qBittorrent-Enhanced-Edition#115]
既需要PT下載，也需要BT下載。如果能兼容會很方便

**Comment by CoderCore** [comment]
不太理解，我只是想Autoban XUNLEI  為什麼會影響PT呢？

**Comment by CoderCore** [comment]
原來是被官方要求的 這就沒辦法了 [https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/70](url)

**Comment by 1970633640** [comment]
其实我觉得可以留个选项，让用户自己设置ua（当然自己编译源码也可以 不过麻烦很多），这样相当于用户行为，可以避开qbittorrent的条款限制

**Comment by c0re100** [comment]
> 其实我觉得可以留个选项，让用户自己设置ua（当然自己编译源码也可以 不过麻烦很多），这样相当于用户行为，可以避开qbittorrent的条款限制

自行設定UA會令到整個qBittorrent被PT封鎖
當初PT沒許可QB也是這個原因

**Comment by neoblackxt** [comment]
> > 其实我觉得可以留个选项，让用户自己设置ua（当然自己编译源码也可以 不过麻烦很多），这样相当于用户行为，可以避开qbittorrent的条款限制
> 
> 自行設定UA會令到整個qBittorrent被PT封鎖 當初PT沒許可QB也是這個原因

反正可以自定义了，为啥还要局限于qBittorrent啊，可以自定义成transmission、utorrent等等。我就不信pt还能全ban了，自己出个闭源加密的私有协议客户端玩吗？就大部分pt的技术力连允许客户端怎么改可能都不知道，或者知道也懒得改。
