### ISSUE TITLE
应用开启的时候从网址自动更新trackers那里时长是空的

### ISSUE THREAD

**Issue by qw4096** [c0re100/qBittorrent-Enhanced-Edition#117]
如图
![QQ截图20200423233827](https://user-images.githubusercontent.com/13681655/80119098-d65cb580-85bb-11ea-8b00-a7d87dbf0820.png)
应用打开的时候红框这里经常是空的，过一会才会添加trackers进去，但是之前开启的下载就没有添加trackers，只能过后再手动添加。

**Comment by c0re100** [comment]
Race condition問題，暫時無意對此作出修改
你連接到jsdelivr太慢的關係，在加入新種子後，因trackers list還沒取得而無法自動新增trackers
建議換一個對於你的網絡連接比較快的trackers list網站

**Comment by qw4096** [comment]
好的，我试试

**Comment by qw4096** [comment]
我测了下不管是jsdelivr.net还是trackerslist.com，网页打开都挺快的，ping的速度也可以，但软件打开还是时常出现trackers是空的，现在我把qb设置为开机启动了，一方面是避免下载拉起的时候出现这种情况，另一方面也是多做种
有个想法不知道行不行，每次从tracker list网站更新下来的trackers可以保存下来，而检查tracker更新的时候，只要成功把tracker list更新下来了，才用新的替换旧的，这样就不会出现没有list可用的情况了。

**Comment by c0re100** [comment]
v4.2.5.11
`Public trackers list caching`
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/tag/release-4.2.5.11
