### ISSUE TITLE
上游更新到4.2.5了

### ISSUE THREAD

**Issue by 123336-mike** [c0re100/qBittorrent-Enhanced-Edition#118]
。。。。

**Comment by abcfy2** [comment]
咋突然变版本帝了。4.2.1到4.2.2等了小半年，4.2.4到4.2.5就三天？

**Comment by 123336-mike** [comment]
> 咋突然变版本帝了。4.2.1到4.2.2等了小半年，4.2.4到4.2.5就三天？

我也感觉很奇怪

**Comment by c0re100** [comment]
> 咋突然变版本帝了。4.2.1到4.2.2等了小半年，4.2.4到4.2.5就三天？

4.2.4 share limit代碼有問題會直接Crash
這幾小時內會更新到4.2.5
