### ISSUE TITLE
I want optional banning μTorrent web

### ISSUE THREAD

**Issue by bakamosokyo** [c0re100/qBittorrent-Enhanced-Edition#121]
Could you add a option for banning μTorrent web too? 
Ofc it will be disabled by default.

**Comment by c0re100** [comment]
Why ban uTorrent Web?
As I know, uTorrent Web is using Libtorrent 1.2.2 and FFmpeg for streaming.
Just like normal torrent client(Download first&last piece and watch the video).

**Comment by bakamosokyo** [comment]
> Why ban uTorrent Web?
> As I know, uTorrent Web is using Libtorrent 1.2.2 and FFmpeg for streaming.
> Just like normal torrent client(Download first&last piece and watch the video).

It will automatically reset progress to 0%. I have rarely see such thing on other clients, including uTorrent desktop.

I don't know why it behaves like this, it's not every time, but this do happen pretty often.
It seems normal at start, but after maybe 15%, it will reset progress to 0%. Then after another 15%, it will repeat this again and again.

No need for me to explain how would it affects BT network.

**Comment by c0re100** [comment]
I guess I can implement a option for banning BitTorrent Player.

**Comment by c0re100** [comment]
> I guess I can implement a option for banning BitTorrent Player.

[v4.2.5.11](https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/tag/release-4.2.5.11) released.
`Auto ban BitTorrent Media Player[Default: OFF]` (Options>Advanced)
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/d9e4ae9ce6dcaf4411afc452742e2dbfd0239537/src/base/bittorrent/session.cpp#L2249
Cause libtorrent does not support WebTorrent right now, so let it go and ban μTorrent web first :)
