### ISSUE TITLE
请问有地方调节这个软件额外功能的设置吗

### ISSUE THREAD

**Issue by wuyu112233** [c0re100/qBittorrent-Enhanced-Edition#122]
这几个功能有额外调节的设置吗？设置里找不到

Auto Ban Xunlei，QQ，百度，Xfplay，DLBT和离线下载器

自动禁止来自中国的未知对等项选项（默认：关闭）

显示跟踪器身份验证窗口（默认值：开）

自动更新公共跟踪器列表（默认：关闭）

**Comment by c0re100** [comment]
Auto Ban不能動
自動禁止未知: 選項>進階
身份驗證: 4.2後已經沒有這個選項
Tracker: 選項>BitTorrent
