### ISSUE TITLE
单项下载上传速度显示不准确

### ISSUE THREAD

**Issue by StrollStars** [c0re100/qBittorrent-Enhanced-Edition#123]
qB：v4.2.5.10
Win7：32bit

当下载速度归零时（接近也是），单项下载上传速度还停留在先前的速度，但是下方状态栏显示的总速度是正确的，也就是说明细的速度加总和状态栏的总速度会对不上。
![2020-05-11_183438](https://user-images.githubusercontent.com/10942225/81552541-3faf3780-93b6-11ea-9ecf-c0d3615b6f9a.jpg)

**Comment by c0re100** [comment]
已知問題
CORE部分要等upstream處理
