### ISSUE TITLE
建议自动更新trackers服务里列表能增加手动按钮

### ISSUE THREAD

**Issue by StrollStars** [c0re100/qBittorrent-Enhanced-Edition#124]
如题，位置在“选项→BitTorrent”最下方，就像IP过滤功能一样，在路径右侧增加一个手动更新按钮，以便在程序自动获取不到列表的时候可以手动更新。当然上面那个框一定程度上可以替代，但是感觉用更新按钮更好，上方更适合填写永久性服务器。

PS1：希望简体中文翻译能更完善些。
PS2：可有还在更新的IP过滤文件下载地址？有些能找到的qB不能完全支持，而且列表太大完全拖累性能。还是说用qB自带的2018年5月文件就行？

**Comment by c0re100** [comment]
下個版本會加入此功能

1. 目前此版本沒有transifex等翻譯平台，所以額外功能都以英文為主........
2. 用自帶就可以

**Comment by qw4096** [comment]
我想问一下，哪些可以tracker可以作为永久的啊

**Comment by StrollStars** [comment]
@c0re100 谢谢

@qw4096 估计不存在这样的服务器，除非是自建。
