### ISSUE TITLE
切换网络  DHT 节点失效  需要重启下qbittorent

### ISSUE THREAD

**Issue by uniquepengpeng** [c0re100/qBittorrent-Enhanced-Edition#125]
**Please provide the following information**

### qBittorrent version and Operating System
mac 10.15.4, qbittorrent v4.2.5.10(64)

### If on linux, libtorrent-rasterbar and Qt version
(type here)

### What is the problem
在A地,启动qbittorrent,发现N个DHT节点. 电脑休眠,在B地(网络环境改变),DHT节点变成0.需要重启qbittorrent客户端软件,才可重新发现DHT节点.

### What is the expected behavior
DHT节点自动刷新

### Steps to reproduce
如上问题描述

### Extra info(if any)
(type here)

**Comment by c0re100** [comment]
DHT問題 請回報到libtorrent issue tracker
