### ISSUE TITLE
最新版本无法ban迅雷客户端

### ISSUE THREAD

**Issue by RJTT233** [c0re100/qBittorrent-Enhanced-Edition#128]
**Please provide the following information**

### qBittorrent version and Operating System
4.2.5.11

### What is the problem
无法ban迅雷客户端

### What is the expected behavior
不应该出现迅雷客户端
![image](https://user-images.githubusercontent.com/49860456/83322250-aa9eb080-a288-11ea-8dd0-ad1e91931847.png)

**Comment by c0re100** [comment]
請先安裝回舊版(4.2.5.10)，調查中

**Comment by c0re100** [comment]
移到 #127 繼續
