### ISSUE TITLE
有办法获取较旧版本的安装包吗？

### ISSUE THREAD

**Issue by Hubedge** [c0re100/qBittorrent-Enhanced-Edition#129]
### qBittorrent version and Operating System
4.1.9.4, Windows 10 x64

### What is the problem
4.1.9.4 是某PT站支持的最后一个qb版本，但该版本的build已从release页面移除。有其他渠道获取吗？

**Comment by c0re100** [comment]
沒有
另外
`Please do not use this modification bittorrent client for Private Trackers, you will get banned.`
