### ISSUE TITLE
w_libt_1.0版本有什么特别之处呢？

### ISSUE THREAD

**Issue by fnscar** [c0re100/qBittorrent-Enhanced-Edition#13]
是指with libtorrent 1.0吗？

**Comment by c0re100** [comment]
是的
因為libtorrent 1.1在使用IPv4+IPv6情況下會回報Port 0至Tracker
如果你有使用Private Tracker的話, 請使用w_libt_1.0版本

**Comment by SeaHOH** [comment]
请问对普通 Tracker 影响大吗？是不是其它客户端都不会主动连过来？

**Comment by c0re100** [comment]
> 请问对普通 Tracker 影响大吗？是不是其它客户端都不会主动连过来？

1. 使用普通的Tracker的話 影響不大, IPv6至今仍未普及....有用IPv6的只佔少數...............
2. 在回報Port 0情況下，其他用戶就會不能主動連接

**Comment by SeaHOH** [comment]
谢谢解答！
正准备换 qbittorrent，以前一直用 utorrent 老版本，7 年了都。

我刚才实际试了下 1.1 的正常版本，发现 v4 和 v6 都正确监听了。
然后，下载一个种子，观察到有出现只有`U I`标志，而没有`X``H`等多余标志的客户端。
做种的时候，也会有许多只有单个`U``P`标志的客户端，不过只有部分能上传，且速度很慢。
请问这是不是说明回报给 Tracker 的端口是正确地？

**Comment by SeaHOH** [comment]
没有X``H等多余标志的客户端，是不是就是用回报给 Tracker 的端口直接连入？
我这个 Tracker 请求能看到`port=8999`，是正确吗？
![x2scrap2](https://user-images.githubusercontent.com/8470820/45585470-539a5180-b8d4-11e8-97e9-749ddeb496b3.png)

**Comment by c0re100** [comment]
1. 是的
2. 正確

**Comment by c0re100** [comment]
> 我这个测试的就是 1.1 版本，这说明 bug 已经修复了？

沒有
因為是隨機出現的

**Comment by SeaHOH** [comment]
写了个脚本来尝试修复这个问题，我不下载 Private，不知道效果如何，需要的可以测试下。
https://gist.github.com/SeaHOH/2f21930db5a613a4fac315f560f814e5
