### ISSUE TITLE
版本号没有更新,仍为4.2.1.10

### ISSUE THREAD

**Issue by RealXuChe** [c0re100/qBittorrent-Enhanced-Edition#131]
version:Archlinux AUR qbittorrent-enhanced-nox-git-4.2.5.12.r0.g0e9d4197d-1

Webui->Help->About中显示的版本为`qBittorrent v4.2.1.10 Web UI (Enhnaced Edition) (64-bit)`

cli显示版本号也不对:
```
➜  ~ qbittorrent-nox -v
qBittorrent v4.2.1.10
```

**Comment by c0re100** [comment]
似乎是yay cache?
https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/89

**Comment by RealXuChe** [comment]
log显示的也是`4.2.1.10`......
CleanBuild后问题解决.
(为什么我的yay总是能出这么多问题啊!

**Comment by c0re100** [comment]
> log显示的也是`4.2.1.10`......
> CleanBuild后问题解决.
> (为什么我的yay总是能出这么多问题啊!

我下次更新試試再加一行 `git pull` 看看怎樣
