### ISSUE TITLE
数字显示乱码

### ISSUE THREAD

**Issue by WhiteDante** [c0re100/qBittorrent-Enhanced-Edition#132]
**Please provide the following information**

### qBittorrent version and Operating System
Windows 10 Pro 2004(19041)  x64 

### What is the problem
部分数字显示乱码，且是有规律的乱码，比如1会显示为<，2会显示为>，以此类推
![图片](https://user-images.githubusercontent.com/23722833/83974010-be978180-a91c-11ea-933c-405f46e6dd2c.png)

如图，其他数字正常，但所有关于“速度”与“文件大小”的数字会为乱码
### What is the expected behavior
数字正常显示

### Steps to reproduce
(type here)

**Comment by c0re100** [comment]
看來跟你的系統語言有關，不是qBittorrent問題
轉區大概應解決這個問題了

**Comment by WhiteDante** [comment]
谢谢，出现问题的系统语言是“简体中文（中华人民共和国）”；将语言切换为“简体中文（新加坡）”后问题解决。
推测是Qt语言包的问题？

**Comment by Love-TNT** [comment]
可以参考这篇文章，我用这个办法解决了https://blog.csdn.net/Fan1534/article/details/136763533
