### ISSUE TITLE
执行日志里的错误。

### ISSUE THREAD

**Issue by gozap99** [c0re100/qBittorrent-Enhanced-Edition#133]
> qBittorrent Enhanced v4.2.5.12

> Windows 10 Version 2004

`2020/6/11` 1:02 - 无法监听 IP：::，端口：TCP/6889。原因：使用了与请求的协议不兼容的地址。

`2020/6/11` 1:02 - 无法监听 IP：::，端口：TCP/6889。原因：通常每个套接字地址(协议/网络地址/端口)只允许使用一次。

**Comment by c0re100** [comment]
正常的
之後那一句日誌就顯示成功監聽了
