### ISSUE TITLE
已下载的文件删掉后会重新下载

### ISSUE THREAD

**Issue by qw4096** [c0re100/qBittorrent-Enhanced-Edition#134]
标题可能有歧义，就是删掉已下载的文件后（不是在qb里删除）qb里的下载任务会重新下载，怎么设置才能让软件不会再重新下载啊，现在删除完文件后还要到qb里取消任务

**Comment by c0re100** [comment]
沒有
還有為何不直接在qb內刪除任務呢.......

**Comment by qw4096** [comment]
> 
> 
> 沒有
> 還有為何不直接在qb內刪除任務呢.......

就是有时候硬盘满了，就用everything搜索不用的资源，在里面删除，回到qb里来找嫌麻烦。然后删掉后发现qb这边种子又重新再下载了只能手动删掉

**Comment by c0re100** [comment]
> > 沒有
> > 還有為何不直接在qb內刪除任務呢.......
> 
> 就是有时候硬盘满了，就用everything搜索不用的资源，在里面删除，回到qb里来找嫌麻烦。然后删掉后发现qb这边种子又重新再下载了只能手动删掉

.......
請你直接從QB刪除好了
因為在做種狀態下，檢測到種子有損壞的話，就會自動下載缺失的部分
