### ISSUE TITLE
做种时，连接里面出现奇怪的用户

### ISSUE THREAD

**Issue by ghost** [c0re100/qBittorrent-Enhanced-Edition#136]
**Please provide the following information**

### qBittorrent version and Operating System
v4.2.5.12 | windows 10 2004

### What is the problem
做种时，连接的用户里面多次出现端口统一为**50321**的客户端类型未知，PeerID未知的用户，并且与我的客户端建立了有效的连接。

具体的图片链接: https://pan.baidu.com/s/1VRoG3c5C0T83HH_5vdmh2A 提取码: rvgh

**Comment by c0re100** [comment]
看來是某client的預設port及開啟了匿名模式
