### ISSUE TITLE
软件闪退

### ISSUE THREAD

**Issue by mingmengyuan** [c0re100/qBittorrent-Enhanced-Edition#137]
**Please provide the following information**

### qBittorrent version and Operating System
(type here)4.2.5.10版本windows

### If on linux, libtorrent-rasterbar and Qt version
(type here)

### What is the problem
(type here)软件闪退

### What is the expected behavior
(type here)打开设置，

### Steps to reproduce
(type here)

### Extra info(if any)
(type here)有时有，有时又没有

**Comment by c0re100** [comment]
有crash log嗎?
