### ISSUE TITLE
BUG导致无法正常关机

### ISSUE THREAD

**Issue by oscarwty** [c0re100/qBittorrent-Enhanced-Edition#139]
### qBittorrent version and Operating System
QEE 4.2.5.12
Windows 10 LTSC 2019 (1809 Build17763.1282) x64

### What is the problem
偶尔退出后还有残留进程，任务栏等已经不显示，任务列表也全部停止
关机时显示QEE保存种子状态中，阻碍正常关机（会在一段时间后退回桌面）
需要强制结束进程或者强制关机，不能正常自己结束进程
偶发，并不是每次都有，很难给出复现条件

**Comment by c0re100** [comment]
原版也會有相同情況，所以..........我也沒辦法了乁 ˘ o ˘ ㄏ

**Comment by f1ume** [comment]
我4.2.5.12也有过，还试了4.1.9.17 x64也一样，然后再试了32位版4.2.5.11没有。比较一下发现win版4.2.5.12和4.1.9.17里的libtorrent是1.1.14，32位4.2.5.11带的libtorrent是1.2.6会不会跟这个有关？32位4.2.5.11至今没发现这情况

**Comment by oscarwty** [comment]
啧，我才发现这个bug甚至会影响到下载完成自动关机……
那我岂不是很难出门无值守挂机了

**Comment by mhtvsSFrpHdE** [comment]
> 
> 
> 原版也會有相同情況，所以..........我也沒辦法了乁 ˘ o ˘ ㄏ

@c0re100 把结束进程的功能移动到外部或是找原版去修？
如下载完成时运行以下（每隔5分钟检查特定列表中是否全部下载完成）
```
taskkill /f /im program.exe
shutdown /s /t 60
````

**Comment by oscarwty** [comment]
> 
> 
> > 原版也會有相同情況，所以..........我也沒辦法了乁 ˘ o ˘ ㄏ
> 
> @c0re100 把结束进程的功能移动到外部或是找原版去修？
> 如下载完成时运行以下（每隔5分钟检查特定列表中是否全部下载完成）
> 
> ```
> taskkill /f /im program.exe
> shutdown /s /t 60
> ```

我觉得会造成意想不到的问题，现在还是小bug，如果在不希望关机的时候关机就问题大了

**Comment by c0re100** [comment]
嗯，強制關閉會導致resume data填零
你下次開啟qBt的時候就會重新檢查一大堆種子了

**Comment by oscarwty** [comment]
> 
> 
> 嗯，強制關閉會導致resume data填零
> 你下次開啟qBt的時候就會重新檢查一大堆種子了

我查了一下官方，基本都指向这个
https://github.com/qbittorrent/qBittorrent/issues/5097#issuecomment-637595127
但是（可能是我没看懂），里面似乎没有提到解决方法？

**Comment by mhtvsSFrpHdE** [comment]
就是那样 我们知道 qBittorrent-Enhanced-Edition 改于 qBittorrent，而qBittorrent又改于libtorrent，  
因此，当一个qBittorrent或qBittorrent-Enhanced-Edition使用包括1.2.4以及以下版本的libtorrent时，将具有此未修复的bug。

当libtorrent为1.2.5以及以上时，似乎已经被修复（但此bug可能由于多种原因导致，他们修了其中一个）。
首先尝试更新libtorrent（咨询您的分支维护人员），当已经是1.2.5以及以上后，仍然遇到这样的问题，  
就到对应的分支下提出问题和确认不是由分支导致后，进一步到上游的libtorrent中提出问题。

**Comment by c0re100** [comment]
> 就是那样 我们知道 qBittorrent-Enhanced-Edition 改于 qBittorrent，而qBittorrent又改于libtorrent，
> 因此，当一个qBittorrent或qBittorrent-Enhanced-Edition使用包括1.2.4以及以下版本的libtorrent时，将具有此未修复的bug。
> 
> 当libtorrent为1.2.5以及以上时，似乎已经被修复（但此bug可能由于多种原因导致，他们修了其中一个）。
> 首先尝试更新libtorrent（咨询您的分支维护人员），当已经是1.2.5以及以上后，仍然遇到这样的问题，
> 就到对应的分支下提出问题和确认不是由分支导致后，进一步到上游的libtorrent中提出问题。
> 
> libtorrent方面的维护人员无法确认所有问题对应的版本，因此目前全部关闭相关问题。
> 要求使用1.2.5以及以上的同时仍然出现此问题再提问。

4.2.5是用libtorrent 1.2.6

**Comment by oscarwty** [comment]
> 
> 
> > 就是那样 我们知道 qBittorrent-Enhanced-Edition 改于 qBittorrent，而qBittorrent又改于libtorrent，
> > 因此，当一个qBittorrent或qBittorrent-Enhanced-Edition使用包括1.2.4以及以下版本的libtorrent时，将具有此未修复的bug。
> > 当libtorrent为1.2.5以及以上时，似乎已经被修复（但此bug可能由于多种原因导致，他们修了其中一个）。
> > 首先尝试更新libtorrent（咨询您的分支维护人员），当已经是1.2.5以及以上后，仍然遇到这样的问题，
> > 就到对应的分支下提出问题和确认不是由分支导致后，进一步到上游的libtorrent中提出问题。
> > libtorrent方面的维护人员无法确认所有问题对应的版本，因此目前全部关闭相关问题。
> > 要求使用1.2.5以及以上的同时仍然出现此问题再提问。
> 
> 4.2.5是用libtorrent 1.2.6

请问4.2.5.13修复了吗

**Comment by f1ume** [comment]
> 请问4.2.5.13修复了吗

新版libtorrent更新到1.2.8了。好像没有再出现这个了

**Comment by oscarwty** [comment]
> 
> 
> > 请问4.2.5.13修复了吗
> 
> 新版libtorrent更新到1.2.8了。好像没有再出现这个了

![Snipaste_2020-08-06_17-00-10](https://user-images.githubusercontent.com/6859653/89512854-62f75080-d806-11ea-8bb8-73d290628ef3.png)

真的耶，我试试看

**Comment by oscarwty** [comment]
@c0re100  我看见说明了，这issue我自行关闭了，没问题吧？

> 我突然發現4.2.5.12用錯了libtorrent 1.1.14來編譯......
等等會更新到4.2.5.13...........
