### ISSUE TITLE
无法编译nox版本

### ISSUE THREAD

**Issue by BecodReyes** [c0re100/qBittorrent-Enhanced-Edition#140]
### qBittorrent version and Operating System
qBittorrent-Enhanced-Edition [#e97259f](https://github.com/c0re100/qBittorrent-Enhanced-Edition/commit/e97259fdba10cdc42f037f2ac75a8274c3b9cf62)
CentOS Linux release 7.4.1708 @ Proxmox VE特权LXC

### If on linux, libtorrent-rasterbar and Qt version
libtorrent-rasterbar-1.2.4
Qt-5.9.7

### What is the problem
无法编译nox版本

### Steps to reproduce
./configure --prefix=/usr --disable-gui CPPFLAGS=-I/usr/include/qt5 --with-boost=${DIR_BOOST} CXXFLAGS=--std=c++14
make

### Extra info(if any)
[https://pastebin.com/ei7PSaTp](https://pastebin.com/ei7PSaTp)
先前编译原版qBittorrent使用此套配置可正常编译运行

**Comment by c0re100** [comment]
如果不使用`--disable-gui`能編譯嗎?

**Comment by BecodReyes** [comment]
> 如果不使用`--disable-gui`能编译吗？

可以的
第一次编译没加`--disable-gui`可正常编译安装
[root@qBittorrent qBittorrent-Enhanced-Edition]# ls src|grep qbittorrent
qbittorrent
qbittorrent.exe.manifest
qbittorrent.rc
qbittorrent_mingw.rc

**Comment by BecodReyes** [comment]
重新clone&configure后正常安装
不知道为什么先不加参数make出一个可执行文件后再加--disable-gui会编译失败
