### ISSUE TITLE
A new client fake

### ISSUE THREAD

**Issue by SeaHOH** [c0re100/qBittorrent-Enhanced-Edition#144]
https://github.com/frostwire/frostwire/issues/921

Fake ID, zero completed progress.

**Comment by c0re100** [comment]
> [frostwire/frostwire#921](https://github.com/frostwire/frostwire/issues/921)
> 
> Fake ID, zero completed progress.

Any details? e.g. Peer ID, User-Agent

**Comment by SeaHOH** [comment]
utorrent did not shown Peer ID and User-Agent directly.
In this case, I guess that Peer ID is "FW" or User-Agent is "FW/6.8.5.3".

**Comment by c0re100** [comment]
https://github.com/frostwire/frostwire/blob/master/common/src/main/java/com/frostwire/bittorrent/BTEngine.java#L154
PeerID look like `-FW6850-`
UA: `FrostWire/6.8.5 libtorrent/1.2.7`
Currently, I don't have any information about this "client", so I can't take a action right now.
It's easy to false ban normal forstwire user.

**Comment by SeaHOH** [comment]
> PeerID look like `-FW6850-`
> UA: `FrostWire/6.8.5 libtorrent/1.2.7`

This is the origin, no version 6.8.5.3 was released.

**Comment by SeaHOH** [comment]
The PeerID is `-FW6853-`, gubatron gave me a wrong answer.
