### ISSUE TITLE
qt.network.ssl: Incompatible version of OpenSSL on Ubuntu20.04

### ISSUE THREAD

**Issue by Provissy** [c0re100/qBittorrent-Enhanced-Edition#146]
**Please provide the following information**

### qBittorrent version and Operating System
v4.2.5.13

### If on linux, libtorrent-rasterbar and Qt version
`libqt5gui5/focal,now 5.12.8+dfsg-0ubuntu1 amd64`
`libssl1.1/focal,now 1.1.1f-1ubuntu2 amd64`

### What is the problem
Log
```
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: Incompatible version of OpenSSL
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed

```

### What is the expected behavior
Runs with no error logged, like v4.1.9

### Steps to reproduce
Run using the AppImage version.

### Extra info(if any)
There is no such error logged using v4.1.9, everything looks fine.

**Comment by Provissy** [comment]
It seems that SSL 1.1 has became default since Qt 5.12.4. Could you please check your build configuration of the AppImage recipe?

**Comment by c0re100** [comment]
Reproduced.
Look like AppImage dosen't use package included OpenSSL library.
ping @abcfy2

**Comment by abcfy2** [comment]
Sure. Wait.

**Comment by abcfy2** [comment]
I can't reproduce this issue. How did you run AppImage?

![VirtualBox_ubuntu-focal_03_08_2020_12_08_26](https://user-images.githubusercontent.com/5327677/89145108-421ec900-d582-11ea-9495-4d0a32cd79f4.png)

**Comment by abcfy2** [comment]
Seems that the [ppa:beineri/opt-qt-5.14.2-xenial](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.14.2-xenial) use `openssl 1.0` for building Qt, maybe I should switch to the official qt building.

**Comment by abcfy2** [comment]
Fixed. Please wait for pull request.
