### ISSUE TITLE
[建议] 弃用自 qt 5.15 起废弃的函数（上游 PR#12969）

### ISSUE THREAD

**Issue by IceCodeNew** [c0re100/qBittorrent-Enhanced-Edition#148]
如题，我在自行静态编译 qbEE 的过程中遇到的这个问题，qt 5.15 推出是 5 月底的事了，希望能尽快跟上上游的动作，弃用旧的函数。

Refer to: https://github.com/qbittorrent/qBittorrent/pull/12969

**Comment by c0re100** [comment]
> 如题，我在自行静态编译 qbEE 的过程中遇到的这个问题，qt 5.15 推出是 5 月底的事了，希望能尽快跟上上游的动作，弃用旧的函数。
> 
> Refer to: [qbittorrent#12969](https://github.com/qbittorrent/qBittorrent/pull/12969)

這個等4.2.6就好了
4.2.5可以cherrypick一下
我等等push上來
