### ISSUE TITLE
[bug]手动屏蔽无效

### ISSUE THREAD

**Issue by zhibinr** [c0re100/qBittorrent-Enhanced-Edition#149]
**Please provide the following information**

### qBittorrent version and Operating System
qBittorrent-Enhanced-Edition v4.2.5.13
widnows

### What is the problem
手动屏蔽无效，对方依然在列表里

**Comment by TurnOffNOD** [comment]
+1，同样出现了这个问题。手动屏蔽的ip已经出现在了Options-Connection-Manually banned IP address 里面了。

**Comment by c0re100** [comment]
請移至 #127 集中處理。
