### ISSUE TITLE
qB 3.3.16.5 memory leak

### ISSUE THREAD

**Issue by KozakaiAya** [c0re100/qBittorrent-Enhanced-Edition#15]
**Please provide the following information**

### qBittorrent version and Operating System
Ubuntu 16.04

### If on linux, libtorrent and Qt version
libtorrent 1.0.11

### What is the problem
Memory Leak

### What is the expected behavior
(type here)

### Steps to reproduce
When I was using qb 3.3.16.3, it can be kept running for a couple of months with stable memory usage. But when I switched to 3.,3.16.5 with same configuration, the memory usage keeps going up.

### Extra info(if any)
(type here)

**Comment by Vstory** [comment]
Why not upgrade to the latest version?
