### ISSUE TITLE
有两个xunlei客户端自动屏蔽无效？

### ISSUE THREAD

**Issue by TurnOffNOD** [c0re100/qBittorrent-Enhanced-Edition#150]
### qBittorrent version and Operating System
qBittorrent Enhanced Edition 4.2.5.13
OS：win10(2004)

### What is the problem
有好几个ip地址上用的是“-XL0012-乱码”客户端，peer ID都是-XL0012-，等了十几分钟，有两个ip还是没有自动屏蔽掉。

### What is the expected behavior
这两个ip应该自动屏蔽。

### Steps to reproduce
没有条件复现……

### Extra info(if any)
![Capture](https://user-images.githubusercontent.com/2140029/89706657-5f94ce00-d99a-11ea-97f6-eb9ca7d1d287.PNG)

图中有上传速度的两个就是我说的自动屏蔽无效的“钉子户”，这是等了十几分钟了自动屏蔽都还没有生效，另外的同样是-XL0012-但是没有上传的两个ip还在观察，可能能够被自动屏蔽，也有可能同样有问题。

**Comment by Simba98** [comment]
![image](https://user-images.githubusercontent.com/7941967/89710258-d7bbbd80-d9b3-11ea-82e6-34b826c74a48.png)

我觉得我能复现，我感觉-XL0012-的都屏蔽不掉

**Comment by c0re100** [comment]
無法重現...
另外，情況與 #127 相同
這邊先關掉
