### ISSUE TITLE
Torrents red after reboot

### ISSUE THREAD

**Issue by NiackZ** [c0re100/qBittorrent-Enhanced-Edition#151]
**Please provide the following information**

### qBittorrent version and Operating System
qbit: 4.2.5.13
win: Win 10.0.18363

### What is the problem
After rebooting the application, some torrents will become red with the "no files" error. This problem hinders the application because after checking the files, the torrents are stopped and not seeding.

### What is the expected behavior
(type here)

### Steps to reproduce
Reboot the app
![2020-08-14_17-34-59](https://user-images.githubusercontent.com/14057913/90249880-ada34900-de54-11ea-9ec2-0502dcafd208.png)

### Extra info(if any)
(type here)

**Comment by c0re100** [comment]
Look like libtorrent verify resume data issue.
I will provide test build to you by tmr.

**Comment by c0re100** [comment]
`v4.2.5.13+libtorrent1.2 baface889`
[test build](https://drive.google.com/file/d/1dwDARRhiihorZEgtOU1XLnKBje3y_u9P/view?usp=sharing)

**Comment by NiackZ** [comment]
> `v4.2.5.13+libtorrent1.2 baface889`
> [test build](https://drive.google.com/file/d/1dwDARRhiihorZEgtOU1XLnKBje3y_u9P/view?usp=sharing)

Yep, now all fine! Thanks
