### ISSUE TITLE
设置代理服务器并保存设置会导致QB崩溃退出

### ISSUE THREAD

**Issue by rihalvnium76** [c0re100/qBittorrent-Enhanced-Edition#155]
### qBittorrent version and Operating System
qBEE v4.2.5.15 (new) x64
win10 x64 ltsc 2019 [10.0.17763.1217]

### What is the problem
先前不使用代理，设置代理服务器并保存设置时，会导致QB崩溃退出
无论代理是否能够正常连接

设置：
SOCKS5 127.0.0.1 1080
勾选 使用代理服务器进行用户连接
勾选 只对torrent使用代理设置

**Comment by rihalvnium76** [comment]
![image](https://user-images.githubusercontent.com/57667144/92343677-f28a6a80-f0f6-11ea-88d6-28a02ae6abb8.png)

**Comment by c0re100** [comment]
有crash report嗎?

**Comment by f1ume** [comment]
关闭upnp/nat-pmp也会立刻crash，之后每次退出都crash，日志里也没有upnp的信息不知道启用还是关闭了。重新打开upnp才正常。

**Comment by c0re100** [comment]
可能是boost1.74問題
我晚上試試用回1.73看看會怎樣。。。。

**Comment by rihalvnium76** [comment]
> 有crash report嗎?

没有，直接闪退
