### ISSUE TITLE
导入qBEE4.2.5.13的下载队列记录导致qBEE启动闪退

### ISSUE THREAD

**Issue by rihalvnium76** [c0re100/qBittorrent-Enhanced-Edition#156]
### qBittorrent version and Operating System
qBEE v4.2.5.15 (new) x64
win10 x64 ltsc 2019 [10.0.17763.1217]

### What is the problem
直接从4.2.5.13升级到新4.2.5.15后，打开qbEE闪退
然后完全卸载qBEE，并全新安装新4.2.5.15
这时启动正常
把旧版的BT_backup目录覆盖现在的BT_backup
然后启动闪退

**Comment by rihalvnium76** [comment]
![image](https://user-images.githubusercontent.com/57667144/92344504-39795f80-f0f9-11ea-94f9-c61a44bac5bd.png)
<br/>

**Comment by rihalvnium76** [comment]
似乎是读取旧版的*.fastresume文件导致崩溃

**Comment by rihalvnium76** [comment]
尝试重新导入种子，并选择之前的下载文件夹，在校验数据到62.5%时，qBEE崩溃
源文件大小2.26GB，下载到97%左右

换另外一个种子，大小3.21GB，下载完成，导入校验到91.3%时qBEE崩溃

**Comment by c0re100** [comment]
請先用回4.2.5.10 :'(

**Comment by rihalvnium76** [comment]
> 請先用回4.2.5.10 :'(
> 另外，有crash report嗎?

怎么看crash report?

**Comment by c0re100** [comment]
> > 請先用回4.2.5.10 :'(
> > 另外，有crash report嗎?
> 
> 怎么看crash report?

正常情況下，崩潰後應該會跳出一個stacktrace的錯誤報告
我試到同樣情況，不過沒這個報告，所以有點束手無策😔
如果有人有的話，可上傳到這裡

**Comment by rihalvnium76** [comment]
> > > 請先用回4.2.5.10 :'(
> > > 另外，有crash report嗎?
> > 
> > 
> > 怎么看crash report?
> 
> 正常情況下，崩潰後應該會跳出一個stacktrace的錯誤報告
> 我試到同樣情況，不過沒這個報告，所以有點束手無策😔
> 如果有人有的話，可上傳到這裡

没有跳出任何的报错弹窗，直接闪退  
系统日志显示如下：  
![image](https://user-images.githubusercontent.com/57667144/92364433-a60a5380-f125-11ea-8f16-b93715350bbe.png)

**Comment by c0re100** [comment]
已確認是boost 1.74問題
降到1.73就沒問題了

**Comment by c0re100** [comment]
已更新至4.2.5.16~
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/tag/release-4.2.5.16

**Comment by marleeang1992** [comment]
求问，旧版本qb总是崩溃，下载新版本后丢失之前全部记录，手里种子文件也删光了
如何把旧下载目录下的文件导入并继续下载，谢谢
