### ISSUE TITLE
Windows版本被Chrome/Edge浏览器报告不安全

### ISSUE THREAD

**Issue by abcfy2** [c0re100/qBittorrent-Enhanced-Edition#157]
![image](https://user-images.githubusercontent.com/5327677/92425663-7b1e0f00-f1ba-11ea-92f9-07991add5e9e.png)

不知道用的什么封装的exe安装包，被浏览器认为不安全

**Comment by c0re100** [comment]
Windows版是用NSIS封裝的
反正都是誤判，官方版本剛更新也會有這樣情況出現
等病毒特徵庫更新就好了(大概

**Comment by wordlesswind** [comment]
![Microsoft Defender SmartScreen 报告此应用不是常见的下载，应仅打开信任的文件。](https://user-images.githubusercontent.com/9050713/94346261-f65a3e80-005d-11eb-9b28-1d661de8b9d5.png)
这种问题没有什么解决方案，因为它的原话是“Microsoft Defender SmartScreen 报告此应用不是常见的下载，应仅打开信任的文件。”。
如果是这个标准的话，大概不是大多数人会下载的文件都会被阻止。
你可以选择在 `edge://settings/privacy#section_services` 中关闭“Microsoft Defender Smartscreen”。
![Microsoft Defender Smartscreen](https://user-images.githubusercontent.com/9050713/94346321-6ec0ff80-005e-11eb-8393-3063b96d159b.png)
当然你也可以选择“将此应用报告为安全”。
![将此应用报告为安全](https://user-images.githubusercontent.com/9050713/94346327-7ed8df00-005e-11eb-8e69-7b8a062871b2.png)
