### ISSUE TITLE
Trackers status "Updating..."

### ISSUE THREAD

**Issue by NiackZ** [c0re100/qBittorrent-Enhanced-Edition#158]
**Please provide the following information**

### qBittorrent version and Operating System
qbit: 4.2.5.16
win: Win 10.0.18363

### What is the problem
After installation 4.2.5.16, the state of trackers is always "Update...". The rollback on 4.2.5.14 did not help. This problem is not for all trackers, but those that used to work now hang with the status "Update...".

### What is the expected behavior
(type here)

### Steps to reproduce
Dunno, i just upgrade from 4.2.5.14 to 4.2.5.16. I attached the archive with the screenshots.
[screens.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/5192753/screens.zip)

### Extra info(if any)
(type here)

**Comment by NiackZ** [comment]
Weird... after ~30 min a lot of trackers up to "Working" status. If there are no status issues until tomorrow, I'll close the thread, sorry.

**Comment by c0re100** [comment]
How many torrents did you have?
It look like too much tracker announce request in progress and not finish yet.
Cause `max_concurrent_http_announces`is 50 [libtorrent default value].
So you need to wait another tracker announce request response/timeout, then libtorrent update those "updating...." trackers.

Tonight, I will cherry pick #13319 and provide test build to you(set higher value for `max_concurrent_http_announces`).
It may solve tracker update problem.

**Comment by NiackZ** [comment]
> How many torrents did you have?
> It look like too much tracker announce request in progress and not finish yet.
> Cause `max_concurrent_http_announces`is 50 [libtorrent default value].
> So you need to wait another tracker announce request response/timeout, then libtorrent update those "updating...." trackers.
> 
> Tonight, I will cherry pick [qbittorrent#13319](https://github.com/qbittorrent/qBittorrent/pull/13319) and provide test build to you(set higher value for `max_concurrent_http_announces`).
> It may solve tracker update problem.

1252 torrents
Maybe you're right and I should wait. It would be nice if the "max_concurrent_http_announces" parameter could be set by itself in the settings.
In any case, I will wait for your test build, I hope it will help.

**Comment by c0re100** [comment]
> > How many torrents did you have?
> > It look like too much tracker announce request in progress and not finish yet.
> > Cause `max_concurrent_http_announces`is 50 [libtorrent default value].
> > So you need to wait another tracker announce request response/timeout, then libtorrent update those "updating...." trackers.
> > Tonight, I will cherry pick [qbittorrent#13319](https://github.com/qbittorrent/qBittorrent/pull/13319) and provide test build to you(set higher value for `max_concurrent_http_announces`).
> > It may solve tracker update problem.
> 
> 1252 torrents
> Maybe you're right and I should wait. It would be nice if the "max_concurrent_http_announces" parameter could be set by itself in the settings.
> In any case, I will wait for your test build, I hope it will help.

test build:
```
qb: 4.2.5.16+max_concurrent_http_announces
libt: 1.2.10+aa3faed
```
https://drive.google.com/file/d/1WPg11iXe8lgaOw92rUWZvlGHT5lsYOYs/view?usp=sharing

Also raise the maximum value to 200

**Comment by NiackZ** [comment]
@c0re100 Thank you, now the trackers are more quickly updated
