### ISSUE TITLE
Fail to compile with latest libtorrent version

### ISSUE THREAD

**Issue by tuapuikia** [c0re100/qBittorrent-Enhanced-Edition#165]
**Please provide the following information**

### qBittorrent version and Operating System
Qbittorrent 4.2.5.16

### If on linux, libtorrent-rasterbar and Qt version
Linux: libtorrent 1.2.10

### What is the problem
Error when try to compile it using libtorrent 1.2.10

resumedatasavingmanager.o: In function `int libtorrent::detail::bencode_recursive<Utils::IO::FileDeviceOutputIterator>(Utils::IO::FileDeviceOutputIterator&, libtorrent::entry const&)':
/usr/include/libtorrent/bencode.hpp:165: undefined reference to `libtorrent::entry::dict[abi:cxx11]() const'
tracker.o: In function `BitTorrent::Tracker::prepareAnnounceResponse(BitTorrent::Tracker::TrackerAnnounceRequest const&)':                                                     
./build-nox/src/../../src/base/bittorrent/tracker.cpp:452: undefined reference to `libtorrent::entry::entry(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, libtorr
ent::entry, libtorrent::aux::strview_less, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, libtorrent::entry> > >)'
tracker.o: In function `BitTorrent::Tracker::prepareAnnounceResponse(BitTorrent::Tracker::TrackerAnnounceRequest const&)':
/usr/include/c++/7/ext/new_allocator.h:136: undefined reference to `libtorrent::entry::entry(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, libtorrent::entry, lib
torrent::aux::strview_less, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, libtorrent::entry> > >)'
tracker.o: In function `BitTorrent::Tracker::processRequest(Http::Request const&, Http::Environment const&)':

### What is the expected behavior
Compile without error

### Steps to reproduce
(type here)

### Extra info(if any)
(type here)

**Comment by abcfy2** [comment]
Try recompile libtorrent with `CXXFLAGS='-std=c++14'`

**Comment by tuapuikia** [comment]
I recompile it with libtorrent CXXFLAGS='-std=c++14 and it working now. Thank you!
