### ISSUE TITLE
Debian Linux custom repo (aka PPA) suggestion

### ISSUE THREAD

**Issue by Kolcha** [c0re100/qBittorrent-Enhanced-Edition#166]
[Debian repo mentioned in README](https://repo.debiancn.org/pool/main/q/qbittorrent-enhanced/) seems to be abandoned and now contains obsolete packages...

So I setup [my own repo](https://software.opensuse.org//download.html?project=home%3Anikoneko%3Aqbittorrent-nightly&package=qbittorrent-enhanced) with qBittorrent Enhanced Edition packaged for various Debian Linux versions and architectures. currently supported list of Debian distro variant can be found [here](https://build.opensuse.org/package/show/home:nikoneko:qbittorrent-nightly/qbittorrent-enhanced). feel free to ask me for adding some other variants.

Repo includes both qBittorrent variants: GUI and headless (daemon, nox): `qbittorrent-enhanced` and `qbittorrent-enhanced-nox` packages. Debug symbols are also available if someone is interested in.

Build process is automated, when new commits appear, it will start. Check for new commits happens each day. So, this repo provides "nightly builds".

This repo also contains libtorrent-rasterbar compiled from latest commits (also checked each day) from RC_1_2 branch. Official latest (unstable, compiled from master branch) qBittorrent also exists in this repo.

Full list of packages in this repo can be found [here](https://build.opensuse.org/project/show/home:nikoneko:qbittorrent-nightly).

**Comment by c0re100** [comment]
README updated~~~
Thank you!
