### ISSUE TITLE
这个是吸血客户端吗？

### ISSUE THREAD

**Issue by wgzeyu** [c0re100/qBittorrent-Enhanced-Edition#17]
![](https://wgzeyu.gtxcn.com/img/dlbt.png)
区块大小256KB，按文件大小算也已经传了14.7%给他，却回报0%

**Comment by SeaHOH** [comment]
是的，手动屏蔽。

**Comment by wgzeyu** [comment]
这个客户端也是国内的，查了下好像叫点量BT

**Comment by Satan023** [comment]
thx 算是让我知道一个新的吸血玩意儿

**Comment by SeaHOH** [comment]
qb 的日志显示不像 ut 有队列限制，屏蔽数量多了以后，内存使用大增，UI 性能作急。
硬伤，像我这种不关机的只能每天手动清除。

**Comment by Satan023** [comment]
请问这个问题是出现在手动屏蔽IP还是说加强版有这个问题？

**Comment by c0re100** [comment]
抱歉 過了這麼久才處理這個問題...

經測試後發現
DLBT是會回傳假的進度 甚至是永遠的0%

而 #18 所說的播放器亦使用DLBT作為BT下載工具之一
![dlbt](https://user-images.githubusercontent.com/5726473/48727099-3daa6380-ec6c-11e8-884f-e8cf6979ddb7.png)

依上圖所示 已符合吸血特徵
大家可以升級到最新版本以自動封鎖方式處理
