### ISSUE TITLE
建议修改下客户端名字太长了

### ISSUE THREAD

**Issue by loading1688** [c0re100/qBittorrent-Enhanced-Edition#170]
老大你好！能不能修改增强版名字为"qBittorrent/4.3.0++"这样！要不看到同类显示一长串名字qBittorrent/4.2.5 Enhanced Edition
一看就知道屏蔽迅雷的！迅雷伪装特意来吸血！
谢谢

**Comment by c0re100** [comment]
我不覺得長，所以不會改
