### ISSUE TITLE
Ban Xunlei, QQ, Baidu, Xfplay, DLBT and Offline downloader

### ISSUE THREAD

**Issue by cjjdaq** [c0re100/qBittorrent-Enhanced-Edition#174]
**Please provide the following information**

### qBittorrent version and Operating System
(type here)

### If on linux, libtorrent-rasterbar and Qt version
(type here)

### What is the problem
可以加个开关吗？是否打开Ban Xunlei, QQ, Baidu, Xfplay, DLBT and Offline downloader

### What is the expected behavior
(type here)

### Steps to reproduce
(type here)

### Extra info(if any)
(type here)

**Comment by luojunyuan** [comment]
加开关干嘛，难道还要选择性的给这些下载器贡献宽带吗🙄

**Comment by cjjdaq** [comment]
对于专门做种的来说。如果是热门的资源，那也就无所谓ban不ban迅雷这些了。但对于冷门的资源来说。如果你不让迅雷尽快保存到它自己服务器上，那可能需要做很久时间的种子。我认为最好就是能像qb本身的超级种子模式一样，针对每一个种子可以增加一个比如”超级分享模式“，用来ban这些客户端。，毕竟国内还是迅雷的天下，完全用bt的人是越来越少，对于冷门资源，不可能自己长期保种。最终的目的还是要把资源分享出去。现在bt已经都迅雷给玩坏了。不是靠一小部分人能再回到以前的样子。

**Comment by SeaHOH** [comment]
看你写了这么多，没搞明白到底要表达个什么意思。既然不想屏蔽渣雷，为什么还要使用这个增强版？而且大多数发布都属于最想干掉渣雷的那一拨吧，出种速度和头几天的下载完成率，是否屏蔽吸血结果差别很大好不好。还有那个冷门资源是什么意思，你指望渣雷给你保种？！

**Comment by cjjdaq** [comment]
就是将增强版的功能做成类似”超级做种模式“一样，可以自由对每一个种子是否启用。

**Comment by SeaHOH** [comment]
不是，你要这样的功能有什么用，或者说你就是要给渣雷续种？这对整个生态有什么好处吗，真的看不懂你的思路，请详细说明。功能肯定可以实现，但要实施需要足够的说服力。

**Comment by cjjdaq** [comment]
生态？都被迅雷给玩坏了。哪还来的生态。要生态就玩pt。
现在做种基本都是迅雷能离线了，就撤种了。
对于一个本来下载人数就三两个人的种子。而且还是都开的迅雷，都ban掉，那自己保种要保到什么时候呢。
对于一个本来下载人数就特别多的种子，这个时候我就需要ban掉所有吸血的。只要纯bt客户端去下载，因为这样也会很快出种，迅雷离线服务器要吸也去吸别人。
https://s1.ax1x.com/2020/11/01/B05DNF.png

**Comment by c0re100** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/5#issuecomment-388323963

**Comment by abcfy2** [comment]
这种需求完全没有意义，不想屏蔽这些客户端你用qb原版不就好了吗。用qbee不就是希望带有客户端屏蔽和ipfilters的功能吗？

**Comment by SeaHOH** [comment]
PT 我是看不起的。
你这种情况还保什么保，按自己的计划来不就行了，渣雷没得下岂不活该。

**Comment by lucktu** [comment]
我也赞成楼主的想法，有时候需要迅雷来帮忙续种，有时候又要毙了它。

否则如楼上的各位所说，那就只好用两个以上的bt软件来实现另外的想法了。

**Comment by abcfy2** [comment]
> 我也赞成楼主的想法，有时候需要迅雷来帮忙续种，有时候又要毙了它。
> 
> 否则如楼上的各位所说，那就只好用两个以上的bt软件来实现另外的想法了。

你在想屁吃，迅雷不会给你续种的，不然你以为为什么叫吸血雷？一个吸血的客户端会续种？

**Comment by ungluee** [comment]
> > 我也赞成楼主的想法，有时候需要迅雷来帮忙续种，有时候又要毙了它。
> > 否则如楼上的各位所说，那就只好用两个以上的bt软件来实现另外的想法了。
> 
> 你在想屁吃，迅雷不会给你续种的，不然你以为为什么叫吸血雷？ 一个吸血的客户端会续种？

会的，只不过他不传给其他客户端

**Comment by cjjdaq** [comment]
观察到现阶段的情况就是  BT软件/迅雷/网盘 的占比大概是 1/6.5/2.5
作为常年资源发布者来说，当一个资源从BT上发布出来，最理想的情况是自己能够尽快撤种。继续发布新的资源，而非长期保种。
如果这个资源下载的人很多。这里面就包含一部分使用bt软件下载的，有使用迅雷下载的，也有网盘离线下载的。这个时候屏蔽掉迅雷后完全不会影响这个资源的分享。因为还有一部bt用户在提供上传。
如果这个资源下载的人很少，三五个人的，而且都是迅雷用户。这个时候软件全局屏蔽掉了迅雷就会导致这个资源完全分享不出去。
这个时候就体现出上面所说的针对单个种子启用“超级分享模式”的灵活性。而非当前全局一刀切。
作为资源发布者主要是屏蔽的那些异常刷量的（用PBH即可）。楼上的种种大部分是站在下载者位考虑而没有考虑到资源发布者遇到的现实情况。


从几年发布资源的过程中来看，就是国内用bt客户端下载的很多也是杜绝上传，或者把上传速度限制的非常小。

![1](https://github.com/user-attachments/assets/a3b08ea9-6544-45d5-b90f-31f01d1dbe7f)
![2](https://github.com/user-attachments/assets/92615109-795c-4579-a87f-0b01aeda5312)

**Comment by SeaHOH** [comment]
> 作为资源发布者主要是屏蔽的那些异常刷量的（用PBH即可）。楼上的种种大部分是站在下载者位考虑而没有考虑到资源发布者遇到的现实情况。

别人刷 PCDN 的还把你的下限刷低了，那你直接用渣雷发好了，撤种超级快。我们这些人还真不稀罕，还能指望你发钱？

**Comment by cjjdaq** [comment]
> 别人刷 PCDN 的还把你的下限刷低了，那你直接用渣雷发好了，撤种超级快。我们这些人还真不稀罕，还能指望你发钱？

可笑
