### ISSUE TITLE
开机启动项名称与原版相同，使得只可设置其中一个成功自启动

### ISSUE THREAD

**Issue by zhongfly** [c0re100/qBittorrent-Enhanced-Edition#175]
**Please provide the following information**

### qBittorrent version and Operating System
v4.3.0.10（64 bit）
windows10

### If on linux, libtorrent-rasterbar and Qt version
(type here)

### What is the problem
该版本的开机启动项的名称与原版相同。
原版的开机自启设置后，该版本的设置也会与之同步勾选。
如果在原版勾选，在Enhanced-Edition中也会被自动勾选，但通过任务管理器中的“启动”-选择qBittorrent这一项-“打开文件所在位置”可以知道，其实只有原版被设置为自启动。
在Enhanced-Edition中取消勾选，则原版亦会取消勾选。

### What is the expected behavior
原版的开机自启设置与该版本无影响：即原版勾选开机自启后，该版本不会同步勾选

### Steps to reproduce
0.两个版本的qBit均不勾选开机启动
1.原版勾选开机启动，并确定
2.打开Enhanced-Edition版，发现也被勾选了开机启动

### Extra info(if any)
None

**Comment by c0re100** [comment]
因為原版與EE皆使用同一個config
要多開的話，建議分開不同config處理
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_3_x/NOTE.md#multiple-instances-tutorial

然後，自動啟動問題無解了...
直接用捷徑方法處理吧..........
現在才改這些東西的話(安裝路徑/qbittorrent檔名)，只會影響全部EE用家
