### ISSUE TITLE
建议 cherry-pick 上游 #13738，否则在最新的 libtorrent RC_1_2 分支上编译会失败

### ISSUE THREAD

**Issue by IceCodeNew** [c0re100/qBittorrent-Enhanced-Edition#178]
如题，相关 PR 在这里：https://github.com/qbittorrent/qBittorrent/pull/13738
问题详情可参见 https://github.com/qbittorrent/qBittorrent/issues/13737

**Comment by c0re100** [comment]
> 如题，相关 PR 在这里：[qbittorrent#13738](https://github.com/qbittorrent/qBittorrent/pull/13738)
> 问题详情可参见 [qbittorrent#13737](https://github.com/qbittorrent/qBittorrent/issues/13737)

Done~
