### ISSUE TITLE
屏蔽dandanplay/8.6.2.0这类播放器

### ISSUE THREAD

**Issue by tnti** [c0re100/qBittorrent-Enhanced-Edition#18]
弹弹play这类播放器的边下边播应该是不上传的... 居然还来吸血
![](http://wx4.sinaimg.cn/mw690/7979e806gy1fw5k2wxolwj211h032aaq.jpg)

**Comment by SeaHOH** [comment]
没用过，从这张截图看不出来。
你这是正在做种吧，是如何判断吸血的？

**Comment by tnti** [comment]
一般尿性来说 没几个开着播放器做种的 我看见过有开着播放器做种的 很少

**Comment by SeaHOH** [comment]
确实是吸血，先前没注意进度是 0。

**Comment by tnti** [comment]
这播放器挺奇葩的 下完片子还会做种 我开着另一台电脑重新下的时候看见这个播放器做种...  问题是有多少人开着播放器做种 我就看见有一个而已

**Comment by SeaHOH** [comment]
有些吸血和设置有关，可能这个播放器也是吧。

**Comment by wgzeyu** [comment]
有时候下片子能看见几个dandanplay做种

**Comment by c0re100** [comment]
ref: #17
