### ISSUE TITLE
code for handling ipfilter.dat

### ISSUE THREAD

**Issue by Kolcha** [c0re100/qBittorrent-Enhanced-Edition#184]
again I had some free to spend on hobby, and decided to review another enhanced feature offered by your fork - IP filtering.
I read the code and found no reason to keep it at all (especially file parser): official qBittorrent already has it and it able to parse files in exactly the same format (I'm using your file downloaded from [here](https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/tag/release-4.2.1.10) with official qBittorrent). your implementation just loads a file from specific location, nothing more, everything else is duplication of already existing logic. so, I suggest just to drop this logic and use existing:
![Screenshot from 2020-11-29 01-50-34](https://user-images.githubusercontent.com/947647/100527667-5f3c6f00-31e5-11eb-9db4-46a5c43dc0c8.png)
this option is also available through the WebUI.

your fix/workaround mentioned in https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/127#issuecomment-684132844 I think also can be safely removed now, a lot of time passed and affected users already fixed their .fastresume files.

moreover, the origin of #127 as I understood was caused by wrong libtorrent version used for 4.2.5.11/12, but workaround was appeared due to libtorrent bug (what was fixed in 1.2.9 or 1.2.10), so I think now is completely safe to drop this obsolete code and make your life more easier :smile: I'll prepare corresponding PR slightly later.

P.S> please don't think that I can read Chinese :smile_cat: , I only can recognize Chinese/Japanese/Korean hieroglyphs, nothing more. I just used Google Translate to translate it into English (because machine translations from Asian languages into Russian very often lead to meaningless and funny phrases, but English at least readable)

**Comment by c0re100** [comment]
About ipfilter.dat:
Cause I'm trying to avoid conflict with user own IP filter, user maybe using different format like p2p and p2b, so I use same logic for loads a file from specific location.

As I know, ipfilter.dat [last updated at 2/5/2017](https://www.emulefans.com/offline-server-ip-170205/).
I guess that file is outdated and no longer maintenance(?).
So It is safely to remove right now.
Let users merge them to own IP filter file if needed.

FYI
QQ Xuan Feng(Aka Tencent offline): shutdown at 2018.
115: server moved to Aliyun at 2018, may change to Aliyun IP now. (I'm not sure)
UC Offline and Huawei: shutdown at 2016.
360: shutdown at 2017.

About my workaround, I'm planning to remove it in the next version.

**Comment by Kolcha** [comment]
thanks for the information about the source of that file and that it is outdated... I stopped using it, peer filter should be enough.

P.S> I'm using one more peer filter rather than I provided for you. it is based on the same code, but provide different logic. I'll plan to suggest it, but slightly later, it is under heavy testing for now.
