### ISSUE TITLE
希望能增加便携版

### ISSUE THREAD

**Issue by lleeopen** [c0re100/qBittorrent-Enhanced-Edition#188]
希望能增加便携版，方便重装系统后不需要再设置~~~

**Comment by c0re100** [comment]
你可以用7z解壓安裝檔裡的exe及pdb，然後新增一個portable資料夾在同一位置，再打開qB就是便攜版了

**Comment by abcfy2** [comment]
Same as: https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/4#issuecomment-566849820

**Comment by escape0707** [comment]
这个issue可以关一下的。
