### ISSUE TITLE
编译的时候出错帮忙看一下

### ISSUE THREAD

**Issue by zhiblin** [c0re100/qBittorrent-Enhanced-Edition#193]
### qBittorrent version and Operating System
4.3.x   macos 11.1

### If on linux, libtorrent-rasterbar and Qt version
libtorrent-rasterbar:  1.2.10   qt: 5.15.2

### What is the problem

linking qbittorrent.app/Contents/MacOS/qbittorrent
ld: warning: dylib (/usr/local/lib/libtorrent-rasterbar.dylib) was built for newer macOS version (11.0) than being linked (10.13)
ld: warning: dylib (/usr/local/lib/libboost_system.dylib) was built for newer macOS version (11.0) than being linked (10.13)
Undefined symbols for architecture x86_64:
  "_EVP_sha512", referenced from:
      __GLOBAL__sub_I_password.cpp in password.o
  "_OpenSSL_version", referenced from:
      Utils::Misc::opensslVersionString() in misc.o
  "_PKCS5_PBKDF2_HMAC", referenced from:
      Utils::Password::PBKDF2::generate(QByteArray const&) in password.o
      Utils::Password::PBKDF2::verify(QByteArray const&, QByteArray const&) in password.o
  "libtorrent::entry::entry(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, libtorrent::entry, libtorrent::aux::strview_less, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, libtorrent::entry> > >)", referenced from:
      BitTorrent::Tracker::processRequest(Http::Request const&, Http::Environment const&) in tracker.o
      BitTorrent::Tracker::prepareAnnounceResponse(BitTorrent::Tracker::TrackerAnnounceRequest const&) in tracker.o
      void std::__1::allocator_traits<std::__1::allocator<libtorrent::entry> >::construct<libtorrent::entry, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, libtorrent::entry, libtorrent::aux::strview_less, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, libtorrent::entry> > >&>(std::__1::allocator<libtorrent::entry>&, libtorrent::entry*, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, libtorrent::entry, libtorrent::aux::strview_less, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, libtorrent::entry> > >&) in tracker.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [qbittorrent.app/Contents/MacOS/qbittorrent] Error 1
make: *** [sub-src-make_first] Error 2

**Comment by c0re100** [comment]
libtorrent要用c++14編譯
