### ISSUE TITLE
QB里的 RSS订阅中，“忽略指定时间后的匹配项”这个功能到底是怎样的一个功能呢？

### ISSUE THREAD

**Issue by ddd-zero** [c0re100/qBittorrent-Enhanced-Edition#195]
选择禁用的时候，可以显示全部内容，而调整到一天，把所有的订阅全部过滤掉了
![QQ截图20201222020701](https://user-images.githubusercontent.com/57771987/102808086-bb686c80-43fa-11eb-8057-ccfb04bad8db.jpg)
![QQ截图20201222020713](https://user-images.githubusercontent.com/57771987/102808141-d804a480-43fa-11eb-9dd1-9d66dd6a2a17.jpg)
在订阅获取到的这些内容之中，有今天发布的，一天前发布的，两天前发布的。而开启过滤之后不管选几天全部都被过滤掉了。

下图是UT中右侧有更新时间
![QQ截图20201222020739](https://user-images.githubusercontent.com/57771987/102808310-1b5f1300-43fb-11eb-8483-bf6961a6e348.jpg)

**Comment by c0re100** [comment]
這個應該要配合Smart Episode Filter一起使用，避免RSS自動下載會重覆下載同一集劇集

詳細可看這2個網站
https://qbforums.shiki.hu/viewtopic.php?t=4658
https://cfzero.wordpress.com/2016/06/07/qbittorrent-rss-auto-episode-download/
