### ISSUE TITLE
Add filter to ban offline download servers of Xunlei, Baidu etc.

### ISSUE THREAD

**Issue by KozakaiAya** [c0re100/qBittorrent-Enhanced-Edition#2]
Recently, I encountered several clients who announce themselves as 'libtorrent 1.1.x' or '1.0.x'. I was really curious about them because I have never seen such clients before. However, after comparing their IP to a [known offline download server list](https://emulefans.com/offline-server-ip-170205/), I found that most of them are from Xunlei. 
So I suggest that the clients who announce them as LTxxxx with Chinese IP should be banned in the enhanced version of qBittorrent.

**Comment by c0re100** [comment]
Thanks for your information. 
The next enhanced version of qBittorrent will process this filter file on start-up. 
The filter file will be installed on the same path with qBittorrent, it can be replaced yourself if the filter file update released.

**Comment by KozakaiAya** [comment]
Is it a little bit not appropriate to put the `ipfilter.dat` under `/usr/bin` or `/usr/local/bin`?
Personally speaking, I feel `~/.config/qBittorrent` more reasonable for this file.

Anyway, thank you for your effort.

**Comment by kkwong7878** [comment]
師兄Good👍
