### ISSUE TITLE
专门登录账户，就为了说一句，安装好了，结果下载说只能下载小于100m文件？逗比。。。？

### ISSUE THREAD

**Issue by stevenlii** [c0re100/qBittorrent-Enhanced-Edition#202]
**Please provide the following information**

### qBittorrent version and Operating System
(type here)

### If on linux, libtorrent-rasterbar and Qt version
(type here)

### What is the problem
(type here)

### What is the expected behavior
(type here)

### Steps to reproduce
(type here)

### Extra info(if any)
(type here)

**Comment by pinyangcong** [comment]
你在说啥？？？
