### ISSUE TITLE
qBEE难以连上特定peer

### ISSUE THREAD

**Issue by rihalvnium76** [c0re100/qBittorrent-Enhanced-Edition#205]
**Please provide the following information**

### qBittorrent version and Operating System
qBEE v4.3.2.10  
Win10 x64 LTSC

### What is the problem
同一网络环境，同一种子，对同一peer，qBEE总是难以连上，或者连上后速度极低（10kib/s左右），或者连上没几秒就毫无征兆地突然断开了。  
![image](https://user-images.githubusercontent.com/57667144/103979842-970ddd80-51b9-11eb-9b7e-b27f5fdb5361.png)
而拿迅雷极速版（绿化版）1.0.35.366，却可以长期连接并保持较高下载速度。  
![image](https://user-images.githubusercontent.com/57667144/103979356-9d4f8a00-51b8-11eb-8f83-fc490eb9de34.png)

### What is the expected behavior
qBEE能与peer建立长效稳定、相对满速的连接

**Comment by SeaHOH** [comment]
好像不算问题吧。BT 下载速度主要是看 peer 多少，而不是每个连接都必须特别快，如果 peer 特别少只能碰运气看对方给你分配。渣雷明显作弊，不按规矩申请 piece。

**Comment by c0re100** [comment]
> 渣雷明显作弊，不按规矩申请 piece。

對，迅雷得一想二的做法又不是第一天的事
