### ISSUE TITLE
为什么udp的tracker都连不上? http的还可以, 怎么解决呢? 广电网

### ISSUE THREAD

**Issue by tess1199** [c0re100/qBittorrent-Enhanced-Edition#207]
**Please provide the following information**

### qBittorrent version and Operating System
(type here)

### If on linux, libtorrent-rasterbar and Qt version
(type here)

### What is the problem
(type here)

### What is the expected behavior
(type here)

### Steps to reproduce
(type here)

### Extra info(if any)
(type here)

**Comment by c0re100** [comment]
你的網絡問題，與軟件無關...
