### ISSUE TITLE
请问这个上传限速没用是bug吗？

### ISSUE THREAD

**Issue by iSteveyang** [c0re100/qBittorrent-Enhanced-Edition#21]
**Please provide the following information**

### qBittorrent version and Operating System
qbt：v 4.1.3.1
MacOS X 10.14

### If on linux, libtorrent and Qt version
(type here)

### What is the problem
我设置的限速没用

### What is the expected behavior
不上传那么快

![image](https://user-images.githubusercontent.com/20753221/47786443-c22d5480-dd46-11e8-9e53-b81a0dc50e5b.png)

**Comment by c0re100** [comment]
這3個選項有開到嗎?
![limit](https://user-images.githubusercontent.com/5726473/47789010-59e27100-dd4e-11e8-8633-54ad44a6f2be.png)
還是你是透過VPN連接?
如果是的話, 可能需要啟用最低那個 `Apply rate limit to peers on LAN` 才能限制上傳速度....
如果啟用後也不能限速, 請到[官方issues](https://github.com/qbittorrent/qBittorrent/issues)反映。

**Comment by iSteveyang** [comment]
> 這3個選項有開到嗎?
> ![limit](https://user-images.githubusercontent.com/5726473/47789010-59e27100-dd4e-11e8-8633-54ad44a6f2be.png)
> 還是你是透過VPN連接?
> 如果是的話, 可能需要啟用最低那個 `Apply rate limit to peers on LAN` 才能限制上傳速度....
> 如果啟用後也不能限速, 請到[官方issues](https://github.com/qbittorrent/qBittorrent/issues)反映。

多谢，没开过，现在好了
