### ISSUE TITLE
新的Qt构建期下载方案

### ISSUE THREAD

**Issue by abcfy2** [c0re100/qBittorrent-Enhanced-Edition#212]
自从qt进一步收缩了开源许可之后，download.qt.io似乎已经不可访问了，这导致了构建过程中下载qt全部失败，需要寻找新的qt下载方案。

这个issue先记录这个问题，回头找到方案之后通过PR关闭这个issue

**Comment by abcfy2** [comment]
https://www.qt.io/blog/problem-with-open-source-downloads

应该只是虚惊一场？如果真的如qt官方所说，下载恢复之后就关闭这个issue

**Comment by GoldJohnKing** [comment]
You might want to try this: [Another Qt Installer](https://github.com/miurahr/aqtinstall) (though I've never used it).

**Comment by abcfy2** [comment]
Thank you for your suggestion. I will review this project later.

**Comment by c0re100** [comment]
Unlucky, It is also using download.qt.io :see_no_evil:

**Comment by GoldJohnKing** [comment]
> Unlucky, It is also using download.qt.io 🙈

It's said to support downloading from Qt mirrors, see: https://aqtinstall.readthedocs.io/en/latest/cli.html#cmdoption-aqt-base.

This seems to be a valid mirror: https://mirrors.tuna.tsinghua.edu.cn/qt/.

**Comment by c0re100** [comment]
> > Unlucky, It is also using download.qt.io 🙈
> 
> It's said to support downloading from Qt mirrors, see: https://aqtinstall.readthedocs.io/en/latest/cli.html#cmdoption-aqt-base.
> 
> This seems to be a valid mirror: https://mirrors.tuna.tsinghua.edu.cn/qt/.

Oh sorry...
I haven't noticed that aqt can use a mirror as fallback.

**Comment by abcfy2** [comment]
似乎download.qt.io暂时恢复了，不过版本排列顺序给变了，不知道官方会不会还原到原来的样式，先让子弹飞一会儿吧。另外似乎由于上游限定必须C++17，所以之前按照C++14的编译方式有些地方编译出错了，这个和qt下载一并修复吧
