### ISSUE TITLE
技术小白希望可以提供 IP 屏蔽文件

### ISSUE THREAD

**Issue by QS0x01** [c0re100/qBittorrent-Enhanced-Edition#216]
请问 Enhanced-Edition 是根据什么规则来屏蔽迅雷等国产吸血客户端的呢？
有无可能提供 IP 过滤规则文件（.dat, .p2p, .p2b）用来导入官方客户端...？
或者有无办法使 Enhanced-Edition 与 Official-Edition 在同一系统内共存呢？
PT 站不允许使用客户端签名与官方不一致的版本，增强版本也没有便携版。

**Comment by QS0x01** [comment]
想了想好像还可以把官方版客户端的种子迁移到便携官方版客户端内，听说只用迁移一个文件夹。

**Comment by RikkaBlue** [comment]
用 docker 的 nox 版本
