### ISSUE TITLE
希望可以批量禁止客户端功能

### ISSUE THREAD

**Issue by Pantyhose-X** [c0re100/qBittorrent-Enhanced-Edition#217]
**Please provide the following information**

### qBittorrent version and Operating System
LibreTorrent-3.0-all.apk
Androird 

### What is the problem
@c0re100 你可以用这个可以[开源安卓版](https://github.com/proninyaroslav/libretorrent) 开发阻止迅雷的。[安卓版](https://github.com/proninyaroslav/libretorrent)的增强版吗？
> 例如  7.10.35.366
> -XL0012
> -XL0018
> Xunlei
这种软件不利于 Torrent 发展存活

**Comment by SeaHOH** [comment]
你列出的这都是渣雷，已经屏蔽了啊。
> # Features:
> 1. Auto Ban Xunlei, QQ, Baidu, Xfplay, DLBT and Offline downloader

**Comment by Survivalwar** [comment]
@SeaHOH 你可以使用这个可以[开源安卓版](https://github.com/proninyaroslav/libretorrent) 开发阻止渣雷的功能吗？
