### ISSUE TITLE
关于DLBT的吸血问题

### ISSUE THREAD

**Issue by SettingDust** [c0re100/qBittorrent-Enhanced-Edition#22]
DLBT开发者表示没有相关吸血操作，关于回报问题很大可能是**边下边播的类似模式调整了块优先级使回报产生错误**，一刀切DLBT是不是不太好？

**Comment by Vstory** [comment]
[https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/5](url)

**Comment by Vstory** [comment]
#5 #18

**Comment by c0re100** [comment]
#17 我沒說得太清楚吧.....
在 #17 中的測試, 除了彈彈play外，我亦有使用DLBT官方所提供的演示版本作為測試
`DLBT是會回傳假的進度 甚至是永遠的0%` > 演示版本正是後者
假設人們是使用這個演示版本的話........這樣也算是吸血吧?
