### ISSUE TITLE
疑似百度网盘离线下载功能吸血

### ISSUE THREAD

**Issue by nekomiya-hinata** [c0re100/qBittorrent-Enhanced-Edition#226]
### qBittorrent version and Operating System
qBittorrent 4.3.2.10 on Windows

### What is the problem
疑似百度网盘离线下载功能吸血，这几天在下载几个热门资源发现连接客户端异常，于是使用besttrace跟踪ip，发现目标为百度的某个地址，虽然有正常bt客户端的行为（汇报进度），但仍值得怀疑
出现过的几个IP地址为：119.167.161.38，119.167.161.70，119.167.161.101，119.167.161.6
疑似假冒客户端为 go.torrent dev 20181121，Peer ID：-GT0002-

### What is the expected behavior
希望能有更多的朋友能够一起来辨识一下，如果真是百度网盘的吸血能够加以屏蔽

**Comment by SeaHOH** [comment]
#190

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/145213910-9199a5d7-85a0-463c-acca-87a6014675de.png)

**Comment by SeaHOH** [comment]
这是祸害到国外了，真恶心。
这如果涉及版权，在日本起诉比中国容易胜诉吧。
