### ISSUE TITLE
dht节点怎么才能正确链接呢

### ISSUE THREAD

**Issue by cool-delete** [c0re100/qBittorrent-Enhanced-Edition#227]
**Please provide the following information**

### qBittorrent version and Operating System
qbee 4.3.3.10

### What is the problem
版本号是 qb e e4.3.3.10 最新版的

已有公网 ip 设置里面的端口监听是连通的

没有使用 upnp 端口 无论我怎么设置 openwrt 里面都看不到活跃的链接 查了 win 的 upnp 服务也是开启的 无果所以关了

热门的种子下了 Ubuntu 上传速度跑满了

dht 一直是 0 挂了有 2 天

#114 提到只要使用了代理就会用代理链接 dht 无论是否设置好代理  于是我也把代理关了吧 重新打开 qb 还是 dht 还是 0

![image](https://user-images.githubusercontent.com/13638610/111784428-5982aa80-88f6-11eb-8439-fa4509464722.png)

**Comment by escape0707** [comment]
你下载 ArchLinux 试试，那个默认没有 tracker。

**Comment by cool-delete** [comment]
> 你下载 ArchLinux 试试，那个默认没有 tracker。

emm 我投诉了运营商后恢复到400+了
