### ISSUE TITLE
为什么linux下的qbee速度上不去呢？

### ISSUE THREAD

**Issue by lucktu** [c0re100/qBittorrent-Enhanced-Edition#229]
大家来讨论一下，我在 ubuntu18.04_64 上和win7上运行qbee（ubuntu是有线连接，win是wifi连接），版本是一样的432，CPU性能、内存也是相近的，同一个局域网下，qbee上的设置也对照修改成一致的，差别就在一个是windows，一个ubuntu，然而下载速度相差却是十万八千里，ubuntu始终没有速度，5G大的文件一个晚上才下载50M的样子，后面根本就没有下载了，而windows版本的却要不了一个小时，就下载好了，这差距也太大了吧？

这是什么原因呢？ 有人遇到这样的问题吗？
1、ubuntu的防火墙挡住了它？
2、qbee因系统不一样，内部运行机制也是不一样的？
3、路由器对它们的友好度不一样？

**Comment by lucktu** [comment]
现在我用uTorrent，下载速度还可以，上传也还行，再配合下面的插件屏蔽迅雷，看起来简单方便，还可以自己修改规则，看起来还行（继续观察中）。
https://github.com/ShenHongFei/utorrent-block-xunlei

**Comment by lucktu** [comment]
给大家推荐一款BT软件，可以防雷，添加新雷特诊，还可以自定义封禁IP，只是全是英文版的：
Tixati
大家可以试试

**Comment by BackMountainDevil** [comment]
大伙防雷就是说经常用公种吗？一般私有站点都不会让没有账号的bt软件连接啊
