### ISSUE TITLE
这些是迅雷吗？

### ISSUE THREAD

**Issue by wordlesswind** [c0re100/qBittorrent-Enhanced-Edition#233]
### qBittorrent version and Operating System
qBittorrent Enhanced Edition 4.3.3.10, Windows 10 OS Version 2009 (Build 19042.868)

### What is the problem
出现了大量乱码 -XL0012- 客户端，还有无客户端标识，只有版本号的 7.10 开头的客户端

### Steps to reproduce
4D4137D910596294984F5CE68BDE8D06DEF888C8

![屏幕截图 2021-03-25 224243](https://user-images.githubusercontent.com/9050713/112492742-7c143800-8dbc-11eb-96b7-13a55e3ed485.png)

**Comment by wordlesswind** [comment]
找到了 #127 和 #150
我现在勾选了 Auto Ban Unknown Peer from China，但仍然在持续地给 -XL0012- 客户端做种。
![屏幕截图 2021-03-25 225557](https://user-images.githubusercontent.com/9050713/112493767-6a7f6000-8dbd-11eb-9963-448fea23ee77.png)

**Comment by c0re100** [comment]
轉到tracker看看是不是private torrent?
是的話就正常
檢查會略過private torrent

**Comment by wordlesswind** [comment]
> 轉到tracker看看是不是private torrent?
> 是的話就正常
> 檢查會略過private torrent

不好意思，我以为 private torrent 是必须要有密钥什么的才能够下载的，没想到是可以公开抓取的。
