### ISSUE TITLE
Peer ID tab change to "7"

### ISSUE THREAD

**Issue by Masaiki** [c0re100/qBittorrent-Enhanced-Edition#234]
**Please provide the following information**

### qBittorrent version and Operating System
4.3.4.10
Win10 20H2 x64

### If on linux, libtorrent-rasterbar and Qt version
(type here)

### What is the problem
Peer ID tab change to "7"

**Comment by c0re100** [comment]
damn....stupid merging
https://github.com/c0re100/qBittorrent-Enhanced-Edition/commit/f3cbc8ed5302eb30ab91112a7eae2b52f838091f#diff-1b2dbde7ab4daff0ac880f9dc26cb0603fc3a34a84f09e5225e4ca465377841f
Fix coming :'(
