### ISSUE TITLE
Libtorrent Rasterbar wanted by Qbitenhanced not available in AUR

### ISSUE THREAD

**Issue by squidds** [c0re100/qBittorrent-Enhanced-Edition#239]
**Please provide the following information**

### qBittorrent version and Operating System
Arch 

### If on linux, libtorrent-rasterbar and Qt version
I can't seem to get the correct libtorrent-rasterbar version installed to re-install qbit enhanced nox. It wan'ts a version higher than what is available on AUR and Arch Repos
### What is the problem
`(configure: error: Package requirements (libtorrent-rasterbar >= 1.2.12) were not met:

Package dependency requirement 'libtorrent-rasterbar >= 1.2.12' could not be satisfied.
Package 'libtorrent-rasterbar' has version '1.2.11', required version is '>= 1.2.12'

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libtorrent_CFLAGS
and libtorrent_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.`

### What is the expected behavior
(type here)

### Steps to reproduce
(type here)

### Extra info(if any)
(type here)

**Comment by c0re100** [comment]
Please remove community version and yay -S libtorrent-rasterbar-1_2-git

to compile newer libtorrent
