### ISSUE TITLE
自动Torrent管理是个啥

### ISSUE THREAD

**Issue by iAM261917** [c0re100/qBittorrent-Enhanced-Edition#24]
这个功能有什么用？如果没什么卵用的话，求把它从右键菜单里面去掉！
上百G的种子不小心点到这个真的是要死……

**Comment by c0re100** [comment]
https://qbforums.shiki.hu/index.php/topic,4388.msg22724.html#msg22724
你可以到qB `選項`>>`下載` 轉回手動模式。

**Comment by iAM261917** [comment]
> https://qbforums.shiki.hu/index.php/topic,4388.msg22724.html#msg22724
> 你可以到qB `選項`>>`下載` 轉回手動模式。

抱歉因为我刚才由于这个东西不得不强制关机然后还得打开qB尽快删除这个种子然后强制结束qB接着把被移动的文件弄回去然后再重新添加种子做种，所以有点暴躁。。。
不是很能理解链接里说的东西，似乎开启了这个模式之后文件会被自动归位？根据附加的子类？
但是我没有对这个Torrent进行任何的“附加子类”之类的操作，不小心点到这个，qB直接自动把我的Torrent的内容转移到C:\Users\xxx\Downloads下面去了，撑爆我的SSD。
而且我取消掉这个模式之后，移动文件的过程并没有停止，而且由于某些不知名原因系统直接卡死，所以我不得不强制关机，重新开机后再次打开qB，仍然继续移动文件的过程，我赶紧把这个Torrent删掉，结果移动文件的过程依然没有停止，我不得不到任务管理器里面强制结束qB的进程，然后把一些已经被移动的文件归位，再重新添加Torrent。

**Comment by iAM261917** [comment]
如果整个系统就一个盘还好……问题是现在SSD价格并不便宜的情况下，用两个盘是很正常的吧……

**Comment by iAM261917** [comment]
Sorry，我可能过激了

**Comment by c0re100** [comment]
> > https://qbforums.shiki.hu/index.php/topic,4388.msg22724.html#msg22724
> > 你可以到qB `選項`>>`下載` 轉回手動模式。
> 
> 抱歉因为我刚才由于这个东西不得不强制关机然后还得打开qB尽快删除这个种子然后强制结束qB接着把被移动的文件弄回去然后再重新添加种子做种，所以有点暴躁。。。
> 不是很能理解链接里说的东西，似乎开启了这个模式之后文件会被自动归位？根据附加的子类？
> 但是我没有对这个Torrent进行任何的“附加子类”之类的操作，不小心点到这个，qB直接自动把我的Torrent的内容转移到C:\Users\xxx\Downloads下面去了，撑爆我的SSD。
> 而且我取消掉这个模式之后，移动文件的过程并没有停止，而且由于某些不知名原因系统直接卡死，所以我不得不强制关机，重新开机后再次打开qB，仍然继续移动文件的过程，我赶紧把这个Torrent删掉，结果移动文件的过程依然没有停止，我不得不到任务管理器里面强制结束qB的进程，然后把一些已经被移动的文件归位，再重新添加Torrent。

是的 開啟這個模式後 種子會自動移到預設位置(視乎你的設定)
![2](https://user-images.githubusercontent.com/5726473/50551911-c7197080-0cc3-11e9-80cf-331934cf3d80.png)
在種子移動期間不能停止 直至完成為止
