### ISSUE TITLE
some xunlei client cannot auto-banning / 最近发现迅雷没有被自动屏蔽的问题

### ISSUE THREAD

**Issue by Minalinsky9-12** [c0re100/qBittorrent-Enhanced-Edition#248]
### qBittorrent version and Operating System
4.3.4.11 @ W10x64-20H2

### What is the problem
for the some Xunlei client not be banning, may rules for Xunlei need update?
最近发现一些迅雷客户端没有被自动屏蔽，大部分是Xunlei 0.0.1.8
有无可能由于迅雷更新的关系绕过了IP过滤？咱们的自动规则(qbee)是否需要更新？
由于不太确定是由于版本问题还是客户端问题，顺便请教如何排查？谢谢
已自我检查qbee设置没有发现可能存在的问题。

**Comment by abcfy2** [comment]
似乎是私有种子不会屏蔽迅雷，你可以看看你下的种子是不是私有的，看看trackers选项卡那里显示的是不是私有

**Comment by Minalinsky9-12** [comment]
> 似乎是私有种子不会屏蔽迅雷，你可以看看你下的种子是不是私有的，看看trackers选项卡那里显示的是不是私有

PT种子我只会使用原版qb的，公网种子才会用qbee，所以排除此情景

**Comment by c0re100** [comment]
> > 似乎是私有种子不会屏蔽迅雷，你可以看看你下的种子是不是私有的，看看trackers选项卡那里显示的是不是私有
> 
> PT种子我只会使用原版qb的，公网种子才会用qbee，所以排除此情景

公網也會有人用私有種子方式發佈的

**Comment by Kolcha** [comment]
feature from https://github.com/c0re100/qBittorrent-Enhanced-Edition/pull/238 can solve this issue, but it is NOT in 4.3.4.11, so wait for next release or build torrent client by yourself

P.S> I can't read Chinese, I just use Google Translate
