### ISSUE TITLE
Feature Request: 安装包默认不勾选 Install with Debug Symbol File

### ISSUE THREAD

**Issue by imba-tjd** [c0re100/qBittorrent-Enhanced-Edition#254]
**Please provide the following information**

### qBittorrent version and Operating System
4.3.5.10
Win10 21H2 x64

### What is the problem

![图片](https://user-images.githubusercontent.com/24759802/117384520-c1786900-af15-11eb-9239-1c4749d453f5.png)

### What is the expected behavior

![图片](https://user-images.githubusercontent.com/24759802/117384530-c9380d80-af15-11eb-9f48-90fd83ddb4d9.png)

**Comment by abcfy2** [comment]
我还是头一次见到这个安装界面，我一般都是用7-zip直接解开安装包就用了，绿色版，创建个`profile`目录就成了便携版了，随便怎么折腾

**Comment by yanuovo** [comment]
> 我还是头一次见到这个安装界面，我一般都是用7-zip直接解开安装包就用了，手工删除了debug文件，绿色版，创建了一个`profile`目录就变成了便携版了，随便怎么折腾

我不会安装 要怎么做才行呢

**Comment by c0re100** [comment]
當然是不可能 :)
有Install with Debug Symbol File選項已經是讓步了
參考 #201
