### ISSUE TITLE
Windows下可能是高分辨率屏导致的UI显示错位问题

### ISSUE THREAD

**Issue by zzz6839** [c0re100/qBittorrent-Enhanced-Edition#256]
**Please provide the following information**

### qBittorrent version and Operating System
WINDOWS 10 Version	10.0.19042 Build 19042

### If on linux, libtorrent-rasterbar and Qt version
(type here)

### What is the problem
![image](https://user-images.githubusercontent.com/57741549/117838601-0f41f800-b2ad-11eb-92a2-825f7fa2423a.png)
缩小再放大应用时，会出现UI显示错位的问题，并且因为错位导致无法正确点击按钮（鼠标要移到其他位置才能点击到）
UI misplaced If you minimize the application then maximize it, you need to move the mouse to other positions to click the setting button

### What is the expected behaviour
(type here)

### Steps to reproduce
缩小应用至状态栏或者任务栏一段时间再放大会产生这个问题，必须重启应用才能解决
Minimize/close the application for a while then maximize it cause this issue, to fix it, you must restart the application 

### Extra info(if any)
我双屏，其中一台2K屏，一台4K屏，日常在4K屏下操作该应用，可能是这个原因导致的
This issue may be caused by dual screen usage since I have 2K and 4K screen running at the same time, but I mainly use the application on the 4K one

**Comment by c0re100** [comment]
Yes, due to your 2K and 4K environment :'(
Unfortunately, It's Qt bug, so can't fix.
https://github.com/qbittorrent/qBittorrent/issues/12960
