### ISSUE TITLE
DNS Resolver

### ISSUE THREAD

**Issue by BLLuis** [c0re100/qBittorrent-Enhanced-Edition#259]
### qBittorrent version and Operating System
qBittorrent Enhnaced Edition v4.3.0.10 Web UI Enhanced Edition (64-bit), Debian 10 headless.

### If on linux, libtorrent-rasterbar and Qt version
Self contained in qBittorrent-nox v4.3.0.10

### What is the problem
Headless Debian box with two nics, each one with its own dns, if I config qBittorrent to use NIC B it wont resolve names until DNS server of NIC B is listed first on /etc/resolv.conf, the same happen if I config qBittorrent to use NIC A and the first dns listed in resolv.conf is the one for NIC B. Some ppl at #debian on irc explained to me that glibc resolver use the first ip of resolv.conf, and I think that its a nonsense to use the dns of NIC A if I want to go via NIC B.
I've tested the same with curl using --interface option and nothing happens until I use --dns-interface or --dns-servers.
So, I think that curl and qBittorrent with options to use NIC B try to resolve hostnames using NIC A, or using the IP of dns/a on the NIC B, I really don't know but it doesn't work when I select NIC B and my resolv.conf list NIC A dns address first or viceversa.

### What is the expected behavior
Let me config the ip/interface of the dns to use like I can config the nic to use.

### Steps to reproduce
explained in the problem

### Extra info(if any)
Works well on windows, Can't use a newer version on Linux because some errors with some libraries, so, stuck on 4.3.10.

**Comment by c0re100** [comment]
I think that dns issue belong to libtorrent itself?

**Comment by BLLuis** [comment]
> I think that dns issue belong to libtorrent itself?

Yes, sorry, I just take a look on libtorrent and they use Boost.ASIO for name resolution, this Boost library didn't allow to select the resolver, and found an entry on Deluge issues asking the same, the worst thing is that there is no issues about this on Boost, so, this limit will be for years.
