### ISSUE TITLE
Prebuild static binary for armhf/arm64

### ISSUE THREAD

**Issue by mzhboy** [c0re100/qBittorrent-Enhanced-Edition#26]
**Please provide the following information**

### qBittorrent version and Operating System
qBittorrent version:ALL
Operating System:Debian/Ubuntu/Armbian
Hardware:arm based SBCS

### Extra info(if any)
It's difficult to build successfully on those SBCs due to the 1GB（or even less） memory limitation.
Would you please provide a static build binary(without GUI ofcourse) for those boards.

**Comment by c0re100** [comment]
Sorry, I don't know how to cross compile(x86>ARM) :(
