### ISSUE TITLE
你好, qBittorrent-Enhanced-Edition有没有单独的反吸血插件？

### ISSUE THREAD

**Issue by tulei770415** [c0re100/qBittorrent-Enhanced-Edition#262]
你好,，我的系统是win7 x86，使用qBittorrent-Enhanced-Edition总是崩溃，从去年一直到今年都有这个问题，升级到最新版本还是一样，问一下有没有单独的反吸血插件，这样我可以安装官方原版qBittorrent，然后安装反吸血插件就可以了，希望给个答复，多谢了。

**Comment by SeaHOH** [comment]
插个题外话，官方版本在 Win7 上不会无故崩溃，你是长时间使用过了吗？我是 64 位的 WIn7，之前也试过加强版，跟你一样总是崩溃，系统也会同时挂掉。我还以为是 qBittorrent 本身就这样，没有测试官方版本。

因为实在无法忍受 uTorrent 越来越莫名其妙的 bug，现在我正使用 Tixati，它也可以屏蔽吸血客户端。

**Comment by tulei770415** [comment]
官方版本去年试过不会无缘无故奔溃，我还发邮件询问过官方，官方答复说是修改版本的原因，但是官方版本没有反吸血插件速度慢，所以只能选择修改版本qbittorrent，我还以为只有我自己遇到这个问题，看来还有别人也遇到这个问题，希望作者给个答复，能够给一个反吸血插件就好了，再次谢谢作者了！

**Comment by c0re100** [comment]
沒有
另外，有沒有Enhanced的崩潰報告?

**Comment by SeaHOH** [comment]
Tixati
现在正在用，感觉还行。
优点主要是每个任务和分类有很多可以单独设置的参数，还提供一些独特的自动化设置；缺点是不开源，文档不够详细，操作略繁琐。

uTorrent 3
需要配合我之前写的 [Python 脚本](https://github.com/SeaHOH/ban-peers)使用，提供更全面的反吸血功能。
优点是上手容易，资源占用少；缺点是 uTorrent 也不开源，还需要自己动手去捆绑、去广告，bug 也很多，长期不修复。如果孙宇晨那个小人能及时修复 bug 的话，我还是很愿意使用它的。
如果它的 bug 不太影响你的使用，可以尝试一下。主要是无法禁止优先下载文件头尾小机率导致下载卡住，切换多文件 torrent 部分下载时内部记录无法重置导致重复下载之前下载文件的头尾，还有一些普通用户不太用到的设置。

qBittorrent
需要配合相应的 [Python 脚本](https://github.com/SeaHOH/ban-peers#related-projects)使用，这几个好像都只是反迅雷。
优点是开发活跃，上手容易；缺点是实现过于死板 (自认为，因为在关键问题上影响到我使用了，我不想使用 UPNP/NAT-PMP 功能，但作者不愿意提供监听 `0.0.0.0` 和 `::` 的权限) 。

Bitcomet
没怎么用过，不喜欢，不评价。

**Comment by tulei770415** [comment]
作者你好，找到一些log之类的文件，希望能够帮忙解决崩溃的问题，在此谢谢了。

**Comment by tulei770415** [comment]
log文件

**Comment by tulei770415** [comment]
[qbit崩溃日志.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/6589141/qbit.zip)

**Comment by tulei770415** [comment]
> Tixati
> 现在正在用，感觉还行。
> 优点主要是每个任务和分类有很多可以单独设置的参数，还提供一些独特的自动化设置；缺点是不开源，文档不够详细，操作略繁琐。
> 
> uTorrent 3
> 需要配合我之前写的 [Python 脚本](https://github.com/SeaHOH/ban-peers)使用，提供更全面的反吸血功能。
> 优点是上手容易，资源占用少；缺点是 uTorrent 也不开源，还需要自己动手去捆绑、去广告，bug 也很多，长期不修复。如果孙宇晨那个小人能及时修复 bug 的话，我还是很愿意使用它的。
> 如果它的 bug 不太影响你的使用，可以尝试一下。主要是无法禁止优先下载文件头尾小机率导致下载卡住，切换多文件 torrent 部分下载时内部记录无法重置导致重复下载之前下载文件的头尾，还有一些普通用户不太用到的设置。
> 
> qBittorrent
> 需要配合相应的 [Python 脚本](https://github.com/SeaHOH/ban-peers#related-projects)使用，~这几个好像都只是反迅雷~，其中有两个可以自定义。
> 优点是开发活跃，上手容易；缺点是实现过于死板 (自认为，因为在关键问题上影响到我使用了，我不想使用 UPNP/NAT-PMP 功能，但作者不愿意提供监听 `0.0.0.0` 和 `::` 的权限) 。
> 
> Bitcomet
> 没怎么用过，不喜欢，不评价。

        多谢分享，试了一下tixaxi，没有汉化版而且下载多个文件时cpu资源占用率比较高，只要别老是崩溃就可以接受，我都是用笔记本下载，下载好了在台式机的大屏幕上面观看。

**Comment by SeaHOH** [comment]
Tixati 现已提供本地化功能，可以自行翻译，但是文本比较多，除了俄语暂时没有用户提交其它语言。而且功能实现也有点问题，是搜索最大匹配，而不是一一对应，单个单词无法匹配上下文使用不同翻译，比如 `OK`。
CPU 占用确实有点多，可以缩到系统托盘节省一些开销。至于稳定性，全天 24 小时不关机，还没有遇到过崩溃。

提醒下，反吸血需要自行设置，Settings >> Transfers >> Peers >> Client Filter Configure 。功能比较死板，就是字符过滤，没有智能检测。以下是我使用的设置，其中有些是播放器，你也可以考虑不这么一刀切。如果你不太清楚相关 ID，可以参考我的 Python 脚本。

Client ID, Never Allow
```
dandan*
dlbt*
libtorrent/1.1.13.0
thunder*
unknown
xunlei*
```
Peer ID, Never Allow, Match Case
```
-BC00*
-BN*
-BT71000*
-DL*
-QD*
-QVOD*
-SD*
-TB*
-TT*
-UT4*
-UT5*
-UT6*
-UW*
-VG*
-XF*
-XL*
-ZO*
```

**Comment by c0re100** [comment]
> [qbit崩溃日志.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/6589141/qbit.zip)

有類似這類的報告嗎?
https://github.com/qbittorrent/qBittorrent/issues/13250

**Comment by tulei770415** [comment]
> > [qbit崩溃日志.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/6589141/qbit.zip)
> 
> 有類似這類的報告嗎?
> [qbittorrent#13250](https://github.com/qbittorrent/qBittorrent/issues/13250)

你说的这种报告没有，笔记本里面找到的log都已经传上来了。

**Comment by tulei770415** [comment]
> Tixati 现已提供本地化功能，可以自行翻译，但是文本比较多，除了俄语暂时没有用户提交其它语言。而且功能实现也有点问题，是搜索最大匹配，而不是一一对应，单个单词无法匹配上下文使用不同翻译，比如 `OK`。
> CPU 占用确实有点多，可以缩到系统托盘节省一些开销。至于稳定性，全天 24 小时不关机，还没有遇到过崩溃。
> 
> 提醒下，反吸血需要自行设置，Settings >> Transfers >> Peers >> Client Filter Configure 。功能比较死板，就是字符过滤，没有智能检测。以下是我使用的设置，其中有些是播放器，你也可以考虑不这么一刀切。如果你不太清楚相关 ID，可以参考我的 Python 脚本。
> 
> Client ID, Never Allow
> 
> ```
> dandan*
> dlbt*
> libtorrent/1.1.13.0
> thunder*
> unknown
> xunlei*
> ```
> 
> Peer ID, Never Allow, Match Case
> 
> ```
> -BC00*
> -BN*
> -BT71000*
> -DL*
> -QD*
> -QVOD*
> -SD*
> -TB*
> -TT*
> -UT4*
> -UT5*
> -UT6*
> -UW*
> -VG*
> -XF*
> -XL*
> -ZO*
> ```

你好，Tixati遇到个问题，下载时显示“could not listen for incoming connections”，不知道应该怎么设置，所以询问一下，先谢谢了。

![could not listen for incoming connections](https://user-images.githubusercontent.com/74222753/122497986-ed146600-d020-11eb-93af-774f1aa00b98.png)

**Comment by SeaHOH** [comment]
> 下载时显示“could not listen for incoming connections”

可以试试第一个选项；如果还是失败，检查防火墙设置是否被更改了，修正后选第一或三个；也可以选最后一个，意思是不处理，不做种的话影响不大。

**Comment by f4nff** [comment]
xdown 支持防吸血了，

**Comment by KevinMX** [comment]
> Tixati 现已提供本地化功能，可以自行翻译，但是文本比较多，除了俄语暂时没有用户提交其它语言。而且功能实现也有点问题，是搜索最大匹配，而不是一一对应，单个单词无法匹配上下文使用不同翻译，比如 `OK`。 CPU 占用确实有点多，可以缩到系统托盘节省一些开销。至于稳定性，全天 24 小时不关机，还没有遇到过崩溃。
> 
> 提醒下，反吸血需要自行设置，Settings >> Transfers >> Peers >> Client Filter Configure 。功能比较死板，就是字符过滤，没有智能检测。以下是我使用的设置，其中有些是播放器，你也可以考虑不这么一刀切。如果你不太清楚相关 ID，可以参考我的 Python 脚本。
> 
> Client ID, Never Allow
> 
> ```
> dandan*
> dlbt*
> libtorrent/1.1.13.0
> thunder*
> unknown
> xunlei*
> ```
> 
> Peer ID, Never Allow, Match Case
> 
> ```
> -BC00*
> -BN*
> -BT71000*
> -DL*
> -QD*
> -QVOD*
> -SD*
> -TB*
> -TT*
> -UT4*
> -UT5*
> -UT6*
> -UW*
> -VG*
> -XF*
> -XL*
> -ZO*
> ```

确实一刀切了
libtorrent1.1.13/Deluge用户惨遭毒手=_=

（哦我是1.1.14那没事了）

**Comment by SeaHOH** [comment]
以下都是完整的客户 UA，不是前缀。

    libtorrent/1.1.13.0

这个其实不太确定，但确实有吸血现象。

    libtorrent/1.1.6.0

这个我之前也有发现问题，现根据 https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/61#issuecomment-1103995750 基本可以确定。
