### ISSUE TITLE
请问高级设置里上传连接策略设置成反吸血后就没有速度了是为什么？

### ISSUE THREAD

**Issue by ayd13swb** [c0re100/qBittorrent-Enhanced-Edition#263]
qBittorrent version and Operating System

4.3.5.10  windows10

What is the problem

高级设置里上传连接策略设置成反吸血后就没有速度了

**Comment by c0re100** [comment]
不建議開反吸血，會造成誤傷

**Comment by dozen007** [comment]
![image](https://user-images.githubusercontent.com/35923210/122000612-b4d31480-cde1-11eb-8222-6e68f4a114ef.png)
这个怎么办啊，已用clash for Windows开启全局，DNS已修改到8.8.8.8，使用本地安装可以使用，但是重启软件后引擎又全部消失
