### ISSUE TITLE
nox在fedora 34上运行一段时间后web界面无反应

### ISSUE THREAD

**Issue by maidmeow4** [c0re100/qBittorrent-Enhanced-Edition#264]
系统 fedora 34，使用 release 页面的 `4.3.5.10 qbittorrent-nox_aarch64-linux-musl_static.zip` ，运行一段时间后 web 界面无反应。
左下角红字提示无法连接，或者新打开时 nginx 提示 504 gateway time-out （我使用 nginx 反代 web 界面）。
出现此情况时要重启 qbittorrent 才能恢复过来。

因为我用 systemd 控制，`systemctl status qbittorrent` 显示 `running` 无 error；`htop` 查看多个进程存在，状态都为 `sleep`

**Comment by abcfy2** [comment]
之前libtorrent有一个BUG会导致程序崩溃或hang死，在最近的版本才修复，试试我这个编译的还有没有这个问题？https://github.com/abcfy2/qBittorrent-Enhanced-Edition/releases/tag/v4.3.5.10

**Comment by maidmeow4** [comment]
@abcfy2 
正在测试，因为上述问题一般要过好几个小时才会出现，可能得晚一点才能看出来结果。

**Comment by maidmeow4** [comment]
@abcfy2 
还是有这个问题。
![图片](https://user-images.githubusercontent.com/8447650/120994367-feef4100-c7b6-11eb-8f83-06ebec8f9e4c.png)

**Comment by abcfy2** [comment]
我没有你的aarch64的环境，我只有x86的服务器，在我的服务器上从没出现过这个问题。你只能尝试自己debug了，看看systemctl的日志，或者看下负载之类的问题能不能发现其他问题了

**Comment by maidmeow4** [comment]
@abcfy2 
我是在树莓派3上运行的， `systemctl` 没有任何有价值的东西

**Comment by abcfy2** [comment]
从负载监控看看，有必要的话尝试开启debug参数编译qbittorrent和libtorrent，看看能不能从gdb运行发现一些端倪，只能帮你到这了

**Comment by abcfy2** [comment]
另外我看fodera官方仓库应该是有qbittorrent原版的，安装那个试试，是否有这个问题 https://fedora.pkgs.org/33/fedora-x86_64/qbittorrent-nox-4.2.5-4.fc33.x86_64.rpm.html

**Comment by maidmeow4** [comment]
直接从前台运行程序，没有任何有价值的东西输出，不过按 <kbd>Ctrl</kbd> + <kbd>C</kbd> 退出时会卡在 `exiting cleanly` 处。

**Comment by abcfy2** [comment]
你可以从软件仓库安装原版看看，如果还有这个问题就给上游提交issue吧

**Comment by maidmeow4** [comment]
仓库装原版运行会崩溃，可能是配置不兼容 🤣 
我现在在用 `gdb` 看看有没有什么线索

**Comment by abcfy2** [comment]
好久不用rpm系了，印象中应该有跟deb-src的包吧？你试试直接安装那个包，就是根据你的环境从源码直接编译出rpm包的那种，fedora官方仓库既然有了rpm那么应该有对应的rpm src吧？试试用那个编译一下能运行不，应该比你自己搭建编译环境方便的多

**Comment by maidmeow4** [comment]
试验了几天发现 4.3.1.11 看起来不会出现上述问题，不过在此期间删了一批种子，不太确定是否有关，正在继续试验。

**Comment by maidmeow4** [comment]
很奇妙，现在又不会出现这个问题了 🤔 4.3.2.10 已经连续正常运行超过24小时

consider issue solved
