### ISSUE TITLE
web页面不停的退出，要重复登录

### ISSUE THREAD

**Issue by youland** [c0re100/qBittorrent-Enhanced-Edition#278]
**Please provide the following information**

### qBittorrent version and Operating System
qBittorrent v4.3.6.10 Web UI (64-bit)，最新版。

### If on linux, libtorrent-rasterbar and Qt version
debian buster 64位

### What is the problem
web页面频繁退出，短时间内需要重复在web登录页输入用户名和密码来登录。用的chrome浏览器92版本。
另外，我发现qBittorrent-nox也有同样的情况。

### What is the expected behavior
希望能保持登录一定的时间，不要重复输入用户名和密码来登录。不太清楚，软件默认设置的停留时长是多久，还没找到设置。

### Steps to reproduce
(type here)

### Extra info(if any)
(type here)

**Comment by SeaHOH** [comment]
你可以按 <kbd>F12</kbd> 打开并切换到网络活动页面监视网络请求的 cookies。如果中途 cookies 中出现登录信息丢失，那么可能和浏览器 (扩展插件) 的隐私设置有关，否则可确定是 qBittorrent 本身的问题。

另外，这种问题应该向上游反映。

**Comment by youland** [comment]
> 你可以按 F12 打开并切换到网络活动页面监视网络请求的 cookies。如果中途 cookies 中出现登录信息丢失，那么可能和浏览器 (扩展插件) 的隐私设置有关，否则可确定是 qBittorrent 本身的问题。
> 
> 另外，这种问题应该向上游反映。

找到问题的原因了，比较低级。
原因：在同一个浏览器同时打开了qBittorrent-nox和qBittorrent-Enhanced-Edition。因为EE不为PT所接受，所以安装了一个qBittorrent-nox，EE版本做为普通BT下载，反吸血。

现在用不同的浏览器打开，可以停留很久了。

感谢回复。

**Comment by SeaHOH** [comment]
Tips: Chrome 支持多账户，用新账户开一个新窗口就行，无需再开其它浏览器。
