### ISSUE TITLE
Possible offline download server: 5.39.226.*

### ISSUE THREAD

**Issue by G2159687** [c0re100/qBittorrent-Enhanced-Edition#28]
Hi. I've just found a possible offline download server from France during my download.

There are many IP addresses within a single IP block, with exactly same client version, plus they do not upload data at all. Probably adding them into IP filter is a good choice. Further discussions are also accepted. Screenshot: https://imgur.com/a/sOO3NTJ

Currently I'm not using qBittorrent to download, but I'd like to do some contributions to this project :)

**Comment by c0re100** [comment]
Thanks. I will adding them into IP filter in next version.

**Comment by c0re100** [comment]
um......
Those IP addresses is a set of NordVPN IP now........
