### ISSUE TITLE
反吸血策略是否对私有torrent无效？

### ISSUE THREAD

**Issue by pinyangcong** [c0re100/qBittorrent-Enhanced-Edition#290]
![image](https://user-images.githubusercontent.com/62090117/133897107-b02a8efc-eb96-4abc-83af-be6539c6f090.png)

我看了下代码，不应该会发生这种情况？

32662a7c863859d08f15c2f8555dd87137ebdf28
8a19de639e30e072aa655a553eacd03a4856baeb
问题主要集中在这两个种子上

这个是个私有torrent，难道反吸血策略对私有种子无效吗

**Comment by pinyangcong** [comment]
@Kolcha

**Comment by Kolcha** [comment]
yes, filters doesn't have effect for private torrents:
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/a0f2567d14d8e36702df9aaa066e1fd4f973027a/src/base/bittorrent/peer_blacklist.hpp#L70-L72

such logic was before my changes, so I just saved it in my implementation. next lines are from 4.3.0.10 (before my changes):
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/dc5fadbb30ef27a4d6637b48b7b1c63457e9c767/src/base/bittorrent/session.cpp#L2121-L2122

so, it is expected that filters don't work for private torrents. even more, in case of private torrents tracker should filter peers
