### ISSUE TITLE
如何删除使用手动 Torrent 管理模式的保存路径记录

### ISSUE THREAD

**Issue by QiTianzu** [c0re100/qBittorrent-Enhanced-Edition#292]
**Please provide the following information**

### qBittorrent version and Operating System
v4.3.8.10 (64-bit), Windows 10 21390.2025

### If on linux, libtorrent-rasterbar and Qt version
(type here)

### What is the problem
如何删除使用手动 Torrent 管理模式的保存路径记录

### What is the expected behavior
(type here)

### Steps to reproduce
(type here)

### Extra info(if any)
(type here)

**Comment by c0re100** [comment]
相關紀錄是儲存於 `C:\Users\<username>\AppData\Roaming\qBittorrent\qBittorrent.ini`
直接找save_path_history就看到了
