### ISSUE TITLE
Can maintain qbit-enhanced-edition-nox version for  arm64  RASBIAN?

### ISSUE THREAD

**Issue by GoogleBeEvil** [c0re100/qBittorrent-Enhanced-Edition#295]
**Please provide the following information**

### qBittorrent version and Operating System

`  OS: Debian GNU/Linux 10 (buster) aarch64`
### What is the problem
Can maintain qbit-enhanced-edition-nox version for  arm64  RASBIAN?

**Comment by abcfy2** [comment]
Could https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/latest/download/qbittorrent-nox_aarch64-linux-musl_static.zip work on your environment ?

**Comment by GoogleBeEvil** [comment]
Sorry ,it's not deb or tar file,how can I run it on my pi？

**Comment by abcfy2** [comment]
It's only a compressed file. You just need to unzip this file and execute `./qbittorrent-nox` to see if it works.

**Comment by GoogleBeEvil** [comment]
It works. 
Suggest rename `qbittorrent-nox-aarch64-linux-musl` to `qbittorrent-enhanced-nox-aarch64-linux-musl`
