### ISSUE TITLE
[Build] Consider use Qt6 for release build

### ISSUE THREAD

**Issue by abcfy2** [c0re100/qBittorrent-Enhanced-Edition#297]
Just recording the issue. Seems qbittorrent 4.4.0 will support Qt6: https://github.com/qbittorrent/qBittorrent/pull/15567

Maybe I should upgrade build dependencies after 4.4.0 released.

If it works I will create a PR to close this issue.

**Comment by c0re100** [comment]
> Just recording the issue. Seems qbittorrent 4.4.0 will support Qt6: [qbittorrent#15567](https://github.com/qbittorrent/qBittorrent/pull/15567)
> 
> Maybe I should upgrade build dependencies after 4.4.0 released.
> 
> If it works I will create a PR to close this issue.

Most important question:
I don't know how many Windows 7/8/8.1 users is using Enhanced Edition.....
Cause Qt6 dropped Windows 7 support.

**Comment by abcfy2** [comment]
https://github.com/abcfy2/qBittorrent-Enhanced-Edition/releases/tag/v4.4.0-beta3

All done. After do some manual test I will submit a PR to close issue.
