### ISSUE TITLE
开放屏蔽功能

### ISSUE THREAD

**Issue by xmn-001** [c0re100/qBittorrent-Enhanced-Edition#299]
请问可以将屏蔽peer节点的功能开放出来吗？
1： 允许用户根据peer还是client屏蔽
2：允许用户自定义peer特征值列表，而不是依赖增强版内置
3：允许用户针对特定peer进行限速

**Comment by xmn-001** [comment]
最想要的功能是： 用户自定义peer特征值列表，如果能支持匹配最好。

**Comment by pinyangcong** [comment]
已经实现了黑名单功能，#251

**Comment by escape0707** [comment]
特定 peer 限速真的重要吗。。。

如果 黑白名单已经满足了你的需求，可以关掉这个 issue
