### ISSUE TITLE
No Linux x86_64 asset for v4.3.9.10 ?

### ISSUE THREAD

**Issue by alexdns1** [c0re100/qBittorrent-Enhanced-Edition#301]
Is there a reason why there is no qbittorrent-nox_x86_64-linux-musl_static.zip asset for v4.3.9.10 ?

**Comment by abcfy2** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/runs/4061749887?check_suite_focus=true

Seems github issue when uploading assets after build. And I've refactored build script. Maybe you have to waiting next release.

Also you may try build yourself via docker:

```sh
docker run -e CROSS_HOST=x86_64-linux-musl -e OPENSSL_COMPILER=linux-x86_64 -e QT_DEVICE=linux-generic-g++ --rm -v `git rev-parse --show-toplevel`:/build alpine /build/.github/workflows/cross_build.sh
```

**Comment by c0re100** [comment]
> https://github.com/c0re100/qBittorrent-Enhanced-Edition/runs/4061749887?check_suite_focus=true
> 
> Seems github issue when uploading assets after build. And I've refactored build script. Maybe you have to waiting for next release.
> 
> Also you may try build yourself via docker:
> 
> ```shell
> docker run -e CROSS_HOST=x86_64-linux-musl -e OPENSSL_COMPILER=linux-x86_64 -e QT_DEVICE=linux-generic-g++ --rm -v `git rev-parse --show-toplevel`:/build alpine /build/.github/workflows/cross_build.sh
> ```
> 
> Then the build asset will be found in `.github/workflows/`

I just realized that AppImage build failed.
Cause ubuntu 16.04 removed on Github Actions lol
https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/

**Comment by alexdns1** [comment]
Ill just wait for the next version. 4.3.9 is not that critical anyways :)
Thanks for checking it out

**Comment by abcfy2** [comment]
> > https://github.com/c0re100/qBittorrent-Enhanced-Edition/runs/4061749887?check_suite_focus=true
> > Seems github issue when uploading assets after build. And I've refactored build script. Maybe you have to waiting for next release.
> > Also you may try build yourself via docker:
> > ```shell
> > docker run -e CROSS_HOST=x86_64-linux-musl -e OPENSSL_COMPILER=linux-x86_64 -e QT_DEVICE=linux-generic-g++ --rm -v `git rev-parse --show-toplevel`:/build alpine /build/.github/workflows/cross_build.sh
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then the build asset will be found in `.github/workflows/`
> 
> I just realized that AppImage build failed. Cause ubuntu 16.04 removed on Github Actions lol https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/

ubuntu-16.04 os removed in github action: https://github.com/actions/virtual-environments/issues/3287

But AppImage build in docker is working now. So I've switch back to use ubuntu 16.04 in docker in `v4_4_x` branch. So It's not affect `v4_4_x` branch build.

**Comment by tbc0309** [comment]
能否pre-release，缺个x86_64的，难过o(╥﹏╥)o

**Comment by abcfy2** [comment]
> 能否pre-release，缺个x86_64的，难过o(╥﹏╥)o

You can use v4.3.8.10 at this time: https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/tag/release-4.3.8.10

**Comment by wxlg1117** [comment]
> 
> 
> 能否pre-release，缺个x86_64的，难过o(╥﹏╥)o
[qbittorrent-nox.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/7563689/qbittorrent-nox.zip)

```
mkdir -p /root/docker
cd /root/docker/
git clone https://github.com/c0re100/qBittorrent-Enhanced-Edition.git
docker run -e CROSS_HOST=x86_64-linux-musl -e OPENSSL_COMPILER=linux-x86_64 -e QT_DEVICE=linux-generic-g++ --rm -v `git rev-parse --show-toplevel`:/root/docker/qBittorrent-Enhanced-Edition alpine /root/docker/qBittorrent-Enhanced-Edition/.github/workflows/cross_build.sh

```
you can find a release bin in /root/docker/qBittorrent-Enhanced-Edition/src/

**Comment by alexdns1** [comment]
> docker run -e CROSS_HOST=x86_64-linux-musl -e OPENSSL_COMPILER=linux-x86_64 -e QT_DEVICE=linux-generic-g++ --rm -v `git rev-parse --show-toplevel`:/root/docker/qBittorrent-Enhanced-Edition alpine /root/docker/qBittorrent-Enhanced-Edition/.github/workflows/cross_build.sh

That worked thanks !
