### ISSUE TITLE
中文界面下部分文字以衬线字体显示

### ISSUE THREAD

**Issue by userxiang** [c0re100/qBittorrent-Enhanced-Edition#302]
**Please provide the following information**

### qBittorrent version and Operating System
qBittorrent Enhanced Edition v4.3.9.10
Windows 10 21H2

### If on linux, libtorrent-rasterbar and Qt version
(type here)

### What is the problem
中文界面下部分文字以衬线字体显示，而另一部分字体以无衬线字体显示，以衬线字体显示的文字并不清晰。
![未命名](https://user-images.githubusercontent.com/50364226/143451707-6ed6e570-a240-47c4-8b83-57b72dfe4df6.jpg)

### What is the expected behavior
字体均以系统默认的无衬线字体显示

### Steps to reproduce
(type here)

### Extra info(if any)
(type here)

**Comment by escape0707** [comment]
这个问题应该是上报到上游  qbittorrent 那边。

另外，这个应该是 Windows 自己字体选择拉胯导致的。如果对字体配置字体回落有比较高的要求，可以考虑用 Linux / FontConfig。你也可以考虑用 WebUI 然后在浏览器里配置字体回落或者改它的 css。
