### ISSUE TITLE
need upgrade something

### ISSUE THREAD

**Issue by jkle112** [c0re100/qBittorrent-Enhanced-Edition#304]
### qBittorrent version and Operating System
4.3.9.10,ubuntu 20.04 lts

### If on linux, libtorrent-rasterbar and Qt version
libtorrent:1.2.14.0,qt:5.12.8
openssl:1.1.1f
### What is the problem
need upgrade all the libraries to latest for security 
I am only known the openssl :1.1.1l,all the packets are require encryption,hope force encryption.

TLS_CHACHA20_POLY1305_SHA256 (0x1303) 							   			Forward Secrecy | 256
-- | --
TLS_AES_256_GCM_SHA384 (0x1302) 							   			Forward Secrecy | 256

Drop WEAK ways

TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)  WEAK | 256
-- | --
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)  WEAK | 128
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)  WEAK | 128
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)  WEAK | 256
TLS_RSA_WITH_AES_128_GCM_SHA256 (0x9c)  WEAK | 128
TLS_RSA_WITH_AES_256_GCM_SHA384 (0x9d)  WEAK | 256
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)  WEAK | 128
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)  WEAK | 256

Thank you!

**Comment by abcfy2** [comment]
Don't worry, Ubuntu LTS will add security patch to this dependency.
