### ISSUE TITLE
Auto banned by byrpt(默认被 北邮人 禁止使用该版本)

### ISSUE THREAD

**Issue by BackMountainDevil** [c0re100/qBittorrent-Enhanced-Edition#305]
**Please provide the following information**

### qBittorrent version and Operating System
- pkgname=qbittorrent-enhanced-git  pkgver=4.3.9.10.r0.ga3955360c
- 5.10.79-1-MANJARO x86_64
### If on linux, libtorrent-rasterbar and Qt version
-  libtorrent-rasterbar 1:1.2.14-1
- qt 5.15.2

### What is the problem

qbittorrent can download and share files on byrpt while the enhanced version not.( 北邮人支持 qb,但是所谓的加强版本是被禁止的)

### What is the expected behavior

let code dance to work with byrpt. 

### Steps to reproduce
1. download torrent file from byr.pt
2. use qb to download, work.
3. uninstall qb and install enhance version
4. use qb-enhance to download, fail. On web will send you drink tea

### Extra info(if any)

猜测五个加强版的特点中自动屏蔽迅雷、qq、xfply等吸血下载工具这一点被byr识别到了，这一个功能没法设置关闭或者开启。或许这是迟迟没有被主线接受的原因。

**Comment by SeaHOH** [comment]
估计是新加的黑白名单功能导致，可使用不含此功能的 v4.3.4.* 验证。

**Comment by c0re100** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_3_x/NOTE.md#important-note

**Comment by SeaHOH** [comment]
某人曾说过可以修改所有 PT 服务器配置，还以为当时已经解决了，原来还是在吹牛。

其实 EE 的屏蔽功能并不会对 PT 起作用，但这些人只会圈地自萌，技术知识方面可能不太合格。

**Comment by BackMountainDevil** [comment]
母鸡啊，看了重要备忘录里的东西，准备像北邮人管理这边标记一下，我已经回到qb主线了，期待目前这个版本代码审查能合并到主线中-.-

**Comment by SeaHOH** [comment]
> 期待目前这个版本代码审查能合并到主线中-.-

这是不可能的，原作者思路太死板。当然，其实也没必要，渣雷祸害范围还是有限，外国友人无需 care。

大家选适合自己的就好，这就是存在这么多不同客户端的原因。

**Comment by xiaooloong** [comment]
pt 的 tracker 端已经针对 qBittorrent-Enhanced-Edition 放行，但是 qBittorrent-Enhanced-Edition 还是无法连接到 transmission 做的种进行下载

**Comment by neoblackxt** [comment]
我想做一个增强兼容版，把peer_id和用户代理的名字改回去，有人想要吗？尽管这可能有些削足适履
