### ISSUE TITLE
我完全搞不清哪里出问题了

### ISSUE THREAD

**Issue by NICOLE1224** [c0re100/qBittorrent-Enhanced-Edition#306]
**Please provide the following information**

### qBittorrent version and Operating System
aur/qbittorrent-enhanced-nox 4.3.9.10-1     ArchLinux
### If on linux, libtorrent-rasterbar and Qt version
extra/libtorrent-rasterbar 1:1.2.15-1  
extra/qt5-base 5.15.2+kde+r263-4

### What is the problem
正常运行了很久的qbittorrent这两天不工作了。
我用sudo -u qbittorrent qbittorrent-nox后，他给我如下的反馈。

qBittorrent version: v4.3.9.10

Caught signal: SIGSEGV
Stack trace:
  qbittorrent-nox : BitTorrent::InfoHash::InfoHash(libtorrent::digest32<160l> const&)+0x4  [0x56499c6ce584]
  qbittorrent-nox : BitTorrent::Session::handleStateUpdateAlert(libtorrent::state_update_alert const*)+0xae  [0x56499c6e942e]
  qbittorrent-nox : BitTorrent::Session::handleAlert(libtorrent::alert const*)+0x1cc  [0x56499c6fd7bc]
  qbittorrent-nox : BitTorrent::Session::readAlerts()+0x54  [0x56499c6fd8c4]
  /usr/lib/libQt5Core.so.5 : QObject::event(QEvent*)+0x2af  [0x7f143a91856f]
  /usr/lib/libQt5Core.so.5 : QCoreApplication::notifyInternal2(QObject*, QEvent*)+0x108  [0x7f143a8eb3e8]
  /usr/lib/libQt5Core.so.5 : QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)+0x189  [0x7f143a8ee519]
  /usr/lib/libQt5Core.so.5 : ()+0x312a14  [0x7f143a944a14]
  /usr/lib/libglib-2.0.so.0 : g_main_context_dispatch()+0x26c  [0x7f143978452c]
  /usr/lib/libglib-2.0.so.0 : ()+0xa87b9  [0x7f14397d87b9]
  /usr/lib/libglib-2.0.so.0 : g_main_context_iteration()+0x31  [0x7f1439781c11]
  /usr/lib/libQt5Core.so.5 : QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)+0x66  [0x7f143a944046]
  /usr/lib/libQt5Core.so.5 : QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)+0x12c  [0x7f143a8e9d8c]
  /usr/lib/libQt5Core.so.5 : QCoreApplication::exec()+0x94  [0x7f143a8f22f4]
  qbittorrent-nox : Application::exec(QStringList const&)+0x9a8  [0x56499c6b9198]
  qbittorrent-nox : main()+0x4fb  [0x56499c6b4c0b]
  /usr/lib/libc.so.6 : __libc_start_main()+0xd5  [0x7f143a118b25]
  qbittorrent-nox : _start()+0x2e  [0x56499c6b68de]
Segmentation fault

### What is the expected behavior
(type here)

### Steps to reproduce
(type here)

### Extra info(if any)
(type here)

**Comment by abcfy2** [comment]
似乎是因为`libtorrent-rasterbar` 更新了，我也遇到这个问题，需要重新编译安装一次`aur/qbittorrent-enhanced`就好了:

```sh
yay -S aur/qbittorrent-enhanced --noconfirm
```

**Comment by NICOLE1224** [comment]
> 似乎是因为`libtorrent-rasterbar` 更新了，我也遇到这个问题，需要重新编译安装一次`aur/qbittorrent-enhanced`就好了:
> 
> ```shell
> yay -S aur/qbittorrent-enhanced --noconfirm
> ```

谢谢！问题解决了。
