### ISSUE TITLE
Please upgrade to v4.4.0

### ISSUE THREAD

**Issue by abcfy2** [c0re100/qBittorrent-Enhanced-Edition#307]
Upsteam has been released v4.4.0: https://github.com/qbittorrent/qBittorrent/releases/tag/release-4.4.0

Please also keep up with the pace.

:)

**Comment by escape0707** [comment]
Yeah! Let’s rock into BTv2 and much more!

**Comment by c0re100** [comment]
WIP

**Comment by c0re100** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/tag/release-4.4.0.10
