### ISSUE TITLE
feeds.json被0填充了...

### ISSUE THREAD

**Issue by zhtw2013** [c0re100/qBittorrent-Enhanced-Edition#31]
### qBittorrent version and Operating System
4.1.5.1
Win10 pro 最新版

今天重開電腦後，發現我qBittorrent-Enhanced-Edition好像被重設了，
覺得有點不妙，馬上去看feeds.json等檔案

檔案大小都正常..然而內容卻被用0填充了...
到現在不知道發生啥事...
作者有頭緒嗎？
有辦法還原為本來的格式嗎？(應該不太可能了吧)

![image](https://user-images.githubusercontent.com/9501406/52405250-d59a4980-2b05-11e9-9d9f-3728e7fd0546.png)
看圖可以知道檔案大小都正常，但實際打開後卻如下圖。

16進位編輯器看內容，會發現HEX已經被0填充了...

![image](https://user-images.githubusercontent.com/9501406/52405364-0da18c80-2b06-11e9-9b2c-017c6e4b0eb4.png)

不止feeds.json 連log file也被0填充了，所以沒辦法發LOG上來...
都是0000000這種無意義的資料而已

**Comment by c0re100** [comment]
沒有方法還原...
大概是因為qbittorrent意外關閉了，導致該數據沒有正確地保存下來.......

**Comment by zhtw2013** [comment]
感謝作者說明！

好扯....不止沒正確儲存還被破壞了...更慘的是qBittorrent沒有自動RSS備份機制
現在幾百個RSS訂閱來源只好手動重新加入了，哎
