### ISSUE TITLE
4.4.0.10版本居然没有编译出64bit Linux版的tar包？

### ISSUE THREAD

**Issue by AbraxasVi** [c0re100/qBittorrent-Enhanced-Edition#310]
### qBittorrent & operating system versions

qBittorrent: 4.4.0.10 x64
Operating system: QNAP QTS 4.5.4
Qt: none
libtorrent-rasterbar: unknown

### What is the problem?

QNAP用户表示用不了AppImage包啊........
手动拆开AppImage包后直接运行会提示缺库文件
error while loading shared libraries: libQt6Widgets.so.6: cannot open shared object file: No such file or directory
QTS里本无Qt6，肯定会显示缺库文件，根本用不着GUI，只用得着web UI

**Comment by c0re100** [comment]
我看了眼.........nox版本上傳失敗了
可以到github action那裡下載
https://github.com/c0re100/qBittorrent-Enhanced-Edition/suites/4865970210/artifacts/138681360
