### ISSUE TITLE
Appimage with qt5 insteadof qt6

### ISSUE THREAD

**Issue by Dnkhatri** [c0re100/qBittorrent-Enhanced-Edition#313]
### Suggestion

Is it possible to get appimage with qt5 instead of qt6 as qt6 has to many bugs. On windows people have a choice on linux we are stuck with the buggy qt6 version.

**Comment by abcfy2** [comment]
Did you see any bugs under qt6? I also use AppImage in my OS, without any problems. And official qbittorrent AppImage also use  Qt6. So I think we do not need to provide qt5 build.

**Comment by c0re100** [comment]
(Possibly) saying UI issue?
