### ISSUE TITLE
x86_64/arm64/universal Qt6-based macOS builds [download link included]

### ISSUE THREAD

**Issue by Kolcha** [c0re100/qBittorrent-Enhanced-Edition#319]
### Suggestion

provide Qt6-based builds for macOS (architecture-specific or universal)
see the end of this message to find download link for 4.4.0.10 compiled by me

### Use case

qBittorrent Enhanced Edition can be compiled for macOS using [my script](https://gist.github.com/Kolcha/3ccd533123b773ba110b8fd778b1c2bf). no Apple M1-based h/w is required for compilation!

only some small changes are required:

- official qBittorrent repository URL should be replaced with qBittorrent Enhanced Edition repository URL (right now it is on [line 133](https://gist.github.com/Kolcha/3ccd533123b773ba110b8fd778b1c2bf#file-build_qbt_dmg-sh-L133), but it may changed in the future), this is **crucial**:

  ```bash
  [[ -d ${_qbt_src_dir} ]] || curl -L https://github.com/qbittorrent/qBittorrent/archive/{$qbittorrent_ver}.tar.gz | tar xz
  ```
  becomes
  ```bash
  [[ -d ${_qbt_src_dir} ]] || curl -L https://github.com/c0re100/qBittorrent-Enhanced-Edition/archive/{$qbittorrent_ver}.tar.gz | tar xz
  ```

next changes are mostly cosmetic, but recommended:

- update the value of `_qbt_dmg_path` variable, replace "qBittorrent" with "qBittorrent-Enhanced-Edition", [line 120](https://gist.github.com/Kolcha/3ccd533123b773ba110b8fd778b1c2bf#file-build_qbt_dmg-sh-L120)
- update the value of `_qbt_src_dir_name` variable, replace "qBittorrent" with "qBittorrent-Enhanced-Edition", [line 129](https://gist.github.com/Kolcha/3ccd533123b773ba110b8fd778b1c2bf#file-build_qbt_dmg-sh-L129)

script must be launched with argument (or corresponding value can be changed in the script):

```bash
./build_qbt_dmg.sh --qbittorrent=release-4.4.0.10
```

### Extra info/examples/attachments

compiled binaries produced by script above can be downloaded [here](https://www.dropbox.com/sh/f9gpn6zf0lk6814/AACS6q4EjJ72pHKfjlmjdHiKa?dl=0)
they were compiled on pretty old MacBook Pro 2016 using Xcode 13.2.1 on macOS Monterey 12.1

P.S> I don't have Apple M1-based MacBook neither even any personal MacBook anymore. MacBook I used for compilation (and Apple M1-based MacBook previously used to create initial version of the script) was got from office I'm working. Just due to work specifics it has suitable environment to build software written in C/C++.

**Comment by abcfy2** [comment]
I think you could make a PR to help add a CI for building MacOS release, just like Linux AppImage or nox.
