### ISSUE TITLE
不能在关机时保存种子

### ISSUE THREAD

**Issue by mr-cn** [c0re100/qBittorrent-Enhanced-Edition#32]
### qBittorrent version and Operating System
4.1.5.1 Enhanced running on Win10

### What is the problem
不能在关机时保存种子，原版无此问题

### What is the expected behavior
Windows在关机时会发信号给运行中的程序，要求程序准备关机，避免强制kill造成数据丢失。

在qbittorrent原版上此功能工作正常，能响应关机信号，并且会要求Windows等待，提示信息为“正在保存 torrents”

更换为此版本后，程序不会令Windows等待保存种子，而是会(被)直接关闭。在下次开机后， qbittorrent就会重新检验种子。

### Steps to reproduce
重启电脑

虽然说此改版改动的部分不应该导致此问题，但确实在用原版的时候，关机时每次都可以看到qbittorrent正在保存torrents(有时候还卡死在这里，让我不得不选强制关机……)也没有发生过重检验的情况。

**Comment by c0re100** [comment]
是的，我沒有更動過關閉程序的處理........

主要測試: Win10 1803
50個種子同一時間開始並關閉Win10有出現到 `正在儲存torrent進度` 並等待程式完全關閉為止 大概1分鐘(?)
重開後 50個種子沒有一個會出現重新檢驗的情況
![default](https://user-images.githubusercontent.com/5726473/52482062-364f8200-2beb-11e9-9bb1-6d24a98020ad.png)
50個fastresume也有正確地儲存下來
![default](https://user-images.githubusercontent.com/5726473/52482572-97c42080-2bec-11e9-953d-1f2ce805e4f5.png)
fastresume沒有出現受損問題(如果儲存失敗會出現 #31 的情況)
![default](https://user-images.githubusercontent.com/5726473/52482663-d6f27180-2bec-11e9-8f44-22409a80d5da.png)


Win7測試:
17個種子同一時間開始並關閉Win7亦有出現到 `正在儲存torrent進度`
重開後 這17個種子亦沒出現過重新檢驗的情況.......
![default](https://user-images.githubusercontent.com/5726473/52482413-2b492180-2bec-11e9-9a1d-7c3ff7917d72.png)

關閉程式時會執行cleanup
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_1_x/src/app/application.cpp#L692

顯示“正在保存 torrents”後會儲存qbittorrent設定
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_1_x/src/app/application.cpp#L712
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_1_x/src/gui/mainwindow.cpp#L789

然後跳到L734 delete session pointer
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_1_x/src/app/application.cpp#L734

delete後跑到session destructor
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_1_x/src/base/bittorrent/session.cpp#L1015
L1018>L2535>L2522
經過L2525-L2528 那4個if後
最後由libtorrent負責儲存fastresume

結論:　我也不清楚發生甚麼事了，也不知道如何重現你說的問題........

**Comment by mr-cn** [comment]
> 
> 
> 是的，我沒有更動過關閉程序的處理........
> 
> 主要測試: Win10 1803
> 50個種子同一時間開始並關閉Win10有出現到 `正在儲存torrent進度` 並等待程式完全關閉為止 大概1分鐘(?)
> 重開後 50個種子沒有一個會出現重新檢驗的情況
> ![default](https://user-images.githubusercontent.com/5726473/52482062-364f8200-2beb-11e9-9bb1-6d24a98020ad.png)
> 50個fastresume也有正確地儲存下來
> ![default](https://user-images.githubusercontent.com/5726473/52482572-97c42080-2bec-11e9-953d-1f2ce805e4f5.png)
> fastresume沒有出現受損問題(如果儲存失敗會出現 #31 的情況)
> ![default](https://user-images.githubusercontent.com/5726473/52482663-d6f27180-2bec-11e9-8f44-22409a80d5da.png)
> 
> Win7測試:
> 17個種子同一時間開始並關閉Win7亦有出現到 `正在儲存torrent進度`
> 重開後 這17個種子亦沒出現過重新檢驗的情況.......
> ![default](https://user-images.githubusercontent.com/5726473/52482413-2b492180-2bec-11e9-9a1d-7c3ff7917d72.png)
> 
> 關閉程式時會執行cleanup
> https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_1_x/src/app/application.cpp#L692
> 
> 顯示“正在保存 torrents”後會儲存qbittorrent設定
> https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_1_x/src/app/application.cpp#L712
> https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_1_x/src/gui/mainwindow.cpp#L789
> 
> 然後跳到L734 delete session pointer
> https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_1_x/src/app/application.cpp#L734
> 
> delete後跑到session destructor
> https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_1_x/src/base/bittorrent/session.cpp#L1015
> L1018>L2535>L2522
> 經過L2525-L2528 那4個if後
> 最後由libtorrent負責儲存fastresume
> 
> 結論:　我也不清楚發生甚麼事了，也不知道如何重現你說的問題........

按道理讲也应该跟Enhanced的部分没有关系，得到你的确认了那我就Close吧。

我过一会装回原版再看一下是否能重现。

**Comment by mr-cn** [comment]
的确不是Enhanced的问题，刚刚关机时第一次看见了保存torrents的提示🙊

应该是我系统的问题，打扰了！
