### ISSUE TITLE
请求，可以麻烦编译一份非增强版吗？

### ISSUE THREAD

**Issue by wei134102** [c0re100/qBittorrent-Enhanced-Edition#321]
### Extra info/examples/attachments

请求，可以麻烦编译一份非增强版吗？我试了所有的NOX版 只有你的可以在我的路由系统使用，在官方项目那里，我语言不通，根本没法理解他说的问题，官方的都试了无法使用。下面这个版本
qBittorrent Enhanced Edition v4.4.0.10这个版本下的 qbittorrent-enhanced-nox_arm-linux-musleabi_static.zip
只有上面的可以使用，但是我的大多数PT站BAN了增强版，您可以指导我编译一份上面版本的正常版或者编译一份那最好了。
非常感谢，我的香港朋友！

我的路由信息

root@XiaoQiang:/userdisk/root# uname -a
Linux XiaoQiang 2.6.36 #3 MiWiFi-R1D-2.25.213 SMP PREEMPT Tue Oct 16 11:44:14 UT                                                                  C 2018 armv7l GNU/Linux

**Comment by abcfy2** [comment]
一劳永逸的办法是请求PT维护方加入可信UA: https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_4_x/NOTE.md

**Comment by Kolcha** [comment]
I see you interested in arm linux build, so I assume you are using something like Raspberry Pi or similar board
many of such boards run Debian-based Linux distro (for example Raspbian or Armbian)
if this is your case, you can just add my repo for Raspbian (regardless the actual name of your Debian-based system) and install official qBittorrent (or qbittorrent-nox) package from it.
my repo and instructions how to add it can be found here https://software.opensuse.org//download.html?project=home%3Anikoneko%3Atest&package=qbittorrent
(just replace `qbittorrent` with `qbittorrent-nox` if you are interested in it)

also you can try official qbittorrent builds from here https://github.com/userdocs/qbittorrent-nox-static

another way (if you want to build it by yourself) is just to follow the steps as GitHub Actions does to build the archive you mentioned, it can be found here:
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/fd047415f4fa9d99edabd4a0cb285bb8d30c8c50/.github/workflows/build_and_release.yml#L77-L79
so, everything you need is mentioned script and set environment variable `CROSS_HOST` before running it

P.S> I don't understand Chinese, just used Google Translate to translate it into English (Google translates it pretty good nowadays), so hope that automatic translation in opposite direction also works so good.

**Comment by wei134102** [comment]
> 一劳永逸的办法是请求PT维护方加入可信UA: https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_4_x/NOTE.md
非常感谢，我只是想把我手里这个闲置的产品发挥更好，小米路由器R1D在中国大概有几十万的销量啊，这么多的存量应该有需求的，还可以插硬盘，如果只能运行transmission ,那太可惜了！

**Comment by wei134102** [comment]
> I see you interested in arm linux build, so I assume you are using something like Raspberry Pi or similar board many of such boards run Debian-based Linux distro (for example Raspbian or Armbian) if this is your case, you can just add my repo for Raspbian (regardless the actual name of your Debian-based system) and try to install official qBittorrent (or qbittorrent-nox) package from it. my repo and instructions how to add it can be found here https://software.opensuse.org//download.html?project=home%3Anikoneko%3Atest&package=qbittorrent (just replace `qbittorrent` with `qbittorrent-nox` if you are interested in it)
> 
> also you can try official qbittorrent builds from here https://github.com/userdocs/qbittorrent-nox-static
> 
> another way (if you want to build it by yourself) is just to follow the steps as GitHub Actions does to build the archive you mentioned, it can be found here:
> 
> https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/fd047415f4fa9d99edabd4a0cb285bb8d30c8c50/.github/workflows/build_and_release.yml#L77-L79
> 
> 
> so, everything you need is mentioned script and set environment variable `CROSS_HOST` before running it
> P.S> I don't understand Chinese, just used Google Translate to translate it into English (Google translates it pretty good nowadays), so hope that automatic translation in opposite direction also works so good.

thank you very  mach,i can understand what you mean,i will try it again,my router(miwifi router r1d) in china ,it have a lot of ,may be a hundred thousand levels be userd now ,may be your country also have it.it just find transmission only,i want use it for lightweight nas,something like that,thank you again,my friend!

**Comment by abcfy2** [comment]
> > 一劳永逸的办法是请求PT维护方加入可信UA: https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_4_x/NOTE.md
> > 非常感谢，我只是想把我手里这个闲置的产品发挥更好，小米路由器R1D在中国大概有几十万的销量啊，这么多的存量应该有需求的，还可以插硬盘，如果只能运行transmission ,那太可惜了！

PT下载用什么工具都很快，所以无所谓用什么了。你用transmission也行，不喜欢transmission也可以用aria2，我自己也维护了一份aria2的musl构建: https://github.com/abcfy2/aria2-static-build/releases/tag/continuous , 可以在小米路由器上运行。

qbee的持续构建已经全部迁移到docker上了，想要编译原版只需要把`.github/workflows/cross_build.sh` 拷贝到原版qb的源码中对应的目录下，使用docker即可构建:

```sh
docker run --rm -e CROSS_HOST=arm-linux-musleabi -e USE_CHINA_MIRROR=1 -v `pwd`:/build ubuntu /build/.github/workflows/cross_build.sh
```

构建生成的二进制文件存放于`.github/workflows/`目录下

**Comment by wei134102** [comment]
> > > 一劳永逸的办法是请求PT维护方加入可信UA: https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_4_x/NOTE.md
> > > 非常感谢，我只是想把我手里这个闲置的产品发挥更好，小米路由器R1D在中国大概有几十万的销量啊，这么多的存量应该有需求的，还可以插硬盘，如果只能运行transmission ,那太可惜了！
> 
> PT下载用什么工具都很快，所以无所谓用什么了。你用transmission也行，不喜欢transmission也可以用aria2，aria2还支持修改UA，我自己也维护了一份aria2的musl构建: https://github.com/abcfy2/aria2-static-build/releases/tag/continuous , 可以在小米路由器上运行。
> 
> qbee的持续构建已经全部迁移到docker上了，想要编译原版只需要把`.github/workflows/cross_build.sh` 拷贝到原版qb的源码中对应的目录下，使用docker即可构建:
> 
> ```shell
> docker run --rm -e CROSS_HOST=arm-linux-musleabi -e USE_CHINA_MIRROR=1 -v `pwd`:/build ubuntu /build/.github/workflows/cross_build.sh
> ```
> 
> 构建生成的二进制文件存放于`.github/workflows/`目录下

以上命令我需要 克隆到本地 然后运行吗？
还是在action 里面运行，新手，真的不太会。

**Comment by abcfy2** [comment]
> > > > 一劳永逸的办法是请求PT维护方加入可信UA: https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_4_x/NOTE.md
> > > > 非常感谢，我只是想把我手里这个闲置的产品发挥更好，小米路由器R1D在中国大概有几十万的销量啊，这么多的存量应该有需求的，还可以插硬盘，如果只能运行transmission ,那太可惜了！
> > 
> > 
> > PT下载用什么工具都很快，所以无所谓用什么了。你用transmission也行，不喜欢transmission也可以用aria2，aria2还支持修改UA，我自己也维护了一份aria2的musl构建: https://github.com/abcfy2/aria2-static-build/releases/tag/continuous , 可以在小米路由器上运行。
> > qbee的持续构建已经全部迁移到docker上了，想要编译原版只需要把`.github/workflows/cross_build.sh` 拷贝到原版qb的源码中对应的目录下，使用docker即可构建:
> > ```shell
> > docker run --rm -e CROSS_HOST=arm-linux-musleabi -e USE_CHINA_MIRROR=1 -v `pwd`:/build ubuntu /build/.github/workflows/cross_build.sh
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 构建生成的二进制文件存放于`.github/workflows/`目录下
> 
> 以上命令我需要 克隆到本地 然后运行吗？ 还是在action 里面运行，新手，真的不太会。

当然是本地就可以

**Comment by wei134102** [comment]
ok,我马上试一下
新手，感谢回复！

**Comment by abcfy2** [comment]
> 
[qbittorrent-nox_arm-linux-musleabi_static.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/7894360/qbittorrent-nox_arm-linux-musleabi_static.zip)

自己编译了一个。不过以小米路由器那个性能估计也不会跑太流畅，建议你还是考虑用aria2搭配webui的方案跑PT会更合适一些

**Comment by wei134102** [comment]
> > ok,我马上试一下 新手，感谢回复！
> 
> [qbittorrent-nox_arm-linux-musleabi_static.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/7894360/qbittorrent-nox_arm-linux-musleabi_static.zip)
> 
> 自己编译了一个。不过以小米路由器那个性能估计也不会跑太流畅，建议你还是考虑用aria2搭配webui的方案跑PT会更合适一些

我还是没研究明白，我本机就是Ubuntu 18.04 克隆项目文件夹下没有workflow文件夹，感谢你的包，我试一下，

**Comment by wei134102** [comment]
> > > ok,我马上试一下 新手，感谢回复！
> > 
> > 
> > [qbittorrent-nox_arm-linux-musleabi_static.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/7894360/qbittorrent-nox_arm-linux-musleabi_static.zip)
> > 自己编译了一个。不过以小米路由器那个性能估计也不会跑太流畅，建议你还是考虑用aria2搭配webui的方案跑PT会更合适一些
> 
> 我还是没研究明白，我本机就是Ubuntu 18.04 克隆项目文件夹下没有workflow文件夹，感谢你的包，我试一下，

你的可以使用不警告，真的感谢，如果你有时间可以教一下我怎么编译吗？万分感谢！

**Comment by wei134102** [comment]
[
![无标题](https://user-images.githubusercontent.com/69394172/150082510-71d9a529-2626-472b-a92d-59eb25982e61.png)
](url)

同时开TR,QB下载文件占用情况，半斤八两他两个，感谢你的编译文件abcfy2 。
