### ISSUE TITLE
不能同时登录同一域名下反代的原版 修改版qb

### ISSUE THREAD

**Issue by Immity** [c0re100/qBittorrent-Enhanced-Edition#322]
### qBittorrent & operating system versions

qbittorrent-enhanced-nox_v4.4.0_x86_64-linux-musl_static

### What is the problem?

应该是cookie冲突的问题，能否将修改版登录后的cookie与原版qb区分开

**Comment by abcfy2** [comment]
参考: https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_4_x/NOTE.md#multiple-instances-tutorial

启动的时候指定不同的profile即可。端口冲突问题可以运行之后在webui上修改端口配置。如果已经有一个运行中的实例了，可以在启动的时候指定端口:

```sh
qbittorrent-nox --webui-port=9876
```

**Comment by Immity** [comment]
已解决，nginx配置cookie相关路径即可实现同时登录

原版qBittorrent反代配置：
###     
    location /qb {
        return 301 /qbittorrent/;
    }
    location /qbittorrent/ {
        proxy_pass http://127.0.0.1:2021/;
        proxy_http_version 1.1;

        proxy_set_header   Host               127.0.0.1:2021;
        proxy_set_header   X-Forwarded-Host   $http_host;
        proxy_set_header   X-Forwarded-For    $remote_addr;

        proxy_cookie_path  / /qbittorrent/;
        proxy_set_header   Cookie $http_cookie; 
    }
修改版qBittorrent反代配置：
### 
    location /qbee {
        return 301 /qbittorrentee/;
    }
    location /qbittorrentee/ {
        proxy_pass http://127.0.0.1:2022/;
        proxy_http_version 1.1;

        proxy_set_header   Host               127.0.0.1:2022;
        proxy_set_header   X-Forwarded-Host   $http_host;
        proxy_set_header   X-Forwarded-For    $remote_addr;

        proxy_cookie_path  / /qbittorrentee/;
        proxy_set_header   Cookie $http_cookie; 
    }
