### ISSUE TITLE
发现有Bittorrent Media Player没有被Ban

### ISSUE THREAD

**Issue by Trustedinstall** [c0re100/qBittorrent-Enhanced-Edition#323]
### qBittorrent & operating system versions

qBittorrent-Enhanced-Edition: 4.4.0.10 x64
OS: Windows 10 Pro 21H2 x64
Qt: 5.15.2
Libtorrent: 2.0.5.0

### What is the problem?

已经在设置>高级中开启了 Auto Ban Bittorrent Media Player Peer 和 Auto Ban Unknown Peer from China
但是还有Bittorrent Media Player出现在用户列表中，并且出现了传输流量。
客户端名称: Stellar Player 2.0.0.0
Peer ID: -SP2000-
这是它的网站: https://www.stellarplayer.com/
可以看出它确实是一个Bittorrent Media Player

### Additional context

![无标题](https://user-images.githubusercontent.com/68763785/150516644-4ee25c94-a291-4fe9-b85e-337c20fd9d7e.png)

**Comment by SeaHOH** [comment]
你可以暂时添加到黑名单。需要注意的是 ID `-SPxxxx-` 和 BitSpirit 撞车了，不过要到 3.6 才会完全撞上，也可以只匹配 UA。

**Comment by SeaHOH** [comment]
3.6 有啊，挺多的。其它旧版就非常罕见。

**Comment by pinyangcong** [comment]
@Kolcha please add the peer ,thanks.

**Comment by SeaHOH** [comment]
> 重启Qbittorrent即可设置 可以顺便屏蔽百度云的离线下载
> 
> > -GT\d{4}-     .*

不该是 `-GT2000-` 吗，莫非百毒升级使用了新版？

**Comment by pinyangcong** [comment]
> > 重启Qbittorrent即可设置 可以顺便屏蔽百度云的离线下载
> > > -GT\d{4}-     .*
> 
> 不该是 `-GT0002-` 吗，莫非百毒升级使用了新版？

GT开头的通配数字，我图省事就全加进去了，反正用这个下载器还不改peer的少之又少
