### ISSUE TITLE
能打包一个Debian的包吗？

### ISSUE THREAD

**Issue by wsndshx** [c0re100/qBittorrent-Enhanced-Edition#33]
看见隔壁arch都有了……Debian表示我也有一个原版的包。
![image](https://user-images.githubusercontent.com/7829265/54801355-75202f80-4ca1-11e9-8106-f5473627d93b.png)

**Comment by c0re100** [comment]
非常抱歉
我不太熟悉Debian，上次接觸Debian已經是6年前了
另外，因學業關係，目前我沒有太多時間處理...

如果有人熟悉Debian的，可以替我打包一下，感謝！

**Comment by yinflying** [comment]
Arch打包非常容易，debian就没那么容易了。

**Comment by axzxc1236** [comment]
[qbittorrent-enhanced-edition_4.1.5-1_amd64.deb.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/3038715/qbittorrent-enhanced-edition_4.1.5-1_amd64.deb.zip)

試著用checkinstall製作了一個.deb包  沒測試過

我不知道怎麼在deb檔加入dependency，但有裝過原版4.1.5版的系統應該都可以用"dpkg -i qbittorrent-enhanced-edition_4.1.5-1_amd64.deb"安裝(請先移除原版)

**Comment by AlexaraWu** [comment]
[qbittorrent-enhanced-edition - Google Drive](https://drive.google.com/drive/folders/1jmG29LPf1Lw4vP5XN2Vj6n7lNbRUmKCz?usp=sharing)
在 stretch 上打了个包，放在 Google Drive 上了。

**qBittorrent：**
```bash
sudo apt install -y libboost-chrono-dev libboost-random-dev libboost-system-dev \
                    libssl-dev qtbase5-dev zlib1g-dev libgeoip-dev
sudo dpkg -i libtorrent-rasterbar9_1.1.11-2_amd64.deb
sudo dpkg -i qbittorrent_4.1.5-1_amd64.deb
```

**qBittorrent-nox：**
```bash
sudo apt install -y libboost-chrono-dev libboost-random-dev libboost-system-dev \
                    libssl-dev qtbase5-dev zlib1g-dev
sudo dpkg -i libtorrent-rasterbar9_1.1.11-2_amd64.deb
sudo dpkg -i qbittorrent-nox_4.1.5-1_amd64.deb
```

**Comment by poplite** [comment]
自己做的 PPA：https://launchpad.net/~poplite/+archive/ubuntu/qbittorrent-enhanced

支持 Ubuntu 16.04、18.04、18.10 和 19.04 版本，支持 i386、amd64、arm64 和 armhf 平台。
按照官网教程给 qbittorrent-nox 添加了一个启动脚本，便于服务器上使用。
与原版 qbittorrent 冲突，安装前记得将其移除。
（别安装 PPA 中的调试包，因为空间不够准备下一次更新后删掉）

自己的机器（64位 Ubuntu 16.04和18.04）上运行正常。其他平台没有测试过。

第一次做 deb 包，如果软件包有什么问题麻烦告诉我一声。

**Comment by mzhboy** [comment]
> 自己做的 PPA：https://launchpad.net/~poplite/+archive/ubuntu/qbittorrent-enhanced
> 
> 支持 Ubuntu 16.04、18.04、18.10 和 19.04 版本，支持 i386、amd64、arm64 和 armhf 平台。
> 按照官网教程给 qbittorrent-nox 添加了一个启动脚本，便于服务器上使用。
> 与原版 qbittorrent 冲突，安装前记得将其移除。
> （别安装 PPA 中的调试包，因为空间不够准备下一次更新后删掉）
> 
> 自己的机器（64位 Ubuntu 16.04和18.04）上运行正常。其他平台没有测试过。
> 
> 第一次做 deb 包，如果软件包有什么问题麻烦告诉我一声。

苦逼的我用的stretch，还在编译libtorrent
我在考虑要不要切回bionic
sbc内存紧张，zram艹得太狠了，慢如蜗牛
还不如换os方便
请问后面保持更新吗

**Comment by poplite** [comment]
若无特殊情况，PPA 会一直更新。

维护这个 PPA 没有多大难度，打包脚本来源于[Debian Sid](https://packages.debian.org/sid/qbittorrent)，还有一个[官方 PPA](https://launchpad.net/~qbittorrent-team/+archive/ubuntu/qbittorrent-stable)可供参考。

**Comment by youling257** [comment]
> > > 自己做的 PPA：https://launchpad.net/~poplite/+archive/ubuntu/qbittorrent-enhanced
> > > 支持 Ubuntu 16.04、18.04、18.10 和 19.04 版本，支持 i386、amd64、arm64 和 armhf 平台。
> > > 按照官网教程给 qbittorrent-nox 添加了一个启动脚本，便于服务器上使用。
> > > 与原版 qbittorrent 冲突，安装前记得将其移除。
> > > （别安装 PPA 中的调试包，因为空间不够准备下一次更新后删掉）
> > > 自己的机器（64位 Ubuntu 16.04和18.04）上运行正常。其他平台没有测试过。
> > > 第一次做 deb 包，如果软件包有什么问题麻烦告诉我一声。
> > 
> > 
> > 苦逼的我用的stretch，还在编译libtorrent
> > 我在考虑要不要切回bionic
> > sbc内存紧张，zram艹得太狠了，慢如蜗牛
> > 还不如换os方便
> > 请问后面保持更新吗
> 
> 若无特殊情况，PPA 会一直更新。
> 
> 维护这个 PPA 没有多大难度，打包脚本来源于[Debian Sid](https://packages.debian.org/sid/qbittorrent)，还有一个[官方 PPA](https://launchpad.net/~qbittorrent-team/+archive/ubuntu/qbittorrent-stable)可供参考。

 仓库 “http://ppa.launchpad.net/poplite/qbittorrent-enhanced/ubuntu eoan Release” 没有 Release 文件。

**Comment by poplite** [comment]
> > > > 自己做的 PPA：https://launchpad.net/~poplite/+archive/ubuntu/qbittorrent-enhanced
> > > > 支持 Ubuntu 16.04、18.04、18.10 和 19.04 版本，支持 i386、amd64、arm64 和 armhf 平台。
> > > > 按照官网教程给 qbittorrent-nox 添加了一个启动脚本，便于服务器上使用。
> > > > 与原版 qbittorrent 冲突，安装前记得将其移除。
> > > > （别安装 PPA 中的调试包，因为空间不够准备下一次更新后删掉）
> > > > 自己的机器（64位 Ubuntu 16.04和18.04）上运行正常。其他平台没有测试过。
> > > > 第一次做 deb 包，如果软件包有什么问题麻烦告诉我一声。
> > > 
> > > 
> > > 苦逼的我用的stretch，还在编译libtorrent
> > > 我在考虑要不要切回bionic
> > > sbc内存紧张，zram艹得太狠了，慢如蜗牛
> > > 还不如换os方便
> > > 请问后面保持更新吗
> > 
> > 
> > 若无特殊情况，PPA 会一直更新。
> > 维护这个 PPA 没有多大难度，打包脚本来源于[Debian Sid](https://packages.debian.org/sid/qbittorrent)，还有一个[官方 PPA](https://launchpad.net/~qbittorrent-team/+archive/ubuntu/qbittorrent-stable)可供参考。
> 
> 仓库 “http://ppa.launchpad.net/poplite/qbittorrent-enhanced/ubuntu eoan Release” 没有 Release 文件。

暂不支持尚未上线的 Ubuntu 19.10

**Comment by yangfl** [comment]
debiancn已加入qBittorrent-Enhanced，欢迎使用及报告问题。
https://repo.debiancn.org/pool/main/q/qbittorrent-enhanced/

**Comment by mzhboy** [comment]
可惜不支持arm

**Comment by yangfl** [comment]
@mzhboy 欢迎贡献一台arm机器 XD

**Comment by mzhboy** [comment]
不知道怎么做，买个SBC最好了，挺有用的。现在最划算的是 树莓派4.要便宜的有国产orangepi一百多能买到。

**Comment by yangfl** [comment]
没钱

**Comment by mzhboy** [comment]
那你看能不能尝试交叉编译一下吧，交叉编译还挺麻烦的。编译能通过一般没问题了。我可以来测

**Comment by c0re100** [comment]
Thanks.
Ubuntu/Debian repository link added to README~
https://github.com/c0re100/qBittorrent-Enhanced-Edition#repository

**Comment by abcfy2** [comment]
@yangfl 上游已经更新到了4.1.7.1，而debian cn仓库依旧停留在4.1.6.1，不知是否考虑启用CI自动更新仓库，减少人工维护的工作量呢？

**Comment by yangfl** [comment]
没有拉取到release-4.1.7.1这个tag。另外目前软件源维护自动化程度太低，暂时还集成不了CI。

**Comment by abcfy2** [comment]
的确，看了下debiancn的说明文档，目前提交deb的方式主要是手工提交，暂时还没有完成自动提交的功能

**Comment by abcfy2** [comment]
看了下 debiancn 的[贡献说明](https://github.com/debiancn/repo/blob/master/README.rst#%E5%90%91%E7%A4%BE%E5%8C%BA%E6%BA%90%E6%8F%90%E4%BA%A4%E4%B8%80%E4%B8%AA%E8%BD%AF%E4%BB%B6%E5%8C%85)

是支持通过scp上传deb的，如果是这样的话理论上应该可以通过 travis-ci 这一类的CI工具直接触发上传

**Comment by IceCodeNew** [comment]
@poplite 新版本发布了，是否可以抽空更新一下 ubuntu 软件仓库？感谢！
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/latest

**Comment by poplite** [comment]
@IceCodeNew 
我已经将源码上传到 Launchpad 上编译了。
现在还在[编译中](https://launchpad.net/~poplite/+archive/ubuntu/qbittorrent-enhanced/+builds?build_text=&build_state=building)，估计要半个小时完成编译和推送。

**Comment by abcfy2** [comment]
我本人对打包deb不熟，是否考虑直接给 @c0re100 提交一个PR，编译deb,rpm,appimage的脚本？我可以贡献一个Travis CI的构建脚本，每次release的时候自动生成deb/rpm/appimage/exe (Wine 环境? 需要测试下)这些assets推送到Release，但是需要熟悉打包过程的高手贡献打包脚本。

我本地的deepin环境连编译都没法通过

**Comment by IceCodeNew** [comment]
> @IceCodeNew
> 我已经将源码上传到 Launchpad 上编译了。
> ~现在还在[编译中](https://launchpad.net/~poplite/+archive/ubuntu/qbittorrent-enhanced/+builds?build_text=&build_state=building)，估计要半个小时完成所有的编译和推送。~已完成所有的编译和推送。

非常感谢，辛苦了。
不知道您是否有意将持续发布集成到 Ubuntu 软件仓库上，这样未来就可以少很多工作了。

**Comment by poplite** [comment]
@IceCodeNew

我认为持续集成比较适合于构建每日版本或者软件测试。软件新版本的发布周期一般比较长，用持续集成发布软件包用处不大。

不过这个项目的活跃度不高，用持续集成发布软件包还是有一定好处的。因此我写了一个自动签名并上传源码包到 Launchpad 编译的脚本，明天就开个 repo 发布出来。

**Comment by poplite** [comment]
qBittorrent (Enhanced Edition) Ubuntu packages repository 
https://github.com/poplite/qBEE-Ubuntu-Packaging

**Comment by abcfy2** [comment]
@poplite 感谢你的脚本参考，我差不多知道我的环境为何无法编译成功了。是libtorrent版本的问题。我考虑把libtorrent静态编译，但是奇怪的是用官方的configure直接编译的静态库有200多MB这么大，动态库so也有90MB这么大，但是deb包却只有4MB。

我用了你的仓库的构建脚本和debian sid上游的source包编译，发现它的build目录下的的libtorrent源码编译出的静态库和动态库同样有200MB和90MB这么大，但是生成的deb只有4MB，安装之后的/usr/lib下的libtorrent-rasterbar这个so同样也只有4MB，不知道它是怎么做到的，我用ldd也检查不出来什么区别，不知道能否提供思路？如何编译这么小的类库？

**Comment by poplite** [comment]
@abcfy2 [strip](http://linux.51yip.com/search/strip)?

**Comment by IceCodeNew** [comment]
> @poplite 感谢你的脚本参考，我差不多知道我的环境为何无法编译成功了。是libtorrent版本的问题。我考虑把libtorrent静态编译，但是奇怪的是用官方的configure直接编译的静态库有200多MB这么大，动态库so也有90MB这么大，但是deb包却只有4MB。
> 
> 我用了你的仓库的构建脚本和debian sid上游的source包编译，发现它的build目录下的的libtorrent源码编译出的静态库和动态库同样有200MB和90MB这么大，但是生成的deb只有4MB，安装之后的/usr/lib下的libtorrent-rasterbar这个so同样也只有4MB，不知道它是怎么做到的，我用ldd也检查不出来什么区别，不知道能否提供思路？如何编译这么小的类库？

你静态编译的 libtorrent 是什么版本？1.2_x 么？目前比较新的 releases 都需要 qBittorrent 4.2_x 才支持。
这个修改版的 qBittorrent 是 4.1_x 版本，只有用 17 年发布的 libtorrent 1.1_x 才行。

**Comment by yangfl** [comment]
debiancn的qbee已更新。
打包脚本在 https://github.com/debiancn/qBittorrent-Enhanced-Edition

**Comment by abcfy2** [comment]
使用的libtorrent是1.1.13版本的，用1.2.2会编译失败。我看了下上游的qBitorrent的PPA仓库，用的就是libtorrent 1.1.13版本，所以也降级到这个版本编译成功了。

google了下，似乎就是strip的问题，应该是deb打包的时候会自动做strip缩减类库的容量。我在google上也找到了这个: https://github.com/facebook/rocksdb/issues/852 编译libtorrent的时候使用 `CXXFLAGS="-flto -Os -s -ffunction-sections -fdata-sections -Wl,--gc-sections" ./configure --with-libiconv`，上面几个参数中，那个`-s`就是直接编译的时候调用`strip`，这样编译出来的so文件就只有4MB了，和deb包相符。

不过静态编译后的`libtorrent-rasterbar.a`文件也有70MB这么大，虽然相比之前200多MB小了很多，但是觉得链接到qbitorrent-ee中还是不合适，软件包太大了，考虑只链接一个so动态链接库算了，其他依赖来自于操作系统，我初步看了下，除了libtorrent之外，别的依赖在Ubuntu 16.04之上，Debian 8之上的版本应该都是满足依赖的，因此理论上只需要把这一个动态链接库包含到产品包中就可以了。

初步的设想是一个deb包可以跑在Ubuntu 16.04+, Debian 8+, deepin 15.11+ 版本，所以需要考虑规避这些环境中依赖的差异性问题。

**Comment by poplite** [comment]
这是我写的用 [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) 自动创建 AppImage 的脚本：[makeAppImage.sh](https://gist.github.com/poplite/2f69f534f2c335fa7a84c4e6fc5b1e73)

下面这是我在 Ubuntu 16.04 (glibc 2.23) 下创建的 AppImage，大小在 40MB 左右。

[qBittorrent_(Enhanced_Edition)-4.1.8.1-x86_64.AppImage.zip - Google Drive](https://drive.google.com/open?id=11p9U5jiPophsGJjLp_kwNBqIZlGuGZag)

**Comment by abcfy2** [comment]
其他的几个类库链接问题我都解决了，就剩下libboost的那几个类库了，奇怪的是我明明把链接参数改成了`-l:libboost_system.so`，但是ldd显示的结果依旧是`libboost_system1.62.so -> xxxxx`这种带具体版本号的，这样在一个系统编译的qBitorrent拿到另一个系统就会提示这几个lib找不到，不同Ubuntu和Debian版本下软件仓库自带的libboost版本不一致，这个我还在想怎么解决

**Comment by poplite** [comment]
@abcfy2 一些库不同版本之间存在有差异（如`API`），若不锁定版本号，运行程序时可能会出错。

要不静态编译，要不像`AppImage`这样将所有的动态运行库都封装在一起。

**Comment by abcfy2** [comment]
不行，搞一个通用的deb工程量太大了，不太好弄

这玩意底层依赖还挺多，Ubuntu和Debian每个版本的glibc, openssl, qt5, libboost这几个版本都不一样。libssl, libboost虽然可以通过静态链接的方式规避版本差异，但是qt5这玩意比较麻烦，debian和ubuntu软件仓库自带的qt5不是静态编译版本的，想静态编译需要重新源码编译整个qt，想想还是算了。

另外glibc这玩意静态链接也不太合适，容量太大了。

所以还是通过CI构建Appimage比较靠谱点，可以做一些优化之类的，比如生成desktop文件，文件关联之类的。

deb还真得每个发行版搞个自己的仓库，每个版本单独编译，整个项目全部静态编译难度有点高啊

**Comment by abcfy2** [comment]
哈哈，搞定，基本所有的坑都踩平了，最终编译的成品29.5MB: https://1drv.ms/u/s!Aj-Tqq25AMlxpjoxr__DWyqjBowl?e=WdDWnW

估计你那个40MB是因为没有strip吧？

已经用脚本成功跑出来了，稍后会添加travis ci脚本自动构建。

一开始用的debian sid构建，发现几乎所有的操作系统都无法运行，都因为libc版本太低导致无法运行。于是按照appimage官方建议，使用glibc版本低的操作系统构建，官方推荐centos 6。

但是centos 6的版本库实在太老，连fuse支持都有问题，编译出来也是一堆问题，于是改成centos 7构建，终于能将构建脚本完整跑下来了。不过依旧额外打包了一些没什么用的selinux相关的so。另外centos 7安装高版本的类库也不是特别方便，软件仓库太少，libtorrent, libboost之类的都是自己编译升级上去的，本来还想编译qt5，一看依赖太重了，编译时间太久无法接受，暂时改用了epel仓库的qt5版本构建(5.9)

考虑到travis ci的Linux OS环境只有Ubuntu，稍后还需要改成ubuntu 16.04的构建脚本。不过依赖安装方便多了，基本都能加ppa装新版本，应该没什么大问题。

**Comment by poplite** [comment]
@abcfy2 有依赖错误（Ubuntu 16.04）
```
$ ./qBittorrent-x86_64.AppImage 
/tmp/.mount_qBittohH19Wr/AppRun.wrapped: symbol lookup error: /tmp/.mount_qBittohH19Wr/usr/bin/../lib/libQt5Gui.so.5: undefined symbol: hb_font_funcs_set_font_h_extents_func
```

估计跟这个有关？https://community.teamviewer.com/t5/Previous-versions-EN/GUI-doesn-t-show-up-on-Centos-7-3/td-p/39967

**Comment by abcfy2** [comment]
@poplite 我是在debian sid下用docker跑的centos 7镜像编译的(centos 6的docker镜像无法运行)。只是在debian sid下运行测试了一下，暂时没在低版本的debian和ubuntu下运行过。

我已经打算在ubuntu 16.04下使用linuxbrew搭建编译环境重新编译，应该可以用上几乎所有最新的lib，这样方便对接travis ci，已经路线跑通，剩下再优化一下就差不多了，到时候再看看

**Comment by abcfy2** [comment]
基本上大方向都没什么问题了，在travis-ci上也build成功: https://travis-ci.com/abcfy2/qBittorrent-Enhanced-Edition/builds/131262072

就是在用homebrew搭建的编译环境我的AMD CPU上运行有报错:

```
Incompatible processor. This Qt build requires the following features:
    ssse3
```

暂时还不知道怎么解决，正在想办法。

**Comment by IceCodeNew** [comment]
ubuntu eoan 正式发布了~
不知道维护者是否可以哪天抽空发布一下新包，提前谢过了 @poplite

**Comment by poplite** [comment]
> ubuntu eoan 正式发布了~
> 不知道维护者是否可以哪天抽空发布一下新包，提前谢过了 @poplite

现在的 v4.8.1.2 有个Bug：https://github.com/c0re100/qBittorrent-Enhanced-Edition/pull/54#issuecomment-541327482

我打算等 v4.8.1.3 发布后再发布新包和支持 19.10。

**Comment by IceCodeNew** [comment]
有道理，那我就先回滚到 19.04 了~

**Comment by c0re100** [comment]
> > ubuntu eoan 正式发布了~
> > 不知道维护者是否可以哪天抽空发布一下新包，提前谢过了 @poplite
> 
> 现在的 v4.8.1.2 有个Bug：[#54 (comment)](https://github.com/c0re100/qBittorrent-Enhanced-Edition/pull/54#issuecomment-541327482)
> 
> 我打算等 v4.8.1.3 发布后再发布新包和支持 19.10。

你可以先發佈4.8.1.1
因為我未能給出準確的日期何時會正式發佈4.8.1.3
因為我在#54提供的Alpha版本方案不可行，仍在嘗試其他方法

**Comment by poplite** [comment]
> > > ubuntu eoan 正式发布了~
> > > 不知道维护者是否可以哪天抽空发布一下新包，提前谢过了 @poplite
> > 
> > 
> > 现在的 v4.8.1.2 有个Bug：[#54 (comment)](https://github.com/c0re100/qBittorrent-Enhanced-Edition/pull/54#issuecomment-541327482)
> > 我打算等 v4.8.1.3 发布后再发布新包和支持 19.10。
> 
> 你可以先發佈4.8.1.1
> 因為我未能給出準確的日期何時會正式發佈4.8.1.3
> 因為我在#54提供的Alpha版本方案不可行，仍在嘗試其他方法

@IceCodeNew 已发布 19.10 的软件包，版本为4.1.8.1。

16.04、18.04、19.04 仍然维持在4.1.8.2，因为 deb 版本管理的限制，无法回滚到4.1.8.1。
希望能尽快释出4.1.8.3。

**Comment by abcfy2** [comment]
今天准备把AppImage的PR提交了，没办法，不想在等Linuxbrew上游了。

之前采用过很多方案，尝试过很多方案构建，暂定使用Ubuntu 16.04系统构建，因为这个系统还在维护中，并且libc版本不至于太高，我实测了下，基本上除了CentOS 7之外，别的还在维护的Linux发行版都能运行。

之前主要想使用的方案是使用Linuxbrew搭建编译环境，因为它的类库几乎都是最新版本。但是发现使用后一堆问题，就是因为homebrew原本是MacOS上的第三方社区包管理器，所以它大多软件构建方式都是优先满足MacOS的，而Linux是后来才加入的，编译出来的版本虽然新，但是各种缺斤少两的问题层出不穷。比如我就发现qt没有编译fontconfig支持，结果编译出来的qbittorrent无法显示界面文字。找了很多天的原因，给官方提交了PR: https://github.com/Homebrew/linuxbrew-core/pull/16216 找打了Ubuntu的构建参数，使用Ubuntu的参数进行构建。官方以优先考虑MacOS为由拒绝了我的PR，希望这些参数优先能在MacOS测试通过，优先合并到上游的Homebrew，然后差异参数在Linuxbrew中单独处理，而我手头没有MacOS，也暂时没有精力继续同时维护MacOS和Linux两大操作系统的包维护。所以暂时放弃了。

最后还是采用Ubuntu 16.04 + PPA的方式搭建编译环境吧，这样虽然各个软件包都不是最新版(比如ppa的QT只到 5.12.3)，但是起码不折腾，省事了。折腾Linuxbrew环境，我都不知道发现了多少小问题，提交了多少次PR，在我本地反复编译测试了多少次，哎，心累。

**Comment by abcfy2** [comment]
已经在 #58 提交了AppImage的CI构建脚本，效果参见: https://github.com/abcfy2/qBittorrent-Enhanced-Edition/releases/tag/v4.1.8.2-2

可以直接在Release 页面下载构建制品，我自己本地测试了Ubuntu 16.04, 18.04, debian 10, debian sid, Deepin等，均可以运行，CentOS7由于glibc版本太低无法运行，欢迎大家测试

**Comment by IceCodeNew** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/latest

@poplite 敲敲（

**Comment by poplite** [comment]
@IceCodeNew 源码已上传至 Launchpad ，现在还处于 Pending 状态，大概还需要半个小时。
[Builds for qBittorrent Enhanced Edition](https://launchpad.net/~poplite/+archive/ubuntu/qbittorrent-enhanced/+builds?build_text=&build_state=all)

**Comment by poplite** [comment]
从 4.2.0 开始，qBittorrent 只支持 Bionic (18.04) 以及以上的 Ubuntu 版本，原因是最低 qt 版本要求[已提高](https://github.com/qbittorrent/qBittorrent/pull/10338)到 5.9。

所以若无意外，PPA 的 Xenial (16.04) 源将会停留在`v4_1_x`分支，其余源更新至`v4_2_x`分支。

**Comment by mzhboy** [comment]
有点离题但是如果有用 [remote torrent adder](https://chrome.google.com/webstore/detail/remote-torrent-adder/oabphaconndgibllomdcjbfdghcmenci) 的用户需要在更新qb 4.2之后使用 [临时解决方案](https://github.com/bogenpirat/remote-torrent-adder/issues/253#issuecomment-534719033)

**Comment by xixky** [comment]
因为ubuntu arm bug多，我换到debian10了 ，我为qbittorrent-enhanced编译了一个包 ，编译文章有空再写。https://github.com/xixky/qbittorrent-enhanced-for-debian-buster-armhf

**Comment by freesilent** [comment]
> 
> 
> debiancn的qbee已更新。
> 打包脚本在 https://github.com/debiancn/qBittorrent-Enhanced-Edition

请问，https://repo.debiancn.org/pool/main/q/qbittorrent-enhanced/ 里的qbee可以和原版共存么？

**Comment by Kolcha** [comment]
release: https://software.opensuse.org//download.html?project=home%3Anikoneko%3Atest&package=qbittorrent-enhanced
nightly: https://software.opensuse.org//download.html?project=home%3Anikoneko%3Aqbittorrent-nightly&package=qbittorrent-enhanced

nightly builds are available only for Debian Testing and Debian Unstable
release builds are also available for Debian and Raspbian 10
feel free to ask me for builds for any other architectures rather than amd64 (x86_64)

the same links are also in README on main page

@c0re100 , maybe it is worth to close this issue
