### ISSUE TITLE
Add webhook/telegram/Discord bot support when download finished

### ISSUE THREAD

**Issue by zzz6839** [c0re100/qBittorrent-Enhanced-Edition#331]
### Suggestion

Adding different notification methods would be helpful for server version Qbittorent, but only email is available right now.

### Use case

docker/server version Qbittorent

**Comment by abcfy2** [comment]
That's a good idea to submit this issue to upstream qbittorrent. If official qbittorrent implements this feature, then qbittorrent enhanced editon will also benefit.
