### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by oOTnTOo** [c0re100/qBittorrent-Enhanced-Edition#34]
Ubuntu 16.04.2

Qt 5.5.1 libtorrent 1.0.7 
编译出错：

**Comment by oOTnTOo** [comment]
cd src/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/kwh/下载/qBittorrent-Enhanced-Edition/src/src.pro QMAKE_LRELEASE= -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/kwh/下载/qBittorrent-Enhanced-Edition/src'
compiling base/bittorrent/session.cpp
base/bittorrent/session.cpp: In constructor ‘BitTorrent::Session::Session(QObject*)’:
base/bittorrent/session.cpp:439:53: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     m_nativeSession->set_alert_dispatch([this](std::auto_ptr<libt::alert> alertPtr)
                                                     ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /usr/include/boost/smart_ptr/shared_array.hpp:19,
                 from /usr/include/boost/shared_array.hpp:17,
                 from /usr/include/libtorrent/torrent_info.hpp:44,
                 from base/bittorrent/torrentinfo.h:32,
                 from base/bittorrent/session.h:62,
                 from base/bittorrent/session.cpp:30:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
base/bittorrent/session.cpp: In member function ‘bool BitTorrent::Session::addTorrent_impl(BitTorrent::CreateTorrentParams, const BitTorrent::MagnetUri&, BitTorrent::TorrentInfo, const QByteArray&)’:
base/bittorrent/session.cpp:2399:20: error: ‘flag_stop_when_ready’ is not a member of ‘libtorrent::add_torrent_params’
         p.flags |= libt::add_torrent_params::flag_stop_when_ready;
                    ^
Makefile:2606: recipe for target 'session.o' failed
make[1]: *** [session.o] Error 1
make[1]: Leaving directory '/home/kwh/下载/qBittorrent-Enhanced-Edition/src'
Makefile:42: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2

**Comment by c0re100** [comment]
編譯libtorrent時 加上c++11
`./configure --disable-debug --enable-encryption --with-libgeoip=system CXXFLAGS=-std=c++11`

**Comment by oOTnTOo** [comment]
没用，我试过了，查了查，是因为4.0往上需要的libtorrent库是1.1以上版本，boost也是高版本……然而最终还是失败了，找到了qBittorrent官方发布的Debian源，直接apt install了，折腾一天没编译成……
另外，请教一下，这个加强版相比官方版有什么异同？

**Comment by c0re100** [comment]
> 没用，我试过了，查了查，是因为4.0往上需要的libtorrent库是1.1以上版本，boost也是高版本……然而最终还是失败了，找到了qBittorrent官方发布的Debian源，直接apt install了，折腾一天没编译成……
> 另外，请教一下，这个加强版相比官方版有什么异同？

4.0以上可以繼續用libtorrent1.0的(詳細可以看本repo的Release), 而4.2以後就不支援1.0了
https://github.com/qbittorrent/qBittorrent/issues/9871#issuecomment-439797224
Ubuntu的話 試試直接用官方PPA 再編譯qbittorrent?

異同方面: 就是多了[自動封鎖吸血端功能, 及一些小功能](https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/tag/release-4.1.5.1)

**Comment by oOTnTOo** [comment]
然而我已经直接使用官方源apt了，请问我在官方版的设置中的“IP过滤”中直接导入ipfilter.dat是不是也能达到封锁吸血端的功能？

**Comment by c0re100** [comment]
> 然而我已经直接使用官方源apt了，请问我在官方版的设置中的“IP过滤”中直接导入ipfilter.dat是不是也能达到封锁吸血端的功能？

使用ipfilter.dat的話 只達到封鎖來自離線伺服器的下載

**Comment by oOTnTOo** [comment]
可我实在编译不过去……好不容易编译通过，运行提示“段错误”……那手动屏蔽应该是可以的吧？迅雷、QQ等客户端会伪装成其他客户端参与下载吗？这种吸血客户端有什么特征呢？

**Comment by c0re100** [comment]
> 可我实在编译不过去……好不容易编译通过，运行提示“段错误”……那手动屏蔽应该是可以的吧？迅雷、QQ等客户端会伪装成其他客户端参与下载吗？这种吸血客户端有什么特征呢？

是的 不過比較麻煩, 而且你需要定期解封這些IP...

**Comment by oOTnTOo** [comment]
好吧，谢谢……等我休息再重新编译一下吧……

**Comment by oOTnTOo** [comment]
编译总算通过了……对于4.1.5.1版本总结一下编译过程：直接使用官方PPA源，安装Qt5，boost 1.65.1，libtorrent-rasterbar1.11.x版本（直接apt libtorrent-rasterbar-dev），可能报qt5svg5找不到（apt libqt5svg5-dev解决）。回到程序目录，configura, make……但是运行还是不稳定……随时可能会闪退跳出……

**Comment by c0re100** [comment]
> 编译总算通过了……对于4.1.5.1版本总结一下编译过程：直接使用官方PPA源，安装Qt5，boost 1.65.1，libtorrent-rasterbar1.11.x版本（直接apt libtorrent-rasterbar-dev），可能报qt5svg5找不到（apt libqt5svg5-dev解决）。回到程序目录，configura, make……但是运行还是不稳定……随时可能会闪退跳出……

咦 你無法編譯時 是用那一個boost版本?
