### ISSUE TITLE
RPM packages for openSUSE and other RPM-based Linux distributions

### ISSUE THREAD

**Issue by PhoenixEmik** [c0re100/qBittorrent-Enhanced-Edition#35]
**Please provide the following information**

### qBittorrent version and Operating System
4.1.5.1, openSUSE

### Extra info(if any)
Since nobody has packaged it yet, I created some RPM packages for openSUSE. Here is my openSUSE Build Service repository: 
https://build.opensuse.org/package/show/home:PhoenixEmik/qbittorrent-enhanced-edition

The [spec file](https://build.opensuse.org/package/view_file/home:PhoenixEmik/qbittorrent-enhanced-edition/qbittorrent-enhanced-edition.spec?expand=1) should work with other RPM-based Linux distributions.

**Comment by bhxch** [comment]
Good job! Use the qbittorrent-enhanced-edition-nox package on openSUSE Tumbleweed and it works well.

**Comment by Mackel123** [comment]
makcelsuse@localhost  ~  qbittorrent
Icon theme "ubuntu-mono-dark" not found.
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
Icon theme "gnome" not found.
QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::removePaths: list is empty

Systerm:Opensuse tumbleweed

**Comment by Mackel123** [comment]
thx，it works after I update the systerm

**Comment by PhoenixEmik** [comment]
Update to version 4.1.6.1.

**Comment by c0re100** [comment]
Thanks.
repository link add to README~
https://github.com/c0re100/qBittorrent-Enhanced-Edition#repository
