### ISSUE TITLE
peer_whitelist.txt里写入.* .*为何不能放行全部

### ISSUE THREAD

**Issue by cjjdaq** [c0re100/qBittorrent-Enhanced-Edition#350]
### qBittorrent & operating system versions

qBittorrent: 4.4.1 x64

### What is the problem?

想通过peer_whitelist.txt放行全部，再通过peer_blacklist.txt根据需要过滤，但发现xunlei啥的还是被ban了。

**Comment by c0re100** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/5#issuecomment-388323963
