### ISSUE TITLE
Ban/Blacklist Torrent Storm 0.0.0.8 Client

### ISSUE THREAD

**Issue by MrGoodGuy2144** [c0re100/qBittorrent-Enhanced-Edition#353]
### Suggestion

For a few years now i have seen many connections from peers using the client "Torrent Storm 0.0.0.8". These peers all seem to be doing the same things, ill list a few below:
-Never downloads the full file, typically only around 1-30% 
-Only downloads with slows speeds 20kbps-200kbps. 
-Usually only connects for a short period of time, then disappears and another torrent storm peer will usually take its place eventually.
-Never uploads anything, EVER (Leech client?)

At first i thought it was a media player, because of the slow download speed and never completes the file, but i quite often see them in non-media torrents too... If you do a quick google search you can see other people having this similar client pop-up over the years, with the same problems... I do wonder if its another program spoofing the client/PeerID and doing something else... but every torrent storm peer do appear to have a different IP and be from all over the world. 

I think considering a ban/blacklist would be reasonable considering the fact that many people have mentioned that the torrent storm client is from around 2005 and hasn't been developed since. (If those peers are truly using the torrent storm 0.0.0.8 client.)

### Use case

Ban/Blacklist this client to prevent the peer abuse.

### Extra info/examples/attachments

![torrentstorm short](https://user-images.githubusercontent.com/58582841/160185760-cb572d36-6121-43fc-8f44-bca243caf313.png)

**Comment by escape0707** [comment]
https://www.grauw.nl/articles/bittorrent.php#TorrentStorm

Some people might be faking this client.
