### ISSUE TITLE
Universal DMGs for both M1 and Intel devices.

### ISSUE THREAD

**Issue by Tsukimeizi** [c0re100/qBittorrent-Enhanced-Edition#354]
### Suggestion

The upstream qBittorrent v4.4.2:
MACOS: Universal DMGs are now offered. They should work natively on both M1 and Intel devices. Minimum supported OS version is macOS 10.15 Catalina.

Could you please also provide a universal DMG for both M1 and Intel devices?

**Comment by toooonyy** [comment]
[qBittorrent-Enhanced-Edition-master-macOS-arm64.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/8355580/qBittorrent-Enhanced-Edition-master-macOS-arm64.zip)
I've complied one for myself, but it's arm only and using non-standard libs. Or you can build one yourself, there's a script.
<img width="657" alt="Screen Shot 2022-03-26 at 15 10 19" src="https://user-images.githubusercontent.com/3480434/160243263-8ec9b341-80f0-4f1f-b029-953a4c26a407.png">

**Comment by Kolcha** [comment]
universal build is already provided, issue can be closed
ping @c0re100
