### ISSUE TITLE
升级4.4.2后 种子数和用户数显示不正常

### ISSUE THREAD

**Issue by Immity** [c0re100/qBittorrent-Enhanced-Edition#355]
### qBittorrent & operating system versions

qBittorrent Enhanced Edition v4.4.2.10 / qbittorrent-enhanced-nox_x86_64-linux-musl_static

Operating system: Debian 11

### What is the problem?

![UKFS_IO497YJ_7L3_6IKOTO](https://user-images.githubusercontent.com/33168134/160241284-10df8e33-4754-46e5-90d1-84e44740a50e.png)

种子数固定显示为420，用户数显示为69

**Comment by c0re100** [comment]
似乎與tracker有關
可以的話，嘗試移除這個tracker `http://atrack.pow7.com/announce` 看看
