### ISSUE TITLE
CI should be fixed.

### ISSUE THREAD

**Issue by abcfy2** [c0re100/qBittorrent-Enhanced-Edition#356]
Upstream qBittorrent has been already fixed. All jobs should be passed.

Seems we should sync from official upsteam codes to fix all CI failed.

@c0re100 .

**Comment by c0re100** [comment]
I will fix it later...
Since libtorrent isn't using latest commit, so our Windows CI failed.

PS: I added 1 Windows only commit.
https://github.com/c0re100/qBittorrent-Enhanced-Edition/commit/3d35b69b181db261e1b0987724f47f8a60c34ebf

**Comment by abcfy2** [comment]
`CI - File health` still failed. But upstream already fixed this.

**Comment by c0re100** [comment]
It's v4_4_x translation file issue.
upstream v4_4_x failed too.

**Comment by abcfy2** [comment]
https://github.com/qbittorrent/qBittorrent/pull/16745 Oh, this PR seems fixed CI, but it's not merged yet.
