### ISSUE TITLE
UI is broken on Mac

### ISSUE THREAD

**Issue by xingcoo** [c0re100/qBittorrent-Enhanced-Edition#36]
### qBittorrent version and Operating System
qBittorrent v4.1.5.1 
MacOS 10.14.4

### What is the problem
UI is broken on Mac version and this problem doesn't exist in original version.
<img width="1011" alt="Enhanced" src="https://user-images.githubusercontent.com/3954137/56873833-d1782b00-6a67-11e9-83a5-6df90ae5a9e2.png">

### What is the expected behavior

<img width="1011" alt="Original" src="https://user-images.githubusercontent.com/3954137/56873832-d1782b00-6a67-11e9-9209-7599e087cdcf.png">

### Steps to reproduce
Just open the app and take a look at the UI.

### Extra info(if any)
(type here)

**Comment by c0re100** [comment]
Oh, official version released after qbittorrent/qBittorrent/pull/10094 merged.
Normally, official version(Mac) will be release in 1-2 weeks after windows version update.
So, the UI is broken in v4.1.5.1

Can you try this build? I'm cherry-picked the progress bar commit.
[qBittorrent-4.1.5.1.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/3129428/qBittorrent-4.1.5.1.zip)

**Comment by xingcoo** [comment]
<img width="1000" alt="Error" src="https://user-images.githubusercontent.com/3954137/56938350-f20db700-6b33-11e9-9fed-9e090ed649ab.png">
Sadly this message showed up when I tried to run the new build.

**Comment by xingcoo** [comment]
After I copied  libboost_system-mt.dylib from 4.1.5.1 the new build works! And its UI is a bit different from official version 4.1.5 now.
<img width="914" alt="New build" src="https://user-images.githubusercontent.com/3954137/56938664-d4415180-6b35-11e9-9cae-9491bc487352.png">

**Comment by c0re100** [comment]
> After I copied libboost_system-mt.dylib from 4.1.5.1 the new build works! And its UI is a bit different from official version 4.1.5 now.
> <img alt="New build" width="914" src="https://user-images.githubusercontent.com/3954137/56938664-d4415180-6b35-11e9-9cae-9491bc487352.png">

The commit is used windows progress bar to fix incorrect progress bar position, so this build have a different progress bar.
QTBUG-72558 seems affected Qt5.10, 5.11 too
I see official version is using Qt 5.9.7, maybe this Qt version is not affected or bug fixed.
Let me try with Qt 5.9.7.

**Comment by c0re100** [comment]
Well, Qt 5.9.7 is not affected.
[qBittorrent-4.1.5.1.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/3133399/qBittorrent-4.1.5.1.zip)

Anyway, since the commit merged, I will follow the official way.

**Comment by xingcoo** [comment]
> Well, Qt 5.9.7 is not affected.
> [qBittorrent-4.1.5.1.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/3133399/qBittorrent-4.1.5.1.zip)
> 
> Anyway, since the commit merged, I will follow the official way.

Awesome, this build completely fixes the issue for me. Thanks!

**Comment by xingcoo** [comment]
libboost_system-mt.dylib is missing in 4.1.5.2, causing the app to crash.

**Comment by c0re100** [comment]
> libboost_system-mt.dylib is missing in 4.1.5.2, causing the app to crash. Copying the missing file from previous version do make it run, however, the app crashes every time when it quits.
> [log.txt](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/3142071/log.txt)
> <img alt="Error" width="1000" src="https://user-images.githubusercontent.com/3954137/57140434-59549100-6dea-11e9-9e61-c9e1b4467e75.png">

Sorry, my mistake. 
fix: https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-4.1.5.1/qBittorrent-4.1.5.2_fix.dmg

**Comment by xingcoo** [comment]
> > libboost_system-mt.dylib is missing in 4.1.5.2, causing the app to crash. Copying the missing file from previous version do make it run, however, the app crashes every time when it quits.
> > [log.txt](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/3142071/log.txt)
> > <img alt="Error" width="1000" src="https://user-images.githubusercontent.com/3954137/57140434-59549100-6dea-11e9-9e61-c9e1b4467e75.png">
> 
> Sorry, my mistake.
> fix: https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-4.1.5.1/qBittorrent-4.1.5.2_fix.dmg

Sadly this build still crashes whenever it quits.

**Comment by c0re100** [comment]
> > > libboost_system-mt.dylib is missing in 4.1.5.2, causing the app to crash. Copying the missing file from previous version do make it run, however, the app crashes every time when it quits.
> > > [log.txt](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/3142071/log.txt)
> > > <img alt="Error" width="1000" src="https://user-images.githubusercontent.com/3954137/57140434-59549100-6dea-11e9-9e61-c9e1b4467e75.png">
> > 
> > 
> > Sorry, my mistake.
> > fix: https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-4.1.5.1/qBittorrent-4.1.5.2_fix.dmg
> 
> Sadly this build still crashes whenever it quits.



> Well, Qt 5.9.7 is not affected.
> [qBittorrent-4.1.5.1.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/3133399/qBittorrent-4.1.5.1.zip)
> 
> Anyway, since the commit merged, I will follow the official way.

How about this build? it still crashes?

**Comment by xingcoo** [comment]
> > > > libboost_system-mt.dylib is missing in 4.1.5.2, causing the app to crash. Copying the missing file from previous version do make it run, however, the app crashes every time when it quits.
> > > > [log.txt](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/3142071/log.txt)
> > > > <img alt="Error" width="1000" src="https://user-images.githubusercontent.com/3954137/57140434-59549100-6dea-11e9-9e61-c9e1b4467e75.png">
> > > 
> > > 
> > > Sorry, my mistake.
> > > fix: https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-4.1.5.1/qBittorrent-4.1.5.2_fix.dmg
> > 
> > 
> > Sadly this build still crashes whenever it quits.
> 
> > Well, Qt 5.9.7 is not affected.
> > [qBittorrent-4.1.5.1.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/3133399/qBittorrent-4.1.5.1.zip)
> > Anyway, since the commit merged, I will follow the official way.
> 
> How about this build? it still crashes?

Unfortunately, this build is also suffering from the same problem. The original 4.1.5.1 build released on Dec 25, 2018 doesn't have it though.

**Comment by c0re100** [comment]
> Unfortunately, this build is also suffering from the same problem. The original 4.1.5.1 build released on Dec 25, 2018 doesn't have it though.

I'm not sure it's failed with Qt5.9.7 or libtorrent......
Qt5.12+cherry-picked: https://drive.google.com/open?id=1djpIX6szGEVXAZkuYTaJ_GGBSMAa83VA

**Comment by xingcoo** [comment]
> > Unfortunately, this build is also suffering from the same problem. The original 4.1.5.1 build released on Dec 25, 2018 doesn't have it though.
> 
> I'm not sure it's failed with Qt5.9.7 or libtorrent......
> Qt5.12+cherry-picked: https://drive.google.com/open?id=1djpIX6szGEVXAZkuYTaJ_GGBSMAa83VA

This build works like a charm. Back to Windows progress bar though...

**Comment by xingcoo** [comment]
Error log: https://pastebin.com/at69tkB3

**Comment by c0re100** [comment]
> Error log: https://pastebin.com/at69tkB3

It seems Qt5.9.7 build failed........
Cause qB official compilation guide isn't up-to-date........I have no idea how to solve it...........

**Comment by c0re100** [comment]
> > > Unfortunately, this build is also suffering from the same problem. The original 4.1.5.1 build released on Dec 25, 2018 doesn't have it though.
> > 
> > 
> > I'm not sure it's failed with Qt5.9.7 or libtorrent......
> > Qt5.12+cherry-picked: https://drive.google.com/open?id=1djpIX6szGEVXAZkuYTaJ_GGBSMAa83VA
> 
> This build works like a charm. Back to Windows progress bar though...

Since qB v4.1.6(Unreleased), the Windows progress bar will be used for MacOS.

**Comment by xingcoo** [comment]
> > > > Unfortunately, this build is also suffering from the same problem. The original 4.1.5.1 build released on Dec 25, 2018 doesn't have it though.
> > > 
> > > 
> > > I'm not sure it's failed with Qt5.9.7 or libtorrent......
> > > Qt5.12+cherry-picked: https://drive.google.com/open?id=1djpIX6szGEVXAZkuYTaJ_GGBSMAa83VA
> > 
> > 
> > This build works like a charm. Back to Windows progress bar though...
> 
> Since qB v4.1.6(Unreleased), the Windows progress bar will be used for MacOS.

Okay, so the Mac progress bar cannot be compiled with Qt5.12? 
BTW, there is still some difference between the Enhanced version and original one:
Enhanced:<img width="914" alt="Enhanced1" src="https://user-images.githubusercontent.com/3954137/57181094-051ce000-6ec2-11e9-8865-3ce775db3a75.png">
Original:
<img width="1011" alt="Original" src="https://user-images.githubusercontent.com/3954137/57181116-53ca7a00-6ec2-11e9-8659-07d31cbf00a5.png">

**Comment by c0re100** [comment]
> > > > > Unfortunately, this build is also suffering from the same problem. The original 4.1.5.1 build released on Dec 25, 2018 doesn't have it though.
> > > > 
> > > > 
> > > > I'm not sure it's failed with Qt5.9.7 or libtorrent......
> > > > Qt5.12+cherry-picked: https://drive.google.com/open?id=1djpIX6szGEVXAZkuYTaJ_GGBSMAa83VA
> > > 
> > > 
> > > This build works like a charm. Back to Windows progress bar though...
> > 
> > 
> > Since qB v4.1.6(Unreleased), the Windows progress bar will be used for MacOS.
> 
> Okay, so the Mac progress bar cannot be compiled with Qt5.12?
> BTW, there is still some difference between the Enhanced version and original one:
> Enhanced:<img alt="Enhanced1" width="914" src="https://user-images.githubusercontent.com/3954137/57181094-051ce000-6ec2-11e9-8865-3ce775db3a75.png">
> Original:
> <img alt="Original" width="1011" src="https://user-images.githubusercontent.com/3954137/57181116-53ca7a00-6ec2-11e9-8659-07d31cbf00a5.png">

Yes. 

The queue status is meaning you're using Torrent Queue (qBit Default setting).
You can edit Torrent Queue setting(qBit > preference > BitTorrent).
