### ISSUE TITLE
Peer ID - XL0012 - not banned?

### ISSUE THREAD

**Issue by LarLei** [c0re100/qBittorrent-Enhanced-Edition#362]
### qBittorrent & operating system versions

Windows 11 Pro 21H2 (OS Build 22000.593) 64-bit
qBittorrent Enhanced Edition v4.4.2.10 (64-bit)
Qt 6.2.4
Libtorrent 2.0.5.0

### What is the problem?

It doesn't seem like this particular Peer ID is banned.  I tried stopping and resuming the torrent and the peer came back several seconds later.  This particular torrent is private, so DHT and PeX are disabled by default.

![notban](https://user-images.githubusercontent.com/76087721/162033696-26981af2-4c54-493a-a36c-def8362d0fd0.png)

### Steps to reproduce

Just add the torrent, select the torrent, and click the Peers tab. 

### Additional context

None

### Log(s) & preferences file(s)

None

**Comment by c0re100** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_4_x/NOTE.md#to-tracker-operators
