### ISSUE TITLE
你好！尊敬的开发者！能为威联通nas开发arm64的应用吗？

### ISSUE THREAD

**Issue by AsukaSoryu0** [c0re100/qBittorrent-Enhanced-Edition#364]
### Suggestion

我现在自用的是威联通的212p3 nas，所用的qb版本是4.3.9的套件版，使用过程中发现常有吸血雷在吸血上传，在网络上寻找很久都没找到适用于威联通nas 的arm qbee套件。

### Extra info/examples/attachments

![Snipaste_2022-04-10_17-46-29](https://user-images.githubusercontent.com/86198114/162614060-fa835f24-c5f3-4f68-9d62-4c259ae38a85.png)

**Comment by abcfy2** [comment]
打印一下`uname -a`的结果，看看CPU是什么？如果是`aarch64`架构的话，你应该选用`aarch64`的那个构建，我基本上应该是已经把常见的嵌入式架构都交叉编译了，如果有缺失可以反馈

**Comment by AsukaSoryu0** [comment]
> 打印一下的结果，看看CPU是什么？如果是架构的话，你应该选用的那个构建，我基本上应该是已经把常见的嵌入式架构都交叉编译了，如果有缺失可以反馈`uname -a``aarch64``aarch64`

/$ uname -a
Linux NAS212P3 4.2.8 #1 SMP Thu Dec 23 05:49:20 CST 2021 aarch64 GNU/Linux

**Comment by abcfy2** [comment]
> > 打印一下的结果，看看CPU是什么？如果是架构的话，你应该选用的那个构建，我基本上应该是已经把常见的嵌入式架构都交叉编译了，如果有缺失可以反馈`` uname -a``aarch64``aarch64 ``
> 
> /$ uname -a Linux NAS212P3 4.2.8 #1 SMP Thu Dec 23 05:49:20 CST 2021 aarch64 GNU/Linux

那你应该可以用`aarch64-musl-linux`这个构建

**Comment by AsukaSoryu0** [comment]
> 打印一下`uname -a`的结果，看看CPU是什么？如果是`aarch64`架构的话，你应该选用`aarch64`的那个构建，我基本上应该是已经把常见的嵌入式架构都交叉编译了，如果有缺失可以反馈

我试试看能不能安装

**Comment by AsukaSoryu0** [comment]
> > > 打印一下的结果，看看CPU是什么？如果是架构的话，你应该选用的那个构建，我基本上应该是已经把常见的嵌入式架构都交叉编译了，如果有缺失可以反馈` uname -a`aarch64`aarch64 `
> > 
> > 
> > /$ uname -a Linux NAS212P3 4.2.8 #1 SMP Thu Dec 23 05:49:20 CST 2021 aarch64 GNU/Linux
> 
> 那你应该可以用`aarch64-linux-musl`这个构建

经过安装测试，nas上提示无法安装，威联通nas上app用的是zip包装的qpkg后缀的安装文件。

1、NAS无法安装图
![nas无法安装](https://user-images.githubusercontent.com/86198114/162618583-04db10ce-c276-4965-a695-4ca0738f7b74.png)
2、威联通官方应用结构图
![威联通官方应用](https://user-images.githubusercontent.com/86198114/162618599-eb002090-0e3c-4dff-8507-40c28073c20a.png)

**Comment by abcfy2** [comment]
目前不提供群晖的安装包格式，zip压缩包存储的是静态编译的二进制可执行程序，你需要自己部署直接运行

**Comment by AsukaSoryu0** [comment]
> 目前不提供群晖的安装包格式，zip压缩包存储的是静态编译的二进制可执行程序，你需要自己部署直接运行

这个部署是指docker吗？还是说我自己根据github中的zip自己制作qpkg

**Comment by abcfy2** [comment]
你都可以ssh上去了理论上你可以把二进制可执行文件放上去自行启动，或者自己做成service，如果你有Linux运维经验应该不难，你也可以找找有没有人做成docker镜像或者打包成qpkg包

**Comment by AsukaSoryu0** [comment]
> 你都可以ssh上去了理论上你可以把二进制可执行文件放上去自行启动，或者自己做成service，如果你有Linux运维经验应该不难，你也可以找找有没有人做成docker镜像或者打包成qpkg包

hh  我也就是跟着网上学了一点皮毛，具体怎么操作还真不太懂  我去网上找找教程吧 按你说的几种办法

**Comment by abcfy2** [comment]
https://github.com/SuperNG6/Docker-qBittorrent-Enhanced-Edition 可以试试这个，有人维护了docker镜像，可以部署在群晖

**Comment by AsukaSoryu0** [comment]
> https://github.com/SuperNG6/Docker-qBittorrent-Enhanced-Edition 可以试试这个，有人维护了docker镜像，可以部署在群晖

万分感谢！可是目前我这台nas性能太差 用不了dockerヽ(°◇° )ノ

**Comment by abcfy2** [comment]
docker只要求一定的内核版本，跟性能无关，又不是虚拟机吃配置，你需要研究下docker是怎么回事。docker使用文件系统级别的隔离环境，几乎不损耗硬件性能

**Comment by AsukaSoryu0** [comment]
> docker只要求一定的内核版本，跟性能无关，又不是虚拟机吃配置，你需要研究下docker是怎么回事。docker使用内核级别的隔离环境，几乎不损耗硬件性能

我刚在开启docker的卡死了  内存不够吧 应该

**Comment by AsukaSoryu0** [comment]
> docker只要求一定的内核版本，跟性能无关，又不是虚拟机吃配置，你需要研究下docker是怎么回事。docker使用内核级别的隔离环境，几乎不损耗硬件性能

经测试 可以用解压出来的nox直接替换原套件版的nox  完美可用

**Comment by AsukaSoryu0** [comment]
> docker只要求一定的内核版本，跟性能无关，又不是虚拟机吃配置，你需要研究下docker是怎么回事。docker使用内核级别的隔离环境，几乎不损耗硬件性能

你好，我还想再问个小白问题，arm64和aarch64两个版本都可以在nas上使用，这两个版本有什么优劣区别吗？

**Comment by abcfy2** [comment]
https://bbs.huaweicloud.com/forum/thread-28512-1-1.html 这种问题你随便百度google就有

**Comment by AsukaSoryu0** [comment]
> https://bbs.huaweicloud.com/forum/thread-28512-1-1.html 这种问题你随便百度google就有

这个网页我在问之前也有了，网上大概说的是两者一个意思，我奇怪的是为什么还是分了两个版本i😂

**Comment by AsukaSoryu0** [comment]
> https://bbs.huaweicloud.com/forum/thread-28512-1-1.html 这种问题你随便百度google就有

不前面的字打错了，我在问之前也搜了下相关问题，也看到了这个网页。😁

**Comment by abcfy2** [comment]
叫不同名字有什么奇怪？x86_64=AMD64=IA64，一个东西，H.264=AVC，一个东西。这种情况多了

**Comment by AsukaSoryu0** [comment]
> 叫不同名字有什么奇怪？x86_64=AMD64=IA64，一个东西，H.264=AVC，一个东西。这种情况多了

又学到新知识了，我的意思其实是为什么在您的项目中，有两个版本可供下载，而且nox文件大小还稍有区别

**Comment by abcfy2** [comment]
哪有两个？你想说arm和aarch64？这俩不是一个架构

**Comment by AsukaSoryu0** [comment]
> 哪有两个？你想说arm和aarch64？这俩不是一个架构。前面是32位arm架构，后者是arm64

才发现是arm没有带64，，谢谢！
