### ISSUE TITLE
Does anonymous mode still work?

### ISSUE THREAD

**Issue by katop1** [c0re100/qBittorrent-Enhanced-Edition#366]
### qBittorrent & operating system versions

qBittorrent Enhanced Edition v4.4.2.10 x64 QT6
Windows 10 21H2

### What is the problem?

(Sorry, I don't speak English, so I use machine translation.)

A few versions ago, iknowwhatyoudownload couldn't show what my ip had downloaded when I was using anonymous mode. With the current version, iknowwhatyoudownload shows the files I have downloaded.

Does anonymous mode still work? Or is this normal working condition?

### Steps to reproduce

1. Turn on the anonymous mode option in settings
2. Download some popular torrents
3. Check if the download item is displayed on iknowwhatyoudownload

**Comment by c0re100** [comment]
https://github.com/qbittorrent/qBittorrent/wiki/Anonymous-Mode
