### ISSUE TITLE
The file  will be download , even if it is not selected

### ISSUE THREAD

**Issue by tyr0911** [c0re100/qBittorrent-Enhanced-Edition#368]
### qBittorrent & operating system versions

qBittorrent: qBittorrent-Enhanced-Edition v4.4.2.10 x32
Operating system: Windows 10 2019 ltsc x64
Qt: 5.15.3
libtorrent-rasterbar: 1.2.11
Libtorrent:2.0.5.0
Boost:1.78.0
OpenSSL:1.1.1n

### What is the problem?
The file will be downloaded even if it is not selected

**Comment by c0re100** [comment]
https://github.com/qbittorrent/qBittorrent/issues/16928
