### ISSUE TITLE
I have installed QT5, but it still fails to compile.

### ISSUE THREAD

**Issue by LanYunDev** [c0re100/qBittorrent-Enhanced-Edition#371]
### qBittorrent & operating system versions

Operating system: Macos 12.3 
The chip is ARM architecture
<img width="586" alt="image" src="https://user-images.githubusercontent.com/95263282/164916103-c32ac56c-5408-4ae4-8011-ce13d22cf9a4.png">
➜  ~ brew install qt
Warning: qt 6.2.3_1 is already installed and up-to-date.
To reinstall 6.2.3_1, run:
  brew reinstall qt
➜  ~ brew install qt5
Warning: qt@5 5.15.3 is already installed and up-to-date.
To reinstall 5.15.3, run:
  brew reinstall qt@5
➜  ~ qmake -v
QMake version 3.1
Using Qt version 6.2.3 in /opt/homebrew/lib
<img width="752" alt="image" src="https://user-images.githubusercontent.com/95263282/164916168-267f85e1-8ca2-49ba-b4c4-0e6b9f939b03.png">

### What is the problem?

 qBittorrent-Enhanced-Edition-4_4_x ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking for a sed that does not truncate output... /usr/bin/sed
checking build system type... arm-apple-darwin21.4.0
checking host system type... arm-apple-darwin21.4.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... ./build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... none
checking dependency style of g++... none
checking whether to enable specific tweaks for current host "darwin21.4.0"... yes
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.23... yes
checking whether to enable the Debug build... no
checking whether to enable the stacktrace feature... yes
checking whether to enable the GUI... yes
checking whether to install the systemd service file... no
checking whether to enable the WebUI... yes
checking for Qt5 qmake >= 5.15.2... not found
configure: error: Could not find qmake
➜  qBittorrent-Enhanced-Edition-4_4_x brew install qt5
Warning: qt@5 5.15.3 is already installed and up-to-date.
To reinstall 5.15.3, run:
  brew reinstall qt@5
➜  qBittorrent-Enhanced-Edition-4_4_x brew reinstall qt5
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/qt%405-5.15
Already downloaded: /Users/lanyun/Library/Caches/Homebrew/downloads/8176649f345506f23fac78768cb30eb47871c5f7892dea106745aa90b417476e--qt@5-5.15.3.arm64_monterey.bottle.tar.gz
==> Reinstalling qt@5
==> Pouring qt@5-5.15.3.arm64_monterey.bottle.tar.gz
==> Caveats
We agreed to the Qt open source license for you.
If this is unacceptable you should uninstall.

This version of Qt on Apple Silicon does not include QtWebEngine.

qt@5 is keg-only, which means it was not symlinked into /opt/homebrew,
because this is an alternate version of another formula.

If you need to have qt@5 first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> ~/.zshrc

For compilers to find qt@5 you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/qt@5/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/qt@5/include"

For pkg-config to find qt@5 you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/qt@5/lib/pkgconfig"

==> Summary
🍺  /opt/homebrew/Cellar/qt@5/5.15.3: 10,649 files, 195.6MB
==> Running `brew cleanup qt@5`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
➜  qBittorrent-Enhanced-Edition-4_4_x ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking for a sed that does not truncate output... /usr/bin/sed
checking build system type... arm-apple-darwin21.4.0
checking host system type... arm-apple-darwin21.4.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... ./build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... none
checking dependency style of g++... none
checking whether to enable specific tweaks for current host "darwin21.4.0"... yes
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.23... yes
checking whether to enable the Debug build... no
checking whether to enable the stacktrace feature... yes
checking whether to enable the GUI... yes
checking whether to install the systemd service file... no
checking whether to enable the WebUI... yes
checking for Qt5 qmake >= 5.15.2... not found
configure: error: Could not find qmake
➜  qBittorrent-Enhanced-Edition-4_4_x ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking for a sed that does not truncate output... /usr/bin/sed
checking build system type... arm-apple-darwin21.4.0
checking host system type... arm-apple-darwin21.4.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... ./build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... none
checking dependency style of g++... none
checking whether to enable specific tweaks for current host "darwin21.4.0"... yes
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.23... yes
checking whether to enable the Debug build... no
checking whether to enable the stacktrace feature... yes
checking whether to enable the GUI... yes
checking whether to install the systemd service file... no
checking whether to enable the WebUI... yes
checking for Qt5 qmake >= 5.15.2... not found
configure: error: Could not find qmake
➜  qBittorrent-Enhanced-Edition-4_4_x qmake -v
QMake version 3.1
Using Qt version 6.2.3 in /opt/homebrew/lib
➜  qBittorrent-Enhanced-Edition-4_4_x ./configure --qmake /opt/homebrew/bin/qmake
configure: error: unrecognized option: `--qmake'
Try `./configure --help' for more information
➜  qBittorrent-Enhanced-Edition-4_4_x ./configure -qmake /opt/homebrew/bin/qmake
configure: error: unrecognized option: `-qmake'
Try `./configure --help' for more information
➜  qBittorrent-Enhanced-Edition-4_4_x ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking for a sed that does not truncate output... /usr/bin/sed
checking build system type... arm-apple-darwin21.4.0
checking host system type... arm-apple-darwin21.4.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... ./build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... none
checking dependency style of g++... none
checking whether to enable specific tweaks for current host "darwin21.4.0"... yes
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.23... yes
checking whether to enable the Debug build... no
checking whether to enable the stacktrace feature... yes
checking whether to enable the GUI... yes
checking whether to install the systemd service file... no
checking whether to enable the WebUI... yes
checking for Qt5 qmake >= 5.15.2... not found
configure: error: Could not find qmake
➜  qBittorrent-Enhanced-Edition-4_4_x export PATH="/usr/local/opt/qt/bin:$PATH"
➜  qBittorrent-Enhanced-Edition-4_4_x ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking for a sed that does not truncate output... /usr/bin/sed
checking build system type... arm-apple-darwin21.4.0
checking host system type... arm-apple-darwin21.4.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... ./build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... none
checking dependency style of g++... none
checking whether to enable specific tweaks for current host "darwin21.4.0"... yes
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.23... yes
checking whether to enable the Debug build... no
checking whether to enable the stacktrace feature... yes
checking whether to enable the GUI... yes
checking whether to install the systemd service file... no
checking whether to enable the WebUI... yes
checking for Qt5 qmake >= 5.15.2... not found
configure: error: Could not find qmake

**Comment by abcfy2** [comment]
qt6 does not contains `pkgconfig`, if you want to build with qt6, you have to use `cmake` instead of `./configure` for building, see issue: https://github.com/qbittorrent/qBittorrent/issues/15609

If you want to use qt5, did you see the output ?
```
qt@5 is keg-only, which means it was not symlinked into /opt/homebrew,
because this is an alternate version of another formula.

If you need to have qt@5 first in your PATH, run:
echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> ~/.zshrc

For compilers to find qt@5 you may need to set:
export LDFLAGS="-L/opt/homebrew/opt/qt@5/lib"
export CPPFLAGS="-I/opt/homebrew/opt/qt@5/include"

For pkg-config to find qt@5 you may need to set:
export PKG_CONFIG_PATH="/opt/homebrew/opt/qt@5/lib/pkgconfig"
```

**Comment by LanYunDev** [comment]
I have solved the problem through brew, thank you, this information may be helpful to others
