### ISSUE TITLE
bt media player “stellarplayer2.0.0.0” work@4.4.2.10

### ISSUE THREAD

**Issue by host2318** [c0re100/qBittorrent-Enhanced-Edition#374]
### qBittorrent & operating system versions

qBittorrent: 4.4.2.10
Operating system: Windows 10 Pro 21H1
Qt: 6.2.4
libtorrent-rasterbar: 2.0.2.0

### What is the problem?

见下图，我已经搜索过，qBittorrent4.4.1的版本已经加入stellarplayer为黑名单，但是在最新版本下其依然连接下载流量

<img src="https://upimg.top/i/2022/05/07/6275db3208e26.jpg" alt="bt-stellarplayer.jpg" title="bt-stellarplayer.jpg" />

**Comment by c0re100** [comment]
> ### qBittorrent & operating system versions
> qBittorrent: 4.4.2.10 Operating system: Windows 10 Pro 21H1 Qt: 6.2.4 libtorrent-rasterbar: 2.0.2.0
> 
> ### What is the problem?
> 见下图，我已经搜索过，qBittorrent4.4.1的版本已经加入stellarplayer为黑名单，但是在最新版本下其依然连接下载流量
> 
> ![bt-stellarplayer.jpg](https://camo.githubusercontent.com/71e0954b96b9e5d2a4d0a518e71242fbc4d731560255056f91da551ca6711c8f/68747470733a2f2f7570696d672e746f702f692f323032322f30352f30372f363237356462333230386532362e6a7067)
> 
> ### Steps to reproduce
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Log(s) & preferences file(s)
> _No response_

請先確定這是不是私有種子?

**Comment by host2318** [comment]
> > ### qBittorrent & operating system versions
> > qBittorrent: 4.4.2.10 Operating system: Windows 10 Pro 21H1 Qt: 6.2.4 libtorrent-rasterbar: 2.0.2.0
> > ### What is the problem?
> > 见下图，我已经搜索过，qBittorrent4.4.1的版本已经加入stellarplayer为黑名单，但是在最新版本下其依然连接下载流量
> > ![bt-stellarplayer.jpg](https://camo.githubusercontent.com/71e0954b96b9e5d2a4d0a518e71242fbc4d731560255056f91da551ca6711c8f/68747470733a2f2f7570696d672e746f702f692f323032322f30352f30372f363237356462333230386532362e6a7067)
> > ### Steps to reproduce
> > _No response_
> > ### Additional context
> > _No response_
> > ### Log(s) & preferences file(s)
> > _No response_
> 
> 請先確定這是不是私有種子?

是的，PT站点的种子

**Comment by c0re100** [comment]
好了 結案
自動封鎖不會對私有種子生效
