### ISSUE TITLE
configure: error: Could not find qmake

### ISSUE THREAD

**Issue by Windy2233** [c0re100/qBittorrent-Enhanced-Edition#375]
### qBittorrent & operating system versions

qbittorrent-enhanced-nox-git 4.4.2.10.r0.gdb18496c9-1
ArchLinuxARM-rpi-armv7
QT-6.3.0-1

### What is the problem?

使用yay安装，配置文件还是检查qmake

![Screenshot_20220509-072025_JuiceSSH](https://user-images.githubusercontent.com/60390896/167324522-a44995ef-a1b0-45fc-a1a9-5d631ccdf4fc.jpg)

**Comment by Kolcha** [comment]
seems that it is impossible to build qBittorrent with Qt 6 using autotools (configure script) - script relies on `pkg-config` and Qt 6 seems not provide `pkg-config` files anymore
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/ab45816bcfafb8633864af9739e667f1ebb9794b/m4/qbittorrent.m4#L7-L26
notice `PKG_CHECK_EXISTS()` calls

so, to build it with Qt 6 please use cmake:

```bash
mkdir build && cd $_
cmake -D QT6=ON ..
make -j$(nproc)
```

that should be enough, add any other options as you want / need

also see PKGBUILD for official ArchLinux qBittorrent package for example https://github.com/archlinux/svntogit-community/blob/packages/qbittorrent/trunk/PKGBUILD

**Comment by Windy2233** [comment]
> seems that it is impossible to build qBittorrent with Qt 6 using autotools (configure script) - script relies on `pkg-config` and Qt 6 seems not provide `pkg-config` files anymore
> 
> https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/ab45816bcfafb8633864af9739e667f1ebb9794b/m4/qbittorrent.m4#L7-L26
> 
> notice `PKG_CHECK_EXISTS()` calls
> 
> so, to build it with Qt 6 please use cmake:
> 
> ```shell
> mkdir build && cd $_
> cmake -D QT6=ON ..
> make -j$(nproc)
> ```
> 
> that should be enough, add any other options as you want / need
> 
> also see PKGBUILD for official ArchLinux qBittorrent package for example https://github.com/archlinux/svntogit-community/blob/packages/qbittorrent/trunk/PKGBUILD

thank you
