### ISSUE TITLE
4.4.2的Mac版不是通用版本吗？为什么安装出来仍然是intel架构

### ISSUE THREAD

**Issue by cbhh** [c0re100/qBittorrent-Enhanced-Edition#376]
### Suggestion

官网更新日志中写了4.4.2的的Mac版已经是通用版本了，可以在M1芯片上原生运行。增强版的4.4.2版安装出来仍然显示是intel架构？

**Comment by toooonyy** [comment]
[qBittorrent-Enhanced-Edition-master-macOS-arm64.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/8707691/qBittorrent-Enhanced-Edition-master-macOS-arm64.zip)
个人实验性的 arm64 build, 用的 Kolcha 脚本。
<img width="657" alt="Screen Shot 2022-05-17 at 13 13 07" src="https://user-images.githubusercontent.com/3480434/168798723-22daaa52-eeab-4bd6-a0c6-9ad2a1c780a5.png">

**Comment by c0re100** [comment]
能不能試試這個universal?
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-4.4.2.10/qBittorrent-Enhanced-4.4.2.10-universal.dmg

**Comment by cbhh** [comment]
感谢两位大佬🐣
<img width="540" alt="截屏2022-05-22 11 33 47" src="https://user-images.githubusercontent.com/47976243/169677188-d0b6e40e-44e0-43b8-9b2e-b638eec08d9e.png">
