### ISSUE TITLE
双屏使用时，弹出的选项菜单总是在主屏幕

### ISSUE THREAD

**Issue by Sullex** [c0re100/qBittorrent-Enhanced-Edition#377]
### qBittorrent & operating system versions

版本：qbittorrent_enhanced_4.4.2.10_Qt6
操作系统：Win10

### What is the problem?

双屏或者多屏使用时，只要是弹出的新窗口，包括右键菜单，点击工具栏弹出的菜单，设置里点击的下拉框等等，
都会出现在主屏幕上而不是跟随软件所在的屏幕。

### Additional context

菜单栏：
![2)VW%A(R(}W{X3D{C@VQ3VR](https://user-images.githubusercontent.com/28750938/168937863-94e31ec1-52ab-4d05-adf4-6b3c4809fab8.png)

右键菜单：
![XW@5M5)1%$AXK593QS0E3RW](https://user-images.githubusercontent.com/28750938/168937958-e75b5231-b4f5-41ee-b7a1-037b10865be0.png)

**Comment by SeaHOH** [comment]
Qt5 也这样？

**Comment by SeaHOH** [comment]
既然与 EE 无关，那应该往上游报。
