### ISSUE TITLE
[GA] Unable to build AppImage

### ISSUE THREAD

**Issue by c0re100** [c0re100/qBittorrent-Enhanced-Edition#380]
```
Fetching submodule simulation/libsimulator
fatal: remote error: upload-pack: not our ref df7a6e308f2c414e4ed5ffe760b8c15f7dc5f17c
```
https://github.com/c0re100/qBittorrent-Enhanced-Edition/runs/6561277755?check_suite_focus=true

ping @abcfy2

**Comment by abcfy2** [comment]
Seems it's only a temp network issue. My build is successful: https://github.com/abcfy2/qBittorrent-Enhanced-Edition/runs/6565911751

You may just click `Re-run failed jobs` will resolve this issue.

**Comment by c0re100** [comment]
> Seems it's only a temp network issue. My build is successful: https://github.com/abcfy2/qBittorrent-Enhanced-Edition/runs/6565911751
> 
> You may just click `Re-run failed jobs` will resolve this issue.

Sadly, still failed.

**Comment by abcfy2** [comment]
Seems the cache is broken. I'll try to fix this issue.

**Comment by c0re100** [comment]
> Seems the cache is broken. I'll try to fix this issue.

Maybe `rm -rf libtorrent_dir` better than git reset or something else.
I lost patience about git fix way lol.
No lucky for git reset/update submodules blahhhhhhh...

**Comment by abcfy2** [comment]
> > Seems the cache is broken. I'll try to fix this issue.
> 
> Maybe `rm -rf libtorrent_dir` better than git reset or something else. I lost patience about git fix way lol. No lucky for git reset/update submodules blahhhhhhh...

Seems the official repo use `push -f` that lose the commit `df7a6e308f2c414e4ed5ffe760b8c15f7dc5f17c`. So I have to delete the clone directory if git clone or pull failed.

**Comment by c0re100** [comment]
> > > Seems the cache is broken. I'll try to fix this issue.
> > 
> > 
> > Maybe `rm -rf libtorrent_dir` better than git reset or something else. I lost patience about git fix way lol. No lucky for git reset/update submodules blahhhhhhh...
> 
> Seems the official repo use `push -f` that lose the commit `df7a6e308f2c414e4ed5ffe760b8c15f7dc5f17c`. So I have to delete the clone directory if git clone or pull failed.

Maybe we can try it lol
https://github.com/actions/cache/issues/2#issuecomment-673493515

**Comment by abcfy2** [comment]
> > > > Seems the cache is broken. I'll try to fix this issue.
> > > 
> > > 
> > > Maybe `rm -rf libtorrent_dir` better than git reset or something else. I lost patience about git fix way lol. No lucky for git reset/update submodules blahhhhhhh...
> > 
> > 
> > Seems the official repo use `push -f` that lose the commit `df7a6e308f2c414e4ed5ffe760b8c15f7dc5f17c`. So I have to delete the clone directory if git clone or pull failed.
> 
> Maybe we can try it lol [actions/cache#2 (comment)](https://github.com/actions/cache/issues/2#issuecomment-673493515)

I know this. We do not need this solution. I'll submit a PR ASAP.
