### ISSUE TITLE
Upgrade to Qt 6.3.0

### ISSUE THREAD

**Issue by FrzMtrsprt** [c0re100/qBittorrent-Enhanced-Edition#381]
### Suggestion

The official version 4.4.3 was released with Qt 6.3.0, which fixed the invisible text issue, according to the release log.

**Comment by c0re100** [comment]
Yes, I forgot to update Qt6 in this version.
I will be release 4.4.3.11 with https://github.com/qbittorrent/qBittorrent/pull/17084.

**Comment by c0re100** [comment]
4.4.3.11 Released.
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/tag/release-4.4.3.11
