### ISSUE TITLE
软件过分卡顿

### ISSUE THREAD

**Issue by hanxuyuan** [c0re100/qBittorrent-Enhanced-Edition#385]
### qBittorrent & operating system versions

qBittorrent: 4.4.3.11 QT6
Operating system: Windows 10 企业版LTSC 21H2 

### What is the problem?

如果软件下载多个文件，未清除文件列表。则下次重新打开软件时会长时间卡死！并且处理器单线程使用率长时间满载，其它线程正常。（CPU5800H）。
软件卡死期间不能有任何操作，否则提示结束进程必须长时间等待（超过10分钟）。
如果清除文件列表，则下次重新打软件时无此情况。

具体表现在软件设置路径的data\BT_backup，文件夹内有过去下载的种子，则重新打开软件卡顿严重的不能忍受，如果清空文件夹内所有文件，则重新打开软件正常。

另：在“设置”—“BitTorrent”—“Auto matically update public trackers list”，点击Refectch后，下方不显示更新列表，为一片空白。网络正常，尝试多次结果一样，实际上浏览器能正常打开该页面。

**Comment by c0re100** [comment]
用4.4.2 Qt6時有相同情況嗎?

trackers相關問題請移步到 #386

**Comment by hanxuyuan** [comment]
> 用4.4.2 Qt6時有相同情況嗎?

我使用了如下几个版本，任务列表中都有过往下载，约30个任务未清除。
4.3.4.11：运行X64程序，一切相对正常。Auto matically update public trackers list正常显示。
4.3.9.10：运行X64程序，打开程序时有明显卡顿，其余一切正常。Auto matically update public trackers list正常显示。
4.4.2.10_qt6：打开程序时卡顿非常明显，需等待，其余一切正常，当清除任务列表后重新打开程序则不卡顿。Auto matically update public trackers list能够正常显示。
4.4.3.11_qt6：卡顿的不能接受！保留任务列表时，再绑定“网络接口”以及绑定“可选IP地址”后，卡顿得到明显的缓解，但仍有卡顿。当清除任务列表后重新打开程序则不卡顿。Auto matically update public trackers list始终不显示，无论是干净运行，还是保留过往设置运行，Auto matically update public trackers list始终无法显示。点击Refetch后，直至变成Fetched，下方始终是空白。

**Comment by hanxuyuan** [comment]
> 用4.4.2 Qt6時有相同情況嗎?
> 
> trackers相關問題請移步到 #386

刚刚尝试了4.4.3.10_qt6，Auto matically update public trackers list正常显示。
似乎的确是QT6.3的问题

**Comment by c0re100** [comment]
> > 用4.4.2 Qt6時有相同情況嗎?
> 
> 我使用了如下几个版本，任务列表中都有过往下载，约30个任务未清除。 4.3.4.11：运行X64程序，一切相对正常。Auto matically update public trackers list正常显示。 4.3.9.10：运行X64程序，打开程序时有明显卡顿，其余一切正常。Auto matically update public trackers list正常显示。 4.4.2.10_qt6：打开程序时卡顿非常明显，需等待，其余一切正常，当清除任务列表后重新打开程序则不卡顿。Auto matically update public trackers list能够正常显示。 4.4.3.11_qt6：卡顿的不能接受！保留任务列表时，再绑定“网络接口”以及绑定“可选IP地址”后，卡顿得到明显的缓解，但仍有卡顿。当清除任务列表后重新打开程序则不卡顿。Auto matically update public trackers list始终不显示，无论是干净运行，还是保留过往设置运行，Auto matically update public trackers list始终无法显示。点击Refetch后，直至变成Fetched，下方始终是空白。

4.4用Qt5呢?

**Comment by hanxuyuan** [comment]
> > > 用4.4.2 Qt6時有相同情況嗎?
> > 
> > 
> > 我使用了如下几个版本，任务列表中都有过往下载，约30个任务未清除。 4.3.4.11：运行X64程序，一切相对正常。Auto matically update public trackers list正常显示。 4.3.9.10：运行X64程序，打开程序时有明显卡顿，其余一切正常。Auto matically update public trackers list正常显示。 4.4.2.10_qt6：打开程序时卡顿非常明显，需等待，其余一切正常，当清除任务列表后重新打开程序则不卡顿。Auto matically update public trackers list能够正常显示。 4.4.3.11_qt6：卡顿的不能接受！保留任务列表时，再绑定“网络接口”以及绑定“可选IP地址”后，卡顿得到明显的缓解，但仍有卡顿。当清除任务列表后重新打开程序则不卡顿。Auto matically update public trackers list始终不显示，无论是干净运行，还是保留过往设置运行，Auto matically update public trackers list始终无法显示。点击Refetch后，直至变成Fetched，下方始终是空白。
> 
> 4.4用Qt5呢?

4.4的QT5，运行X64时，Auto matically update public trackers list正常显示。

**Comment by c0re100** [comment]
> > > > 用4.4.2 Qt6時有相同情況嗎?
> > > 
> > > 
> > > 我使用了如下几个版本，任务列表中都有过往下载，约30个任务未清除。 4.3.4.11：运行X64程序，一切相对正常。Auto matically update public trackers list正常显示。 4.3.9.10：运行X64程序，打开程序时有明显卡顿，其余一切正常。Auto matically update public trackers list正常显示。 4.4.2.10_qt6：打开程序时卡顿非常明显，需等待，其余一切正常，当清除任务列表后重新打开程序则不卡顿。Auto matically update public trackers list能够正常显示。 4.4.3.11_qt6：卡顿的不能接受！保留任务列表时，再绑定“网络接口”以及绑定“可选IP地址”后，卡顿得到明显的缓解，但仍有卡顿。当清除任务列表后重新打开程序则不卡顿。Auto matically update public trackers list始终不显示，无论是干净运行，还是保留过往设置运行，Auto matically update public trackers list始终无法显示。点击Refetch后，直至变成Fetched，下方始终是空白。
> > 
> > 
> > 4.4用Qt5呢?
> 
> 4.4的QT5，运行X64时，Auto matically update public trackers list正常显示。

我是指卡死情況

**Comment by hanxuyuan** [comment]
> > > > > 用4.4.2 Qt6時有相同情況嗎?
> > > > 
> > > > 
> > > > 我使用了如下几个版本，任务列表中都有过往下载，约30个任务未清除。 4.3.4.11：运行X64程序，一切相对正常。Auto matically update public trackers list正常显示。 4.3.9.10：运行X64程序，打开程序时有明显卡顿，其余一切正常。Auto matically update public trackers list正常显示。 4.4.2.10_qt6：打开程序时卡顿非常明显，需等待，其余一切正常，当清除任务列表后重新打开程序则不卡顿。Auto matically update public trackers list能够正常显示。 4.4.3.11_qt6：卡顿的不能接受！保留任务列表时，再绑定“网络接口”以及绑定“可选IP地址”后，卡顿得到明显的缓解，但仍有卡顿。当清除任务列表后重新打开程序则不卡顿。Auto matically update public trackers list始终不显示，无论是干净运行，还是保留过往设置运行，Auto matically update public trackers list始终无法显示。点击Refetch后，直至变成Fetched，下方始终是空白。
> > > 
> > > 
> > > 4.4用Qt5呢?
> > 
> > 
> > 4.4的QT5，运行X64时，Auto matically update public trackers list正常显示。
> 
> 我是指卡死情況

我是保留了设置文件profile，仅替换了程序，所以设置选项是已优化后的情况，特别是“网络接口”以及“可选IP地址”都已绑定，此时打开程序，卡顿相对不明显，仅启动初始的2s左右时间。

我个人使用体验：近些版本（4.4.X，4.3.9等）卡顿主要集中体现在文件列表内保留过往任务的情况下，双击运行时卡顿至无响应，需长时间等待。如果过往任务列表干净（data\BT_backup，文件夹内无种子文件），则无卡顿现象。
如果文件列表保留过往任务，则需要“设置”—“高级”中，对“网络接口”“可选IP地址”进行绑定，可极大幅度降低双击运行时卡顿情况。

**Comment by c0re100** [comment]
Qt6問題 大概
https://github.com/qbittorrent/qBittorrent/issues/16395
