### ISSUE TITLE
Cannot fetch trackers list

### ISSUE THREAD

**Issue by louzc** [c0re100/qBittorrent-Enhanced-Edition#389]
### qBittorrent & operating system versions

v4.3.3.12
qt6

### What is the problem?

1. Cannot fetch trackers list( I use: https://ghproxy.futils.com/https://github.com/XIU2/TrackersListCollection/blob/master/best.txt )
2. Chinese is not complete

### Steps to reproduce

options——bittorent——fetch

**Comment by louzc** [comment]
![image](https://user-images.githubusercontent.com/63027469/171991439-6de64422-d806-46bf-9d5a-979b421f8c26.png)

**Comment by louzc** [comment]
@c0re100 plz solve it

**Comment by chinanoahli** [comment]
应该是你的github镜像有问题，你可以去注册一个coding帐号，coding提供github项目镜像功能，每天还可以自动pull
你自己克隆一个github上的tracker list项目到coding，然后设置每天自动更新，再使用coding提供的raw地址就好了
记得将coding项目也设为开源，不然raw地址不能直接生效

或者你也可以直接用我的（每天00:00自动跟github同步一次，偶尔会失败总比没有好）：
https://chinanoahli.coding.net/p/ProxyTools/d/trackerslist/git/raw/master/trackers_all.txt

项目地址：
https://chinanoahli.coding.net/public/ProxyTools/trackerslist/git/files

上游项目是：
https://github.com/ngosang/trackerslist

**Comment by abcfy2** [comment]
推荐这个： https://trackerslist.com/all.txt
