### ISSUE TITLE
CI-Windows version of ssl and rss function does not work

### ISSUE THREAD

**Issue by baka-gourd** [c0re100/qBittorrent-Enhanced-Edition#391]
### qBittorrent & operating system versions

latest github action CI Winodows build
https://github.com/baka-gourd/qBittorrent-Enhanced-Edition/actions/runs/2435575808

### What is the problem?

Unable to load https link
/ was replaced with \ in rss

**Comment by c0re100** [comment]
[No problem](https://github.com/baka-gourd/qBittorrent-Enhanced-Edition/actions/runs/2435575808) for me and It's not related to enhanced repo.
