### ISSUE TITLE
Qt 6 版本安装程序的默认安装路径为 Program Files (x86)

### ISSUE THREAD

**Issue by cherinyy** [c0re100/qBittorrent-Enhanced-Edition#394]
### qBittorrent & operating system versions

Version: qBittorrent Enhanced Edition 4.4.3.12 x86-64
OS: Windows 11 Version 22H2 (Build 22621.1) Beta 渠道
Qt: 6.3.0
libtorrent: 2.0.6.0

### What is the problem?

Qt 6 版本安装程序的默认安装路径为“Program Files (x86)”而不是 “Program Files”，安装后的程序架构为 x86-64。
![image](https://user-images.githubusercontent.com/9050713/173302007-9cc8bc48-640d-4736-9d66-8713fc2ea91e.png)

**Comment by c0re100** [comment]
咦 我忘了改這裡...
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_4_x/dist/windows/options.nsi#L73

https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-4.4.3.12/qbittorrent_enhanced_4.4.3.12_Qt6_setup_fix.exe
試試這個安裝檔有沒有問題?

**Comment by cherinyy** [comment]
> https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-4.4.3.12/qbittorrent_enhanced_4.4.3.12_Qt6_setup_fix.exe
> 試試這個安裝檔有沒有問題?

正常了
