### ISSUE TITLE
能改一下界面的缩放吗

### ISSUE THREAD

**Issue by xiaozixun** [c0re100/qBittorrent-Enhanced-Edition#396]
### qBittorrent & operating system versions

qBittorrent：4.4.3.12
操作系统：arch linux 5.18.9（kde 5.25.2 X11）
Qt：5.15.4
libtorrent-rasterbar：2.0.6.0

### What is the problem?

（我不知道它该叫什么，只好这样称呼）
在我改变字体大小之后，界面会变形，甚至有些界面会出现本该有的一部分内容被遮挡并难以选取。偏偏我又是小屏幕，以至于我操作起来十分难受。
例如下图中的界面

### Additional context

![Screenshot_2022-07-06 19:20:52 %Nd](https://user-images.githubusercontent.com/22409452/177539651-f341cb7b-6a03-4c46-82da-af53dbee176b.png)

**Comment by Flyfish233** [comment]
scale?

**Comment by xiaozixun** [comment]
4.5.10已修复
