### ISSUE TITLE
Coexist with the original version

### ISSUE THREAD

**Issue by cherinyy** [c0re100/qBittorrent-Enhanced-Edition#398]
### Suggestion

The Enhanced Edition currently uses the same configuration directory (qBittorrent) as the original, and the installers are mutually exclusive. Since the qBittorrent team [refused to provide support for the Enhanced Edition](https://github.com/qbittorrent/qBittorrent/blame/3567ae3529328c75e8983db8f97e99a32c16e8e6/.github/ISSUE_TEMPLATE/bug_report.yml#L10), users need to install the original version when they need to report upstream issues.

### Use case

When users report upstream issues.

**Comment by userdocs** [comment]
Since qbittorrent natively supports multiple instances you can already do this.

```
qbittorrent-nox --configuration=my_custom_instance
```

Now all folders linked to that instance have the suffix `my_custom_instance`

So as soon as you want more than one instance of qBittorrent, upstream or here, you have to do this anyway. So this is the correct method

**Comment by luzpaz** [comment]
Maybe this is worth mentioning in the README ?
