### ISSUE TITLE
qBittorrent能不能做个便携版

### ISSUE THREAD

**Issue by CloudxM** [c0re100/qBittorrent-Enhanced-Edition#4]
想作者加入便携功能，至少重装系统后不会丢失qBittorrent的配置。。。
重装系统后qBittorrent的自定义Tracker和配置丢失也是挺麻烦的事。。。
（utorrent本身就是便携版，但是没有qBittorrent好用。。。

**Comment by c0re100** [comment]
qBittorrent v4.0開始支援便攜模式
在qBittorrent安裝位置打開cmd(shift+右鍵)
再輸入 `qbittorrent.exe --portable` 就能啟動, qB會自動生成profile的資料夾, 配置全都在裡面
或者怕麻煩的話, 可以寫一個批次檔(.bat)
例如: portable.bat
裡面就一句
`qbittorrent.exe --portable`
下次直接開啟batch檔就可以了

**Comment by CloudxM** [comment]
可是这种方法，关联磁力协议后，在关闭程序的情况下，调用的不是便携版的配置，有解吗。。。

**Comment by c0re100** [comment]
這是bug...
請到官方repo [issue](https://github.com/qbittorrent/qBittorrent/issues)回報

**Comment by myfreeer** [comment]
使用DLL劫持和API Hook便携化
https://github.com/myfreeer/qbittorrent-portable
(仅Windows)

**Comment by CloudxM** [comment]
@c0re100 楼上myfreeer的工具很有用，可以自弄便携版，大佬要不要集成进去。而且不开exe，协议拉起的也是便携版配置。

**Comment by SeaHOH** [comment]
正准备淘换个客户端，浏览多篇推荐简介，大致锁定 qbittorrent。
先前在隔壁官版逛，看到有人因为 portable bug 翻车了好几个 T，我差点想放弃 qbittorrent，还好在这里看到了 myfreeer 的杰作。

**Comment by xzy722** [comment]
> @c0re100 楼上myfreeer的工具很有用，可以自弄便携版，大佬要不要集成进去。而且不开exe，协议拉起的也是便携版配置。

请问能写个教程吗？不太懂编译

**Comment by Remonli** [comment]
4.2.1 解决了这个问题, 目录里新建profile文件夹就是便携版了. 

FEATURE: Enable portable mode if "profile" directory exists (Tester798)
