### ISSUE TITLE
i just cant make it on my mac it shows that checking for Qt5 qmake >= 5.5.1... not found configure: error: Could not find qmake

### ISSUE THREAD

**Issue by hommy112** [c0re100/qBittorrent-Enhanced-Edition#40]
**Please provide the following information**

### qBittorrent version and Operating System
(type here)

### If on linux, libtorrent and Qt version
(type here)

### What is the problem
(type here)

### What is the expected behavior
(type here)

### Steps to reproduce
(type here)

### Extra info(if any)
(type here)

**Comment by c0re100** [comment]
For Mac Compilation:
Fastest way:
Install Qt5 via Homebrew
`brew install qt5` and `brew link qt5`

If you compiled it yourself
you may need export QT_QMAKE first or just use CMake.
https://github.com/qbittorrent/qBittorrent/wiki/Compilation-guide-for-macOS-systems#compile-qbittorrent
