### ISSUE TITLE
Geographic data still cannot be displayed

### ISSUE THREAD

**Issue by H-Sofie** [c0re100/qBittorrent-Enhanced-Edition#404]
### qBittorrent & operating system versions

qBittorrent： 4.4.3.12 x64
Operating system: Windows 10 Pro 21H2 19044.1706 x64
Qt: 5.15.2

### What is the problem?

![捕获](https://user-images.githubusercontent.com/67623049/185105670-8f67fb2e-ab41-4e92-a63d-349b52f8ca0d.PNG)
I have tried to manually add files to the geoip folder, but I still can't recognize them.

### Additional context

![捕获](https://user-images.githubusercontent.com/67623049/185105670-8f67fb2e-ab41-4e92-a63d-349b52f8ca0d.PNG)
![image](https://user-images.githubusercontent.com/67623049/185106285-9e6226f4-6e27-47bb-8dec-08a5c1181aba.png)
There is still no national flag on the left.

**Comment by c0re100** [comment]
Are you place into geoip directory `AppData\Local\qBittorrent\GeoDB`?

**Comment by H-Sofie** [comment]
> Are you place into geoip directory`AppData\Local\qBittorrent\GeoDB`?

Oh, my new folder is named geoip. After it is renamed GeoDB, it is normal for me to download the database files manually, but the database may still not be updated automatically.

**Comment by c0re100** [comment]
> > Are you place into geoip directory`AppData\Local\qBittorrent\GeoDB`?
> 
> Oh, my new folder is named geoip. After it is renamed GeoDB, it is normal for me to download the database files manually, but the database may still not be updated automatically.

It looks like your network issue.
https://download.db-ip.com/free/dbip-country-lite-2022-08.mmdb.gz
I don't have any problem to download geoip db.

**Comment by H-Sofie** [comment]
> > > Are you place into geoip directory?`AppData\Local\qBittorrent\GeoDB`
> > 
> > 
> > Oh, my new folder is named geoip. After it is renamed GeoDB, it is normal for me to download the database files manually, but the database may still not be updated automatically.
> 
> It looks like your network issue. https://download.db-ip.com/free/dbip-country-lite-2022-08.mmdb.gz I don't have any problem to download geoip db.

![image](https://user-images.githubusercontent.com/67623049/185190006-bc9582e2-27d1-486e-bed5-eff5c19879a6.png)
So strange.There is no problem for me to download files manually on the website, but the program cannot download files automatically
