### ISSUE TITLE
Appimage build failed

### ISSUE THREAD

**Issue by c0re100** [c0re100/qBittorrent-Enhanced-Edition#409]
### qBittorrent & operating system versions

qBittorrent: 4.4.4.10
Operating system: GitHub Action
Qt: 6.3.1
libtorrent-rasterbar: 2.0.7

### What is the problem?

@abcfy2
Seems Qt6.3.1 need QtQml to compile QtWayland.
https://github.com/c0re100/qBittorrent-Enhanced-Edition/runs/7984056205?check_suite_focus=true#step:5:10171

x86_64 nox and other arch also failed
https://github.com/c0re100/qBittorrent-Enhanced-Edition/runs/7984057167?check_suite_focus=true#step:5:1859

**Comment by abcfy2** [comment]
Got it. I'll check it later. You can assign this issue to me. Thanks.

**Comment by abcfy2** [comment]
https://bugreports.qt.io/browse/QTBUG-104318?filter=-2 I find I've committed this issue to Qt bug tracker, and this issue has been fixed in future release.

But at this time I should build QtQml to make AppImage build could pass.
