### ISSUE TITLE
libtorrent 1.2.x

### ISSUE THREAD

**Issue by f1ume** [c0re100/qBittorrent-Enhanced-Edition#411]
### Suggestion

之前原版4.4下载页会有表明释出libtorrent 1.2.x版4.4.x

> These are offered to help the transition from v4.3.x to v4.4.x and to allow users to test for possible regressions. They may not be offered for future versions.

现在4.4.4版这句删掉了。是不是表明libtorrent 1.2的4.4还会持续提供一段时间。那EE版会不会做呢？

**Comment by c0re100** [comment]
> ### Suggestion
> 之前原版4.4下载页会有表明释出libtorrent 1.2.x版4.4.x
> 
> > These are offered to help the transition from v4.3.x to v4.4.x and to allow users to test for possible regressions. They may not be offered for future versions.
> 
> 现在4.4.4版这句删掉了。是不是表明libtorrent 1.2的4.4还会持续提供一段时间。那EE版会不会做呢？
> 
> ### Use case
> _No response_
> 
> ### Extra info/examples/attachments
> _No response_

如果有libtorrent版本需求，可以到action那邊下載
https://github.com/c0re100/qBittorrent-Enhanced-Edition/actions/runs/2928842651
目前是沒有1.2 release版的打算
