### ISSUE TITLE
选项窗口内部文字太小

### ISSUE THREAD

**Issue by TheStar4Fate** [c0re100/qBittorrent-Enhanced-Edition#419]
### qBittorrent & operating system versions

qBittorrent: 4.4.5.10
Operating system: Windows 10 专业版 21H2
Qt: 5.15.5

### What is the problem?

![image](https://user-images.githubusercontent.com/7358871/190545984-4829ad00-81ba-4e71-a03d-e0d2759b1277.png)
文字非常小，看不清楚。显示器分辨率是3840*2160，系统缩放是200%

**Comment by EmmettTsai** [comment]
C:\Program Files\qBittorrent\qt.conf

Enable the config
```
[Platforms]
WindowsArguments = dpiawareness=1
```

**Comment by TheStar4Fate** [comment]
> 

thank you very much
