### ISSUE TITLE
请问如何在linux上使用?

### ISSUE THREAD

**Issue by LN-NG** [c0re100/qBittorrent-Enhanced-Edition#42]
**Please provide the following information**

### qBittorrent version and Operating System
4.1.6  Debian 9

### If on linux, libtorrent and Qt version
libtorrent 1.1.13
Qt5

### What is the problem
我希望有一个详细的使用流程，下载页面的描述对于Linux认识程度较低的人可能无法提供帮助，
目前我不知道是不是把“ipfilter.dat”放在"/root/.config/qBittorrent"中就能启用还是在qb的“过滤规则路径”中添加“ipfilter.dat”的路径就能启用。两个方法我都尝试了，但还是不能屏蔽“xl0012-随机字符”的客户端.所以我怀疑我用的方法不正确。
麻烦大佬解答了 谢谢

**Comment by c0re100** [comment]
由於你在用qBittorrent官方版本，所以無法載入 `.config/qBittorrent/ipfilter.dat`
Debian/Ubuntu用戶可以使用PPA(詳情: #33) 或者 [自行編譯安裝](https://github.com/qbittorrent/qBittorrent/wiki/Compiling-qBittorrent-on-Debian-and-Ubuntu)
