### ISSUE TITLE
增强版目前还是libtorrent v2，能否重新打包个libtorrent 1.2.17的

### ISSUE THREAD

**Issue by tbc0309** [c0re100/qBittorrent-Enhanced-Edition#424]
### Suggestion

libtorrent v2内存占用8个G，实在跑不动，

Changelog里面Switch to libtorrent 1.2实际还是v2。

**Comment by c0re100** [comment]
嗯???
請問你是用哪個版本?

**Comment by tbc0309** [comment]
> 嗯???
> 
> 請問你是用哪個版本?

就是现在的4.4.5.10，查看实际还是v2

**Comment by f1ume** [comment]
releases那里 点
**Show all 14 assets**
现在的github UI自动折叠了一些项目

**Comment by c0re100** [comment]
> > 嗯???
> > 請問你是用哪個版本?
> 
> 就是现在的4.4.5.10，查看实际还是v2

哪個系統的?

**Comment by tbc0309** [comment]
qbittorrent-enhanced-nox_x86_64-linux-musl_static.zip

qbittorrent-enhanced-nox_aarch64-linux-musl_static.zip

qBittorrent 的构建使用了以下库：

Qt:	6.3.1
Libtorrent:	2.0.7.0
Boost:	1.80.0
OpenSSL:	3.0.5
zlib:	1.2.11.zlib-ng

**Comment by c0re100** [comment]
ping @abcfy2
我沒改錯吧...
https://github.com/c0re100/qBittorrent-Enhanced-Edition/commit/200324dd650278d06709716a5fa0e3f024c0e74c

appimage有用1.2去編譯
https://github.com/c0re100/qBittorrent-Enhanced-Edition/actions/runs/2981795707/jobs/4793343609#step:5:7625
反而cross compile用了2.0
https://github.com/c0re100/qBittorrent-Enhanced-Edition/actions/runs/2981795707/jobs/4793343639#step:5:3728
https://github.com/c0re100/qBittorrent-Enhanced-Edition/actions/runs/2981795707/jobs/4793343689#step:5:3745

**Comment by abcfy2** [comment]
这个我应该修正了，之前旧的构建脚本对`cross_compile`这里多复制了一份变量，导致你改了上面的变量之后下面还有个赋值，又给改回去了

这个问题我应该再上次PR的时候修正了

**Comment by abcfy2** [comment]
https://github.com/abcfy2/qBittorrent-Enhanced-Edition/releases/tag/v4.4.5.12 我的仓库也同步了代码，并且重新触发过新的CI，这些构建均已修正，基于Qt 6.4 + libtorrent 1.2构建成功

**Comment by c0re100** [comment]
> 这个我应该修正了，之前旧的构建脚本对`cross_compile`这里多复制了一份变量，导致你改了上面的变量之后下面还有个赋值，又给改回去了
> 
> 这个问题我应该再上次PR的时候修正了

咦，我看到了

那麼 @tbc0309 到action重新下載nox x86_64/aarch64就應該能轉回1.2了
https://github.com/c0re100/qBittorrent-Enhanced-Edition/actions/runs/3163407390

**Comment by tbc0309** [comment]
谢谢两位大佬❥(^_-)
