### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by waxjack** [c0re100/qBittorrent-Enhanced-Edition#43]
### qBittorrent version and Operating System
qbee 4.161 win10 64

### What is the problem
大文件检查后，一旦取消勾选（不下载），无法再重新选择，进行正常做种（即便再选择正常，也会自动取消）。而且我觉得tracker大概也有问题，ut上能有更多tracker是工作状态（通常qbee只有一两个tracker显示工作中），并且tracker标题栏还是点不了。还有下载后，即便没有选择要下载的文件，也会在硬盘上生成对应的空文件，有些空文件还占用了空间。最后不知道是不是bug，dht的连接数在ut上更高（ut1500多/qbee 500多）。

**Comment by c0re100** [comment]
檢查問題 < 無法重現
如有相關檔案
取消勾選後，相關檔案應該會移動到`.unwanted`資料夾下，再一次勾選下會重新移動到相關位置
如沒有相關檔案
在勾選後，此種子應該會轉為`Stalled`狀態並會重新透過Tracker尋找`Peer`
當連接到Peer後會再轉到`Downloading`狀態並開始下載相關檔案

工作狀態問題
Options>Advanced>勾選Always announce to all trackers in a tier/all tiers 這2個選項即可

tracker標題 #27 

佔用空間問題
https://github.com/qbittorrent/qBittorrent/wiki/Frequently-Asked-Questions#I_configured_qBittorrent_to_not_download_some_files_in_a_torrent_but_they_still_appear_on_my_hard_disk_why_is_that

DHT問題
不太清楚，可能utorrent有更多DHT節點?
目前qb只5個DHT節點
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_1_x/src/base/bittorrent/session.cpp#L1451
