### ISSUE TITLE
Update to 4.5.0

### ISSUE THREAD

**Issue by abcfy2** [c0re100/qBittorrent-Enhanced-Edition#434]
Official released https://github.com/qbittorrent/qBittorrent/releases/tag/release-4.5.0

Please update. @c0re100

**Comment by Yztqszp** [comment]
@c0re100 新的版本最明显区别在于  更新UI，别的细节没有什么明显的变化。
期待更新~~~~

https://www.fosshub.com/qBittorrent.html 有更新说明

**Comment by c0re100** [comment]
Sorry, I'm too busy recently :'(
Update will resume on weekend.

**Comment by genesis-7** [comment]
期待了，bilibili推荐来的

**Comment by snfcx** [comment]
更新了
