### ISSUE TITLE
Traditional Chinese is not yet fully completed. 繁體中文似乎不完全

### ISSUE THREAD

**Issue by cmcmcmcm2** [c0re100/qBittorrent-Enhanced-Edition#437]
### Suggestion

對下載項目右鍵選單是簡體中文
Right-click menu is still SC.
![image](https://user-images.githubusercontent.com/32160080/205446522-0c680032-dc75-442f-a3b9-09837534350f.png)

**Comment by abcfy2** [comment]
官方版本似乎也有，试试在设置中语言切换成英文，退出重新打开，再切换成目标语言，重新打开一次应该就好了，我遇到过中文和英文各一半的情况，切换语言重启就好了

**Comment by cmcmcmcm2** [comment]
> 

剛剛嘗試過了 
看起來情況一樣qq

**Comment by c0re100** [comment]
這是transifex那邊的問題，要等官方修正了
https://github.com/qbittorrent/qBittorrent/issues/18130
我沒正體中文的翻譯權限去還原以前的東西

**Comment by cmcmcmcm2** [comment]
瞭解 感謝回覆
