### ISSUE TITLE
More architecture support and nox version for the AUR package

### ISSUE THREAD

**Issue by XCNova** [c0re100/qBittorrent-Enhanced-Edition#44]
Please add "arm","armv6h","armv7h"and"aarch64" architecture support to the AUR package.
Please submit a nox version package to AUR.
I did some dirty hacks with the PKGBUILD to achieve that and it worked fine with my rpi3.
Here's the modified PKGBUILD, I hope it could help.

[PKGBUILD.txt](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/3424766/PKGBUILD.txt)

**Comment by c0re100** [comment]
I don't have SD card for my rpi2...can you test it?
https://aur.archlinux.org/packages/qbittorrent-enhanced-nox-git/

**Comment by XCNova** [comment]
I tested it on my rpi3 and I didn't see any problem building or running.

**Comment by c0re100** [comment]
> I tested it on my rpi3 and I didn't see any problem building or running.

Ok, thanks~~
