### ISSUE TITLE
V4.5.0.10 界面无法设置简体中文 + 乱码

### ISSUE THREAD

**Issue by HuangLuxuan** [c0re100/qBittorrent-Enhanced-Edition#441]
### qBittorrent & operating system versions

qBittorrent: 4.5.0.10 x64
Operating system: Windows 8.1 Pro x64
Qt: 5.15.7
libtorrent: 1.2.18.0

### What is the problem?

设置语言选项没有任何用处，仍然是英文且全是乱码，但是旧版本正常
![image](https://user-images.githubusercontent.com/19358299/205896754-9f3c9456-b3d3-4252-9fff-c88aaf18fcf8.png)
![image](https://user-images.githubusercontent.com/19358299/205896820-fe289b86-2857-4cf4-bcdd-2d6616b3b42b.png)
![image](https://user-images.githubusercontent.com/19358299/205897759-3d9a6299-a7b8-4ccb-9688-7dfab4f682a9.png)

**Comment by abcfy2** [comment]
已知问题，这个是上游的issue,等待上游解决： https://github.com/qbittorrent/qBittorrent/issues/18142

GUI版本可以通过切换语言，再退出重进的方式修复。

比如切换成英文，退出之后再切换成简体中文，退出重进可以修复，webui等官方解决吧

**Comment by HuangLuxuan** [comment]
那乱码问题有什么思路吗，注意到已经有一些种子的tracker列表变成乱码了

**Comment by abcfy2** [comment]
没遇到过，你的tracker有问题吧

![image](https://user-images.githubusercontent.com/5327677/205935781-6d025653-cd1e-4446-848a-d7627cb5aab9.png)

**Comment by HuangLuxuan** [comment]
刚刚仔细对比了一下，乱码问题好像不是这个版本出来的，是之前的某个版本莫名其妙的，然后带乱码的种子就不会在列表中显示，结果是127个种子一个一个数下来只有77个，所以一直没发现，最新的版本可能是修复了什么，所以就出来了，才叫我发现了
