### ISSUE TITLE
关于qBittorrent 4.5.0简体中文语言的修正

### ISSUE THREAD

**Issue by tbc0309** [c0re100/qBittorrent-Enhanced-Edition#442]
### qBittorrent & operating system versions

qBittorrent: 4.5.0
Operating system: linux

### What is the problem?

建议修正后重新打包，否则Web UI设置 简体中文 无效，谢谢。

src/webui/www/private/views/preferences.html

```
- <option value="zh">简体中文</option>
+ <option value="zh_CN">简体中文</option>
```

**Comment by Kal-tsit63** [comment]
还在疑惑，为什么更新完了以后中文没了，原来如此

**Comment by abcfy2** [comment]
这个是上游问题，上游已经在解决了，等待上游解决下游合并就行了

**Comment by tbc0309** [comment]
意思……上游错下游就不允许改了？

**Comment by abcfy2** [comment]
当然不改了，上游自己的BUG自己解决下游受益就完事了。这个问题请给上游反馈： https://github.com/qbittorrent/qBittorrent/issues

**Comment by tbc0309** [comment]
……意思上游一坨屎下游就得接着吃，倒掉都不行，明白了。
