### ISSUE TITLE
Fix Winget Releaser error

### ISSUE THREAD

**Issue by sitiom** [c0re100/qBittorrent-Enhanced-Edition#445]
### What is the problem?

The [last Winget Releaser job](https://github.com/c0re100/qBittorrent-Enhanced-Edition/actions/runs/3607979602/jobs/6080323340) failed with an error, but it had silently exited with a success (@vedantmgoyal2009 bug from action?):
![image](https://user-images.githubusercontent.com/56180050/209430716-710e3d73-c888-4f1a-8120-3cd13d63529a.png)
This means that the https://github.com/c0re100/winget-pkgs fork is outdated. You could do either one of the two things to fix this. From the README:
> Ensure that the fork is up-to-date with the upstream repository. You can do this using one of the following methods:
>
> - Give `workflow` permission to the token you created in Step 1. This will allow the action to automatically update your fork with the upstream repository.
> - You can use **[Pull App](https://github.com/apps/pull)** which keeps your fork up-to-date with the upstream repository via automated pull requests.

For now, I have manually added 4.5.0.10 to Winget: https://github.com/microsoft/winget-pkgs/pull/92203.

**Comment by sitiom** [comment]
@c0re100 Did you install [Pull](https://github.com/apps/pull) to https://github.com/c0re100/winget-pkgs?

**Comment by c0re100** [comment]
> @c0re100 Did you install [Pull](https://github.com/apps/pull) to https://github.com/c0re100/winget-pkgs?

Installed now.
