### ISSUE TITLE
qBittorrent EE v4.5.0.10 has no simple Chinese display exception,but tradional Chinese is good

### ISSUE THREAD

**Issue by NothingIsNull** [c0re100/qBittorrent-Enhanced-Edition#449]
### qBittorrent & operating system versions

qBittorrent: EE v4.5.0.10
OS:Armbian

### What is the problem?

qBittorrent EE v4.5.0.10  Web UI simple Chinese display exception,but tradional Chinese is good.

### Steps to reproduce

If I choose simple Chinese,the Web UI displayed English,and if I choose traditional Chinese from HongKong or Taiwan,it's good.

**Comment by abcfy2** [comment]
Known issue: https://github.com/qbittorrent/qBittorrent/issues/18090

It's an upstream BUG

**Comment by NothingIsNull** [comment]
> Known issue: [qbittorrent#18090](https://github.com/qbittorrent/qBittorrent/issues/18090)
> 
> It's an upstream BUG

could I find the language packages path like qbittorrent EE in windows as the path"..\qbittorrent\translation"?then I put the simple_Chinese package file into this path.

**Comment by c0re100** [comment]
> > Known issue: [qbittorrent#18090](https://github.com/qbittorrent/qBittorrent/issues/18090)
> > It's an upstream BUG
> 
> could I find the language packages path like qbittorrent EE in windows as the path"..\qbittorrent\translation"?then I put the simple_Chinese package file into this path.

No, language packages built with qBittorrent itself.
