### ISSUE TITLE
防火墙例外没有设置正确

### ISSUE THREAD

**Issue by eebssk1** [c0re100/qBittorrent-Enhanced-Edition#45]
**Please provide the following information**

### qBittorrent version and Operating System
(type here)
4.1.6.1 windows10 1903
### If on linux, libtorrent and Qt version
(type here)

### What is the problem
(type here)
新系统第一次安装qbt之后，windows防火墙的专用那一个选项框总是没给qbt勾上，只有公用那一个是勾上的，不是很懂
### What is the expected behavior
(type here)
防火墙阻止了还怎么下载
### Steps to reproduce
(type here)
全新安装windows
安装qbt
打开防火墙（允许应用程序通过）
### Extra info(if any)
(type here)
nmd，wsm，找了半天才发现是防火墙==

**Comment by c0re100** [comment]
這是正常的，只允許qBt使用公用網絡
在開啟Windows防火牆下測試，一樣可以連接外網
