### ISSUE TITLE
汉化不完全

### ISSUE THREAD

**Issue by ghost** [c0re100/qBittorrent-Enhanced-Edition#451]
### Extra info/examples/attachments

![圖片](https://user-images.githubusercontent.com/62539795/210783757-fefb77b4-5b12-4b28-bbf9-6aa75355a41e.png)

**Comment by abcfy2** [comment]
Known issue. It's an upstream issue, we have to wait for upstream to fix it: https://github.com/qbittorrent/qBittorrent/issues/18130
