### ISSUE TITLE
WEB UI的中文设置有问题

### ISSUE THREAD

**Issue by MIMOtopunv** [c0re100/qBittorrent-Enhanced-Edition#453]
### qBittorrent & operating system versions

qBittorrent Enhanced Edition v4.5.0.10
 OS : Windows 企业版 19045.2546 , OpenWrt R23.1.1
Qt:  Windows/6.4.0 OpenWrt/6.4.1
Libtorrent:	1.2.18.0

### What is the problem?

在webUI中设置用户界面语言为简体中文时, 配置文件被错误的设置为了"General\Locale=zh"
实际应为"General\Locale=zh_CN"
![Snipaste_2023-01-30_02-10-29](https://user-images.githubusercontent.com/77264353/215346819-677bae00-437f-43b1-a10a-c765af3cb54f.png)
![Snipaste_2023-01-30_02-13-35](https://user-images.githubusercontent.com/77264353/215346825-7a1144fa-dec2-4b58-984d-fbfa96a42d81.png)

**Comment by c0re100** [comment]
Known issue: https://github.com/qbittorrent/qBittorrent/issues/18090
