### ISSUE TITLE
4.5.0.10 版本翻译消失, 界面变成全英文

### ISSUE THREAD

**Issue by microcai** [c0re100/qBittorrent-Enhanced-Edition#458]
### qBittorrent & operating system versions

测试 Qt: 6.4.2 和 Qt 5.15.8 下都没有翻译.
OS: Gentoo Linux

### What is the problem?

4.5.0.10 版本翻译消失, 界面变成全英文

### Steps to reproduce

编译三部曲
运行

**Comment by abcfy2** [comment]
上游已知问题，等待上游版本修复即可。Please wait for upstream to fix it.

**Comment by wxlg1117** [comment]
web ui:
cat .config/qBittorrent_EE/qBittorrent.conf

General\Locale=zh
改为
General\Locale=zh_CN

**Comment by c0re100** [comment]
Should be fixed in 4.5.1.10
