### ISSUE TITLE
又是bug？

### ISSUE THREAD

**Issue by waxjack** [c0re100/qBittorrent-Enhanced-Edition#46]
qBittorrent version and Operating System
qbee 4.161 win10 64

What is the problem
怎么文件都没下完就开始做种了？
(https://user-images.githubusercontent.com/36566872/62218543-3fbde800-b3df-11e9-86d6-2a5a60312313.PNG)
重启又好了......
(https://user-images.githubusercontent.com/36566872/62219452-f078b700-b3e0-11e9-9380-20324a0b6056.PNG)

**Comment by c0re100** [comment]
> qBittorrent version and Operating System
> qbee 4.161 win10 64
> 
> What is the problem
> 怎么文件都没下完就开始做种了？
> (https://user-images.githubusercontent.com/36566872/62218543-3fbde800-b3df-11e9-86d6-2a5a60312313.PNG)
> 重启又好了......
> (https://user-images.githubusercontent.com/36566872/62219452-f078b700-b3e0-11e9-9380-20324a0b6056.PNG)

等待是指該種子暫時沒有Peer擁有其他資源，所以無法下載更多
而上傳本身是同時進行的，與做種沒有衝突。
準確一點就是你下載的一刻，已經在做種了~

不過根據下圖，似乎是舊bug....錯誤的百分比
