### ISSUE TITLE
百度网盘BT下载使用的客户端go.torrent dev 20181121，Peer ID  -GT0002-，考虑进BanList

### ISSUE THREAD

**Issue by HonokaRen** [c0re100/qBittorrent-Enhanced-Edition#460]
### Suggestion

有几个下不完的种子，想用百度网盘试一下，在百度网盘创建任务后，这几个种子上传列表就有几个同一网段的IP用这个客户端（go.torrent dev 20181121，Peer ID  -GT0002-）下载，IP地址为阳泉（百度有在阳泉建数据中心）和石家庄，百度网盘取消任务后，这几个客户端也随即消失
经观察后发现基本上出现此客户端的种子都处于吸血状态，建议加入BanList

![~ASH2~T8BPJ@MUMLJBXNO$1](https://user-images.githubusercontent.com/42889950/219857599-90fed2e5-7890-498e-a40a-f7f6c2fe9401.png)

![NF{FTIDL)6T8XW} %T`@BLE](https://user-images.githubusercontent.com/42889950/219857609-9918034d-76cf-4da4-86fe-86b0e7d58ae0.png)

![B7S L}H7O)`$NY0Y`R(SOZ1](https://user-images.githubusercontent.com/42889950/219857655-614778f5-bf02-46f7-9b71-5b4e16afda5a.png)

甚至有海外服务器吸血
![RKV5Q@`LI9WNN6(AP2D8%@8](https://user-images.githubusercontent.com/42889950/219952065-7b037000-700d-4ea2-ac70-28294b522c29.png)

**Comment by HonokaRen** [comment]
或者是不是可以出一个客户端、peer id白名单或黑名单功能

**Comment by escape0707** [comment]
> 或者是不是可以出一个客户端、peer id白名单或黑名单功能

Client name and peer id based blacklisting and whitelisting function is already implemented: https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/tag/release-4.3.5.10

I don't know anything about the current Baidu disk peer id situation, though.

**Comment by zhelunofficial** [comment]
https://github.com/Simple-Tracker/qBittorrent-ClientBlocker
推荐用这个

**Comment by KevinChen-CMYK** [comment]
> 或者是不是可以出一个客户端、peer id白名单或黑名单功能

也可以用这个PeerBanHelper 
[PeerBanHelper ](https://github.com/PBH-BTN/PeerBanHelper)

**Comment by regsitezzxcss** [comment]
thanks everyone!
I am very grateful for the many great people who maintain it.
感谢大家！
我很感激有那么多伟大的人在维护它。
