### ISSUE TITLE
每次启动时已完成任务也会校验，导致大量读盘。

### ISSUE THREAD

**Issue by gljx** [c0re100/qBittorrent-Enhanced-Edition#463]
### qBittorrent & operating system versions

qBittorrent v4.5.0.10
win 11

### What is the problem?

每次启动都会强制对所有任务进行哈希校验。如果是未完成的任务我能理解。为什么已经完成的任务。还要进行哈希校验？以至于每次启动软件都会卡半分钟，而且还会把我硬盘疯狂读取，必须手动停。

### Steps to reproduce

no response

### Additional context

no response

### Log(s) & preferences file(s)

no response

**Comment by abcfy2** [comment]
你自己勾选了高级设置中的完成后重新校验 Torrent了吧？自己去掉就行了，默认这个参数是不勾选的

**Comment by gljx** [comment]
> 你自己勾选了高级设置中的完成后重新校验 Torrent了吧？自己去掉就行了，默认这个参数是不勾选的

谢谢，我看有人说取消勾选会导致下载文件不完整就勾了。

**Comment by abcfy2** [comment]
> > 你自己勾选了高级设置中的完成后重新校验 Torrent了吧？自己去掉就行了，默认这个参数是不勾选的
> 
> 谢谢，我看有人说取消勾选会导致下载文件不完整就勾了。

绝大多数情况下只要不是硬盘故障一般都不会下载不完整，因为torrent本身也是有块校验的。你要是不放心也可以在下载完成后手动点击右键选择校验就行了，效果是一样的
