### ISSUE TITLE
i686 musl static binary

### ISSUE THREAD

**Issue by wdlkmpx** [c0re100/qBittorrent-Enhanced-Edition#465]
### Suggestion

would you please provide i686 static binaries

### Use case

Some old laptops/netbooks/pcs don't support x86_64

And i686 static binaries also run on x86_64 systems, "universal x86 binaries"

**Comment by sdip15fa** [comment]
There are compile instructions

**Comment by abcfy2** [comment]
You can build yourself follow the comments of build script: https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_5_x/.github/workflows/cross_build.sh

You may try:

```sh
docker run --rm -v `git rev-parse --show-toplevel`:/build abcfy2/muslcc-toolchain-ubuntu:i686-linux-musl /build/.github/workflows/cross_build.sh
```

I'll try to add this build in CI later.

**Comment by abcfy2** [comment]
You can download from build artifacts: https://github.com/c0re100/qBittorrent-Enhanced-Edition/actions/runs/4465707779

And auto release build will publish next release.

**Comment by wdlkmpx** [comment]
Testing with palemoon and qtbittorent-nox [both i686]... Thank you so much, it works fine. 
I'll use the i686 static binary in i686 and x86_64 systems, it works the same in both

I was not expecting this request to be fulfilled, there is an insane amount of prejudice towards i686, but when it comes to static binaries, i686 binaries are "universal x86 binaries" that work on any x86 processor released since 2003 I guess...

The world would be a better place if more projects that release static cli apps would include i686 binaries..
