### ISSUE TITLE
被qb误删文件真的太痛苦了

### ISSUE THREAD

**Issue by alan636** [c0re100/qBittorrent-Enhanced-Edition#469]
### qBittorrent & operating system versions

想体验一下做种功能，于是直接新建种子，由于第一次上手不是很懂，没有填啥直接就创建，结果创建出来就是40个g大小，我觉得程序出错了，右键勾选连文件一起删除，结果把我用户文件夹所有都删除了！不要说什么小白用户活该，就算是小白，也不能默认对整个用户文件直接创建种子吧？作为当事人真的非常气愤！很多重要文件现在正在抢救！希望后人看到不要随意把玩，这东西默认机制有问题！

### What is the problem?

想体验一下做种功能，于是直接新建种子，由于第一次上手不是很懂，没有填啥直接就创建，结果创建出来就是40个g大小，我觉得程序出错了，右键勾选连文件一起删除，结果把我用户文件夹所有都删除了！不要说什么小白用户活该，就算是小白，也不能默认对整个用户文件直接创建种子吧？作为当事人真的非常气愤！很多重要文件现在正在抢救！希望后人看到不要随意把玩，这东西默认机制有问题！

**Comment by abcfy2** [comment]
Upstream issue. You should ask upstream to help
