### ISSUE TITLE
做唔到seed

### ISSUE THREAD

**Issue by hellelan** [c0re100/qBittorrent-Enhanced-Edition#47]
**Please provide the following information**

### qBittorrent version and Operating System
v4.1.6.1/Windows 10 Pro(1809)

### If on linux, libtorrent and Qt version
(type here)

### What is the problem
唔知點解同路人會show我既IP，但唔係個個都show
如果show，會顯示進度只有大約50%
我己經下載完成，但只有50%
咁樣我做唔到種

### What is the expected behavior
我要做種

### Steps to reproduce
(type here)

### Extra info(if any)
巴打，有無方法令到更多人下載到個seed
我手頭上都係做緊舊seed，想有人下載時，我可以比人search到，將資源分到出去
(吸血鬼除外)
拜託

**Comment by c0re100** [comment]
做seed係視乎雙方係咪有共同Tracker
雙方網絡連線情況
