### ISSUE TITLE
rss 订阅更新不会获取最新的信息

### ISSUE THREAD

**Issue by lingxd** [c0re100/qBittorrent-Enhanced-Edition#476]
### qBittorrent & operating system versions

qBittorrent: v4.5.2.10 x64
Operating system: Windows 11 Pro

### What is the problem?

rss 订阅链接是正常的，但是却不会更新最新的数据。

### Steps to reproduce

1. 新增rss订阅
2. 等待订阅链接更新
3. 手动更新所有rss订阅
4. 发现订阅数据并未更新到软件

**Comment by cyilin36** [comment]
同样的问题

**Comment by dzlong6** [comment]
同样的问题，我的直接更新不了RSS了

**Comment by Chengyuan-artist** [comment]
Same problem with RSS feed updating.

log(e.g.):
4/23/23 10:29 AM - 下载 RSS 订阅 'https://acg.rip/.xml?term=%E5%A4%A9%E5%9B%BD%E5%A4%A7%E9%AD%94%E5%A2%83' 失败。原因：The operation was canceled
4/23/23 10:30 AM - 下载 RSS 订阅 'https://acg.rip/.xml?term=%E5%A4%A9%E5%9B%BD%E5%A4%A7%E9%AD%94%E5%A2%83' 失败。原因：The connection to the remote server timed out

Maybe it's related to GFW？

**Comment by AidanYang0618** [comment]
我遇到了相同的问题，日志报错相同

**Comment by lingxd** [comment]
2023/4/23 18:43 - 下载 RSS 订阅 'https://dmhy.b168.net/topics/rss/rss.xml?keyword=&sort_id=0&team_id=0&order=date-desc' 失败。原因：The operation was canceled
2023/4/23 18:43 - 下载 RSS 订阅 'https://dmhy.b168.net/topics/rss/rss.xml?keyword=%5BLilith-Raws%5D+%E9%AC%BC%E6%BB%85%E4%B9%8B%E5%88%83+%E5%88%80%E5%8C%A0%E6%9D%91%E7%AF%87' 失败。原因：The operation was canceled
2023/4/23 18:43 - 下载 RSS 订阅 'https://dmhy.b168.net/topics/rss/rss.xml?keyword=%E4%B8%8D%E5%BD%93%E5%93%A5%E5%93%A5&sort_id=0&team_id=803&order=date-desc' 失败。原因：The operation was canceled
2023/4/23 18:43 - 下载 RSS 订阅 'https://dmhy.b168.net/topics/rss/team_id/803/rss.xml' 失败。原因：The operation was canceled

**Comment by lingxd** [comment]
但是我复制到我的浏览器是可以正常查看的

**Comment by dzlong6** [comment]
> 

acg.rip被墙了，开梯子之后在设置里面配置一下代理就行

**Comment by lingxd** [comment]
> > 
> 
> acg.rip被墙了，开梯子之后在设置里面配置一下代理就行

设置连接->代理服务器->仅对种子使用代理  

就ok了
