### ISSUE TITLE
RSS订阅无法更新

### ISSUE THREAD

**Issue by dzlong6** [c0re100/qBittorrent-Enhanced-Edition#477]
### qBittorrent & operating system versions

qBittorrent: v4.5.2.10 x64
Windows 11 Home 22H2

### What is the problem?

RSS订阅可以正常使用的，但是在qb中无法更新，一直显示红色的×。之前也能正常用，上两天突然不行了
<img width="107" alt="image" src="https://user-images.githubusercontent.com/96406198/233594587-e6cf15f7-0334-4189-9184-36c48e746c4b.png">

### Steps to reproduce

点击更新所有（或逐个手动更新）
等待一段时间后显示红色的×

### Log(s) & preferences file(s)

部分日志如下：
(W) 2023-04-21T16:53:52 - UPnP/NAT-PMP 端口映射失败。消息： "could not map port using UPnP: no router found"
(W) 2023-04-21T16:53:52 - UPnP/NAT-PMP 端口映射失败。消息： "could not map port using UPnP: no router found"
(W) 2023-04-21T16:53:52 - UPnP/NAT-PMP 端口映射失败。消息： "could not map port using UPnP: no router found"
(W) 2023-04-21T16:54:04 - 下载 RSS 订阅 'https://acg.rip/.xml?term=%E5%8D%83%E5%A4%8F%E5%AD%97%E5%B9%95%E7%BB%84+%E5%A4%A9%E5%9B%BD%E5%A4%A7%E9%AD%94%E5%A2%83+1080p+%E7%AE%80%E4%BD%93' 失败。原因：An unknown network-related error was detected

**Comment by abcfy2** [comment]
你这个订阅地址已经被墙了，不翻墙无法访问
