### ISSUE TITLE
qbittorrent enhanced v4.5.3.10 cannot run

### ISSUE THREAD

**Issue by oupeng** [c0re100/qBittorrent-Enhanced-Edition#484]
### qBittorrent & operating system versions

qbittorrent:4.5.2.10
Operating system: Mac Catalina 10.15.7 (19H2026)

### What is the problem?

It seems that after upgrading from v4.5.2.10 to v4.5.3.10, the software is not responding. There are no error messages popping up, and the process cannot be found.Abandon support for Mac Catalina?
thanks

**Comment by shenzhui007** [comment]
v4.5.3.10 can't run in my Debian Linux.

### Steps to reproduce
cmd run ./qBittorrent-Enhanced-Edition-x86_64.AppImage

### Log(s) & preferences file(s)
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, wayland-egl, wayland, xcb.

[1]    197167 IOT instruction  ./qBittorrent-Enhanced-Edition-x86_64.AppImage

**Comment by c0re100** [comment]
> ### qBittorrent & operating system versions
> qbittorrent:4.5.2.10 Operating system: Mac Catalina 10.15.7 (19H2026)
> 
> ### What is the problem?
> It seems that after upgrading from v4.5.2.10 to v4.5.3.10, the software is not responding. There are no error messages popping up, and the process cannot be found.Abandon support for Mac Catalina? thanks
> 
> ### Steps to reproduce
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Log(s) & preferences file(s)
> _No response_

Cause Qt6.5 dropped macOS 10.x support now :'(
https://doc.qt.io/qt-6/macos.html

Edit:
Downgraded to Qt v6.4.3, please re-download dmg file~
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-4.5.3.10/qBittorrent-Enhanced-Edition-release-4.5.3.10-macOS-universal.dmg

**Comment by c0re100** [comment]
> v4.5.3.10 can't run in my Debian Linux.
> 
> ### Steps to reproduce
> cmd run ./qBittorrent-Enhanced-Edition-x86_64.AppImage
> 
> ### Log(s) & preferences file(s)
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found. This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: minimal, offscreen, wayland-egl, wayland, xcb.
> 
> [1] 197167 IOT instruction ./qBittorrent-Enhanced-Edition-x86_64.AppImage

ping @abcfy2

**Comment by abcfy2** [comment]
> v4.5.3.10 can't run in my Debian Linux.
> 
> ### Steps to reproduce
> cmd run ./qBittorrent-Enhanced-Edition-x86_64.AppImage
> 
> ### Log(s) & preferences file(s)
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found. This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: minimal, offscreen, wayland-egl, wayland, xcb.
> 
> [1] 197167 IOT instruction ./qBittorrent-Enhanced-Edition-x86_64.AppImage

What's your debian version ?

Please show `lsb_release -a`

And also please post the result `QT_DEBUG_PLUGINS=1 ./qBittorrent-Enhanced-Edition-x86_64.AppImage`

**Comment by shenzhui007** [comment]
> > v4.5.3.10 can't run in my Debian Linux.
> > ### Steps to reproduce
> > cmd run ./qBittorrent-Enhanced-Edition-x86_64.AppImage
> > ### Log(s) & preferences file(s)
> > qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found. This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> > Available platform plugins are: minimal, offscreen, wayland-egl, wayland, xcb.
> > [1] 197167 IOT instruction ./qBittorrent-Enhanced-Edition-x86_64.AppImage
> 
> What's your debian version ?
> 
> Please show `lsb_release -a`
> 
> And also please post the result `QT_DEBUG_PLUGINS=1 ./qBittorrent-Enhanced-Edition-x86_64.AppImage`

### Result of `lsb_release -a`
```
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2023.2
Codename:       kali-rolling
```

### Result  of `QT_DEBUG_PLUGINS=1 ./qBittorrent-Enhanced-Edition-x86_64.AppImage`
```
qt.core.plugin.factoryloader: checking directory path "/tmp/.mount_qBittogKVyLm/usr/plugins/platforms" ...
qt.core.plugin.factoryloader: looking at "/tmp/.mount_qBittogKVyLm/usr/plugins/platforms/libqminimal.so"
qt.core.plugin.loader: Found metadata in lib /tmp/.mount_qBittogKVyLm/usr/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "archlevel": 1,
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("minimal")
qt.core.plugin.factoryloader: looking at "/tmp/.mount_qBittogKVyLm/usr/plugins/platforms/libqoffscreen.so"
qt.core.plugin.loader: Found metadata in lib /tmp/.mount_qBittogKVyLm/usr/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "archlevel": 1,
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("offscreen")
qt.core.plugin.factoryloader: looking at "/tmp/.mount_qBittogKVyLm/usr/plugins/platforms/libqwayland-egl.so"
qt.core.plugin.loader: Found metadata in lib /tmp/.mount_qBittogKVyLm/usr/plugins/platforms/libqwayland-egl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland-egl"
        ]
    },
    "archlevel": 1,
    "className": "QWaylandEglPlatformIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("wayland-egl")
qt.core.plugin.factoryloader: looking at "/tmp/.mount_qBittogKVyLm/usr/plugins/platforms/libqwayland-generic.so"
qt.core.plugin.loader: Found metadata in lib /tmp/.mount_qBittogKVyLm/usr/plugins/platforms/libqwayland-generic.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland"
        ]
    },
    "archlevel": 1,
    "className": "QWaylandIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("wayland")
qt.core.plugin.factoryloader: looking at "/tmp/.mount_qBittogKVyLm/usr/plugins/platforms/libqxcb.so"
qt.core.plugin.loader: Found metadata in lib /tmp/.mount_qBittogKVyLm/usr/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archlevel": 1,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("xcb")
qt.core.plugin.factoryloader: checking directory path "/tmp/.mount_qBittogKVyLm/usr/bin/platforms" ...
qt.core.library: "/tmp/.mount_qBittogKVyLm/usr/plugins/platforms/libqxcb.so" cannot load: Cannot load library /tmp/.mount_qBittogKVyLm/usr/plugins/platforms/libqxcb.so: (libxcb-cursor.so.0: cannot open shared object file: No such file or directory)
qt.core.plugin.loader: QLibraryPrivate::loadPlugin failed on "/tmp/.mount_qBittogKVyLm/usr/plugins/platforms/libqxcb.so" : "Cannot load library /tmp/.mount_qBittogKVyLm/usr/plugins/platforms/libqxcb.so: (libxcb-cursor.so.0: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, wayland-egl, wayland, xcb.

[1]    41252 IOT instruction  QT_DEBUG_PLUGINS=1 ./qBittorrent-Enhanced-Edition-x86_64.AppImage
```

**Comment by abcfy2** [comment]
@shenzhui007 Got it. The output shows you lost `libxcb-cursor.so.0` in your system, which required by some libxcb libraries.

Your OS is Kali Linux, which is Debian based system. So you can use this command to  install the lost files:

```sh
sudo apt install -y libxcb-cursor0
```
