### ISSUE TITLE
Winget runner issue

### ISSUE THREAD

**Issue by c0re100** [c0re100/qBittorrent-Enhanced-Edition#488]
ping @vedantmgoyal2009

I'm not sure what bug it is.

It looks like Winget runner found x64 InstallerUrl for x86? 
https://github.com/microsoft/winget-pkgs/pull/110157#issuecomment-1597807312
https://github.com/microsoft/winget-pkgs/pull/110157/files#diff-95ad031d149d0a52f40fb87e5f242a6bd471330be5b77033344ca844c00b03b6R19-R21

I've checked GA log, runner found qt6_x64 and x86 InstallerUrl, 
https://github.com/c0re100/qBittorrent-Enhanced-Edition/actions/runs/5314547068/jobs/9621883114#step:3:13
but the result is x86 using x64 InstallerUrl...
https://github.com/c0re100/qBittorrent-Enhanced-Edition/actions/runs/5314547068/jobs/9621883114#step:3:36

**Comment by vedantmgoyal2009** [comment]
cc @russellbanks, another bug of installer mismatch
