### ISSUE TITLE
调用api无法删除种子

### ISSUE THREAD

**Issue by soulmatelh** [c0re100/qBittorrent-Enhanced-Edition#492]
### qBittorrent & operating system versions

qBittorrent：qbittorrent-enhanced-nox_x86_64-linux-musl_static
操作系统：Debian11

### What is the problem?

调用api无法删除种子和下载的数据

### Steps to reproduce

第一步：curl -i --header "Referer: ${qb_web_url}" --data "username=${qb_username}&password=${qb_password}" "${qb_web_url}/api/v2/auth/login"
第二步： 我通过webui获取任意任务hash值
第三步：curl "${qb_web_url}/api/v2/torrents/delete?hashes=$1&deleteFiles=true" --cookie ${cookie}

**Comment by c0re100** [comment]
https://github.com/qbittorrent/qBittorrent/issues/18097
