### ISSUE TITLE
能不能不屏蔽迅雷7，之屏蔽xl0012,或者设置里加一个选项也行啊

### ISSUE THREAD

**Issue by 1608637229** [c0re100/qBittorrent-Enhanced-Edition#5]
**Please provide the following information**

### qBittorrent version and Operating System
(type here)

### If on linux, libtorrent and Qt version
(type here)

### What is the problem
(type here)

### What is the expected behavior
(type here)

### Steps to reproduce
(type here)

### Extra info(if any)
(type here)

对于我来说，经过我观察。xl0012这个标识的几乎一定是吸血，但是有不少的迅雷7和迅雷极速版是会上传的，所以我希望可以只屏蔽xl0012这个就好了。

**Comment by EuropeanWithSSR** [comment]
![image](https://user-images.githubusercontent.com/39738950/56878421-a2bd7d00-6a86-11e9-9ea6-035498fa6858.png)

**Comment by DarkAge2018** [comment]
这样子做太极端了，完全一刀切，XL0010有非常不错的上传量，甚至0012也有上传，完全屏蔽掉迅雷并不适合当下的中国用户。应该是设置成像比特彗星那样子，在某一段时间内检测上传，没有上传再屏蔽掉，这才是对所有BT客户端一视同仁的做法。
![XL0012](https://user-images.githubusercontent.com/4428897/71723031-17428a00-2e66-11ea-8c14-d6aa76125c5b.png)

**Comment by SeaHOH** [comment]
我现在的做法是，12345 和 15000 端口这种不可能回传的直接屏蔽，其它迅雷就计算上传/下载比例，超过一定限度才屏蔽。
https://github.com/SeaHOH/ban-peers/blob/4f82f3ec741335d1fcd58ef543d2f4727c15c3d8/ban_peers.py#L460

**Comment by wdfx** [comment]
想来最好的办法就是进迅雷直接举报资源，，，，以毒攻毒~~~~~~~~

**Comment by Ken-n** [comment]
> 我现在的做法是，12345 和 15000 端口这种不可能回传的直接屏蔽，其它迅雷就计算上传/下载比例，超过一定限度才屏蔽。那种零进度也直接屏蔽，下载完成后做种也不会传给迅雷，就是要反吸它血。 https://github.com/SeaHOH/ban-peers/blob/4f82f3ec741335d1fcd58ef543d2f4727c15c3d8/ban_peers.py#L460

请问怎么使用您的方法呢？我是代码小白

**Comment by SeaHOH** [comment]
@Ken-n 这需要你把客户端换成 μTorrent，一般用顺手了没啥大毛病的话应该不会换，然后按照[说明](https://github.com/SeaHOH/ban-peers/blob/master/README_zh.md)安装使用即可。不过我现在使用的是 Tixati，后续估计不会再继续维护。
