### ISSUE TITLE
好lag

### ISSUE THREAD

**Issue by hellelan** [c0re100/qBittorrent-Enhanced-Edition#50]
**Please provide the following information**

### qBittorrent version and Operating System
qBv4.1.7.1 windows 10 Pro 1809

### If on linux, libtorrent and Qt version
(type here)

### What is the problem
做種一多就lag，而家有184 seeds
好lag

### What is the expected behavior
唔應該lag
### Steps to reproduce
(type here)

**Comment by c0re100** [comment]
建議唔好將堆seed同OS放埋一齊
放落另一隻disk到
若果184粒熱門seed 邊隻hdd都會慢死........
真係有呢個需求嘅建議轉用SSD 或者 唔好一次過seed咁多粒
