### ISSUE TITLE
No Linux x86_64 asset for v4.5.5.10

### ISSUE THREAD

**Issue by alexdns1** [c0re100/qBittorrent-Enhanced-Edition#504]
### qBittorrent & operating system versions

--

### What is the problem?

Linux x86_64 asset is missing for v4.5.5.10
Probably the same issue as https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/301

**Comment by c0re100** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-4.5.5.10/qBittorrent-Enhanced-Edition-x86_64.AppImage
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-4.5.5.10/qbittorrent-enhanced-nox_x86_64-linux-musl_static.zip

**Comment by alexdns1** [comment]
hey thanks !
