### ISSUE TITLE
qBittorrent Enhanced Edition v4.6.0.10 icon not show 

### ISSUE THREAD

**Issue by cappelikan** [c0re100/qBittorrent-Enhanced-Edition#512]
### qBittorrent & operating system versions

qBittorrent: Enhanced Edition v4.6.0.10 x64
Operation system: KDE Neon 5.27.9   
Qt: 5.15.11
libtorrent-rasterbar: 2.0.9.0

### What is the problem?

Not show icon in system tray KDE
![Screenshot_20231105_065216](https://github.com/c0re100/qBittorrent-Enhanced-Edition/assets/7409626/c91d17a0-be58-4a72-8400-e3d9fd8e8684)

**Comment by c0re100** [comment]
https://github.com/qbittorrent/qBittorrent/pull/19815

Should be fixed in the next version.
