### ISSUE TITLE
Version for Windows versions older than 10

### ISSUE THREAD

**Issue by zooool** [c0re100/qBittorrent-Enhanced-Edition#523]
### Suggestion

Make this version or a new version that supports Windows <10

### Use case

Many people still use Windows 7, 8, 8.1 etc. Since qBittorrent no longer supports these operating systems it would be cool if you made this version work on those OSes or a new version that works on those OSes.

**Comment by c0re100** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/tag/release-4.6.0.10

**Comment by zooool** [comment]
By the way, oddly enough v4.6.2.10 installs and works just fine too.
