### ISSUE TITLE
Suspected Xunlei / PikPak offline download server `libtorrent/2.0.7.0`

### ISSUE THREAD

**Issue by FrzMtrsprt** [c0re100/qBittorrent-Enhanced-Edition#526]
### qBittorrent & operating system versions

qBittorent v4.6.2.10
Operating System: Windows 11 Pro 23H2
Qt: 6.4.3
libtorrent-rasterbar: 1.2.19.0

### What is the problem?

According to discussions on the internet (see discussions on [itzmx](https://bbs.itzmx.com/forum.php?mod=viewthread&tid=102666) and [cometbbs](https://www.cometbbs.com/t/80624)), Xunlei and PikPak has updated their offline download server to using libtorrent 2.0.7.0.

These clients have peer ID `-LT2070-`, client name `libtorrent/2.0.7.0`, and their ports range from `6881` to `6884` (there might be more, but I'm not sure).

They keep their upload speed under 10KB/s, but they keep downloading from others.

![image](https://github.com/c0re100/qBittorrent-Enhanced-Edition/assets/15852717/25ff8f56-9d42-45aa-aec1-1887236b129b)

Note that in my screenshot, some of the libtorrent 2.0.7.0 clients are from Netherlands. I think these are PikPak's offline download server, since PikPak's server is located in Netherlands (see [reddit](https://www.reddit.com/r/androidapps/comments/11zbdul/can_i_use_pikpak_a_10t_offline_network_disk_to)), and they also seem to use Xunlei's offline downloading SDK (see [here](https://www.cometbbs.com/t/80624/4))

I also checked their download history on https://iknowwhatyoudownload.com (see [result for 120.72.33.132](https://iknowwhatyoudownload.com/en/peer/?ip=120.72.33.132) and [result for 218.91.199.15](https://iknowwhatyoudownload.com/en/peer/?ip=218.91.199.15)), it show that they download hundreds of torrents every day. This further proves that they are offline download servers. In fact, if you search `libtorrent/2.0.7.0 site:iknowwhatyoudownload.com` on Google, you can see many more similar results.

### Steps to reproduce

1. Download `6a7200535fee91cef8887c931d4f60ffa509e7b3` with qBittorrent Enhanced Edition
2. Observe the peer list

**Comment by c0re100** [comment]
You can enable `Auto ban Unknown Peer from China`, it should be auto ban libtorrent/2.0.7.0 peer which come from Netherlands or China.
![image](https://github.com/c0re100/qBittorrent-Enhanced-Edition/assets/5726473/4277efcf-c20e-4dbd-aa26-774fd867ae84)
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_6_x/src/base/bittorrent/peer_blacklist.hpp#L29-L41

**Comment by FrzMtrsprt** [comment]
I see, I thought `Auto ban Unknown Peer from China` bans all of the non white listed peers from China. I think this option can have a better name. Anyway, thanks for clarifying!

**Comment by qianbinbin** [comment]
Is there any human (rather than a server) using libtorrent?

I was writing a Shell script for Transmission, but it's not easy to implement features like qee, so I was wondering what if I simply block all of libtorrent.

libtorrent 这个客户端是否有人类用户使用？我给 Transmission 写的 Shell 脚本，打算干脆屏蔽所有的 libtorrent
