### ISSUE TITLE
请求大伙帮助编译一个支持arm平台的版本.

### ISSUE THREAD

**Issue by RoeltaNcRave** [c0re100/qBittorrent-Enhanced-Edition#53]
目前用的n1盒子.刷的小钢炮系统.上面带有传统版的qBittorrent,在下载一些在国内也比较热门的资源的时候,总是会遇到大量的吸血迅雷,那些吸血迅雷完成度永远都是百分之0,永远都是在给它们上传,而没有一点下载.
想在盒子上也用上qbittorrentEE,但是自己学艺不精,尝试编译,总是遇到重重困难.
希望有人看到可以帮忙编译一个arm平台的版本.
然后小弟再接受,尝试去做一个docker.让广大盒子用户也能用用上屏蔽吸血客户端的版本.
谢谢

**Comment by XCNova** [comment]
在这里提供一个arm打包思路，我之前在用debian时用过，有点不靠谱就是了
可以用archlinux aur安装后将二进制和所有连接库打包，拷贝到其他系统上用
运行前记得改LD_PRELOAD
搜集动态链接库可以用附件里的脚本完成 (脚本是CSDN上找的。
[collectso.txt](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/3639414/collectso.txt)

**Comment by poplite** [comment]
我维护的 Ubuntu PPA 源有提供 armhf / arm64 包。https://github.com/c0re100/qBittorrent-Enhanced-Edition#repository

**Comment by RoeltaNcRave** [comment]
https://github.com/gshang2017/docker/issues/7
在大佬们的帮助下,qbee有支持arm的docker了

docker地址
https://hub.docker.com/r/johngong/qbittorrent

让我们在各位大佬们的帮助下
愉快的用上qbee共建健康的p2p环境吧
