### ISSUE TITLE
Requests Add a blocking client

### ISSUE THREAD

**Issue by NovaOPCJ** [c0re100/qBittorrent-Enhanced-Edition#533]
### Suggestion

Request to add a blocking client
-GT0003- github.com/anacrolix/torrent
-DT0001- dt/torrent
Behavior reference:
https://www.bilibili.com/read/cv32717071/

**Comment by maidmeow4** [comment]
See also: 
https://github.com/anacrolix/torrent/discussions/891

**Comment by c0re100** [comment]
Only dt/torrent and Taipei-torrent was added, it hurts legitimate client if I decided to ban GT0003.
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/tag/release-4.6.4.10
