### ISSUE TITLE
这是什么新的客户端疯狂的吸血。

### ISSUE THREAD

**Issue by snfcx** [c0re100/qBittorrent-Enhanced-Edition#540]
### Suggestion

Rt看客户端也很正常，不像之前的乱七八糟的客户端。
ip都是同一段，端口也都一样。
有没有办法屏蔽？

### Extra info/examples/attachments

![image](https://github.com/c0re100/qBittorrent-Enhanced-Edition/assets/55078254/6a51c2f1-c8da-448a-b2ea-bcbd1b13fbdc)

**Comment by lzhzh1** [comment]
这是伪装成比特彗星的吸血客户端，与HP0001、DT0001等行为相同，恶意重复下载资源，占用上传宽带。
解决方法：
1.设置qBEE过滤规则，屏蔽相关ip段，及标识为HP0001的客户端。（不建议：屏蔽BC0204）
2.利用相关工具屏蔽。如[PeerBanHelper](https://github.com/Ghost-chu/PeerBanHelper)
相关建议：
在社群持续跟踪恶意吸血客户端的动向。链接
[qBitTorrent users seeing infinite requests](https://github.com/anacrolix/torrent/discussions/891)
[Damn☆You的动态-哔哩哔哩](https://t.bilibili.com/886509991839662137)

**Comment by wyylzy** [comment]
打开目录C:\Users\用户名\AppData\Local\qBittorrent\
在此文件夹下新建文本文档peer_blacklist.txt
格式为Peer ID 客户端
![截屏2024-04-26 19 25 15](https://github.com/c0re100/qBittorrent-Enhanced-Edition/assets/61929738/34b5b574-6926-49ae-8e9b-b86449fecd75)
全部填好以后保存,重启QBEE就可以过滤吸血客户端了.

**Comment by yeezylife** [comment]
无奈把bitcomet这个版本给屏蔽了 就这样吧
