### ISSUE TITLE
被xunlei 0.0.1.8 XL0018吸血了

### ISSUE THREAD

**Issue by wyylzy** [c0re100/qBittorrent-Enhanced-Edition#541]
### qBittorrent & operating system versions

设置已开反吸血+屏蔽未知来自中国IP
![截屏2024-04-18 01 03 02](https://github.com/c0re100/qBittorrent-Enhanced-Edition/assets/61929738/811244e0-dcfa-4614-875d-94c123b621cf)

### What is the problem?

设置已开反吸血+屏蔽未知来自中国IP
![截屏2024-04-18 01 03 02](https://github.com/c0re100/qBittorrent-Enhanced-Edition/assets/61929738/811244e0-dcfa-4614-875d-94c123b621cf)

**Comment by wyylzy** [comment]
屏蔽一个xunlei 0.0.1.8,马上又冒出来另一个IP地址的相同客户端,怎么办啊,上传都被这些吸血雷占完了,我不可能总守在电脑前面啊

**Comment by qpzr** [comment]
轮到迅雷了，哈哈。你应该去迅雷论坛说的，让迅雷官方出面，送那帮坏人去踩缝纫机吧

**Comment by c0re100** [comment]
很明顯.........該種子是私有的
