### ISSUE TITLE
无法在win11通知中心显示下载完成通知

### ISSUE THREAD

**Issue by si255210** [c0re100/qBittorrent-Enhanced-Edition#543]
### qBittorrent & operating system versions

qBittorrent: 4.5.5.10 x64
Operating system: Windows 11 23H2

### What is the problem?

![image](https://github.com/c0re100/qBittorrent-Enhanced-Edition/assets/121077830/357d5c5f-0144-4148-868a-ae6ece657a1f)
通知横幅能用，但是通知中心会随着通知横幅自动消失。

**Comment by FrzMtrsprt** [comment]
这个问题应该去原版qBittorrent反馈，通知和增强版没有关系
