### ISSUE TITLE
是否有选项可以设置只允许打开一个qBittorrent客户端？

### ISSUE THREAD

**Issue by shikkoku** [c0re100/qBittorrent-Enhanced-Edition#55]
**Please provide the following information**

### qBittorrent version and Operating System
qBittorrent v4.1.8.2 Enhanced Edition 
Windows 10 Build 18363

### What is the problem
当我已经运行qBittorrent时，每当打开一个种子文件会重新启动一个新的qBittorrent客户端（多开状态）会使得我正在下载的文件在新窗口中被重新recheck。

https://github.com/c0re100/qBittorrent-Enhanced-Edition/pull/54

**Comment by c0re100** [comment]
> **Please provide the following information**
> 
> ### qBittorrent version and Operating System
> qBittorrent v4.1.8.2 Enhanced Edition
> Windows 10 Build 18363
> 
> ### What is the problem
> 当我已经运行qBittorrent时，每当打开一个种子文件会重新启动一个新的qBittorrent客户端（多开状态）会使得我正在下载的文件在新窗口中被重新recheck。

如果可以，請先重新安裝4.1.8.1回到舊版繼續使用，抱歉。

另外，Windows的多開問題已修正，而*nix仍需多一點時間進行修正工作。
如無意外，4.1.8.3會在短期內發佈。

***[Windows用家亦可以暫時使用此Alpha版本以繼續使用多開功能](https://drive.google.com/open?id=1qKXxUTft1MGx5sMLdjE3FWDXh2YJwrHV)***
