### ISSUE TITLE
Github Actions workflow broken

### ISSUE THREAD

**Issue by c0re100** [c0re100/qBittorrent-Enhanced-Edition#559]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/actions/runs/9522695106

ping @abcfy2

**Comment by KagurazakaNyaa** [comment]
ref: https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt6_671/Updates.xml

maybe need change `gcc_64` to `linux_gcc_64` in
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/c9f1c9a57708a5472762a8dd6b1b33f641262d7e/.github/workflows/cross_build.sh#L275

**Comment by jothi-prasath** [comment]
oh thats why there was no linux builds

![image](https://github.com/c0re100/qBittorrent-Enhanced-Edition/assets/64248628/c03bb600-8610-4718-807e-db78ce7853f9)

**Comment by abcfy2** [comment]
Got it. I'll check my script. Wait.
