### ISSUE TITLE
可以自定义 Tracker list 订阅 URL 吗？

### ISSUE THREAD

**Issue by XIU2** [c0re100/qBittorrent-Enhanced-Edition#56]
### What is the problem
可以自定义 Tracker list 订阅 URL 吗？

### What is the expected behavior
自定义 Tracker list 订阅 URL。
在其他地方看到这个软件里的 *[Automatically update public trackers list]* 选项，以为可以设置 Tracker list 订阅 URL，结果发现是内置的 URL，希望可以支持自定义！

**Comment by DavidpYau** [comment]
+1
当时看到新功能以为是自定义url，可惜哦！希望能出自定义吧，这样就更好了！

**Comment by NJCCJohnWason** [comment]
+1
自定义URL最好了

**Comment by c0re100** [comment]
4.1.9.3已支援自訂tracker list url
