### ISSUE TITLE
关于v4.6.4.10版本中的新功能疑问

### ISSUE THREAD

**Issue by marswow** [c0re100/qBittorrent-Enhanced-Edition#564]
### Suggestion

qBittorrent Enhanced Edition v4.6.4.10的更新日志
Changelog

Official Update (v4.6.4)
[Update client blacklist](https://github.com/c0re100/qBittorrent-Enhanced-Edition/commit/8a23c0d6464145f497e4d2018d43a2d8d745b239)
Auto ban dt/torrent and Taipei-torrent (from China)
Just a cat and mouse game :|
-------------------------------------------------------------------
其中：
“Auto ban dt/torrent and Taipei-torrent (from China)
Just a cat and mouse game :|”
这个我通过机翻得到的答案是：
“自动禁止 dt/torrent 和 Taipei-torrent（来自中国）
只是一场猫捉老鼠的游戏:|”
请问这个是干嘛？
更新后影响我在国内正常上传和下载使用吗？

**Comment by f1ume** [comment]
翻前面issue #537 
更多讨论在https://github.com/anacrolix/torrent/discussions/891

**Comment by xixky** [comment]
跑pcdn的人，用修改过的bt软件刷下载流量，防止宽带被封

**Comment by GoogleBeEvil** [comment]
所以这个功能开启后  啥也不用设置，就能自动拉取pbh的恶意ip列表 ，动态封禁？

**Comment by Zerorigin** [comment]
> 所以这个功能开启后 啥也不用设置，就能自动拉取pbh的恶意ip列表 ，动态封禁？

两码事，这个功能只能自动封禁内置的特定 PeerID/Client Name 的 Client，建议配合 PeerBanHelper + BTN 网络使用。
