### ISSUE TITLE
I don't know how to name this issue. please help me edit this. 

### ISSUE THREAD

**Issue by starobots** [c0re100/qBittorrent-Enhanced-Edition#567]
### Suggestion

![image](https://github.com/user-attachments/assets/44816f11-ab7b-4438-a8b1-cb73ae99883c)
![image](https://github.com/user-attachments/assets/e6f931cc-7aa9-4119-9544-768f7fdafafa)
IP is located at Hubei, China. 
The size of torrent is only about 2.3 GiB, and these 4 peers are always connecting, leeching and shown as 0% progress.
I know I can ban these 4 peers permanently, but what are the clients of these 4 peers? What should I do?
These 4 peers cost me over 200 GiB upload in weeks and nearly 10% of total upload bandwidth. : / 
I just stop seeding this torrent and waiting the solution. 

### Use case

win10, qbit Enhanced v4.6.10

**Comment by c0re100** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/537
