### ISSUE TITLE
发现一个 漏网之鱼，但不确定是否还有

### ISSUE THREAD

**Issue by marswow** [c0re100/qBittorrent-Enhanced-Edition#569]
### qBittorrent & operating system versions

![屏幕截图 2024-07-19 225107](https://github.com/user-attachments/assets/a3a92134-2cba-4dbb-9cef-c6ed0e1764e3)

### What is the problem?

该IP为：180.97.209.32:25094
进度始终为1%与上图相比

![屏幕截图 2024-07-19 230324](https://github.com/user-attachments/assets/ed0013c6-7be5-4d28-a6b2-df1cb890dad8)

**Comment by c0re100** [comment]
下次更新
https://github.com/c0re100/qBittorrent-Enhanced-Edition/commit/3fdf3140dc53f4def5423f42eb6aab0163d82bad

**Comment by marswow** [comment]
> 下次更新 [3fdf314](https://github.com/c0re100/qBittorrent-Enhanced-Edition/commit/3fdf3140dc53f4def5423f42eb6aab0163d82bad)

58.216.63.0     - 58.216.63.255  ,   0 , A2-1-33-
这个规则添加一个，不知道是度还是鸟的。这客户端都是相似的IP，相同的aria2/1.33.1版本peer ID都是A2-1-33-
84.145.230.131:52102
另外上面这个德国的IP和这aria2的客户端特征相似，但不确定是不是检测用的。我这边对其上传速度很少就没添加进规则
新的IP：
218.92.139.139:28491  客户端 Taipei-Torrent dev
218.92.139.137:22634  客户端 Taipei-Torrent dev
