### ISSUE TITLE
程序启动多个界面

### ISSUE THREAD

**Issue by lleeopen** [c0re100/qBittorrent-Enhanced-Edition#57]
4.1.8之后的版本，每双击打开程序就会出现一个程序界面，导致会出现多个程序界面，之前的版本不是这样的，只会启动一个程序界面，有没有什么选项可以关闭啊，只启动一个程序界面啊
![QQ图片20191019123826](https://user-images.githubusercontent.com/35162785/67137845-ff4b6900-f26d-11e9-8789-7dfc2eab3f63.png)

**Comment by c0re100** [comment]
> 4.1.8之后的版本，每双击打开程序就会出现一个程序界面，导致会出现多个程序界面，之前的版本不是这样的，只会启动一个程序界面，有没有什么选项可以关闭啊，只启动一个程序界面啊
> ![QQ图片20191019123826](https://user-images.githubusercontent.com/35162785/67137845-ff4b6900-f26d-11e9-8789-7dfc2eab3f63.png)

https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/55#issuecomment-542087546

**Comment by shikkoku** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/pull/54 (pr)
