### ISSUE TITLE
archlinux下好像4.6.5.10开始无法连接任何用户，无任何上下传。DHT有连接数，网络也是绿色联机状态

### ISSUE THREAD

**Issue by liuyunyue** [c0re100/qBittorrent-Enhanced-Edition#575]
### qBittorrent & operating system versions

archlinux
4.6.5.10

### What is the problem?

无法连接任何用户，无任何上下传。DHT有连接数，网络也是绿色联机状态

**Comment by Izofeu** [comment]
I'm experiencing the same issue. 4.6.4.10 works fine.

**Comment by LockRim** [comment]
一样
从 archlinuxcn 源的 qbittorrent-enhanced-git-4.6.5.10.r3.g3fdf3140d-2 开始出现该问题
应该是 3fdf3140d 
先使用 downgrade 回退版本吧

**Comment by vincentaxhe** [comment]
我的也是

**Comment by servimo** [comment]
When trying to connect to AUR: "curl: Failed to connect to aur.archlinux.org port 443 after 919 ms: Could not connect to server". Maybe it's just a wrong config of my internet, but happens after I start qbittorrent-enhanced.
