### ISSUE TITLE
qbittorrent: symbol lookup error: qbittorrent: undefined symbol

### ISSUE THREAD

**Issue by spirillen** [c0re100/qBittorrent-Enhanced-Edition#585]
### qBittorrent & operating system versions

qBittorrent version: v4.6.5.10-1ppa1~noble1
Libtorrent version: 2.0.11.0
Qt version: 5?
Boost version: 1.74.0?
OpenSSL version: 3.0.13
zlib version: 1.3?
OS version: Ubuntu 24.04 LTS 6.8.0-40-generic x86_64

### What is the problem?

When I tried to start the installation I see this error in my konsole

```bash
qbittorrent: symbol lookup error: qbittorrent: undefined symbol: _ZN10libtorrent17write_resume_dataERKNS_18add_torrent_paramsE
```

### Steps to reproduce

1. Install PPA `sudo add-apt-repository ppa:poplite/qbittorrent-enhanced -y`
2. `sudo apt install qbittorrent-enhanced`
3. execute `qbittorrent`

### Additional context

This issue could be related to https://github.com/qbittorrent/qBittorrent/issues/21221

### Log(s) & preferences file(s)

None, tried searching with grep, no luck

**Comment by poplite** [comment]
> Libtorrent version: 2.0.11.0

What about downgrading it to 2.0.10? 

It seems libtorrent-rasterbar library on your system can't provide some symbols required by qbittorrent-enhanced, since the version of the library you are using is different from the one that qbittorrent-enhanced was built with on Launchpad (Noble PPA now uses v2.0.10 from official repository). If you want to use qbittorrent-enhanced with your own library, you need to compile it manually following qBittorrent's [Compilation Guide](https://github.com/qbittorrent/qBittorrent/wiki/Compilation-Debian-and-Ubuntu).

**Comment by spirillen** [comment]
Well I don't see 2.10 besides from `libtorrent-rasterbar2.0t64` and that is the one used in the other issue from above. so same issue

```
libtorrent-dev/noble 0.13.8-2.1build2 amd64
libtorrent-rasterbar-dev/noble 2.0.11.git20240821.2ab8fedabb-1ppa1~24.04 amd64
libtorrent-rasterbar-doc/noble,noble 2.0.11.git20240821.2ab8fedabb-1ppa1~24.04 all
libtorrent-rasterbar2.0/noble,now 2.0.11.git20240821.2ab8fedabb-1ppa1~24.04 amd64 [installed,automatic]
libtorrent-rasterbar2.0t64/noble 2.0.10-1.1build2 amd64
libtorrent21t64/noble 0.13.8-2.1build2 amd64
```

**Comment by spirillen** [comment]
Followup, after a good nights sleep, I did try to downgrade `libtorrent-rasterbar2.0/noble,now 2.0.11.git20240821.2ab8fedabb-1ppa1~24.04 amd64` to `libtorrent-rasterbar2.0t64/noble 2.0.10-1.1build2` and then install `qbittorrent-enhanced/noble 4.6.5.10-1ppa1~noble1` and that worked. Leaving the following line for other that would stumble on this issue


```bash
sudo apt install 0y qbittorrent-enhanced libtorrent-rasterbar2.0t64
```

```bash
sudo apt remove -y libtorrent-rasterbar2.0
```

```bash
sudo apt autoremove -y
```
