### ISSUE TITLE
提问，将下载的文件重命名后如何继续做种？/Question, how do I continue to do seeding after renaming a downloaded file?

### ISSUE THREAD

**Issue by NuclearSnack** [c0re100/qBittorrent-Enhanced-Edition#589]
### Suggestion

希望能有下载前后重命名、重命名后重新对应之类的功能

**Comment by starobots** [comment]
用qbt软件里的content - rename改名就没事。外面的就不行了。

**Comment by NingMYZZ** [comment]
> 用qbt软件里的content - rename改名就没事。外面的就不行了。

这样改了之后，只是qbittorrent 显示改了，实际文件夹并没有改
