### ISSUE TITLE
Debian使用软件源安装的问题

### ISSUE THREAD

**Issue by jianfei96** [c0re100/qBittorrent-Enhanced-Edition#59]
**Please provide the following information**

### qBittorrent version and Operating System
4.1.8，Debian 10

### If on linux, libtorrent and Qt version
正是libtorrent依赖出了问题

### What is the problem
无法通过debiancn源安装，不过testing版的Debian可以安装
应该是依赖问题
软件源：deb https://repo.debiancn.org/ buster main

The following packages have unmet dependencies:
 qbittorrent-enhanced-nox : Depends: libtorrent-rasterbar9 (>= 1.1.13) but 1.1.11-2 is to be installed
E: Unable to correct problems, you have held broken packages.

### What is the expected behavior
不知道该去维护者那里提问还是...但维护者也没qbt的项目
总之修一下比较好吧

**Comment by abcfy2** [comment]
我提交了一个PR: #58 添加AppImage构建，欢迎测试。

**Comment by anadano** [comment]
“desktop集成
关联支持
自动更新支持”
大佬啊，我是server用的，用的是nox版，带webui的那个。

**Comment by abcfy2** [comment]
哦，AppImage还是比较适合简单的图形化程序，对于service就不如软件包好用了，也没法打包systemd脚本。最多也就只能编译一个bundle过的二进制可执行程序，systemd脚本什么的还是得自己手工写，也不比自己编译省多少事了

**Comment by anadano** [comment]
emmm所以我决定把Debian升级到testing，就没问题了

**Comment by abcfy2** [comment]
做server用你用debian testing？

**Comment by anadano** [comment]
我也很绝望
最新的稳定版Debian10都安不上我怎么办，所以我想着是维护者编译的时候没考虑依赖问题吧
不过Debian的testing稳定性还好，unstable才是“喜欢刺激和挑战的人士”用的版本（官方钦定

**Comment by abcfy2** [comment]
你说反了吧，testing才是最不稳定的，其次才会进入unstable/sid，最后进入stable然后LTS

**Comment by anadano** [comment]
unstable应该是最不稳定的
https://www.debian.org/releases/

**Comment by abcfy2** [comment]
看来是我记错了。我基本没用过debian testing，平时server和个人使用Ubuntu LTS，Ubuntu都是基于当年Debian sid版本fork的。其次用Debian sid，偶尔需要测试最新软件包，也会经常使用debian sid

**Comment by anadano** [comment]
sid那是真的崩起来分分钟...我就试过一次
不管找什么软件PPA源都好多，我也想换Ubuntu了

**Comment by abcfy2** [comment]
换Ubuntu吧。之前Ubuntu被RH党抨击支持时间短，但是从18.04开始，LTS版本也维护10年了，和RHEL持平。而且Ubuntu还有do-release-upgrade跨版本升级方案，我的产品服务器维护很多年，从12.04一路升级到18.04.

Debian的LTS版本只维护三年: https://wiki.debian.org/LTS 相比Ubuntu时间太短了。服务器还是用Ubuntu Server LTS

**Comment by anadano** [comment]
哦哦！不过服务一旦跑起来，一堆配置太麻烦就很难换系统了。
Debian的维护问题不大，我都用testing源了还在乎维护十年吗哈哈哈
testing版的Debian可以直接当滚动发行版用的，什么时候滚死了再换（

**Comment by WordlessEcho** [comment]
**软件包会随着时间推移更新，请注意版本**

手动下载安装解决依赖就好了，一共三个依赖问题，按从上往下的顺序是：
1. gcc-9-base (= 9.2.1-25)
2. libstdc++6 (>= 9)
3. libtorrent-rasterbar9 (>= 1.1.13)

然后查Debian软件包网站发现，bullseye下的libtorrent-rasterbar9是1.1.13-1.1，按着依赖一个个摸过去
只需要在机器上手动下载软件包（速度太慢可以使用镜像）：
```shell
mkdir /tmp/qBittorrent-enhanced-depends/ && cd /tmp/qBittorrent-enhanced-depends/
wget http://http.us.debian.org/debian/pool/main/g/gcc-9/gcc-9-base_9.2.1-25_amd64.deb
wget http://http.us.debian.org/debian/pool/main/g/gcc-9/libstdc++6_9.2.1-25_amd64.deb
wget http://http.us.debian.org/debian/pool/main/libt/libtorrent-rasterbar/libtorrent-rasterbar9_1.1.13-1.1+b1_amd64.deb
```
然后安装：
```shell
apt install ./*.deb
```

**Comment by WordlessEcho** [comment]
现在正在testing的bullseye有1.1.13版本的libtorrent-rasterbar9
那么，直接添加testing源并设置优先级为400，这样就可以在需要时安装testing的软件包

先新建`/etc/apt/preferences.d/testing.pref`，写入如下内容：
```pref
Package: *
Pin: release a=testing
Pin-Priority: 400
```

再复制一份`/etc/apt/sources.list`到`/etc/apt/sources.list.d/`，并命名为`testing.list`，然后将原先的版本名（如stretch、 buster或stable）改为testing

再安装测试版的libtorrent-rasterbar9：
```shell
apt update && apt install libtorrent-rasterbar9/testing
```

 最后安装qBittorrent-Enhanced-Edition（此处为nox版，根据需要替换）：
```shell
sudo apt install qbittorrent-enhanced-nox
```

**Comment by Kolcha** [comment]
use my repo, it provides required libtorrent package alongside qBittorrent

release: https://software.opensuse.org//download.html?project=home%3Anikoneko%3Atest&package=qbittorrent-enhanced
nightly: https://software.opensuse.org//download.html?project=home%3Anikoneko%3Aqbittorrent-nightly&package=qbittorrent-enhanced

nightly builds are available only for Debian Testing and Debian Unstable
release builds are also available for Debian and Raspbian 10
feel free to ask me for builds for any other architectures rather than amd64 (x86_64)

the same links are also in README on main page

see details here https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/166

@c0re100 , maybe it is worth to close this issue
