### ISSUE TITLE
两个不同IP段下的数十个IP的peer在连接不同的种子。

### ISSUE THREAD

**Issue by starobots** [c0re100/qBittorrent-Enhanced-Edition#591]
一个IP段是58.241.88.x，另一个是36.250.241.x，这两个ip段几乎同时有十几个不同的IP在连接不同的种子。
客户端ID都是qb466，很多，隔一会儿就又出现新的不同IP，手动封封不完。
导致几乎所有的种子都有上传，上传倍数约为0.3到0.5之后自动切断，然后qtb软件耗尽所有内存（物理内存20gb虚拟内存20gb）就爆了。估算了一下，基本上传流量有大概一半是到这两个ip段的客户端。

**Comment by Z2d4383rX35** [comment]
被吸血了呗
https://github.com/PBH-BTN/BTN-Collected-Rules/blob/9a5fb88308d30e38f9da4ccc84a0489954b3eea9/combine/all.txt#L265
https://github.com/PBH-BTN/BTN-Collected-Rules/blob/9a5fb88308d30e38f9da4ccc84a0489954b3eea9/combine/all.txt#L239

详见https://docs.qq.com/doc/DQnJBTGJjSFZBR2JW

刚提的 `https://github.com/qbittorrent/qBittorrent/issues/21310`建议能获取在线ip封禁列表并自动更新，有兴趣来捧个场(虽然我感觉还不如提到这边，原版那边多半会无视)
