### ISSUE TITLE
'peer_blacklist.txt' not working in portable mode.

### ISSUE THREAD

**Issue by katyurua** [c0re100/qBittorrent-Enhanced-Edition#595]
### qBittorrent & operating system versions

qBittorrent: 4.6.6.10 x64
Operating system: Windows server 2019 latest update
Qt: 6.4.3
libtorrent-rasterbar: 1.2.19

### What is the problem?

'peer_blacklist.txt' not working in portable mode.
log 
```
2024/9/18 15:21 - 'peer_blacklist.txt' doesn't exist. The corresponding filter is disabled.
```

### Steps to reproduce

1. Creat   'profile\qBittorrent\peer_blacklist.txt' (utf-8)
2. run qbit
3. get log output ```  'peer_blacklist.txt' doesn't exist. The corresponding filter is disabled. ```

**Comment by qpzr** [comment]
![IMG_20240919_060754.jpg](https://github.com/user-attachments/assets/bb06f434-edbe-4b6e-909d-3a00b44769bf)

你懂的

**Comment by katyurua** [comment]
> ![IMG_20240919_060754.jpg](https://private-user-images.githubusercontent.com/58745620/368758783-bb06f434-edbe-4b6e-909d-3a00b44769bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDU2ODUsIm5iZiI6MTcyNjcwNTM4NSwicGF0aCI6Ii81ODc0NTYyMC8zNjg3NTg3ODMtYmIwNmY0MzQtZWRiZS00YjZlLTkwOWQtM2EwMGI0NDc2OWJmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDAwMjMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiY2MzOWZlNzAzNjRmNjU4MzIwNzk5ZDgwYzkyY2M5ZDRiOTVmNjZkOWY2OTcyZDExY2E0MGI3NTEzNDk1ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DQ1R9xp7L55PmA4EQn9aRvgFYeuaF9MwqTV3Ckc-e10)
> 
> 你懂的

it works. thanks
