### ISSUE TITLE
一个名叫deluge的客户端疯狂吸血,一个300m的种子一天吸了我130G,希望有大佬查查是不是新的迅雷

### ISSUE THREAD

**Issue by xiaojiejieouo** [c0re100/qBittorrent-Enhanced-Edition#597]
### Extra info/examples/attachments

![image](https://github.com/user-attachments/assets/a83b59a0-2354-46dd-a155-883b872532a5)
x这个是ip地址

**Comment by c0re100** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/discussions/582
