### ISSUE TITLE
能新增一个获取最新trackerslist的功能嘛?

### ISSUE THREAD

**Issue by 23233** [c0re100/qBittorrent-Enhanced-Edition#6]
[https://github.com/ngosang/trackerslist](每日更新的trackerslist)

**可以新增一下 打开软件去获取最新的trackerslist 或者有一个开关去更新一下吗?**

**Comment by c0re100** [comment]
不好意思, 目前分身不暇
這個可能要到七月底才會處理...

**Comment by Joyace** [comment]
强烈建议这个功能

**Comment by c0re100** [comment]
已於最新版加入此功能。

**Comment by fnscar** [comment]
![tim 20180807192137](https://user-images.githubusercontent.com/18730988/43773339-ff362e04-9a77-11e8-863d-ffc80db0e9f9.png)
勾选automatically update public trackers list选项，实际无法输入任何内容。
OS：windows8.1 embedded industry pro
qb：4.1.1.3

**Comment by c0re100** [comment]
這是正常的, 此欄位不能修改內容, 只作查看最新的tracker列表用途

在勾選`Automatically update public trackers list`選項後 再Apply
它就會即時取得 [trackers_best](https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt) , 之後會每隔24小時再次取得trackers_best內容以作更新

另外. 開啟後並不會主動更新此欄位內容, 要重新開啟選項UI才會顯示tracker列表...

**Comment by fnscar** [comment]
感谢讲解。
