### ISSUE TITLE
修复编译 nox 失败

### ISSUE THREAD

**Issue by poplite** [c0re100/qBittorrent-Enhanced-Edition#60]
编译 nox 版本时出现如下错误：

```
compiling ../../src/app/main.cpp
../../src/app/main.cpp: In function ‘int main(int, char**)’:
../../src/app/main.cpp:252:9: error: ‘QProcess’ was not declared in this scope
         QProcess process;
         ^~~~~~~~
../../src/app/main.cpp:252:9: note: suggested alternative: ‘eaccess’
         QProcess process;
         ^~~~~~~~
         eaccess
../../src/app/main.cpp:253:9: error: ‘process’ was not declared in this scope
         process.setReadChannel(QProcess::StandardOutput);
         ^~~~~~~
../../src/app/main.cpp:253:9: note: suggested alternative: ‘eaccess’
         process.setReadChannel(QProcess::StandardOutput);
         ^~~~~~~
         eaccess
../../src/app/main.cpp:253:32: error: ‘QProcess’ is not a class, namespace, or enumeration
         process.setReadChannel(QProcess::StandardOutput);
                                ^~~~~~~~
../../src/app/main.cpp:254:39: error: ‘QProcess’ is not a class, namespace, or enumeration
         process.setProcessChannelMode(QProcess::MergedChannels);
                                       ^~~~~~~~
Makefile:1787: recipe for target 'main.o' failed
make[3]: *** [main.o] Error 1
```
详细的 Buildlog：https://launchpadlibrarian.net/447988610/buildlog_ubuntu-bionic-amd64.qbittorrent-enhanced_4.1.8.3-1ppa1~bionic1_BUILDING.txt.gz

patch 如下：

```diff
diff --git a/src/app/main.cpp b/src/app/main.cpp
index 80fa350..7530ecc 100644
--- a/src/app/main.cpp
+++ b/src/app/main.cpp
@@ -33,6 +33,8 @@
 #include <QScopedPointer>
 #include <QString>
 #include <QStringList>
+#include <QProcess>
+#include <QTextCodec>
 #include <QThread>
 
 #ifndef DISABLE_GUI
@@ -41,10 +43,8 @@
 #include <QMessageBox>
 #include <QPainter>
 #include <QPen>
-#include <QProcess>
 #include <QPushButton>
 #include <QSplashScreen>
-#include <QTextCodec>
 
 #ifdef QBT_STATIC_QT
 #include <QtPlugin>
```

**Comment by c0re100** [comment]
> 编译 nox 版本时出现如下错误：
> 
> ```
> compiling ../../src/app/main.cpp
> ../../src/app/main.cpp: In function ‘int main(int, char**)’:
> ../../src/app/main.cpp:252:9: error: ‘QProcess’ was not declared in this scope
>          QProcess process;
>          ^~~~~~~~
> ../../src/app/main.cpp:252:9: note: suggested alternative: ‘eaccess’
>          QProcess process;
>          ^~~~~~~~
>          eaccess
> ../../src/app/main.cpp:253:9: error: ‘process’ was not declared in this scope
>          process.setReadChannel(QProcess::StandardOutput);
>          ^~~~~~~
> ../../src/app/main.cpp:253:9: note: suggested alternative: ‘eaccess’
>          process.setReadChannel(QProcess::StandardOutput);
>          ^~~~~~~
>          eaccess
> ../../src/app/main.cpp:253:32: error: ‘QProcess’ is not a class, namespace, or enumeration
>          process.setReadChannel(QProcess::StandardOutput);
>                                 ^~~~~~~~
> ../../src/app/main.cpp:254:39: error: ‘QProcess’ is not a class, namespace, or enumeration
>          process.setProcessChannelMode(QProcess::MergedChannels);
>                                        ^~~~~~~~
> Makefile:1787: recipe for target 'main.o' failed
> make[3]: *** [main.o] Error 1
> ```
> 
> 详细的 Buildlog：https://launchpadlibrarian.net/447988610/buildlog_ubuntu-bionic-amd64.qbittorrent-enhanced_4.1.8.3-1ppa1~bionic1_BUILDING.txt.gz
> 
> patch 如下：
> 
> ```diff
> diff --git a/src/app/main.cpp b/src/app/main.cpp
> index 80fa350..7530ecc 100644
> --- a/src/app/main.cpp
> +++ b/src/app/main.cpp
> @@ -33,6 +33,8 @@
>  #include <QScopedPointer>
>  #include <QString>
>  #include <QStringList>
> +#include <QProcess>
> +#include <QTextCodec>
>  #include <QThread>
>  
>  #ifndef DISABLE_GUI
> @@ -41,10 +43,8 @@
>  #include <QMessageBox>
>  #include <QPainter>
>  #include <QPen>
> -#include <QProcess>
>  #include <QPushButton>
>  #include <QSplashScreen>
> -#include <QTextCodec>
>  
>  #ifdef QBT_STATIC_QT
>  #include <QtPlugin>
> ```

咦 抱歉
我忘記測試nox版本-__-
