### ISSUE TITLE
吸血客户端

### ISSUE THREAD

**Issue by Furrylang** [c0re100/qBittorrent-Enhanced-Edition#601]
### qBittorrent & operating system versions

最新客户端

### What is the problem?

![mmexport1728177945571](https://github.com/user-attachments/assets/8f3d3a22-b38a-4169-96e5-1bb49c6156c4)
这个客户端已经下载了足够他100%的数据 但进度依然是不足1%

**Comment by f1ume** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/commit/adda699efb1bab9df68ae6ae11b3dc1131c2b38c 已经加进黑名单了。等5.0吧
