### ISSUE TITLE
[GA] unable to build v5 appimage

### ISSUE THREAD

**Issue by c0re100** [c0re100/qBittorrent-Enhanced-Edition#605]
qBittorrent: 5.0.0
Container: ubuntu 22.04
GCC: 11
Qt: 6.8.0

@abcfy2 exit at the very last step LOL
https://github.com/c0re100/qBittorrent-Enhanced-Edition/actions/runs/11331437288/job/31511448814#step:5:13053

**Comment by abcfy2** [comment]
@c0re100 Got it. I'll take time to check.
