### ISSUE TITLE
Where is qBittorrent 5.0?

### ISSUE THREAD

**Issue by henrypp** [c0re100/qBittorrent-Enhanced-Edition#608]
### Suggestion

3 weeks ago original qBittorrent was released 5.0 version, but enahanced was not, it still 4.6.7 (10)

why? and when do you made new version?

**Comment by c0re100** [comment]
When it's ready.
https://github.com/c0re100/qBittorrent-Enhanced-Edition/tree/v5_0_x

**Comment by henrypp** [comment]
how much weeks to wait left?
