### ISSUE TITLE
新的吸血客户端？客户端：libtorrent/0.15.9.0，Peer ID：AL1000

### ISSUE THREAD

**Issue by Sonic853** [c0re100/qBittorrent-Enhanced-Edition#61]
### qBittorrent version and Operating System
v4.1.8.4 Windows 10

### What is the problem
发现时该客户端获取数据时进度冻结在0%（未截图），获取到的数据已经有文件总大小的四分之一，手动Ban后再恢复会显示并固定在当前进度不动，怀疑是新的吸血客户端？

### Extra info(if any)
客户端：libtorrent/0.15.9.0，Peer ID：AL1000
该客户端再次获取四分之一的文件后，进度依旧固定在该值↓
![Snipaste_2019-10-26_17-41-46](https://user-images.githubusercontent.com/8389962/67618319-60e87600-f820-11e9-818e-f66c3d926c8c.png)
![Snipaste_2019-10-26_17-43-26](https://user-images.githubusercontent.com/8389962/67618320-66de5700-f820-11e9-996c-f9fb08466fb4.png)

**Comment by c0re100** [comment]
初步懷疑是舊版libtorrent bug
https://github.com/arvidn/libtorrent/blob/RC_0_15/ChangeLog
0.15.10 release
fix overflow bug in progress_ppm field
一個與進度有關的變數
然後這個端用了0.15.9版本的libtorrent，所以無法顯示正確的進度

**Comment by qianbinbin** [comment]
我是 Transmission 用户，最近发现一些 libtorrent (Rasterbar) 1.1.6 客户端疑似吸血，IP 属地为 河北省张家口市 电信，下载进度显示为 0 或偶尔正常，从不上传

从 [这个帖子](https://www.cometbbs.com/t/%E5%81%9A%E7%A7%8D%E4%B8%8A%E4%BC%A0%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E6%9C%89%E4%BA%BA%E4%B8%8B%E8%BD%BD%E5%BF%AB%EF%BC%8C%E6%9C%89%E4%BA%BA%E4%B8%8B%E8%BD%BD%E6%85%A2%E3%80%82/61090/3) 看可能是迅雷服务器

供参考

**Comment by xinjiawei** [comment]
> 我就是河北张家口电信, 哈哈
