### ISSUE TITLE
The IP appears to have been added to the Shadow Ban list, but is actually still not banned | IP 看似已经加入 Shadow Ban list 实则仍然未封禁

### ISSUE THREAD

**Issue by z0z0r4** [c0re100/qBittorrent-Enhanced-Edition#611]
### qBittorrent & operating system versions

qBittorrent Enhanced Edition v5.0.0.10 (64-bit)
Windows 11

### What is the problem?

The IP appears to have been added to the Shadow Ban list, but is actually still not banned

IP 看似已经加入 Shadow Ban list 实则仍然未封禁

Such as `223.111.104.12:56062`

例如图中的 `223.111.104.12:56062`

![image](https://github.com/user-attachments/assets/54d9922b-5661-49cd-b471-c03080663834)

![image](https://github.com/user-attachments/assets/b730f31f-71dc-458c-acda-57c34d090ccb)

![{43D8E6CE-D700-437E-9B64-86B8F2BF2C93}](https://github.com/user-attachments/assets/e291906e-2ca7-4ee7-b14a-125cf7422ba6)

Use with PeerBanHelper

![image](https://github.com/user-attachments/assets/01438818-a230-426b-b576-d19ed661f437)

### Steps to reproduce

Unknown

Of course, it works when I ban the user manually...

**Comment by c0re100** [comment]
Can't reproduce :|
Ban via option or ban via peer list, both work fine for me.

**Comment by z0z0r4** [comment]
Should I provide any debug log?

I will upload log when I found the IP continues downloading...It is not found now

**Comment by c0re100** [comment]
> Should I provide any debug log?
> 
> I will upload log when I found the IP continues downloading...It is not found now

Maybe you can post your `qBittorrent.ini` config here?
Remove sensitive data first.
email also ok.
`c0re@husky.dev`

**Comment by z0z0r4** [comment]
Failed to fire again after disabling PeerBanHelper... I'm not sure if this is the reason, as I've already uninstalled PeerBanHelper
