### ISSUE TITLE
Automatically update public tracker list unable to be enabled

### ISSUE THREAD

**Issue by arianwen27** [c0re100/qBittorrent-Enhanced-Edition#612]
### qBittorrent & operating system versions

qbitorrent 5.0.0.10
win 11 23h2

### What is the problem?

"Automatically update public tracker list" is set to disabled and uses "trackers_best". Enabling it and or changing the tracker list, pressing ok or apply and closing the settings menu disables it. Opening settings again shows it has reset to disabled and back to using "trackers_best".

Meaning "Automatically update public tracker list" does not work at all

### Steps to reproduce

Open options
go to bitorrent
enable Automatically update public tracker list
apply and close settings
open settings again
option is back to disabled

**Comment by c0re100** [comment]
fix in the next version.
https://github.com/c0re100/qBittorrent-Enhanced-Edition/pull/610

2 workaround: 
1. set global ratio to 999999 or something else
2. download CI build

**Comment by Func86** [comment]
> fix in the next version. #610

Upstream v5.0.1 was released 1 week ago, you may also release v5.0.1.10?

**Comment by escape0707** [comment]
@Func86 Current qBEE version is already [up-to-date](https://github.com/c0re100/qBittorrent-Enhanced-Edition/compare/release-5.0.0.10...qbittorrent:qBittorrent:release-5.0.1) with upstream v5.0.1 in the meaning of functioning codes. So it seems that we'll need to wait for a new version or use workarounds mentioned above.

**Comment by escape0707** [comment]
BTW, I'm having the opposite issue. I can't disable that option, trackers are always appended to my torrents, although I prefer to use DHT exclusively, and I don't have a "fetch update" button in my `-nox` build client. Then I tried the mentioned PR using Arch, AUR PKGBUILD, `libtorrent-rasterbar-1`, swapped source tarball to branch `v5-0-x`, but it's still the same.

I even tried to set the url to an empty txt file, but since it doesn't fetch the file on saving of the config, it still doesn't work.

**Comment by escape0707** [comment]
I'm using:

qBittorrent Enhanced Edition v5.0.2 WebUI (64-bit)
Qt: 	6.8.0
Libtorrent: 	1.2.19.0
Boost: 	1.86.0
OpenSSL: 	3.4.0
zlib: 	1.3.1

And the problem still occurs. I cannot disable the auto tracker addition, and there is no refresh button.

I'm using Arch and built the -nox variant with AUR.

**Comment by c0re100** [comment]
> I'm using:
> 
> qBittorrent Enhanced Edition v5.0.2 WebUI (64-bit) Qt: 6.8.0 Libtorrent: 1.2.19.0 Boost: 1.86.0 OpenSSL: 3.4.0 zlib: 1.3.1
> 
> And the problem still occurs. I cannot disable the auto tracker addition, and there is no refresh button.
> 
> I'm using Arch and built the -nox variant with AUR.

WebUI don't have refresh button.
Rebuild should be fixed.
https://github.com/c0re100/qBittorrent-Enhanced-Edition/commit/50561bf126905e83532a7de7a8c26f4ecd129b7d

**Comment by escape0707** [comment]
@c0re100 I can confirm building from latest commit fixes my problem. Thanks for the speedy response!
