### ISSUE TITLE
Trackers list option not working

### ISSUE THREAD

**Issue by Mashiro-qwq** [c0re100/qBittorrent-Enhanced-Edition#613]
### qBittorrent & operating system versions

qBittorrent Enhanced Edition v5.0.0.10 x64
Operating system: Microsoft Windows 11 Pro for Workstations 24H2 26100.2161 x64

### What is the problem?

Trackers list option not working, After saving the completed subscription link, it will be reset to the default state.

### Steps to reproduce

After checking the "automatically update public trackers list" option, fill in the subscription link, save, and confirm. When you open the settings again, it has been reset to the default state.

### Additional context

https://github.com/user-attachments/assets/afaf5e62-c7a1-46f2-8163-af23bc2fb295

### Log(s) & preferences file(s)

[qbittorrent.log](https://github.com/user-attachments/files/17526331/qbittorrent.log)
[qBittorrent.ini.zip](https://github.com/user-attachments/files/17526348/qBittorrent.ini.zip)

**Comment by c0re100** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/612#issuecomment-2438484290
