### ISSUE TITLE
[Winget] auto update issue

### ISSUE THREAD

**Issue by c0re100** [c0re100/qBittorrent-Enhanced-Edition#614]
ping @vedantmgoyal9
I wonder...
qBittorrent now only support Windows 10 64bit version 1809 or newer
Is there a way to submit x64 version only?
https://github.com/microsoft/winget-pkgs/pull/185659

**Comment by vedantmgoyal9** [comment]
Simply remove x86 installer entry from the manifest. In the next update, only x64 will be submitted.

**Comment by c0re100** [comment]
Got it, thanks.
