### ISSUE TITLE
Setting didn't show correctly

### ISSUE THREAD

**Issue by Innocence** [c0re100/qBittorrent-Enhanced-Edition#616]
### qBittorrent & operating system versions

qBittorrent 5.0.0.10
Operating system: Windows 11 Pro 24H2

### What is the problem?

Setting didn't show correctly

In Tools->Options->BitTorrent, I checked the 'Automatically update public trackers list.' and pasted a url, then pressed Apply.But when I open  Tools->Options->BitTorrent again,  'Automatically update public trackers list.' is unchecked. 

But in **C:\Users\xxxx\AppData\Roaming\qBittorrent\qBittorrent.ini**,   'AutoUpdateTrackersEnabled=true' is there. And that url is set to Bittorrent\CustomizeTrackersListUrl .

![微信截图_20241026233456](https://github.com/user-attachments/assets/a3f62d4f-aec5-4976-8238-d951eab8405a)
![微信截图_20241026233140](https://github.com/user-attachments/assets/03866e54-4e06-43ba-9185-90ad826be283)

**Comment by c0re100** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/612#issuecomment-2438484290
