### ISSUE TITLE
No option to untick “Install with Debug Symbol File”

### ISSUE THREAD

**Issue by win98se** [c0re100/qBittorrent-Enhanced-Edition#618]
### qBittorrent & operating system versions

qBittorrent: 5.0.0.10 x64
Operating system: Windows 11 Version 24H2 x64

### What is the problem?

As in title, the installer of 5.0.0.10 does not even give the option to untick “Install with Debug Symbol File”.

It was untickable in 4.6.7.10 and before.

As a normal user that will never use debuggers on a software, the debug symbol file should be made optional once again.

### Additional context

So, it's #201 all over again.

**Comment by c0re100** [comment]
For now, debug symbol file is just 60MB (after ntfs compress: 30MB) and 2.5x smaller than official.
IMO it's a slim file, so I don't think it's a problem at all.

Comparison
qbittorrent_enhanced_5.0.0.10_x64_setup.exe 24.8MB
pdb: 60MB (after ntfs compress: 30MB)

qbittorrent_5.0.0_x64_setup.exe
pdb: 160MB (after ntfs compress: 90MB)

qbittorrent_enhanced_4.6.7.10_qt6_x64_setup.exe 57MB
pdb: 260MB (after ntfs compress: 150MB)
