### ISSUE TITLE
自动添加trackers选项勾选，再次打开发现被关闭。

### ISSUE THREAD

**Issue by qi935720935** [c0re100/qBittorrent-Enhanced-Edition#619]
### qBittorrent & operating system versions

qBittorrent：5.0.0.10
操作系统：Windows 11 24H2

### What is the problem?

自动添加trackers选项勾选不生效。

### Additional context

![屏幕截图 2024-10-28 161805](https://github.com/user-attachments/assets/3cca9ed6-61a9-4774-9b55-5fe3b1616b3e)
![屏幕截图 2024-10-28 161834](https://github.com/user-attachments/assets/901f3dc2-1017-435d-8647-9d62fd15044f)

**Comment by c0re100** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/612
