### ISSUE TITLE
Appimage version doesn't use system theme

### ISSUE THREAD

**Issue by Bryan2333** [c0re100/qBittorrent-Enhanced-Edition#621]
### qBittorrent & operating system versions

Here is the qbittorrent enhanced information:
qBittorrent-Enhanced: 5.0.0.10(64bit)
Qt: 6.8.0
Libtorrent: 1.2.19.0
Boost: 1.86.0
OpenSSL: 3.4.0
zlib: 1.3.1

Here is my system information:
Operating System: Arch Linux 
KDE Plasma Version: 6.2.2
KDE Frameworks Version: 6.7.0
Qt Version: 6.8.0
Kernel Version: 6.10.10-zen1-1-zen-cjktty (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5800H with Radeon Graphics
Memory: 13.5 GiB of RAM
Graphics Processor: AMD Radeon Graphics

### What is the problem?

The appimage version does not respect system theme.

### Steps to reproduce

1. Just launch qbittorrent-enhanced

### Additional context

Here is the screenshot of the appimage download from release
![q1](https://github.com/user-attachments/assets/03cf0ae3-f034-48e9-996b-8316d3945fec)

Here is the screenshot of qbittorrent-enhanced from AUR, which is built from source.
![q2](https://github.com/user-attachments/assets/d12630d5-1445-41ec-958e-ee48941d9468)

You can see the difference obviously.

**Comment by abcfy2** [comment]
Known issue. We force set qt to use GTK theme. See: https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/341#issuecomment-1066018193

**Comment by Bryan2333** [comment]
> If you're using KDE, in addition to set a plasma theme, you should also set a similar GTK theme.

It seems that the GTK theme has been set to Breeze already.

![Snipaste_2024-10-30_12-47-38](https://github.com/user-attachments/assets/41827d4d-7e8e-4dfc-b6bc-93c8de9ed0fe)

Some other GTK application like solaar in system is using Breeze theme, qbittorrent enhanced should use Breeze too. But they look quite different.

![Snipaste_2024-10-30_12-50-34](https://github.com/user-attachments/assets/76ad7be1-35bd-41f8-8ecc-850cac0214a4)

**Comment by abcfy2** [comment]
Would you please try this build ? https://github.com/abcfy2/qBittorrent-Enhanced-Edition/releases/tag/v5.0.0.12

I guess it may be the influence of gtk2 style. Currently I removed `qt6gtk2` from AppImage build since gtk+ plugin in qt-base already works fine, and next release will use this patch.

**Comment by Bryan2333** [comment]
![Snipaste_2024-10-30_14-02-20](https://github.com/user-attachments/assets/4a5fd580-d514-4495-a1f5-0e1c00106d0c)

Other than the background color, I don't see a difference in the buttons, dropdown menus, and other components

**Comment by abcfy2** [comment]
So that's might be the qt style used gtk theme. Since it's not a real GTK application, so maybe a little different style from GTK application.

I think it's not a AppImage problem. So you may close this issue now.
