### ISSUE TITLE
自动更新公共tracker列表无法修改地址的BUG

### ISSUE THREAD

**Issue by syl353794035** [c0re100/qBittorrent-Enhanced-Edition#626]
### qBittorrent & operating system versions

qBittorrent Enhanced Edition v5.0.0.10 (64-bit)
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2024/‎1/‎6
操作系统内部版本	19045.5073
体验	Windows Feature Experience Pack 1000.19060.1000.0

### What is the problem?

在自动更新公共tracker列表处修改tracker地址，并点击应用然后重启软件之后又变回软件默认设置。
![Snipaste_2024-11-10_23-27-56](https://github.com/user-attachments/assets/b4d47c3a-bdcc-4e27-b96f-31993a937dc2)

**Comment by Alvin-Blithe** [comment]
兄弟解决了吗？我也遇到这个问题了

**Comment by syl353794035** [comment]
> 兄弟解决了吗？我也遇到这个问题了

你看作者关闭的completed，里面第一个问题有对这个问题的回答，好像说是在下一个版本修复这个问题。

**Comment by Alvin-Blithe** [comment]
> > 兄弟解决了吗？我也遇到这个问题了
> 
> 你看作者关闭的completed，里面第一个问题有对这个问题的回答，好像说是在下一个版本修复这个问题。

看到了，我瞎了。请问那个全局比率在哪些设置呢？我没找着

**Comment by syl353794035** [comment]
> > > 兄弟解决了吗？我也遇到这个问题了
> > 
> > 
> > 你看作者关闭的completed，里面第一个问题有对这个问题的回答，好像说是在下一个版本修复这个问题。
> 
> 看到了，我瞎了。请问那个全局比率在哪些设置呢？我没找着

全局速率就是下载速度那里，但是我测试了一下并不能解决，等下个版本更新之后再看看吧。

**Comment by Alvin-Blithe** [comment]
> > > > 兄弟解决了吗？我也遇到这个问题了
> > > 
> > > 
> > > 你看作者关闭的completed，里面第一个问题有对这个问题的回答，好像说是在下一个版本修复这个问题。
> > 
> > 
> > 看到了，我瞎了。请问那个全局比率在哪些设置呢？我没找着
> 
> 全局速率就是下载速度那里，但是我测试了一下并不能解决，等下个版本更新之后再看看吧。

好的，谢谢
