### ISSUE TITLE
[BUG]There is still a memory overflow problem

### ISSUE THREAD

**Issue by fgr178707** [c0re100/qBittorrent-Enhanced-Edition#628]
### qBittorrent & operating system versions

qBittorrent： 5.0.2.10 x64
Operating system: Windows ： Windows 11 Pro 22H2
Qt： 6.7.3
libtorrent-rasterbar： 1.2.19.

### What is the problem?

There is still a memory overflow problem

### Steps to reproduce

No steps, starts 5 minutes or so after normal startup Memory overflow.

### Additional context

This number is about 100 or more

English Google Translate
![translated_image_en](https://github.com/user-attachments/assets/0975f6ae-e7b1-4523-ac9c-a7248d9c2246)

Chinese Original
![image](https://github.com/user-attachments/assets/8366ec72-40ff-4372-a201-21333d767923)

### Log(s) & preferences file(s)

No logs.

**Comment by c0re100** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/617

**Comment by fgr178707** [comment]
> #617

So that means V5.0.2, the version that hasn't fixed the memory overflow problem?

**Comment by c0re100** [comment]
> > #617
> 
> So that means V5.0.2, the version that hasn't fixed the memory overflow problem?

Yes.

**Comment by fgr178707** [comment]
> > > #617
> > 
> > 
> > So that means V5.0.2, the version that hasn't fixed the memory overflow problem?
> 
> Yes.

Well, I thought this version fixed it.

**Comment by c0re100** [comment]
> > > > #617
> > > 
> > > 
> > > So that means V5.0.2, the version that hasn't fixed the memory overflow problem?
> > 
> > 
> > Yes.
> 
> Well, I thought this version fixed it.

If official qBt(w/ libtorrent 1.2) is still happening, then enhanced edition too.
I can't reproduce, so nothing I can do.

**Comment by fgr178707** [comment]
> If official qBt(w/ libtorrent 1.2) is still happening, then enhanced edition too. I can't reproduce, so nothing I can do.

Are you saying that the memory overflow issue, is not an enhancement issue, but an official client issue?

**Comment by c0re100** [comment]
> > If official qBt(w/ libtorrent 1.2) is still happening, then enhanced edition too. I can't reproduce, so nothing I can do.
> 
> Are you saying that the memory overflow issue, is not an enhancement issue, but an official client issue?

Yes, you can try to reproduce on official v5.0.2.

**Comment by fgr178707** [comment]
> > > If official qBt(w/ libtorrent 1.2) is still happening, then enhanced edition too. I can't reproduce, so nothing I can do.
> > 
> > 
> > Are you saying that the memory overflow issue, is not an enhancement issue, but an official client issue?
> 
> Yes, you can try to reproduce on official v5.0.2.

Tried the official version of V5.0.2 for about 10 minutes, direct overwrite installation, no memory leaks, average 450MB, no more than 500MB.

![image](https://github.com/user-attachments/assets/7deac613-5766-46cf-9bbc-17ae3d68aa8f)

**Comment by c0re100** [comment]
you're using libtorrent 2.0, not 1.2

**Comment by fgr178707** [comment]
> you're using libtorrent 2.0, not 1.2

Oh, so that's it.

> If official qBt(w/ libtorrent 1.2) is still happening, then enhanced edition too. I can't reproduce, so nothing I can do.

Oh

**Comment by fgr178707** [comment]
> you're using libtorrent 2.0, not 1.2

Oh

**Comment by VK3002** [comment]
> you're using libtorrent 2.0, not 1.2

[#21859](https://github.com/qbittorrent/qBittorrent/issues/21859#issue-2664130085)  It seems that libtorrent 2.0 also have the memory leaking issue. However, some people just wouldn't meet that. So perhaps this issue has something to do with settings/advaced options instead of the libtorrent version. Or you 'll encounter memory leaking just because you are unlucky😂.
