### ISSUE TITLE
webui错误

### ISSUE THREAD

**Issue by zqm545** [c0re100/qBittorrent-Enhanced-Edition#629]
### qBittorrent & operating system versions

qBittorrent：qbittorrent_enhanced_5.0.2.10_x64
操作系统：win11 24H2

### What is the problem?

qbittorrent_enhanced_4.6.7.10_x64中webui设置是正确的能读取到，升级到5.0以后的版本webui一直是错误状态
![屏幕截图 2024-11-19 212618](https://github.com/user-attachments/assets/94e3e11f-f279-4cbe-807b-8d947689f042)

**Comment by zqm545** [comment]
这个webui的ip地址填成*就没有问题了，和4.6版本不同

**Comment by abcfy2** [comment]
ip 地址又不是 URL 地址，你写 `http://` 就是个错误的ip地址格式

**Comment by zqm545** [comment]
> ip 地址又不是 URL 地址，你写 就是个错误的ip地址格式`http://`

我在4.6里这么填能被正确识别，而在5.0里就是错误的。从4.6覆盖安装的我这里的设置没有改过，
