### ISSUE TITLE
renew the url of public trackers list

### ISSUE THREAD

**Issue by bhxch** [c0re100/qBittorrent-Enhanced-Edition#63]
**Please provide the following information**

### qBittorrent version and Operating System
V4_1_X_X, all platforms 

### If on linux, libtorrent and Qt version
(type here)

### What is the problem
As raw.githubusercontent.com has been blocked by dns posioning in the country we all know, we cannot update the public trackers list normally.

### What is the expected behavior
Maybe we can use https://cdn.jsdelivr.net/gh/ngosang/trackerslist/trackers_best.txt instead of the original url.

### Steps to reproduce
![](https://raw.githubusercontent.com/bhxch/pic/pic/20191102211522.png)
![](https://raw.githubusercontent.com/bhxch/pic/pic/20191102211529.png)
![](https://raw.githubusercontent.com/bhxch/pic/pic/20191102211716.png)
![](https://raw.githubusercontent.com/bhxch/pic/pic/20191102211530.png)

### Extra info(if any)
It would be better if we could set a custom url.

**Comment by c0re100** [comment]
Custom public tracker URL will be available next upcoming release.
But no ETA. Sorry.

**Comment by bhxch** [comment]
Take your time. Don't be worried about that.

**Comment by c0re100** [comment]
> Take your time. Don't be worried about that.

Pre-release version:
change to https://cdn.jsdelivr.net/gh/ngosang/trackerslist/trackers_best.txt temporarily.
https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/tag/release-4.1.9.2

Final version should be available this weekend.
