### ISSUE TITLE
WebUI 用户界面空白

### ISSUE THREAD

**Issue by BeRealQueally** [c0re100/qBittorrent-Enhanced-Edition#634]
### qBittorrent & operating system versions

qBittorrent: qBittorrent Enhanced Edition v5.0.2.10-nox

### What is the problem?

Webui用户界面无法显示， 控制台报错
![image](https://github.com/user-attachments/assets/e7d03192-7eac-4026-90c2-c27dc8254bef)

**Comment by Victor4869** [comment]
这个解决了吗，遇到同样问题了
