### ISSUE TITLE
v5.0.3.10 被Windows安全中心（Windows Defender）删除

### ISSUE THREAD

**Issue by RC-1140Fixer** [c0re100/qBittorrent-Enhanced-Edition#638]
### qBittorrent & operating system versions

Operating system: Windows 11 Pro 23H2 x64

### What is the problem?

![report](https://github.com/user-attachments/assets/9552b5ea-48fb-4a77-bb5e-8addc9ea7ccb)

先前版本下载后，在浏览器选择“保留”即可安装使用，但最新这个版本保留后却被Windows删除。

**Comment by c0re100** [comment]
被defender擋的話，放進白名單就行了吧
https://www.virustotal.com/gui/file/f9f5017c251933d788bc6ab9a4cdc4abf2d64cccb4cd82e28803ff787cc2c369
