### ISSUE TITLE
5.0.3.10 virus detected

### ISSUE THREAD

**Issue by monkiely** [c0re100/qBittorrent-Enhanced-Edition#639]
### qBittorrent & operating system versions

[qbittorrent_enhanced_5.0.3.10_x64_setup.exe](https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/download/release-5.0.3.10/qbittorrent_enhanced_5.0.3.10_x64_setup.exe)

### What is the problem?

WIndows Security: Trojan:Win32/Wacatac.B!ml

**Comment by c0re100** [comment]
https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/638#issuecomment-2558037678
