### ISSUE TITLE
自动更新public trackers list的功能不起作用了？

### ISSUE THREAD

**Issue by abcfy2** [c0re100/qBittorrent-Enhanced-Edition#64]
**Please provide the following information**

### qBittorrent version and Operating System
4.1.9.1

OS: Deepin V15.11

### What is the problem

勾选了自动更新public trackers list，但是始终为空白，我记得以前版本这里是会自动更新trackers列表的

![深度截图_选择区域_20191108171944](https://user-images.githubusercontent.com/5327677/68464695-06054480-024c-11ea-9032-82ec26c685d6.png)

而且下载种子的时候也没有其他trackers添加进来，我记得以前版本都是有这个功能的
![深度截图_选择区域_20191108171956](https://user-images.githubusercontent.com/5327677/68464706-07367180-024c-11ea-83b3-7c3f5b0cdab7.png)

**Comment by c0re100** [comment]
> **Please provide the following information**
> 
> ### qBittorrent version and Operating System
> 4.1.9.1
> 
> OS: Deepin V15.11
> 
> ### What is the problem
> 勾选了自动更新public trackers list，但是始终为空白，我记得以前版本这里是会自动更新trackers列表的
> 
> ![深度截图_选择区域_20191108171944](https://user-images.githubusercontent.com/5327677/68464695-06054480-024c-11ea-9032-82ec26c685d6.png)
> 
> 而且下载种子的时候也没有其他trackers添加进来，我记得以前版本都是有这个功能的
> ![深度截图_选择区域_20191108171956](https://user-images.githubusercontent.com/5327677/68464706-07367180-024c-11ea-83b3-7c3f5b0cdab7.png)

#63 
因為raw.githubusercontent.com被GFW了

**Comment by abcfy2** [comment]
这个没有缓存功能吗？我记得我以前还是成功获取到过trackers的。我觉得可以每次成功获取列表的时候缓存起来，下次成功获取的时候再覆盖，而不是失败了就全清了

**Comment by c0re100** [comment]
> 这个没有缓存功能吗？我记得我以前还是成功获取到过trackers的。我觉得可以每次成功获取列表的时候缓存起来，下次成功获取的时候再覆盖，而不是失败了就全清了

沒有快取，只會在開啟qB的時候才會取得trackers list及24小時後自動取得最新trackers並覆蓋(如果成功)
儲存到配置檔功能的話，會連同自訂trackers list一起更新

**Comment by abcfy2** [comment]
偶然现象，暂时先关闭吧
