### ISSUE TITLE
Trackers from "Automatically update public trackers list" are not added to torrents added via magnet links

### ISSUE THREAD

**Issue by txtsd** [c0re100/qBittorrent-Enhanced-Edition#69]
**Please provide the following information**

### qBittorrent version and Operating System
v4.1.9.3
OS: Archlinux

### If on linux, libtorrent and Qt version
libtorrent: 1.1.13.0
Qt: 5.13.2

### What is the problem
The trackers from `Automatically update public trackers list` are not added to torrents added via magnet links, but they are correctly added to torrents added via a .torrent file.

### What is the expected behavior
Torrents added via magnet links should correctly import trackers from the automatically updated public trackers list.

### Steps to reproduce
1. Activate `Automatically update public trackers list`
2. Add torrent via magnet link
3. Check list of trackers in torrent once it starts

**Comment by c0re100** [comment]
Sorry, but I can't reproduced this bug in my Arch Linux machine.
Does any Arch user have an issue with that?

**Comment by txtsd** [comment]
I double-checked, and it does seem to work correctly. However, a number of torrents that I had added via magnet links within the past month are missing the trackerlist trackers, and have only the default included trackers. Any way to debug this?

**Comment by c0re100** [comment]
> I double-checked, and it does seem to work correctly. However, a number of torrents that I had added via magnet links within the past month are missing the trackerlist trackers, and have only the default included trackers. Any way to debug this?

I guess you can't access raw.githubusercontent.com to get newest trackers list.
If failed to download trackers list, you can see the log with failed reason.
`Updating the public tracker list failed: xxxxxxxxxxxxx`
ref.: #63

**Comment by txtsd** [comment]
It's not happening anymore, so I'll close this.
