### ISSUE TITLE
Please change your PeerID and user-agent

### ISSUE THREAD

**Issue by sledgehammer999** [c0re100/qBittorrent-Enhanced-Edition#70]
Hey, I am one of the core devs of the official qBittorrent. You are free to make a fork of our code but don't use the same identification as our code.
Please change the peerID and user-agent you announce to the peers and trackers of the network. They need to know you're a different client.
Otherwise, undesirable behavior that comes from your fork might get the official qbittorrent banned too (from trackers), which isn't nice.

PeerID is defined here:
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/c33d8e08feb3d78943607c1b9aa3ae26b1a7b6bb/src/base/bittorrent/session.cpp#L109

User agent is defined here:
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/c33d8e08feb3d78943607c1b9aa3ae26b1a7b6bb/src/base/bittorrent/session.cpp#L111

**Comment by Balls0fSteel** [comment]
Subscribe. Don't want my favorite client get banned on various trackers because apparently there is a client/fork that uses the very same PeerID but behaves vastly different. We also have no idea how this behaves on the trackers - there are so many running various software.

Point is, it took many many years for qBittorrent to get whitelisted. If a more conservative tracker sees this, they will put the client on block again. That would be a huge setback.

**Comment by c0re100** [comment]
As I know, a Private Tracker is using PeerID whitelist.
I know a core feature(Auto Ban Xunlei, QQ, Baidu, Xfplay, DLBT and Offline downloader) is may be affecting private tracker. 
How about adding private torrent checking to [this feature](https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_1_x/src/base/bittorrent/session.cpp#L1997-L2030)?
If the torrent is private, just ignore it.
```
if(!torrent->isPrivate()) {
    code
}
```

Anyway, Here is my solution:
1. Add a warning to README (e.g. Don't use this fork for PT.)
2. `VER_BUILD` greater than official qB (So it's not same identification as official qB and a private tracker can block this fork easily)
3. Add Enhanced tag to User Agent (`"qBittorrent/" ENH_VERSION " Enhanced"`)
4. As I mentioned, Ignore private torrent.

**Comment by c0re100** [comment]
> 1. Add a warning to README (e.g. Don't use this fork for PT.)
> 2. `VER_BUILD` greater than official qB (So it's not same identification as official qB and a private tracker can block this fork easily)
> 3. Add Enhanced tag to User Agent (`"qBittorrent/" ENH_VERSION " Enhanced"`)
> 4. As I mentioned, Ignore private torrent.

@sledgehammer999, Do you accept these changes?

**Comment by sledgehammer999** [comment]
@c0re100 sorry, I got bogged down with a serious bug in qbt and forgot about this.

>Add a warning to README (e.g. Don't use this fork for PT.)

Then why not change the PEER_ID instead? If the a Private Tracker doesn't like your changes then it (the tracker) will block your fork.

>VER_BUILD greater than official qB (So it's not same identification as official qB and a private tracker can block this fork easily)

This needs to be coupled with

>Add Enhanced tag to User Agent ("qBittorrent/" ENH_VERSION " Enhanced")

Otherwise, you are messing up our (qbt official) version numbers when you do a release. Recent example: We did a 4.1.9.1 release.

On another note:
>Add Enhanced tag to User Agent ("qBittorrent/" ENH_VERSION " Enhanced")

I think that's not correct. I think it needs to be `"qBittorrent Enhanced/" ENH_VERSION`.
The generally accepted [format](https://en.wikipedia.org/wiki/User_agent) seems to be `<program_name>/<version>`
Furthermore your `ENH_VERSION` is probably wrong. You never use the `VER_BUILD` number. You probably should switch to using `QBT_VERSION_2`

>As I mentioned, Ignore private torrent.

If you change your PEER_ID it will not matter to me. But it may matter to private trackers. If they know that you don't enable your special features for private torrents, then they likely won't ban you.

**Comment by c0re100** [comment]
@sledgehammer999 
> Then why not change the PEER_ID instead? If the a Private Tracker doesn't like your changes then it (the tracker) will block your fork.

Cause a Private Tracker is using PeerID whitelist.
For example, 1 PT whitelisted PeerID `-qB4200-`, `-qB4201-`, `-qB4210-`
If my fork using `-qB420A-`/`-qB4211-` something else, the tracker will block my fork automatically.

> Otherwise, you are messing up our (qbt official) version numbers when you do a release. Recent example: We did a 4.1.9.1 release.

Yes, I know.
I'll prevent this to happen again.

> I think that's not correct. I think it needs to be "qBittorrent Enhanced/" ENH_VERSION.
The generally accepted format seems to be <program_name>/<version>

Ah, make sense.

> Furthermore your ENH_VERSION is probably wrong. You never use the VER_BUILD number. You probably should switch to using QBT_VERSION_2

Sorry, I forgot why using ENH_VERSION since 4.1.X. 
I'll switch back to QBT_VERSION_2.

> If you change your PEER_ID it will not matter to me. But it may matter to private trackers. If they know that you don't enable your special features for private torrents, then they likely won't ban you.

No matter how, a private tracker do not allow a modification BT client.
FYI: As a private tracker user, there is no need any special features for PT.

**Comment by IceCodeNew** [comment]
> Sorry, I forgot why using ENH_VERSION since 4.1.X.
I'll switch back to QBT_VERSION_2.

请问目前 peerID 的命名规则有确定下来吗？
试着测试了一下看到 4.1.9.15 版本回报的 peerID 是 `-qB419F-`，想知道以后发布的版本回报 peerID 是不是就都是 qB`xyz`F 的形式了。

**Comment by c0re100** [comment]
> > Sorry, I forgot why using ENH_VERSION since 4.1.X.
> > I'll switch back to QBT_VERSION_2.
> 
> 请问目前 peerID 的命名规则有确定下来吗？
> 试着测试了一下看到 4.1.9.15 版本回报的 peerID 是 `-qB419F-`，想知道以后发布的版本回报 peerID 是不是就都是 qB`xyz`F 的形式了。

現在PeerID格式統一為 `-qB{Current_version}[A-Z]-`
即是 `-qB419A-`, `-qB419B-`
4.1.9.10=419A
11=419B
12=419C
13=419D
14=419E
15=419F
........
如此類推
經測試後，這一種格式的用戶端不能使用於PT上

**Comment by IceCodeNew** [comment]
哈哈，谢谢解释，我明白了。
关于会被 PT 站 ban 的事这个完全不出乎预料，我已经在给所有我测试到会不能下载的站点发送意见反馈，希望他们增设白名单了。

P.S. 不知道 4.1.9.15 之前的版本安装包是否会在考虑之后重新放出来，Windows 上之前的几次编译经历都不是很愉快，可以的话还是希望能下载现成的安装包。

**Comment by c0re100** [comment]
> 哈哈，谢谢解释，我明白了。
> 关于会被 PT 站 ban 的事这个完全不出乎预料，我已经在给所有我测试到会不能下载的站点发送意见反馈，希望他们增设白名单了。
> 
> P.S. 不知道 4.1.9.15 之前的版本安装包是否会在考虑之后重新放出来，Windows 上之前的几次编译经历都不是很愉快，可以的话还是希望能下载现成的安装包。

抱歉，我沒有備份4.1.9.15之前的版本

**Comment by misaka00251** [comment]
> 哈哈，谢谢解释，我明白了。
> 关于会被 PT 站 ban 的事这个完全不出乎预料，我已经在给所有我测试到会不能下载的站点发送意见反馈，希望他们增设白名单了。
> 
> P.S. 不知道 4.1.9.15 之前的版本安装包是否会在考虑之后重新放出来，Windows 上之前的几次编译经历都不是很愉快，可以的话还是希望能下载现成的安装包。


[qbittorrent_4.1.9.4_x64_setup.zip](https://github.com/c0re100/qBittorrent-Enhanced-Edition/files/3986439/qbittorrent_4.1.9.4_x64_setup.zip)

**Comment by 1265578519** [comment]
这是目前所有PT站使用的tracker私人种子数据库客户端版本判断方式，如果有需要更改请联系我
'/^-qB4([0-9])([0-9A-Z])([0-9])-/',
'-qB4000-',
'/^qBittorrent\\/4\\.([0-9])\\.([0-9]+)/',

**Comment by TurnOffNOD** [comment]
Hi, @c0re100 , maybe it will be better if we use QBT_VERSION-EE.ver as version number?
For example, when official qbittorrent version which it is based on is 4.2.5, the qbittorrent Enhanced Edition will use 4.2.5-EE.1 as version number? 
And this can also apply to PeerID and user-agent.

**Comment by firedent** [comment]
Well, remaining the official Peer ID is not allowed by the official. I must, however, point that ANYONE CAN CHANGE THE PEER ID BACK and re-compile it. Moreover, if you guys do that, nobody knows it. ; )
