### ISSUE TITLE
qbittorrent 4.2.0 已发布

### ISSUE THREAD

**Issue by abcfy2** [c0re100/qBittorrent-Enhanced-Edition#71]
上游已经更新新版本，不知道qbee什么时候更新呢？

看上游已经添加了新的分支 `v4_2_x`，编译环境支持 libtorrent 1.2以上版本，到时候可以更新一下AppImage的编译

**Comment by c0re100** [comment]
預設會在周末更新
同時要等IPv6的問題解決
https://github.com/qbittorrent/qBittorrent/issues/11561

**Comment by jkle112** [comment]
希望Qt,Libtorrent,Boost都可以升级一下
另有一个配置问题：无法添加public trackers list，主要是添加地址让软件自动更新，
![Image 1](https://user-images.githubusercontent.com/17021524/70387250-09702500-19de-11ea-9902-c11f1ef4be88.png)

**Comment by c0re100** [comment]
> 希望Qt,Libtorrent,Boost都可以升级一下
> 另有一个配置问题：无法添加public trackers list，主要是添加地址让软件自动更新，
> ![Image 1](https://user-images.githubusercontent.com/17021524/70387250-09702500-19de-11ea-9902-c11f1ef4be88.png)

基本上，每次更新EE都會使用最新版本的Qt,Libtorrent,Boost
4.1.9.3才可以自訂public trackers list

**Comment by jkle112** [comment]
最新版本用了，实在太简陋，我需要添加好几个public trackers list，默认只有一个位置，官方默认的list,我想添加更多，拓宽资源，希望继续升级，谢谢！

**Comment by c0re100** [comment]
qBt v4.2.0 skipped.
From qB maintainer (sledgehammer999): `If possible I would like to make a release this weekend.`
ref.: #11642

@abcfy2 已推原版v4_2_x分支
因我目前沒有時間做完整的測試，所以沒有將Enhanced功能一起Push上來。
你可以先更新及測試一下AppImage編譯。

**Comment by abcfy2** [comment]
PR已提交 #73 

官方发布4.2.0的时候我本地都测试的差不多了，根据官方的ubuntu ppa的编译方式也修正了编译参数

**Comment by jkle112** [comment]
我需要添加好几个public trackers list，默认只有一个位置，官方默认的list,我想添加更多，拓宽资源，由于是增强版，希望以后可以添加！

**Comment by c0re100** [comment]
> 我需要添加好几个public trackers list，默认只有一个位置，官方默认的list,我想添加更多，拓宽资源，由于是增强版，希望以后可以添加！

老實說，加更多tracker list是沒有用的
最有效的應該由檔案提供者(或檔案分享網站)使用這些tracker讓下載者交換資訊
