### ISSUE TITLE
为什么检索元数据会这么久

### ISSUE THREAD

**Issue by kaweizz** [c0re100/qBittorrent-Enhanced-Edition#74]
就是拿磁链解析出文件的步骤..

吸血雷秒解析..

**Comment by c0re100** [comment]
> 就是拿磁链解析出文件的步骤..
> 
> 吸血雷秒解析..

magnet快慢是視乎你連接到DHT節點數量及DHT網絡有沒有這個magnet資料及相關上載或下載者
而迅雷是將記錄保留在自己的伺服器內
當有使用者下載magnet時，迅雷會先經過自己的伺服器
如有就會返回相關torrent資料
如沒有就請求DHT網絡並儲存相關資料，給下一個用家使用

**Comment by abcfy2** [comment]
迅雷有自己的服务器，遇到迅雷自己的服务器没有的种子一样解析很久

**Comment by kaweizz** [comment]
感谢大佬科普... 总之迅雷有自己的服务器就对了。 匹配准确就自动秒解析。
