### ISSUE TITLE
[Suggestion] Seed until XX amount of seeds available

### ISSUE THREAD

**Issue by sploitmyhost** [c0re100/qBittorrent-Enhanced-Edition#76]
Please add an option to seed a torrent until there are xxx amount of other seeds available in the swarm.

eg, seed until 10 seeds available, then pauze/delete.

Thanks.

**Comment by c0re100** [comment]
After the test, it's impossible to determine xxx amount of other seeds available.
Seeders may contains a `fake seeder`, you don't know those seeders is real or fake without connection.
