### ISSUE TITLE
在macOS Catalina上，工具栏背景变成透明的

### ISSUE THREAD

**Issue by Resunny** [c0re100/qBittorrent-Enhanced-Edition#77]
**Please provide the following information**

### qBittorrent version and Operating System
qBittorrent v4.2.1.10(Enhanced Edition)
系统：macOS Catalina 10.15.2

### What is the problem
在macOS Catalina上，工具栏背景变成透明的，影响使用。
![image](https://user-images.githubusercontent.com/32325828/71254009-88614800-2364-11ea-8a7f-c0040519453f.png)

### What is the expected behavior
能显示正常的背景色，而不是透明

### Steps to reproduce
1.点击启动 qBittorrent app
2.点击左上角❎关闭当前显示的 qBittorrent 窗口（不是退出程序，仅关闭窗口）
3.从dock栏点击 qBittorrent 图标再次打开 qBittorrent 窗口，工具栏就丢失背景变成透明了

### Extra info(if any)
希望可以尽快修复这个bug。

谢谢您的付出与努力！

**Comment by c0re100** [comment]
已知問題: #11612
