### ISSUE TITLE
如何和原版qBittorrent共存安装

### ISSUE THREAD

**Issue by mjl371** [c0re100/qBittorrent-Enhanced-Edition#78]
windows环境下安装时发现直接覆盖原版了，想使用原版用于PT下载

**Comment by abcfy2** [comment]
qbittorrent支持便携模式，参考: https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/4

**Comment by CoderCore** [comment]
> 
> 
> qbittorrent支持便携模式，参考: #4

按这个方法试了一下 就算能共存安装也无法同时使用。

**Comment by abcfy2** [comment]
> > qbittorrent支持便携模式，参考: #4
> 
> 按这个方法试了一下 就算能共存安装也无法同时使用。

不明白你的“同时使用”是什么意思，有何必要性？我试了下qbittorrent官方自带的编写方案（创建`profile`目录），是可以正常使用的，包括磁力链关联，torrent文件关联都没有任何问题

**Comment by c0re100** [comment]
> > > qbittorrent支持便携模式，参考: #4
> > 
> > 
> > 按这个方法试了一下 就算能共存安装也无法同时使用。
> 
> 不明白你的“同时使用”是什么意思，有何必要性？我试了下qbittorrent官方自带的便携方案（创建`profile`目录），是可以正常使用的，包括磁力链关联，torrent文件关联都没有任何问题

因為他想官方版qB用於PT，qBEE用於公種上
我沒試過用portable mode雙開
不過 @CoderCore 你可以試試用configuration指令
正常開啟qBEE
然後官方版用: `./qbittorrent.exe --configuration="new_config_name"` 開啟

**Comment by CoderCore** [comment]
> 
> 
> > > > qbittorrent支持便携模式，参考: #4
> > > 
> > > 
> > > 按这个方法试了一下 就算能共存安装也无法同时使用。
> > 
> > 
> > 不明白你的“同时使用”是什么意思，有何必要性？我试了下qbittorrent官方自带的便携方案（创建`profile`目录），是可以正常使用的，包括磁力链关联，torrent文件关联都没有任何问题
> 
> 因為他想官方版qB用於PT，qBEE用於公種上
> 我沒試過用portable mode雙開
> 不過 @CoderCore 你可以試試用configuration指令
> 正常開啟qBEE
> 然後官方版用: `./qbittorrent.exe --configuration="new_config_name"` 開啟

目前改用4.1.9.4EE（旧版本EE）正常使用PT/BT，对于官方要求改UA/PeerID表示理解。但个人认为仅仅是屏蔽迅雷客户端并没有影响PT下载，更不会影响数据汇报。
官方可能是担心有人在此基础之上做别的更改，影响PT站点的数据汇报，以至于各大站点封杀qB。

**Comment by sunyink** [comment]
看来得虚拟化了。

**Comment by MUXINAzusa** [comment]
> 看来得虚拟化了。

其實並不盡然，我試了一下官方版本的我用的是4.1.9版本，直接正常安裝即可，不改便攜版，而qbEE則推薦下載4.2.1以上版本，原因大概是這麼回事#https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/4#issuecomment-566849820，直接目錄下新建profile文件夾即可，經本人測試，至少我兩個版本一起使用是沒問題的，簡單來說就是一個使用便攜一個採用默認就好了

**Comment by MUXINAzusa** [comment]
> > 看来得虚拟化了。
> 
> 其實並不盡然，我試了一下官方版本的我用的是4.1.9版本，直接正常安裝即可，不改便攜版，而qbEE則推薦下載4.2.1以上版本，原因大概是這麼回事#[https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/4#issuecomment-566849820，直接目錄下新建profile文件夾即可，經本人測試，至少我兩個版本一起使用是沒問題的，簡單來說就是一個使用便攜一個採用默認就好了](https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/4#issuecomment-566849820%EF%BC%8C%E7%9B%B4%E6%8E%A5%E7%9B%AE%E9%8C%84%E4%B8%8B%E6%96%B0%E5%BB%BAprofile%E6%96%87%E4%BB%B6%E5%A4%BE%E5%8D%B3%E5%8F%AF%EF%BC%8C%E7%B6%93%E6%9C%AC%E4%BA%BA%E6%B8%AC%E8%A9%A6%EF%BC%8C%E8%87%B3%E5%B0%91%E6%88%91%E5%85%A9%E5%80%8B%E7%89%88%E6%9C%AC%E4%B8%80%E8%B5%B7%E4%BD%BF%E7%94%A8%E6%98%AF%E6%B2%92%E5%95%8F%E9%A1%8C%E7%9A%84%EF%BC%8C%E7%B0%A1%E5%96%AE%E4%BE%86%E8%AA%AA%E5%B0%B1%E6%98%AF%E4%B8%80%E5%80%8B%E4%BD%BF%E7%94%A8%E4%BE%BF%E6%94%9C%E4%B8%80%E5%80%8B%E6%8E%A1%E7%94%A8%E9%BB%98%E8%AA%8D%E5%B0%B1%E5%A5%BD%E4%BA%86)

推薦一個教程#https://tieba.baidu.com/p/7499036915

**Comment by MUXINAzusa** [comment]
> 看来得虚拟化了。

其實並不盡然，我一開始想著要兩個版本都改成便攜版來使用，在一些配置上容易出現錯誤，後來我轉變了一下想法，據此#https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/4#issuecomment-566849820 ，何不一個便攜一個正常默認安裝，經過嘗試，我的qb4.1.9和qbEE4.6.4實現了在電腦共存，並可雙開無影響，首先qb4.1.9貌似4.2.1以前版本有個錯誤，注意以下【】內容為版本前錯誤問題，並非操作演示，【（據此#https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/4#issuecomment-566849820 ）------接著來說說我一開始的操作，將安裝程序用7zip等提取文件，自己手動創建一個目錄，在qBittorrent安裝位置打開cmd(shift+右鍵)
再輸入 qbittorrent.exe --portable , qB會自動生成一個叫 profile 的資料夾, 配置全都在裡面，同時該主程序同樣會啟動，但這不是正常安裝我們會右鍵發送桌面快捷方式，再在桌面快捷方式打開該程序，你會發現，你雖然上面的操作中在文件目錄生成了一個profile文件夾，裡面有配置，但你在桌面快捷方式打開時會彈出一個你第一次打開該程序的一個聲明對話框，此時我回到C盤APPDATA-Roming-qbit文件夾，你會發現裡面有生成了一個profile文件夾】，當然上面這個錯誤並非沒有解決辦法，可參見#https://tieba.baidu.com/p/7499036915 。但實在是太麻煩了，根據兩種情況，第一種假設一個qb是4.2.1版本前，一個是qbee4.2.1版本後，那麼4.2.1版本前的使用默認安裝，4.2.1版本後先用7zip等提取文件到qbittorrent目錄（自己創一個），然後目錄下創建一個profile文件夾，即可使用，發送到桌面快捷方式還是安裝目錄打開該程序均無任何影響；另一種就是兩個都是4.2.1版本後的那就都直接提取文件，安裝目錄添加profile文件夾，即可，當然還有一種極端的都是4.2.1版本前，你就照上面教程自己整，這種太麻煩了我沒肆，你可以自己試試看，反正第一種我是親測後同時使用是沒問題的
