### ISSUE TITLE
能增加一个自定义“客户端标识”的功能么

### ISSUE THREAD

**Issue by wwqgtxx** [c0re100/qBittorrent-Enhanced-Edition#8]
提这个主要是有一些PT站对于客户端版本号限制较为严格，这个增强版会在客户端标识的后面加上一个小版本号，比如官方版本是`qBittorrent/4.1.1`，而增强版为`qBittorrent/4.1.1.2`，这就导致了该客户端会被某些tracker服务器封禁，所以希望可以提供一个自定义该版本标识的功能绕过一些不太合理的版本限制，望采纳

**Comment by c0re100** [comment]
這個功能會違反了PT站的規則(禁止修改客戶端識別標籤等等)
建議向相關PT站反映一下這個增強版版本問題....
