### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by jkle112** [c0re100/qBittorrent-Enhanced-Edition#82]
![0](https://user-images.githubusercontent.com/17021524/71983020-d5985180-3260-11ea-8e50-44a226e61e01.png)
用的最新版本，限制了上传速度，但是不起作用，最终导致上传快，下载慢，上传比下载大。
如果有办法修复，请升级时解决，谢谢！
![Image 1](https://user-images.githubusercontent.com/17021524/71781850-59a6cb00-300e-11ea-8dcc-a2ebb1016e92.png)

**Comment by c0re100** [comment]
![try](https://user-images.githubusercontent.com/5726473/73662837-7864b400-46d7-11ea-84c6-df093b0d56b5.png)
試試這樣設定Rate limit settings?
