### ISSUE TITLE
300+以上的.torrent打不开前端的WebUI

### ISSUE THREAD

**Issue by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [c0re100/qBittorrent-Enhanced-Edition#87]
硬件是树莓派4B~4GB
原版qBittorrent好像也是这样的问题
总种子>300个  同时下载100就打不开WebUI了
虽然前端是打不开了  但是后端还在下载  网速也是满载的  可惜没WebUI我都不知道哪些下载完了  哪些没下载完 无语  进度也看不到
版本也换了N个了  
Libtorrent从1.0.11编译到1.1.14 到最新的1.2.3都不稳
qBittorrent从4.1.3编译到4.1.5一直到最新的4.2.1 统统打不开前端
I F了U!

害得我只好换回Transmission 3.0了
哎~ 虽然Transmission 3.0稳如泰山(同时下载100个.torrent 目前总下载>1500行.torrent)
不过Transmission没有批量自动添加Tracker真是让我炒鸡不爽

综上所述  只能得出qBittorrent太吃硬件资源了  至少在树莓派最新的4GB平台上这个只有i3~10%的弱鸡性能也只有Transmission能Hold住了~~~

**Comment by c0re100** [comment]
> 硬件是树莓派4B~4GB
> 原版qBittorrent好像也是这样的问题
> 总种子>300个 同时下载100就打不开WebUI了
> 虽然前端是打不开了 但是后端还在下载 网速也是满载的 可惜没WebUI我都不知道哪些下载完了 哪些没下载完 无语 进度也看不到
> 版本也换了N个了
> Libtorrent从1.0.11编译到1.1.14 到最新的1.2.3都不稳
> qBittorrent从4.1.3编译到4.1.5一直到最新的4.2.1 统统打不开前端
> I F了U!
> 
> 害得我只好换回Transmission 3.0了
> 哎~ 虽然Transmission 3.0稳如泰山(同时下载100个.torrent 目前总下载>1500行.torrent)
> 不过Transmission没有批量自动添加Tracker真是让我炒鸡不爽
> 
> 综上所述 只能得出qBittorrent太吃硬件资源了 至少在树莓派最新的4GB平台上这个只有i3~10%的弱鸡性能也只有Transmission能Hold住了~~~

Related issue(?): #10999

**Comment by FranciscoPombal** [comment]
The WebAPI performance issues are not fully resolved, but there have been big improvements lately to the way the WebUI uses it.

If you want to use the `4_1_x` branch, compile from source at this commit https://github.com/qbittorrent/qBittorrent/commit/f16d21964698aaf82ddf3a92aca39665e68e3cf9
If you want to use 4.2.x, compile at this commit https://github.com/qbittorrent/qBittorrent/commit/8be804b6ff5593daea5c4cafca6383d72c1c37ff or later.

At this time there is no official release tag with these improvements. 4.2.2 will be the first such release.

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
> The WebAPI performance issues are not fully resolved, but there have been big improvements lately to the way the WebUI uses it.
> 
> If you want to use the `4_1_x` branch, compile from source at this commit [qbittorrent@f16d219](https://github.com/qbittorrent/qBittorrent/commit/f16d21964698aaf82ddf3a92aca39665e68e3cf9)
> If you want to use 4.2.x, compile at this commit [qbittorrent@8be804b](https://github.com/qbittorrent/qBittorrent/commit/8be804b6ff5593daea5c4cafca6383d72c1c37ff) or later.
> 
> At this time there is no official release tag with these improvements. 4.2.2 will be the first such release.

Hope to optimize the performance of embedded devices as soon as possible, such as Raspberry Pi 4, thank you ~
