### ISSUE TITLE
Not blocking XunLei clients.

### ISSUE THREAD

**Issue by RealXuChe** [c0re100/qBittorrent-Enhanced-Edition#89]
如图.
UA: -XL0012-�ō���6���Nw
![图片](https://user-images.githubusercontent.com/47659370/73623954-e11d4380-4679-11ea-8426-9fbe5acb66ba.png)
建议:屏蔽所有UA为"XL\d{4}"的客户端

**Comment by c0re100** [comment]
正常會自動封鎖有關Peer ID
`QRegExp IDFilter("-(XL|SD|XF|QD|BN|DL)(\\d+)-");`
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_2_x/src/base/bittorrent/session.cpp#L2148

請問你在用哪一個版本出現這問題的?

**Comment by RealXuChe** [comment]
AUR最新版,Arch x86_64

**Comment by mxi-box** [comment]
![捕获](https://user-images.githubusercontent.com/35442369/73731394-60db0900-4773-11ea-9bc6-6b1dc120a7f2.PNG)
Windows x64 v4.2.1.10

**Comment by c0re100** [comment]
@RealXuChe @mxi-box 
可否上傳qbittorrent.log到pastebin給我看看? 
請先刪除敏感資料(e.g. 你的IP, port)再上傳~~
linux: `/home/c0re/.config/qBittorrent/log/qbittorrent.log`
windows: `C:\Users\<username>\AppData\Local\qBittorrent\logs\qbittorrent.log`

**Comment by RealXuChe** [comment]
https://paste.ubuntu.com/p/dc8mTJVb4k/
https://paste.ubuntu.com/p/ydgdYbpjTM/
https://paste.ubuntu.com/p/6xqNNWqhzr/

**Comment by c0re100** [comment]
> https://paste.ubuntu.com/p/dc8mTJVb4k/
> https://paste.ubuntu.com/p/ydgdYbpjTM/
> https://paste.ubuntu.com/p/6xqNNWqhzr/

咦，沒有這一類log?
`5/2/2020 XX:XX pm - Auto banning bad Peer 'x.x.x.x'...'-XL0012-'...'Xunlei 0.0.1.2'...'XX'`

**Comment by RealXuChe** [comment]
没有 
屏蔽掉的地方全部换成了星号,我没有删除任何行

**Comment by c0re100** [comment]
> 没有
> 屏蔽掉的地方全部换成了星号,我没有删除任何行

ummmmmmmm.........
有問題的種子是私有還是公開的?

**Comment by RealXuChe** [comment]
是公开的种子.
我在log文件夹下总共找到了8个log文件.我在这8个文件中查找了"banning",没有任何匹配

**Comment by mxi-box** [comment]
> (N) 2020-02-04T17:32:23 - Auto banning bad Peer ''...'-SD0100-'...'Xunlei 0.1.0'...'CN'
(N) 2020-02-04T17:32:58 - Auto banning bad Peer ''...'-XL0018-'...'Xunlei 0.0.1.8'...'CN'
(N) 2020-02-04T17:33:34 - Peer &quot;***.***.***.***&quot; is manually banned. PeerID: '-XL0012-' Client: '-XL0012-w?e?S4?N3?' Country Name: '中国'
(N) 2020-02-04T17:39:22 - Auto banning bad Peer ''...'-XL0012-'...'Xunlei 0.0.1.2'...'CN'
(N) 2020-02-04T17:40:07 - Auto banning bad Peer ''...'-XL0012-'...'Xunlei 0.0.1.2'...'CN'
(N) 2020-02-04T17:45:02 - Auto banning bad Peer ''...'-XL0018-'...'Xunlei 0.0.1.8'...'CN'
(N) 2020-02-04T17:48:53 - Auto banning bad Peer ''...'-XL0012-'...'Xunlei 0.0.1.2'...'CN'

从log里面截取了一段，那个手动ban的就是没有被识别出来的。
还需要别的信息吗？

**Comment by c0re100** [comment]
> > (N) 2020-02-04T17:32:23 - Auto banning bad Peer ''...'-SD0100-'...'Xunlei 0.1.0'...'CN'
> > (N) 2020-02-04T17:32:58 - Auto banning bad Peer ''...'-XL0018-'...'Xunlei 0.0.1.8'...'CN'
> > (N) 2020-02-04T17:33:34 - Peer "_**.**_._**.**_" is manually banned. PeerID: '-XL0012-' Client: '-XL0012-w?e�?S4?N3?' Country Name: '中国'
> > (N) 2020-02-04T17:39:22 - Auto banning bad Peer ''...'-XL0012-'...'Xunlei 0.0.1.2'...'CN'
> > (N) 2020-02-04T17:40:07 - Auto banning bad Peer ''...'-XL0012-'...'Xunlei 0.0.1.2'...'CN'
> > (N) 2020-02-04T17:45:02 - Auto banning bad Peer ''...'-XL0018-'...'Xunlei 0.0.1.8'...'CN'
> > (N) 2020-02-04T17:48:53 - Auto banning bad Peer ''...'-XL0012-'...'Xunlei 0.0.1.2'...'CN'
> 
> 从log里面截取了一段，那个手动ban的就是没有被识别出来的。
> 还需要别的信息吗？出现问题的这个种子是私有的。

私有種子是會自動跳過這個檢查的
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_2_x/src/base/bittorrent/session.cpp#L2137
詳情可細閱: https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/70#issuecomment-561409836

**Comment by c0re100** [comment]
> 是公开的种子.
> 我在log文件夹下总共找到了8个log文件.我在这8个文件中查找了"banning",没有任何匹配

我發現到甚麼問題了
https://aur.archlinux.org/packages/qbittorrent-enhanced-git/
我在`dc8mTJVb4k`看到這個
```
(N) 2020-01-17T15:56:57 - Peer ID: -qB4210-
(N) 2020-01-17T15:56:57 - HTTP User-Agent is 'qBittorrent/4.2.1'
```
這裡顯示你仍在使用qBittorrent官方版本
你需要移除官方版後，再透過[AUR](https://aur.archlinux.org/packages/qbittorrent-enhanced-git/)重新安裝
以下非官方版為特徵
```
Window Title: qBittorrent v4.2.1.10 (Enhanced Edition)
Peer ID: -qB421A-
User-Agent: qBittorrent/4.2.1.10
```

**Comment by RealXuChe** [comment]
这还真是怪事一桩.我安装的应该是你的版本.
```
[user@user root]$ yay -Ss qbittorrent-enhanced-nox-git
aur/qbittorrent-enhanced-nox-git 4.2.1.10.r0.g0e9d4197d-1 (+1 0.22%)
(Installed: 4.2.1.10.r0.g118af0353-1)
    A bittorrent client powered by C++, Qt5 and the good libtorrent library
(Enhanced Edition)
```

C0RE <notifications@github.com> 于2020年2月6日周四 上午12:13写道：

**Comment by RealXuChe** [comment]
看了一下yay的缓存.缓存的仓库的确是c0re100/qBittorrent-Enhanced-Edition,但是分支不知道为什么切换到了上游qbittorrent/qBittorrent:v4_2_x. 
我觉得有可能是AUR脚本问题,毕竟我在升级时都没有Clean build.
建议AUR脚本每次构建前都切换一下分支.

**Comment by c0re100** [comment]
> 看了一下yay的缓存.缓存的仓库的确是c0re100/qBittorrent-Enhanced-Edition,但是分支不知道为什么切换到了上游qbittorrent/qBittorrent:v4_2_x.
> 我觉得有可能是AUR脚本问题,毕竟我在升级时都没有Clean build.
> 建议AUR脚本每次构建前都切换一下分支.

之後的更新會改一改
