### ISSUE TITLE
Is development still active?

### ISSUE THREAD

**Issue by txtsd** [c0re100/qBittorrent-Enhanced-Edition#90]
There haven't been any commits since last year.

Is this https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/70 blocking?

**Comment by partment** [comment]
@txtsd Yes, and becuase the official qbittorrent hasn't release any stable version this year. Thus this repo has no need to do any updates.

**Comment by txtsd** [comment]
Thanks!
