### ISSUE TITLE
“Xunlei 0.0.1.8”客户端没有被自动屏蔽

### ISSUE THREAD

**Issue by Aristrotle** [c0re100/qBittorrent-Enhanced-Edition#91]
**Please provide the following information**

### qBittorrent version and Operating System
Windows 10 build 18363.592; qBittorrent v4.2.1.10

### What is the problem
有多个来自不同ip段的名为 Xunlei 0.0.1.8 的客户端出现在peer列表中，下图是其中一个
![image](https://user-images.githubusercontent.com/60840549/74099785-1df9a680-4b62-11ea-8b2c-eb0399c7b1a3.png)

**Comment by c0re100** [comment]
> **Please provide the following information**
> 
> ### qBittorrent version and Operating System
> Windows 10 build 18363.592; qBittorrent v4.2.1.10
> 
> ### What is the problem
> 有多个来自不同ip段的名为 Xunlei 0.0.1.8 的客户端出现在peer列表中，下图是其中一个
> ![image](https://user-images.githubusercontent.com/60840549/74099785-1df9a680-4b62-11ea-8b2c-eb0399c7b1a3.png)

如果是私有種子: 屬於正常情況
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_2_x/src/base/bittorrent/session.cpp#L2137 
詳情可細閱: https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/70#issuecomment-561409836
這一個可以用EE API處理掉

公開種子的話: 有待觀察

**Comment by Aristrotle** [comment]
> 
> 
> > **Please provide the following information**
> > ### qBittorrent version and Operating System
> > Windows 10 build 18363.592; qBittorrent v4.2.1.10
> > ### What is the problem
> > 有多个来自不同ip段的名为 Xunlei 0.0.1.8 的客户端出现在peer列表中，下图是其中一个
> > ![image](https://user-images.githubusercontent.com/60840549/74099785-1df9a680-4b62-11ea-8b2c-eb0399c7b1a3.png)
> 
> 如果是私有種子: 屬於正常情況
> https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_2_x/src/base/bittorrent/session.cpp#L2137
> 詳情可細閱: [#70 (comment)](https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/70#issuecomment-561409836)
> 這一個可以用EE API處理掉
> 
> 公開種子的話: 有待觀察

原来是这样，那确实是一个私有种子

**Comment by jojo022** [comment]
还update嘛？
