### ISSUE TITLE
存在未被Ban的迅雷客户端

### ISSUE THREAD

**Issue by ljcbaby** [c0re100/qBittorrent-Enhanced-Edition#93]
### qBittorrent version and Operating System
![image](https://user-images.githubusercontent.com/46277145/74519074-0189af80-4f50-11ea-8be6-5c1f0468aae0.png)
![image](https://user-images.githubusercontent.com/46277145/74519102-11a18f00-4f50-11ea-9d6b-dc66ab8824d7.png)

### What is the problem
存在未被Ban的迅雷客户端

### What is the expected behavior
相关客户端应该被Ban

### Extra info(if any)
![image](https://user-images.githubusercontent.com/46277145/74519246-50cfe000-4f50-11ea-9319-97143a7835cf.png)
![image](https://user-images.githubusercontent.com/46277145/74519270-59281b00-4f50-11ea-888a-230077daf7f9.png)

**Comment by c0re100** [comment]
如果是私有種子: 屬於正常情況
https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/v4_2_x/src/base/bittorrent/session.cpp#L2137
詳情可細閱: https://github.com/c0re100/qBittorrent-Enhanced-Edition/issues/70#issuecomment-561409836
這一個可以用EE API處理掉

公開種子的話: 有待觀察

**Comment by ljcbaby** [comment]
应该是公开种子

**Comment by c0re100** [comment]
> 应该是公开种子

你的qB是長期開啟的嗎?

**Comment by ljcbaby** [comment]
> > 应该是公开种子
> 
> 你的qB是長期開啟的嗎?

是的

**Comment by c0re100** [comment]
> > > 应该是公开种子
> > 
> > 
> > 你的qB是長期開啟的嗎?
> 
> 是的

當時有其他auto ban log嗎?

**Comment by ljcbaby** [comment]
有的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "C0RE"<notifications@github.com&gt;; 
发送时间: 2020年2月16日(星期天) 晚上6:53
收件人: "c0re100/qBittorrent-Enhanced-Edition"<qBittorrent-Enhanced-Edition@noreply.github.com&gt;; 
抄送: "卢俊成"<ljcbaby@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [c0re100/qBittorrent-Enhanced-Edition] 存在未被Ban的迅雷客户端 (#93)



   
应该是公开种子
  
你的qB是長期開啟的嗎?
  
是的
  
當時有其他auto ban log嗎?
 
&mdash;

**Comment by c0re100** [comment]
> 有的

有其他ban log....
感覺是私有種子，所以沒有跳過了自動封鎖

如果你還看見的話，可以試試重開qB(可能是舊bug重現...)
然後再看這個peer有沒有自動封禁和那一類種子(公/私)

**Comment by ljcbaby** [comment]
那那我就下次遇到再看吧。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "C0RE"<notifications@github.com&gt;; 
发送时间: 2020年2月16日(星期天) 晚上10:01
收件人: "c0re100/qBittorrent-Enhanced-Edition"<qBittorrent-Enhanced-Edition@noreply.github.com&gt;; 
抄送: "卢俊成"<ljcbaby@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [c0re100/qBittorrent-Enhanced-Edition] 存在未被Ban的迅雷客户端 (#93)



 
有的
  
有其他ban log....
 感覺是私有種子，所以沒有跳過了自動封鎖
 
如果你還看見的話，可以試試重開qB(可能是舊bug重現...)
 然後再看這個peer有沒有自動封禁和那一類種子(公/私)
 
&mdash;

**Comment by ljcbaby** [comment]
实际上私种也可以Ban迅雷，因为不会有PT站允许用户使用迅雷这些吸血的下载器的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "C0RE"<notifications@github.com&gt;; 
发送时间: 2020年2月16日(星期天) 晚上10:01
收件人: "c0re100/qBittorrent-Enhanced-Edition"<qBittorrent-Enhanced-Edition@noreply.github.com&gt;; 
抄送: "卢俊成"<ljcbaby@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [c0re100/qBittorrent-Enhanced-Edition] 存在未被Ban的迅雷客户端 (#93)



 
有的
  
有其他ban log....
 感覺是私有種子，所以沒有跳過了自動封鎖
 
如果你還看見的話，可以試試重開qB(可能是舊bug重現...)
 然後再看這個peer有沒有自動封禁和那一類種子(公/私)
 
&mdash;

**Comment by lomemeng** [comment]
未ban的吸血雷我也遇到了

**Comment by abcfy2** [comment]
![image](https://user-images.githubusercontent.com/5327677/77087241-dbb76500-6a3d-11ea-876a-60eb5792bf1e.png)

似乎还真有这种情况，确实有未被ban的迅雷客户端的存在

**Comment by c0re100** [comment]
> ![image](https://user-images.githubusercontent.com/5327677/77087241-dbb76500-6a3d-11ea-876a-60eb5792bf1e.png)
> 
> 似乎还真有这种情况，确实有未被ban的迅雷客户端的存在

是公開種子嗎........?

**Comment by abcfy2** [comment]
> > ![image](https://user-images.githubusercontent.com/5327677/77087241-dbb76500-6a3d-11ea-876a-60eb5792bf1e.png)
> > 似乎还真有这种情况，确实有未被ban的迅雷客户端的存在
> 
> 是公開種子嗎........?

请问如何查看种子是公开的还是私有的？

**Comment by c0re100** [comment]
> > > ![image](https://user-images.githubusercontent.com/5327677/77087241-dbb76500-6a3d-11ea-876a-60eb5792bf1e.png)
> > > 似乎还真有这种情况，确实有未被ban的迅雷客户端的存在
> > 
> > 
> > 是公開種子嗎........?
> 
> 请问如何查看种子是公开的还是私有的？

Tracker > 視乎種子的DHT/PeX/LSD狀態
如果是停用的就是私有，相反就是公開

**Comment by abcfy2** [comment]
这么看来的确是私有的

![image](https://user-images.githubusercontent.com/5327677/77129770-32e62580-6a90-11ea-8240-7b36c3a0d1ec.png)

**Comment by c0re100** [comment]
我下個版本改回不檢查私有種子吧.......

**Comment by abcfy2** [comment]
迅雷确实挺恶心的，列表中可以看到进度一直是0%，根本不分享，疯狂吸血

**Comment by ljcbaby** [comment]
我觉得没必要改回去，私有种子也绝对不会允许用吸血雷下载的。




------------------&nbsp;Original&nbsp;------------------

**Comment by c0re100** [comment]
> 我觉得没必要改回去，私有种子也绝对不会允许用吸血雷下载的。
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From:&nbsp;"C0RE"<notifications@github.com&gt;; Date:&nbsp;Fri, Mar 20, 2020 10:33 AM To:&nbsp;"c0re100/qBittorrent-Enhanced-Edition"<qBittorrent-Enhanced-Edition@noreply.github.com&gt;; Cc:&nbsp;"卢俊成"<ljcbaby@qq.com&gt;;"Author"<author@noreply.github.com&gt;; Subject:&nbsp;Re: [c0re100/qBittorrent-Enhanced-Edition] 存在未被Ban的迅雷客户端 (#93) 我下個版本改回不檢查私有種子吧....... — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯，事實，私有不應該由做Client做而是由Tracker去阻擋
