### ISSUE TITLE
无法解析用户所在地区

### ISSUE THREAD

**Issue by linus-chong** [c0re100/qBittorrent-Enhanced-Edition#94]
**Please provide the following information**

### qBittorrent version and Operating System
windows10
v4.2.1.10

### If on linux, libtorrent-rasterbar and Qt version
NO

### What is the problem
用户-国家栏空白

### What is the expected behavior
显示国旗图标

### Steps to reproduce
任何种子

### Extra info(if any)
![1](https://user-images.githubusercontent.com/46522179/74598886-c81e8480-50b4-11ea-8eec-90ecebdff4fa.JPG)
![2](https://user-images.githubusercontent.com/46522179/74598889-cce33880-50b4-11ea-98b7-ac7cda757677.JPG)
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

**Comment by c0re100** [comment]
WIP: #12014

**Comment by FranciscoPombal** [comment]
Issue reports must be posted in English only (though I realize this one is related to the geo ip flags issue which will be fixed soon anyway).

@thalieht close please

**Comment by c0re100** [comment]
> Issue reports must be posted in English only (though I realize this one is related to the geo ip flags issue which will be fixed soon anyway).
> 
> @thalieht close please

Sorry, there is a fork version git.
I will close it when PR merged.

**Comment by c0re100** [comment]
Upstream PR merged.

**Comment by FranciscoPombal** [comment]
> Sorry, there is a fork version git repo.
> I will close it when PR merged.

Right, totally missed it. Sorry!
