### ISSUE TITLE
最新win版无法显示用户国家

### ISSUE THREAD

**Issue by with1ight** [c0re100/qBittorrent-Enhanced-Edition#96]
最新win版无法显示用户国家，想了解一下这是什么原因以及应该如何修复

**Comment by c0re100** [comment]
會於下個版本修復

**Comment by ausers** [comment]
> 會於下個版本修復

在现有情况下能否手动复制GeoIP数据库临时解决？翻阅文档后我仍不确定数据库的保存位置和命名，应该置于什么位置？

**Comment by c0re100** [comment]
> > 會於下個版本修復
> 
> 在现有情况下能否手动复制GeoIP数据库临时解决？翻阅文档后我仍不确定数据库的保存位置和命名，应该置于什么位置？

GeoIP位置: `C:\Users\<username>\AppData\Local\qBittorrent\GeoIP\`
