### ISSUE TITLE
客户端unknown，peer乱码，这类是什么客户端呢？

### ISSUE THREAD

**Issue by ausers** [c0re100/qBittorrent-Enhanced-Edition#98]
![20200227232103](https://user-images.githubusercontent.com/54773815/75526000-e046ba00-5a4b-11ea-8908-2839761f19a8.png)
下载和上传时发现这类客户端，好奇来源

**Comment by c0re100** [comment]
> ![20200227232103](https://user-images.githubusercontent.com/54773815/75526000-e046ba00-5a4b-11ea-8908-2839761f19a8.png)
> 下载和上传时发现这类客户端，好奇来源

別在意，只是某些用戶開啟了匿名模式(Anonymous mode)
例如: VPN用戶
